In [1]:
import gbd_mapping
import risk_distributions
import pathlib
import pandas as pd, numpy as np
import vivarium_inputs
from vivarium_inputs import utility_data, globals as vi_globals, utilities as vi_utils
from vivarium_gbd_access import gbd
import os, contextlib, warnings, loguru

from vivarium_inputs.validation.raw import DataDoesNotExistError, DataAbnormalError
from tqdm.notebook import tqdm

Config: 'input_data:
    cache_data:
        base: True
    intermediary_data_cache_path:
        base: /share/scratch/users/{username}/cache'
Cache Dir: '/share/scratch/users/zmbc/cache'

In [2]:
pd.set_option("display.max_columns", 30)

In [3]:
warnings.simplefilter(action='ignore', category=pd.errors.PerformanceWarning)

In [4]:
location = "india"
vehicle = "rice"
intervention_scenario = "intervention"

In [5]:
# Parameters
location = "nigeria"
vehicle = "bouillon"
intervention_scenario = "intervention"

In [6]:
index_cols = ["sex", "age_start", "age_end", "wealth_quintile"]

age_group_ids = [
    2,3,
    388,389,
    6,7,8,9,10,11,12,13,14,15,16,17,18,19,20, 30, 31, 32, 235
]
sex_ids = [1,2]

DRAWS = [f'draw_{i}' for i in range(500)] # NOTE: Some GBD 2021 things return 1,000 but others don't

In [7]:
fortification_hemoglobin_mean_difference = (
    pd.read_csv('../0100_data_prep/results/iron/fortification_hemoglobin_effects.csv')
        .set_index('vehicle_name').value
        .loc[vehicle]
)
fortification_hemoglobin_mean_difference

4.2

In [8]:
effective_baseline_coverage = (
    pd.read_csv(f'../0100_data_prep/results/iron/{vehicle}/baseline_fortification/effective_coverage/{location}.csv')
)
assert (effective_baseline_coverage.vehicle_name == vehicle).all()
effective_baseline_coverage = effective_baseline_coverage.drop(columns=["vehicle_name"])
effective_baseline_coverage

  wealth_quintile     value
0          fourth  0.535497
1         highest  0.559838
2          lowest  0.415369
3          middle  0.510484
4          second  0.467278

In [9]:
def expand(df):
    for col in sorted(list(set(df.columns) - {'value'})):
        if df[col].isnull().any():
            df = pd.concat([
                df[df[col].notnull()],
                *[df[df[col].isnull()].assign(**{col: value}) for value in df[df[col].notnull()][col].unique()]
            ])
    
    return df

In [10]:
for col, fill_value in [("age_start", 0), ("age_end", 125)]:
    if col not in effective_baseline_coverage.columns:
        effective_baseline_coverage[col] = fill_value
    else:
        effective_baseline_coverage[col] = effective_baseline_coverage[col].fillna(fill_value)

In [11]:
effective_baseline_coverage = expand(effective_baseline_coverage)
effective_baseline_coverage

  wealth_quintile     value  age_start  age_end
0          fourth  0.535497          0      125
1         highest  0.559838          0      125
2          lowest  0.415369          0      125
3          middle  0.510484          0      125
4          second  0.467278          0      125

In [12]:
effective_counterfactual_coverage = (
    pd.read_csv(f'../0100_data_prep/results/iron/{vehicle}/{intervention_scenario}/intervention_fortification/effective_coverage/{location}.csv')
)
assert (effective_counterfactual_coverage.vehicle_name == vehicle).all()
effective_counterfactual_coverage = effective_counterfactual_coverage.drop(columns=["vehicle_name"])
effective_counterfactual_coverage

  wealth_quintile     sex     value
0          lowest  Female  0.618069
1          second  Female  0.626300
2          middle  Female  0.627742
3          fourth  Female  0.632860
4         highest  Female  0.629615
5          lowest    Male  0.618069
6          second    Male  0.626300
7          middle    Male  0.627742
8          fourth    Male  0.632860
9         highest    Male  0.629615

In [13]:
for col, fill_value in [("age_start", 0), ("age_end", 125)]:
    if col not in effective_counterfactual_coverage.columns:
        effective_counterfactual_coverage[col] = fill_value
    else:
        effective_counterfactual_coverage[col] = effective_counterfactual_coverage[col].fillna(fill_value)

In [14]:
effective_counterfactual_coverage = expand(effective_counterfactual_coverage)
effective_counterfactual_coverage

  wealth_quintile     sex     value  age_start  age_end
0          lowest  Female  0.618069          0      125
1          second  Female  0.626300          0      125
2          middle  Female  0.627742          0      125
3          fourth  Female  0.632860          0      125
4         highest  Female  0.629615          0      125
5          lowest    Male  0.618069          0      125
6          second    Male  0.626300          0      125
7          middle    Male  0.627742          0      125
8          fourth    Male  0.632860          0      125
9         highest    Male  0.629615          0      125

In [15]:
non_pregnant_pop = (
    pd.read_csv(f'../0100_data_prep/results/population/stratified/{location}.csv')
).pipe(lambda df: df[df.pregnant == "not_pregnant"]).drop(columns="pregnant")
non_pregnant_pop = non_pregnant_pop.set_index([c for c in non_pregnant_pop.columns if c != 'value']).value
non_pregnant_pop

sex     age_start  age_end     wealth_quintile
Female  0.0        0.019178    lowest             16960.496219
                               second             16890.884668
                               middle             15946.960379
                               fourth             14017.956071
                               highest            13029.810174
                                                      ...
Male    95.0       125.000000  lowest              1846.968043
                               second              1616.329970
                               middle              1661.447043
                               fourth              1779.062429
                               highest             1896.973078
Name: value, Length: 250, dtype: float64

In [16]:
population_age_groups = non_pregnant_pop.reset_index()[["age_start", "age_end"]].drop_duplicates().sort_values("age_start")
population_age_groups

     age_start     age_end
0     0.000000    0.019178
5     0.019178    0.076712
10    0.076712    0.500000
15    0.500000    1.000000
20    1.000000    2.000000
25    2.000000    5.000000
30    5.000000   10.000000
35   10.000000   15.000000
40   15.000000   20.000000
45   20.000000   25.000000
50   25.000000   30.000000
55   30.000000   35.000000
60   35.000000   40.000000
65   40.000000   45.000000
70   45.000000   50.000000
75   50.000000   55.000000
80   55.000000   60.000000
85   60.000000   65.000000
90   65.000000   70.000000
95   70.000000   75.000000
100  75.000000   80.000000
105  80.000000   85.000000
110  85.000000   90.000000
115  90.000000   95.000000
120  95.000000  125.000000

In [17]:
def map_to_population_age_groups(df):
    return (
        population_age_groups.merge(df, how="cross", suffixes=("", "_orig"))
            .pipe(lambda df: df[(df.age_end <= df.age_end_orig) & (df.age_start >= df.age_start_orig)])
            .drop(columns=["age_start_orig", "age_end_orig"])
    )

In [18]:
effective_baseline_coverage = map_to_population_age_groups(effective_baseline_coverage).set_index([c for c in effective_baseline_coverage.columns if c != 'value']).value
effective_counterfactual_coverage = map_to_population_age_groups(effective_counterfactual_coverage).set_index([c for c in effective_counterfactual_coverage.columns if c != 'value']).value

In [19]:
delta_effective_coverage = effective_counterfactual_coverage.sub(effective_baseline_coverage)
delta_effective_coverage

wealth_quintile  age_start  age_end     sex
fourth           0.000000   0.019178    Female    0.097363
                                        Male      0.097363
                 0.019178   0.076712    Female    0.097363
                                        Male      0.097363
                 0.076712   0.500000    Female    0.097363
                                                    ...
second           85.000000  90.000000   Male      0.159021
                 90.000000  95.000000   Female    0.159021
                                        Male      0.159021
                 95.000000  125.000000  Female    0.159021
                                        Male      0.159021
Name: value, Length: 250, dtype: float64

In [20]:
def reshape_to_vivarium_format(df, location):
    df = vi_utils.reshape(df, value_cols=[c for c in df.columns if 'draw_' in c])
    df = vi_utils.scrub_gbd_conventions(df, location)
    df = vi_utils.split_interval(df, interval_column="age", split_column_prefix="age")
    df = vi_utils.split_interval(df, interval_column="year", split_column_prefix="year")
    df = vi_utils.sort_hierarchical_data(df)
    df.index = df.index.droplevel("location")
    return df

In [21]:
me_ids = {
    "hemoglobin_mean": 10487,
    "hemoglobin_sd": 10488,
}

In [22]:
location_id = utility_data.get_location_id(location.title())
hgb_mean = gbd.get_modelable_entity_draws(me_id=me_ids["hemoglobin_mean"], location_id=location_id, year_id=2021)
hgb_mean = reshape_to_vivarium_format(hgb_mean, location.title()).droplevel(["year_start", "year_end", "measure_id", "metric_id", "model_version_id", "modelable_entity_id"])[DRAWS].copy()
hgb_mean

                                 draw_0      draw_1      draw_2      draw_3  \
sex    age_start age_end
Female 0.000000  0.019178    140.203331  139.700680  137.486100  143.738463
       0.019178  0.076712    121.992596  122.837138  123.877519  120.604868
       0.076712  0.500000    104.152465  104.343166  100.933682  103.672346
       0.500000  1.000000    100.148802   99.844921   99.645127  100.145850
       1.000000  2.000000    100.955723  100.339208  102.148597  101.234802
       2.000000  5.000000    105.233662  104.333100  102.835176  105.304765
       5.000000  10.000000   119.455834  112.957619  115.682929  114.256919
       10.000000 15.000000   119.312919  106.273992  111.855854  122.097443
       15.000000 20.000000   114.861226  117.794304  116.359602  117.648438
       20.000000 25.000000   116.232257  117.251310  116.393998  114.894111
       25.000000 30.000000   116.082332  114.626063  116.408492  116.811736
       30.000000 35.000000   115.103530  115.163515  116.767807  116.269128
       35.000000 40.000000   115.986054  113.528076  114.852973  114.288218
       40.000000 45.000000   115.257500  117.940598  117.278455  116.853328
       45.000000 50.000000   118.568757  119.048450  117.278407  117.835148
       50.000000 55.000000   115.669641  121.096756  111.909301  123.510802
       55.000000 60.000000   116.888277  111.934668  117.516013  116.335911
       60.000000 65.000000   117.073529  120.448205  112.138824  119.361783
       65.000000 70.000000   120.936133  131.305616  125.299052  121.720141
       70.000000 75.000000   120.728706  120.069195  124.432953  117.908148
       75.000000 80.000000   126.020295  126.733554  121.556975  127.985198
       80.000000 85.000000   126.158836  126.248607  116.366249  123.473284
       85.000000 90.000000   118.780034  118.418548  114.061451  115.310723
       90.000000 95.000000   109.477010  104.789317  110.610979  108.944244
       95.000000 125.000000  102.971577  100.970692   99.657313   98.358658
Male   0.000000  0.019178    139.655000  152.652888  141.405358  135.236759
       0.019178  0.076712    111.875330  122.227176  119.526917  118.369764
       0.076712  0.500000     94.267052   98.335982   96.967303   98.720429
       0.500000  1.000000    100.092403   98.678200   93.913129   99.908232
       1.000000  2.000000    100.226883   94.470196   98.331789   95.255325
       2.000000  5.000000    101.069093  107.942797  103.555610  102.374253
       5.000000  10.000000   119.838610  110.970261  109.073412  112.143982
       10.000000 15.000000   129.595152  119.217013  127.657332  129.642930
       15.000000 20.000000   129.129905  144.220990  141.441577  142.995724
       20.000000 25.000000   151.050744  131.461208  146.612140  132.307327
       25.000000 30.000000   132.425569  149.591271  142.560174  135.773968
       30.000000 35.000000   140.605288  141.846950  135.968545  160.662459
       35.000000 40.000000   138.202586  145.354328  144.617087  133.079794
       40.000000 45.000000   141.806468  145.535717  136.109962  148.130476
       45.000000 50.000000   133.416092  136.101393  150.337119  141.486861
       50.000000 55.000000   144.695059  135.210554  139.837715  139.728713
       55.000000 60.000000   138.257682  142.365263  142.266348  143.671582
       60.000000 65.000000   137.633530  133.990371  143.313102  140.484227
       65.000000 70.000000   143.947810  146.078428  140.887869  134.047618
       70.000000 75.000000   141.462864  144.115084  130.980064  145.225366
       75.000000 80.000000   125.293565  127.635808  121.016674  127.115747
       80.000000 85.000000   136.438006  140.853010  131.367813  139.943361
       85.000000 90.000000   133.029351  120.328832  136.611180  126.391697
       90.000000 95.000000   116.866389  104.222078  111.737153  113.207507
       95.000000 125.000000  104.414752  104.110723   99.482286  102.887575

                                 draw_4      draw_5      draw_6      draw_7  \
sex    age_start age_end
Female 0.000000  0.019178    148.622155  142.898403  135.879741  146.860804
       0.019178  0.076712    118.583369  114.759783  121.062536  115.664404
       0.076712  0.500000    105.214707  102.017120  101.666111  104.391111
       0.500000  1.000000    100.608923  101.012091  100.358797   98.995013
       1.000000  2.000000    100.603498  100.260029  100.667909  100.806325
       2.000000  5.000000    105.698959  105.270406  104.383177  104.944148
       5.000000  10.000000   112.445778  108.129095  115.269360  116.949897
       10.000000 15.000000   112.101844  112.573722  110.628343  111.910474
       15.000000 20.000000   117.718187  118.038089  117.539722  117.631445
       20.000000 25.000000   117.201976  115.441273  115.564658  116.283234
       25.000000 30.000000   118.125046  118.053523  115.809354  115.666409
       30.000000 35.000000   116.706487  115.153682  116.801983  113.712861
       35.000000 40.000000   115.248647  116.584322  116.712603  114.931580
       40.000000 45.000000   115.971911  117.309627  118.413162  117.185406
       45.000000 50.000000   119.888282  119.242264  117.953520  118.917692
       50.000000 55.000000   105.246494  113.013340  113.315487  116.507582
       55.000000 60.000000   116.196913  108.945164  118.153491  111.249024
       60.000000 65.000000   121.980984  114.051134  120.805249  121.372152
       65.000000 70.000000   130.708385  129.355625  125.709029  126.209303
       70.000000 75.000000   122.213798  128.178021  130.401904  130.637428
       75.000000 80.000000   125.280079  126.995331  128.937650  123.316893
       80.000000 85.000000   121.423435  125.664959  123.011669  122.934808
       85.000000 90.000000   116.190198  124.807436  111.070989  119.262830
       90.000000 95.000000   110.272233  102.837675  110.397164  106.996263
       95.000000 125.000000   96.036401  101.532534  102.345743  101.051934
Male   0.000000  0.019178    145.950384  148.051338  145.753920  143.368754
       0.019178  0.076712    110.899432  132.687274  113.096215  110.843494
       0.076712  0.500000    100.392380   97.388312   99.835516  105.483599
       0.500000  1.000000     98.806275   97.043218   90.629506   95.910213
       1.000000  2.000000     97.563575   99.224006   96.391036   99.129051
       2.000000  5.000000    102.478360  105.307768  106.502021   98.257520
       5.000000  10.000000   113.808712  121.817283  116.570179  106.415407
       10.000000 15.000000   112.928565  120.507986  136.626822  127.254933
       15.000000 20.000000   134.893712  135.590220  134.734586  130.920151
       20.000000 25.000000   140.617992  134.857577  143.955917  150.234689
       25.000000 30.000000   155.446834  152.764731  154.675099  152.349818
       30.000000 35.000000   139.997667  137.561719  142.785512  150.152448
       35.000000 40.000000   149.194421  145.240541  130.272282  149.016715
       40.000000 45.000000   131.555709  148.512512  140.948951  140.280393
       45.000000 50.000000   138.002726  147.616175  143.353695  148.856435
       50.000000 55.000000   128.840348  141.879073  128.012092  143.710892
       55.000000 60.000000   142.116835  142.340961  132.625360  131.458105
       60.000000 65.000000   137.657843  149.676107  137.490021  138.255288
       65.000000 70.000000   138.305347  143.738034  144.738884  146.325436
       70.000000 75.000000   139.549364  138.368488  141.333839  131.561358
       75.000000 80.000000   138.057306  124.135326  131.351376  140.422146
       80.000000 85.000000   136.350483  131.038066  123.096959  137.390001
       85.000000 90.000000   129.370208  136.797710  127.729441  121.481892
       90.000000 95.000000   106.352527   98.297926  113.236702  105.723986
       95.000000 125.000000  107.603354  105.459291  103.255580  110.455551

                                 draw_8      draw_9     draw_10     draw_11  \
sex    age_start age_end
Female 0.000000  0.019178    148.441575  136.598751  141.466550  138.089184
       0.019178  0.076712    113.872047  118.315783  119.589692  117.163783
       0.076712  0.500000    101.872444  103.526095  101.283339  103.663214
       0.500000  1.000000     99.743129  100.867444  100.802132   99.360873
       1.000000  2.000000    101.008100   99.686666   99.714662  100.772973
       2.000000  5.000000    104.233312  106.923858  103.931931  104.222128
       5.000000  10.000000   116.004710  113.079119  110.131016  113.399954
       10.000000 15.000000   109.547810  115.805717  112.611635  116.003393
       15.000000 20.000000   117.140323  116.770157  116.720418  117.249697
       20.000000 25.000000   116.316618  117.074015  115.365220  115.648786
       25.000000 30.000000   117.056230  115.181358  116.837717  116.757552
       30.000000 35.000000   115.813215  114.817594  113.653704  115.341602
       35.000000 40.000000   115.667189  116.278426  116.681642  118.095610
       40.000000 45.000000   117.077432  117.657980  117.054500  116.975735
       45.000000 50.000000   117.489349  119.521306  119.418178  118.604975
       50.000000 55.000000   115.821738  117.970520  112.586683  107.338111
       55.000000 60.000000   117.338496  116.239039  115.204805  116.056558
       60.000000 65.000000   117.384561  119.873163  113.489156  116.758345
       65.000000 70.000000   121.546710  122.603228  130.165223  122.009977
       70.000000 75.000000   121.612261  126.719624  127.652742  126.543977
       75.000000 80.000000   124.858928  126.612797  125.403155  118.701534
       80.000000 85.000000   127.697045  119.799646  120.019189  119.549908
       85.000000 90.000000   117.795365  126.255445  111.993769  118.694922
       90.000000 95.000000   113.492466  112.580471  110.611752  105.897065
       95.000000 125.000000  100.307373   98.663466  102.553751   97.456725
Male   0.000000  0.019178    148.505532  149.271473  150.363622  135.086188
       0.019178  0.076712    116.429972  122.955986  128.089332  117.348339
       0.076712  0.500000     97.071404   97.055824  100.354579  102.827298
       0.500000  1.000000     94.262673   97.302075   97.875045   97.561767
       1.000000  2.000000     93.744372   96.324011  101.993191  100.080094
       2.000000  5.000000    102.124309  100.409932  103.983532  102.920718
       5.000000  10.000000   110.620094  111.324468  107.668301  107.006246
       10.000000 15.000000   114.645329  120.478304  121.805357  119.113806
       15.000000 20.000000   140.395444  145.143500  132.886093  146.887070
       20.000000 25.000000   138.525246  150.619108  145.954753  133.518881
       25.000000 30.000000   136.539225  149.159022  134.084235  152.577941
       30.000000 35.000000   151.069363  149.089416  146.875961  147.048821
       35.000000 40.000000   134.838400  137.859408  145.256161  143.353014
       40.000000 45.000000   142.162264  163.478077  144.007176  136.568286
       45.000000 50.000000   126.762191  141.755796  148.495302  140.141041
       50.000000 55.000000   140.694183  130.967252  127.929693  135.280819
       55.000000 60.000000   134.607110  132.374558  133.299788  133.288925
       60.000000 65.000000   134.467162  132.907559  133.728541  136.444556
       65.000000 70.000000   141.687655  137.607029  146.345463  143.516944
       70.000000 75.000000   140.272928  141.656767  133.897411  139.386611
       75.000000 80.000000   134.386319  133.184690  141.882365  135.301478
       80.000000 85.000000   135.796309  130.850945  137.295287  134.727373
       85.000000 90.000000   124.340741  129.907846  130.052311  136.490227
       90.000000 95.000000   114.701460  109.299417  110.747712  111.304806
       95.000000 125.000000  105.846010  113.724775   93.089021  107.019766

                                draw_12     draw_13     draw_14  ...  \
sex    age_start age_end                                         ...
Female 0.000000  0.019178    138.401927  137.448153  145.690438  ...
       0.019178  0.076712    115.086902  129.699933  118.144320  ...
       0.076712  0.500000    101.193666  100.801412  102.098223  ...
       0.500000  1.000000    100.678774  100.171735   99.245162  ...
       1.000000  2.000000    100.699001  101.696056   99.871979  ...
       2.000000  5.000000    106.051692  104.640680  103.694541  ...
       5.000000  10.000000   111.877002  117.352725  116.644265  ...
       10.000000 15.000000   117.517359  109.337545  112.435858  ...
       15.000000 20.000000   117.732660  117.377174  115.036573  ...
       20.000000 25.000000   117.322746  114.522481  117.394546  ...
       25.000000 30.000000   116.844960  117.919896  115.795500  ...
       30.000000 35.000000   113.943478  116.351574  115.005835  ...
       35.000000 40.000000   115.574220  115.979558  115.805756  ...
       40.000000 45.000000   117.157656  118.107750  116.236390  ...
       45.000000 50.000000   117.847856  117.377386  116.803793  ...
       50.000000 55.000000   118.392422  118.114204  120.903323  ...
       55.000000 60.000000   114.129473  116.346613  113.083471  ...
       60.000000 65.000000   120.184594  126.069878  127.089311  ...
       65.000000 70.000000   127.523037  123.574835  124.362464  ...
       70.000000 75.000000   123.135847  124.790998  125.936801  ...
       75.000000 80.000000   116.755162  121.424450  124.002985  ...
       80.000000 85.000000   116.893657  121.330004  122.393335  ...
       85.000000 90.000000   119.468646  112.054621  122.471296  ...
       90.000000 95.000000   105.221954  105.872161  106.524521  ...
       95.000000 125.000000   98.114855  104.579160  100.657417  ...
Male   0.000000  0.019178    159.586357  137.677792  151.960142  ...
       0.019178  0.076712    103.723857  129.776858  121.710994  ...
       0.076712  0.500000    102.819068  103.065592   98.066537  ...
       0.500000  1.000000     95.587779   96.588824   98.730787  ...
       1.000000  2.000000     97.572005   96.942734  106.497842  ...
       2.000000  5.000000    101.970571  102.331105  104.527396  ...
       5.000000  10.000000   110.726687  116.066721  104.095569  ...
       10.000000 15.000000   113.115182  114.215649  116.258365  ...
       15.000000 20.000000   140.595584  138.607096  144.538106  ...
       20.000000 25.000000   142.796583  151.875038  140.009641  ...
       25.000000 30.000000   142.661891  148.438973  138.114751  ...
       30.000000 35.000000   138.802514  136.349820  151.906280  ...
       35.000000 40.000000   129.473316  137.907653  132.718411  ...
       40.000000 45.000000   140.707200  131.780923  129.703159  ...
       45.000000 50.000000   155.770919  155.526978  128.705201  ...
       50.000000 55.000000   146.391665  133.609346  141.219097  ...
       55.000000 60.000000   123.722522  150.227740  129.660435  ...
       60.000000 65.000000   136.354665  133.454938  137.763005  ...
       65.000000 70.000000   141.750016  145.324966  145.307205  ...
       70.000000 75.000000   143.733054  141.577366  141.067729  ...
       75.000000 80.000000   130.874232  128.052195  137.237723  ...
       80.000000 85.000000   128.774877  132.820308  138.039457  ...
       85.000000 90.000000   136.994602  128.872908  137.616207  ...
       90.000000 95.000000   106.249037  114.580986  107.998177  ...
       95.000000 125.000000  104.101099  101.899419  105.139965  ...

                               draw_485    draw_486    draw_487    draw_488  \
sex    age_start age_end
Female 0.000000  0.019178    148.158842  143.108725  141.183825  145.659528
       0.019178  0.076712    119.937355  115.927150  122.556811  121.588115
       0.076712  0.500000     99.679287  101.404434  103.839107  102.392914
       0.500000  1.000000     98.584190   98.128164   99.681944   99.146289
       1.000000  2.000000    101.224107  101.772763  101.318127  101.532636
       2.000000  5.000000    104.918129  105.133946  104.354045  104.612321
       5.000000  10.000000   120.231450  114.432924  110.502240  106.766019
       10.000000 15.000000   120.030163  116.722073  114.383796  116.518445
       15.000000 20.000000   116.920922  117.565697  117.501441  117.127796
       20.000000 25.000000   115.302969  114.986318  115.443238  116.342303
       25.000000 30.000000   116.704709  116.531208  116.333145  116.156243
       30.000000 35.000000   116.479299  115.161401  115.881622  115.436885
       35.000000 40.000000   115.461690  116.372342  117.086767  115.934798
       40.000000 45.000000   116.819069  115.829972  116.201116  117.608217
       45.000000 50.000000   117.922000  119.059610  118.685848  117.576888
       50.000000 55.000000   115.125934  114.852243  116.901071  121.077797
       55.000000 60.000000   121.994697  114.174437  117.099471  111.779959
       60.000000 65.000000   128.109117  121.635740  124.089725  123.708079
       65.000000 70.000000   124.621956  127.613080  120.253318  119.869281
       70.000000 75.000000   126.781306  122.809045  121.389164  130.405547
       75.000000 80.000000   121.513741  127.488803  131.521214  122.642803
       80.000000 85.000000   124.821075  126.403947  126.214913  126.021307
       85.000000 90.000000   120.594002  120.461586  120.590368  117.553759
       90.000000 95.000000   107.628009  108.363187  104.228011  111.380387
       95.000000 125.000000  107.676782  102.746974  101.886621  109.612358
Male   0.000000  0.019178    151.900134  147.659926  145.972178  161.995751
       0.019178  0.076712    129.370312  113.386824  127.497146  110.661130
       0.076712  0.500000     99.428275  100.607618   93.890265  101.315661
       0.500000  1.000000     95.439500   92.142664   96.758823   98.693111
       1.000000  2.000000     92.062141   95.559719   98.977133   99.034130
       2.000000  5.000000    103.741233  103.930138  101.470737  107.666306
       5.000000  10.000000   120.622369  115.962095  111.688280  117.842470
       10.000000 15.000000   124.982642  121.517526  113.097938  120.704688
       15.000000 20.000000   123.554063  136.182116  127.133344  131.086191
       20.000000 25.000000   143.860193  146.228402  148.868955  132.043034
       25.000000 30.000000   139.850274  150.437736  143.363869  146.783381
       30.000000 35.000000   143.783236  159.611434  143.573741  149.435694
       35.000000 40.000000   144.948825  128.251250  141.106181  143.005238
       40.000000 45.000000   134.943279  147.853756  142.513938  143.624231
       45.000000 50.000000   132.899587  143.124623  153.901949  131.534586
       50.000000 55.000000   138.731094  148.087067  149.458335  142.908689
       55.000000 60.000000   135.338629  139.005111  144.471909  133.303675
       60.000000 65.000000   140.410712  139.010696  130.308095  143.793886
       65.000000 70.000000   136.603900  137.621172  136.052392  139.456403
       70.000000 75.000000   149.563868  137.053116  152.119673  163.158256
       75.000000 80.000000   149.061098  133.667673  139.410706  134.838816
       80.000000 85.000000   143.504264  133.947790  133.962062  139.980380
       85.000000 90.000000   127.024112  123.029800  122.528450  124.441129
       90.000000 95.000000   106.568651  111.126046  122.154788  108.199992
       95.000000 125.000000  104.558724   99.790967   99.893821  102.335976

                               draw_489    draw_490    draw_491    draw_492  \
sex    age_start age_end
Female 0.000000  0.019178    138.089369  140.399313  143.182558  134.555407
       0.019178  0.076712    118.717618  125.158604  121.377385  116.888345
       0.076712  0.500000    102.808211  102.597493  100.522398  102.431276
       0.500000  1.000000    101.534138   98.288392   99.606637  100.119695
       1.000000  2.000000    102.880176  101.100577  100.836094  101.675217
       2.000000  5.000000    105.006839  103.926467  106.277032  105.134380
       5.000000  10.000000   113.429190  116.773722  108.297797  113.539354
       10.000000 15.000000   110.849736  110.076764  117.764986  117.239881
       15.000000 20.000000   117.131486  117.304231  116.404365  117.401352

In [23]:
hemoglobin_mean_disparities = pd.read_csv(f'../0100_data_prep/results/hemoglobin/mean_disparities/{location}.csv')
hemoglobin_mean_disparities = (
    map_to_population_age_groups(hemoglobin_mean_disparities[hemoglobin_mean_disparities.pregnant == "not_pregnant"].drop(columns=["pregnant"]))
        .set_index(["sex", "age_start", "age_end", "wealth_quintile"]).value
)
hemoglobin_mean_disparities

sex     age_start  age_end     wealth_quintile
Female  0.0        0.019178    lowest              97.093264
                               second              99.647180
                               middle             102.658490
                               fourth             103.792784
                               highest            107.778540
                                                     ...
Male    95.0       125.000000  lowest             113.444966
                               second             115.420130
                               middle             116.087185
                               fourth             116.578539
                               highest            118.793246
Name: value, Length: 250, dtype: float64

In [24]:
wealth_quintile_probabilities = pd.read_csv(f'../0100_data_prep/results/wealth_quintile_probabilities/{location}.csv')
wealth_quintile_probabilities

,sex,age_start,age_end,pregnant,lowest,second,middle,fourth,highest
0,Female,0.0,5.0,not_pregnant,0.220707,0.219801,0.207518,0.182416,0.169557
1,Female,5.0,15.0,not_pregnant,0.222903,0.211314,0.200941,0.189893,0.174949
2,Female,15.0,30.0,not_pregnant,0.165248,0.194708,0.200403,0.223650,0.215992
3,Female,15.0,30.0,pregnant,0.229568,0.269087,0.218290,0.169175,0.113880
4,Female,30.0,50.0,not_pregnant,0.167414,0.176150,0.188366,0.214621,0.253449
5,Female,30.0,50.0,pregnant,0.247900,0.197054,0.182014,0.163763,0.209268
6,Female,50.0,125.0,not_pregnant,0.196077,0.184902,0.228885,0.192974,0.197161
7,Male,0.0,5.0,not_pregnant,0.214963,0.223211,0.203137,0.188194,0.170495
8,Male,5.0,15.0,not_pregnant,0.227134,0.211917,0.202795,0.189340,0.168813
9,Male,15.0,30.0,not_pregnant,0.194480,0.197231,0.196587,0.211924,0.199779
10,Male,30.0,50.0,not_pregnant,0.155586,0.166481,0.189007,0.217201,0.271724
11,Male,50.0,125.0,not_pregnant,0.209864,0.183658,0.188784,0.202148,0.215546

In [25]:
wealth_quintile_probabilities = (
    map_to_population_age_groups(wealth_quintile_probabilities[wealth_quintile_probabilities.pregnant == "not_pregnant"].drop(columns=["pregnant"]))
        .set_index(["sex", "age_start", "age_end"])
)
wealth_quintile_probabilities.columns.name = 'wealth_quintile'
wealth_quintile_probabilities = wealth_quintile_probabilities.stack()
wealth_quintile_probabilities

sex     age_start  age_end     wealth_quintile
Female  0.0        0.019178    lowest             0.220707
                               second             0.219801
                               middle             0.207518
                               fourth             0.182416
                               highest            0.169557
                                                    ...
Male    95.0       125.000000  lowest             0.209864
                               second             0.183658
                               middle             0.188784
                               fourth             0.202148
                               highest            0.215546
Length: 250, dtype: float64

In [26]:
assert np.allclose(wealth_quintile_probabilities.groupby(["sex", "age_start", "age_end"]).sum(), 1.0)

In [27]:
pre_disparity_groups = hgb_mean.mul(wealth_quintile_probabilities, axis=0).groupby([c for c in hgb_mean.index.names if c != 'wealth_quintile']).sum()
pre_disparity_groups

                                 draw_0      draw_1      draw_2      draw_3  \
sex    age_start age_end
Female 0.000000  0.019178    140.203331  139.700680  137.486100  143.738463
       0.019178  0.076712    121.992596  122.837138  123.877519  120.604868
       0.076712  0.500000    104.152465  104.343166  100.933682  103.672346
       0.500000  1.000000    100.148802   99.844921   99.645127  100.145850
       1.000000  2.000000    100.955723  100.339208  102.148597  101.234802
       2.000000  5.000000    105.233662  104.333100  102.835176  105.304765
       5.000000  10.000000   119.455834  112.957619  115.682929  114.256919
       10.000000 15.000000   119.312919  106.273992  111.855854  122.097443
       15.000000 20.000000   114.861226  117.794304  116.359602  117.648438
       20.000000 25.000000   116.232257  117.251310  116.393998  114.894111
       25.000000 30.000000   116.082332  114.626063  116.408492  116.811736
       30.000000 35.000000   115.103530  115.163515  116.767807  116.269128
       35.000000 40.000000   115.986054  113.528076  114.852973  114.288218
       40.000000 45.000000   115.257500  117.940598  117.278455  116.853328
       45.000000 50.000000   118.568757  119.048450  117.278407  117.835148
       50.000000 55.000000   115.669641  121.096756  111.909301  123.510802
       55.000000 60.000000   116.888277  111.934668  117.516013  116.335911
       60.000000 65.000000   117.073529  120.448205  112.138824  119.361783
       65.000000 70.000000   120.936133  131.305616  125.299052  121.720141
       70.000000 75.000000   120.728706  120.069195  124.432953  117.908148
       75.000000 80.000000   126.020295  126.733554  121.556975  127.985198
       80.000000 85.000000   126.158836  126.248607  116.366249  123.473284
       85.000000 90.000000   118.780034  118.418548  114.061451  115.310723
       90.000000 95.000000   109.477010  104.789317  110.610979  108.944244
       95.000000 125.000000  102.971577  100.970692   99.657313   98.358658
Male   0.000000  0.019178    139.655000  152.652888  141.405358  135.236759
       0.019178  0.076712    111.875330  122.227176  119.526917  118.369764
       0.076712  0.500000     94.267052   98.335982   96.967303   98.720429
       0.500000  1.000000    100.092403   98.678200   93.913129   99.908232
       1.000000  2.000000    100.226883   94.470196   98.331789   95.255325
       2.000000  5.000000    101.069093  107.942797  103.555610  102.374253
       5.000000  10.000000   119.838610  110.970261  109.073412  112.143982
       10.000000 15.000000   129.595152  119.217013  127.657332  129.642930
       15.000000 20.000000   129.129905  144.220990  141.441577  142.995724
       20.000000 25.000000   151.050744  131.461208  146.612140  132.307327
       25.000000 30.000000   132.425569  149.591271  142.560174  135.773968
       30.000000 35.000000   140.605288  141.846950  135.968545  160.662459
       35.000000 40.000000   138.202586  145.354328  144.617087  133.079794
       40.000000 45.000000   141.806468  145.535717  136.109962  148.130476
       45.000000 50.000000   133.416092  136.101393  150.337119  141.486861
       50.000000 55.000000   144.695059  135.210554  139.837715  139.728713
       55.000000 60.000000   138.257682  142.365263  142.266348  143.671582
       60.000000 65.000000   137.633530  133.990371  143.313102  140.484227
       65.000000 70.000000   143.947810  146.078428  140.887869  134.047618
       70.000000 75.000000   141.462864  144.115084  130.980064  145.225366
       75.000000 80.000000   125.293565  127.635808  121.016674  127.115747
       80.000000 85.000000   136.438006  140.853010  131.367813  139.943361
       85.000000 90.000000   133.029351  120.328832  136.611180  126.391697
       90.000000 95.000000   116.866389  104.222078  111.737153  113.207507
       95.000000 125.000000  104.414752  104.110723   99.482286  102.887575

                                 draw_4      draw_5      draw_6      draw_7  \
sex    age_start age_end
Female 0.000000  0.019178    148.622155  142.898403  135.879741  146.860804
       0.019178  0.076712    118.583369  114.759783  121.062536  115.664404
       0.076712  0.500000    105.214707  102.017120  101.666111  104.391111
       0.500000  1.000000    100.608923  101.012091  100.358797   98.995013
       1.000000  2.000000    100.603498  100.260029  100.667909  100.806325
       2.000000  5.000000    105.698959  105.270406  104.383177  104.944148
       5.000000  10.000000   112.445778  108.129095  115.269360  116.949897
       10.000000 15.000000   112.101844  112.573722  110.628343  111.910474
       15.000000 20.000000   117.718187  118.038089  117.539722  117.631445
       20.000000 25.000000   117.201976  115.441273  115.564658  116.283234
       25.000000 30.000000   118.125046  118.053523  115.809354  115.666409
       30.000000 35.000000   116.706487  115.153682  116.801983  113.712861
       35.000000 40.000000   115.248647  116.584322  116.712603  114.931580
       40.000000 45.000000   115.971911  117.309627  118.413162  117.185406
       45.000000 50.000000   119.888282  119.242264  117.953520  118.917692
       50.000000 55.000000   105.246494  113.013340  113.315487  116.507582
       55.000000 60.000000   116.196913  108.945164  118.153491  111.249024
       60.000000 65.000000   121.980984  114.051134  120.805249  121.372152
       65.000000 70.000000   130.708385  129.355625  125.709029  126.209303
       70.000000 75.000000   122.213798  128.178021  130.401904  130.637428
       75.000000 80.000000   125.280079  126.995331  128.937650  123.316893
       80.000000 85.000000   121.423435  125.664959  123.011669  122.934808
       85.000000 90.000000   116.190198  124.807436  111.070989  119.262830
       90.000000 95.000000   110.272233  102.837675  110.397164  106.996263
       95.000000 125.000000   96.036401  101.532534  102.345743  101.051934
Male   0.000000  0.019178    145.950384  148.051338  145.753920  143.368754
       0.019178  0.076712    110.899432  132.687274  113.096215  110.843494
       0.076712  0.500000    100.392380   97.388312   99.835516  105.483599
       0.500000  1.000000     98.806275   97.043218   90.629506   95.910213
       1.000000  2.000000     97.563575   99.224006   96.391036   99.129051
       2.000000  5.000000    102.478360  105.307768  106.502021   98.257520
       5.000000  10.000000   113.808712  121.817283  116.570179  106.415407
       10.000000 15.000000   112.928565  120.507986  136.626822  127.254933
       15.000000 20.000000   134.893712  135.590220  134.734586  130.920151
       20.000000 25.000000   140.617992  134.857577  143.955917  150.234689
       25.000000 30.000000   155.446834  152.764731  154.675099  152.349818
       30.000000 35.000000   139.997667  137.561719  142.785512  150.152448
       35.000000 40.000000   149.194421  145.240541  130.272282  149.016715
       40.000000 45.000000   131.555709  148.512512  140.948951  140.280393
       45.000000 50.000000   138.002726  147.616175  143.353695  148.856435
       50.000000 55.000000   128.840348  141.879073  128.012092  143.710892
       55.000000 60.000000   142.116835  142.340961  132.625360  131.458105
       60.000000 65.000000   137.657843  149.676107  137.490021  138.255288
       65.000000 70.000000   138.305347  143.738034  144.738884  146.325436
       70.000000 75.000000   139.549364  138.368488  141.333839  131.561358
       75.000000 80.000000   138.057306  124.135326  131.351376  140.422146
       80.000000 85.000000   136.350483  131.038066  123.096959  137.390001
       85.000000 90.000000   129.370208  136.797710  127.729441  121.481892
       90.000000 95.000000   106.352527   98.297926  113.236702  105.723986
       95.000000 125.000000  107.603354  105.459291  103.255580  110.455551

                                 draw_8      draw_9     draw_10     draw_11  \
sex    age_start age_end
Female 0.000000  0.019178    148.441575  136.598751  141.466550  138.089184
       0.019178  0.076712    113.872047  118.315783  119.589692  117.163783
       0.076712  0.500000    101.872444  103.526095  101.283339  103.663214
       0.500000  1.000000     99.743129  100.867444  100.802132   99.360873
       1.000000  2.000000    101.008100   99.686666   99.714662  100.772973
       2.000000  5.000000    104.233312  106.923858  103.931931  104.222128
       5.000000  10.000000   116.004710  113.079119  110.131016  113.399954
       10.000000 15.000000   109.547810  115.805717  112.611635  116.003393
       15.000000 20.000000   117.140323  116.770157  116.720418  117.249697
       20.000000 25.000000   116.316618  117.074015  115.365220  115.648786
       25.000000 30.000000   117.056230  115.181358  116.837717  116.757552
       30.000000 35.000000   115.813215  114.817594  113.653704  115.341602
       35.000000 40.000000   115.667189  116.278426  116.681642  118.095610
       40.000000 45.000000   117.077432  117.657980  117.054500  116.975735
       45.000000 50.000000   117.489349  119.521306  119.418178  118.604975
       50.000000 55.000000   115.821738  117.970520  112.586683  107.338111
       55.000000 60.000000   117.338496  116.239039  115.204805  116.056558
       60.000000 65.000000   117.384561  119.873163  113.489156  116.758345
       65.000000 70.000000   121.546710  122.603228  130.165223  122.009977
       70.000000 75.000000   121.612261  126.719624  127.652742  126.543977
       75.000000 80.000000   124.858928  126.612797  125.403155  118.701534
       80.000000 85.000000   127.697045  119.799646  120.019189  119.549908
       85.000000 90.000000   117.795365  126.255445  111.993769  118.694922
       90.000000 95.000000   113.492466  112.580471  110.611752  105.897065
       95.000000 125.000000  100.307373   98.663466  102.553751   97.456725
Male   0.000000  0.019178    148.505532  149.271473  150.363622  135.086188
       0.019178  0.076712    116.429972  122.955986  128.089332  117.348339
       0.076712  0.500000     97.071404   97.055824  100.354579  102.827298
       0.500000  1.000000     94.262673   97.302075   97.875045   97.561767
       1.000000  2.000000     93.744372   96.324011  101.993191  100.080094
       2.000000  5.000000    102.124309  100.409932  103.983532  102.920718
       5.000000  10.000000   110.620094  111.324468  107.668301  107.006246
       10.000000 15.000000   114.645329  120.478304  121.805357  119.113806
       15.000000 20.000000   140.395444  145.143500  132.886093  146.887070
       20.000000 25.000000   138.525246  150.619108  145.954753  133.518881
       25.000000 30.000000   136.539225  149.159022  134.084235  152.577941
       30.000000 35.000000   151.069363  149.089416  146.875961  147.048821
       35.000000 40.000000   134.838400  137.859408  145.256161  143.353014
       40.000000 45.000000   142.162264  163.478077  144.007176  136.568286
       45.000000 50.000000   126.762191  141.755796  148.495302  140.141041
       50.000000 55.000000   140.694183  130.967252  127.929693  135.280819
       55.000000 60.000000   134.607110  132.374558  133.299788  133.288925
       60.000000 65.000000   134.467162  132.907559  133.728541  136.444556
       65.000000 70.000000   141.687655  137.607029  146.345463  143.516944
       70.000000 75.000000   140.272928  141.656767  133.897411  139.386611
       75.000000 80.000000   134.386319  133.184690  141.882365  135.301478
       80.000000 85.000000   135.796309  130.850945  137.295287  134.727373
       85.000000 90.000000   124.340741  129.907846  130.052311  136.490227
       90.000000 95.000000   114.701460  109.299417  110.747712  111.304806
       95.000000 125.000000  105.846010  113.724775   93.089021  107.019766

                                draw_12     draw_13     draw_14  ...  \
sex    age_start age_end                                         ...
Female 0.000000  0.019178    138.401927  137.448153  145.690438  ...
       0.019178  0.076712    115.086902  129.699933  118.144320  ...
       0.076712  0.500000    101.193666  100.801412  102.098223  ...
       0.500000  1.000000    100.678774  100.171735   99.245162  ...
       1.000000  2.000000    100.699001  101.696056   99.871979  ...
       2.000000  5.000000    106.051692  104.640680  103.694541  ...
       5.000000  10.000000   111.877002  117.352725  116.644265  ...
       10.000000 15.000000   117.517359  109.337545  112.435858  ...
       15.000000 20.000000   117.732660  117.377174  115.036573  ...
       20.000000 25.000000   117.322746  114.522481  117.394546  ...
       25.000000 30.000000   116.844960  117.919896  115.795500  ...
       30.000000 35.000000   113.943478  116.351574  115.005835  ...
       35.000000 40.000000   115.574220  115.979558  115.805756  ...
       40.000000 45.000000   117.157656  118.107750  116.236390  ...
       45.000000 50.000000   117.847856  117.377386  116.803793  ...
       50.000000 55.000000   118.392422  118.114204  120.903323  ...
       55.000000 60.000000   114.129473  116.346613  113.083471  ...
       60.000000 65.000000   120.184594  126.069878  127.089311  ...
       65.000000 70.000000   127.523037  123.574835  124.362464  ...
       70.000000 75.000000   123.135847  124.790998  125.936801  ...
       75.000000 80.000000   116.755162  121.424450  124.002985  ...
       80.000000 85.000000   116.893657  121.330004  122.393335  ...
       85.000000 90.000000   119.468646  112.054621  122.471296  ...
       90.000000 95.000000   105.221954  105.872161  106.524521  ...
       95.000000 125.000000   98.114855  104.579160  100.657417  ...
Male   0.000000  0.019178    159.586357  137.677792  151.960142  ...
       0.019178  0.076712    103.723857  129.776858  121.710994  ...
       0.076712  0.500000    102.819068  103.065592   98.066537  ...
       0.500000  1.000000     95.587779   96.588824   98.730787  ...
       1.000000  2.000000     97.572005   96.942734  106.497842  ...
       2.000000  5.000000    101.970571  102.331105  104.527396  ...
       5.000000  10.000000   110.726687  116.066721  104.095569  ...
       10.000000 15.000000   113.115182  114.215649  116.258365  ...
       15.000000 20.000000   140.595584  138.607096  144.538106  ...
       20.000000 25.000000   142.796583  151.875038  140.009641  ...
       25.000000 30.000000   142.661891  148.438973  138.114751  ...
       30.000000 35.000000   138.802514  136.349820  151.906280  ...
       35.000000 40.000000   129.473316  137.907653  132.718411  ...
       40.000000 45.000000   140.707200  131.780923  129.703159  ...
       45.000000 50.000000   155.770919  155.526978  128.705201  ...
       50.000000 55.000000   146.391665  133.609346  141.219097  ...
       55.000000 60.000000   123.722522  150.227740  129.660435  ...
       60.000000 65.000000   136.354665  133.454938  137.763005  ...
       65.000000 70.000000   141.750016  145.324966  145.307205  ...
       70.000000 75.000000   143.733054  141.577366  141.067729  ...
       75.000000 80.000000   130.874232  128.052195  137.237723  ...
       80.000000 85.000000   128.774877  132.820308  138.039457  ...
       85.000000 90.000000   136.994602  128.872908  137.616207  ...
       90.000000 95.000000   106.249037  114.580986  107.998177  ...
       95.000000 125.000000  104.101099  101.899419  105.139965  ...

                               draw_485    draw_486    draw_487    draw_488  \
sex    age_start age_end
Female 0.000000  0.019178    148.158842  143.108725  141.183825  145.659528
       0.019178  0.076712    119.937355  115.927150  122.556811  121.588115
       0.076712  0.500000     99.679287  101.404434  103.839107  102.392914
       0.500000  1.000000     98.584190   98.128164   99.681944   99.146289
       1.000000  2.000000    101.224107  101.772763  101.318127  101.532636
       2.000000  5.000000    104.918129  105.133946  104.354045  104.612321
       5.000000  10.000000   120.231450  114.432924  110.502240  106.766019
       10.000000 15.000000   120.030163  116.722073  114.383796  116.518445
       15.000000 20.000000   116.920922  117.565697  117.501441  117.127796
       20.000000 25.000000   115.302969  114.986318  115.443238  116.342303
       25.000000 30.000000   116.704709  116.531208  116.333145  116.156243
       30.000000 35.000000   116.479299  115.161401  115.881622  115.436885
       35.000000 40.000000   115.461690  116.372342  117.086767  115.934798
       40.000000 45.000000   116.819069  115.829972  116.201116  117.608217
       45.000000 50.000000   117.922000  119.059610  118.685848  117.576888
       50.000000 55.000000   115.125934  114.852243  116.901071  121.077797
       55.000000 60.000000   121.994697  114.174437  117.099471  111.779959
       60.000000 65.000000   128.109117  121.635740  124.089725  123.708079
       65.000000 70.000000   124.621956  127.613080  120.253318  119.869281
       70.000000 75.000000   126.781306  122.809045  121.389164  130.405547
       75.000000 80.000000   121.513741  127.488803  131.521214  122.642803
       80.000000 85.000000   124.821075  126.403947  126.214913  126.021307
       85.000000 90.000000   120.594002  120.461586  120.590368  117.553759
       90.000000 95.000000   107.628009  108.363187  104.228011  111.380387
       95.000000 125.000000  107.676782  102.746974  101.886621  109.612358
Male   0.000000  0.019178    151.900134  147.659926  145.972178  161.995751
       0.019178  0.076712    129.370312  113.386824  127.497146  110.661130
       0.076712  0.500000     99.428275  100.607618   93.890265  101.315661
       0.500000  1.000000     95.439500   92.142664   96.758823   98.693111
       1.000000  2.000000     92.062141   95.559719   98.977133   99.034130
       2.000000  5.000000    103.741233  103.930138  101.470737  107.666306
       5.000000  10.000000   120.622369  115.962095  111.688280  117.842470
       10.000000 15.000000   124.982642  121.517526  113.097938  120.704688
       15.000000 20.000000   123.554063  136.182116  127.133344  131.086191
       20.000000 25.000000   143.860193  146.228402  148.868955  132.043034
       25.000000 30.000000   139.850274  150.437736  143.363869  146.783381
       30.000000 35.000000   143.783236  159.611434  143.573741  149.435694
       35.000000 40.000000   144.948825  128.251250  141.106181  143.005238
       40.000000 45.000000   134.943279  147.853756  142.513938  143.624231
       45.000000 50.000000   132.899587  143.124623  153.901949  131.534586
       50.000000 55.000000   138.731094  148.087067  149.458335  142.908689
       55.000000 60.000000   135.338629  139.005111  144.471909  133.303675
       60.000000 65.000000   140.410712  139.010696  130.308095  143.793886
       65.000000 70.000000   136.603900  137.621172  136.052392  139.456403
       70.000000 75.000000   149.563868  137.053116  152.119673  163.158256
       75.000000 80.000000   149.061098  133.667673  139.410706  134.838816
       80.000000 85.000000   143.504264  133.947790  133.962062  139.980380
       85.000000 90.000000   127.024112  123.029800  122.528450  124.441129
       90.000000 95.000000   106.568651  111.126046  122.154788  108.199992
       95.000000 125.000000  104.558724   99.790967   99.893821  102.335976

                               draw_489    draw_490    draw_491    draw_492  \
sex    age_start age_end
Female 0.000000  0.019178    138.089369  140.399313  143.182558  134.555407
       0.019178  0.076712    118.717618  125.158604  121.377385  116.888345
       0.076712  0.500000    102.808211  102.597493  100.522398  102.431276
       0.500000  1.000000    101.534138   98.288392   99.606637  100.119695
       1.000000  2.000000    102.880176  101.100577  100.836094  101.675217
       2.000000  5.000000    105.006839  103.926467  106.277032  105.134380
       5.000000  10.000000   113.429190  116.773722  108.297797  113.539354
       10.000000 15.000000   110.849736  110.076764  117.764986  117.239881
       15.000000 20.000000   117.131486  117.304231  116.404365  117.401352

In [28]:
hgb_mean = hgb_mean.mul(hemoglobin_mean_disparities, axis=0)

In [29]:
scale_factor = pre_disparity_groups / hgb_mean.mul(wealth_quintile_probabilities, axis=0).groupby([c for c in hgb_mean.index.names if c != 'wealth_quintile']).sum()
scale_factor

                               draw_0    draw_1    draw_2    draw_3    draw_4  \
sex    age_start age_end
Female 0.000000  0.019178    0.009819  0.009819  0.009819  0.009819  0.009819
       0.019178  0.076712    0.009819  0.009819  0.009819  0.009819  0.009819
       0.076712  0.500000    0.009819  0.009819  0.009819  0.009819  0.009819
       0.500000  1.000000    0.009819  0.009819  0.009819  0.009819  0.009819
       1.000000  2.000000    0.009819  0.009819  0.009819  0.009819  0.009819
       2.000000  5.000000    0.009819  0.009819  0.009819  0.009819  0.009819
       5.000000  10.000000   0.009182  0.009182  0.009182  0.009182  0.009182
       10.000000 15.000000   0.009182  0.009182  0.009182  0.009182  0.009182
       15.000000 20.000000   0.008605  0.008605  0.008605  0.008605  0.008605
       20.000000 25.000000   0.008605  0.008605  0.008605  0.008605  0.008605
       25.000000 30.000000   0.008605  0.008605  0.008605  0.008605  0.008605
       30.000000 35.000000   0.008597  0.008597  0.008597  0.008597  0.008597
       35.000000 40.000000   0.008597  0.008597  0.008597  0.008597  0.008597
       40.000000 45.000000   0.008597  0.008597  0.008597  0.008597  0.008597
       45.000000 50.000000   0.008597  0.008597  0.008597  0.008597  0.008597
       50.000000 55.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       55.000000 60.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       60.000000 65.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       65.000000 70.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       70.000000 75.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       75.000000 80.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       80.000000 85.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       85.000000 90.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       90.000000 95.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       95.000000 125.000000  0.008615  0.008615  0.008615  0.008615  0.008615
Male   0.000000  0.019178    0.009962  0.009962  0.009962  0.009962  0.009962
       0.019178  0.076712    0.009962  0.009962  0.009962  0.009962  0.009962
       0.076712  0.500000    0.009962  0.009962  0.009962  0.009962  0.009962
       0.500000  1.000000    0.009962  0.009962  0.009962  0.009962  0.009962
       1.000000  2.000000    0.009962  0.009962  0.009962  0.009962  0.009962
       2.000000  5.000000    0.009962  0.009962  0.009962  0.009962  0.009962
       5.000000  10.000000   0.009250  0.009250  0.009250  0.009250  0.009250
       10.000000 15.000000   0.009250  0.009250  0.009250  0.009250  0.009250
       15.000000 20.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       20.000000 25.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       25.000000 30.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       30.000000 35.000000   0.008591  0.008591  0.008591  0.008591  0.008591
       35.000000 40.000000   0.008591  0.008591  0.008591  0.008591  0.008591
       40.000000 45.000000   0.008591  0.008591  0.008591  0.008591  0.008591
       45.000000 50.000000   0.008591  0.008591  0.008591  0.008591  0.008591
       50.000000 55.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       55.000000 60.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       60.000000 65.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       65.000000 70.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       70.000000 75.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       75.000000 80.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       80.000000 85.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       85.000000 90.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       90.000000 95.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       95.000000 125.000000  0.008614  0.008614  0.008614  0.008614  0.008614

                               draw_5    draw_6    draw_7    draw_8    draw_9  \
sex    age_start age_end
Female 0.000000  0.019178    0.009819  0.009819  0.009819  0.009819  0.009819
       0.019178  0.076712    0.009819  0.009819  0.009819  0.009819  0.009819
       0.076712  0.500000    0.009819  0.009819  0.009819  0.009819  0.009819
       0.500000  1.000000    0.009819  0.009819  0.009819  0.009819  0.009819
       1.000000  2.000000    0.009819  0.009819  0.009819  0.009819  0.009819
       2.000000  5.000000    0.009819  0.009819  0.009819  0.009819  0.009819
       5.000000  10.000000   0.009182  0.009182  0.009182  0.009182  0.009182
       10.000000 15.000000   0.009182  0.009182  0.009182  0.009182  0.009182
       15.000000 20.000000   0.008605  0.008605  0.008605  0.008605  0.008605
       20.000000 25.000000   0.008605  0.008605  0.008605  0.008605  0.008605
       25.000000 30.000000   0.008605  0.008605  0.008605  0.008605  0.008605
       30.000000 35.000000   0.008597  0.008597  0.008597  0.008597  0.008597
       35.000000 40.000000   0.008597  0.008597  0.008597  0.008597  0.008597
       40.000000 45.000000   0.008597  0.008597  0.008597  0.008597  0.008597
       45.000000 50.000000   0.008597  0.008597  0.008597  0.008597  0.008597
       50.000000 55.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       55.000000 60.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       60.000000 65.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       65.000000 70.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       70.000000 75.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       75.000000 80.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       80.000000 85.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       85.000000 90.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       90.000000 95.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       95.000000 125.000000  0.008615  0.008615  0.008615  0.008615  0.008615
Male   0.000000  0.019178    0.009962  0.009962  0.009962  0.009962  0.009962
       0.019178  0.076712    0.009962  0.009962  0.009962  0.009962  0.009962
       0.076712  0.500000    0.009962  0.009962  0.009962  0.009962  0.009962
       0.500000  1.000000    0.009962  0.009962  0.009962  0.009962  0.009962
       1.000000  2.000000    0.009962  0.009962  0.009962  0.009962  0.009962
       2.000000  5.000000    0.009962  0.009962  0.009962  0.009962  0.009962
       5.000000  10.000000   0.009250  0.009250  0.009250  0.009250  0.009250
       10.000000 15.000000   0.009250  0.009250  0.009250  0.009250  0.009250
       15.000000 20.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       20.000000 25.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       25.000000 30.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       30.000000 35.000000   0.008591  0.008591  0.008591  0.008591  0.008591
       35.000000 40.000000   0.008591  0.008591  0.008591  0.008591  0.008591
       40.000000 45.000000   0.008591  0.008591  0.008591  0.008591  0.008591
       45.000000 50.000000   0.008591  0.008591  0.008591  0.008591  0.008591
       50.000000 55.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       55.000000 60.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       60.000000 65.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       65.000000 70.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       70.000000 75.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       75.000000 80.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       80.000000 85.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       85.000000 90.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       90.000000 95.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       95.000000 125.000000  0.008614  0.008614  0.008614  0.008614  0.008614

                              draw_10   draw_11   draw_12   draw_13   draw_14  \
sex    age_start age_end
Female 0.000000  0.019178    0.009819  0.009819  0.009819  0.009819  0.009819
       0.019178  0.076712    0.009819  0.009819  0.009819  0.009819  0.009819
       0.076712  0.500000    0.009819  0.009819  0.009819  0.009819  0.009819
       0.500000  1.000000    0.009819  0.009819  0.009819  0.009819  0.009819
       1.000000  2.000000    0.009819  0.009819  0.009819  0.009819  0.009819
       2.000000  5.000000    0.009819  0.009819  0.009819  0.009819  0.009819
       5.000000  10.000000   0.009182  0.009182  0.009182  0.009182  0.009182
       10.000000 15.000000   0.009182  0.009182  0.009182  0.009182  0.009182
       15.000000 20.000000   0.008605  0.008605  0.008605  0.008605  0.008605
       20.000000 25.000000   0.008605  0.008605  0.008605  0.008605  0.008605
       25.000000 30.000000   0.008605  0.008605  0.008605  0.008605  0.008605
       30.000000 35.000000   0.008597  0.008597  0.008597  0.008597  0.008597
       35.000000 40.000000   0.008597  0.008597  0.008597  0.008597  0.008597
       40.000000 45.000000   0.008597  0.008597  0.008597  0.008597  0.008597
       45.000000 50.000000   0.008597  0.008597  0.008597  0.008597  0.008597
       50.000000 55.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       55.000000 60.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       60.000000 65.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       65.000000 70.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       70.000000 75.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       75.000000 80.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       80.000000 85.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       85.000000 90.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       90.000000 95.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       95.000000 125.000000  0.008615  0.008615  0.008615  0.008615  0.008615
Male   0.000000  0.019178    0.009962  0.009962  0.009962  0.009962  0.009962
       0.019178  0.076712    0.009962  0.009962  0.009962  0.009962  0.009962
       0.076712  0.500000    0.009962  0.009962  0.009962  0.009962  0.009962
       0.500000  1.000000    0.009962  0.009962  0.009962  0.009962  0.009962
       1.000000  2.000000    0.009962  0.009962  0.009962  0.009962  0.009962
       2.000000  5.000000    0.009962  0.009962  0.009962  0.009962  0.009962
       5.000000  10.000000   0.009250  0.009250  0.009250  0.009250  0.009250
       10.000000 15.000000   0.009250  0.009250  0.009250  0.009250  0.009250
       15.000000 20.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       20.000000 25.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       25.000000 30.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       30.000000 35.000000   0.008591  0.008591  0.008591  0.008591  0.008591
       35.000000 40.000000   0.008591  0.008591  0.008591  0.008591  0.008591
       40.000000 45.000000   0.008591  0.008591  0.008591  0.008591  0.008591
       45.000000 50.000000   0.008591  0.008591  0.008591  0.008591  0.008591
       50.000000 55.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       55.000000 60.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       60.000000 65.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       65.000000 70.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       70.000000 75.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       75.000000 80.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       80.000000 85.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       85.000000 90.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       90.000000 95.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       95.000000 125.000000  0.008614  0.008614  0.008614  0.008614  0.008614

                             ...  draw_485  draw_486  draw_487  draw_488  \
sex    age_start age_end     ...
Female 0.000000  0.019178    ...  0.009819  0.009819  0.009819  0.009819
       0.019178  0.076712    ...  0.009819  0.009819  0.009819  0.009819
       0.076712  0.500000    ...  0.009819  0.009819  0.009819  0.009819
       0.500000  1.000000    ...  0.009819  0.009819  0.009819  0.009819
       1.000000  2.000000    ...  0.009819  0.009819  0.009819  0.009819
       2.000000  5.000000    ...  0.009819  0.009819  0.009819  0.009819
       5.000000  10.000000   ...  0.009182  0.009182  0.009182  0.009182
       10.000000 15.000000   ...  0.009182  0.009182  0.009182  0.009182
       15.000000 20.000000   ...  0.008605  0.008605  0.008605  0.008605
       20.000000 25.000000   ...  0.008605  0.008605  0.008605  0.008605
       25.000000 30.000000   ...  0.008605  0.008605  0.008605  0.008605
       30.000000 35.000000   ...  0.008597  0.008597  0.008597  0.008597
       35.000000 40.000000   ...  0.008597  0.008597  0.008597  0.008597
       40.000000 45.000000   ...  0.008597  0.008597  0.008597  0.008597
       45.000000 50.000000   ...  0.008597  0.008597  0.008597  0.008597
       50.000000 55.000000   ...  0.008615  0.008615  0.008615  0.008615
       55.000000 60.000000   ...  0.008615  0.008615  0.008615  0.008615
       60.000000 65.000000   ...  0.008615  0.008615  0.008615  0.008615
       65.000000 70.000000   ...  0.008615  0.008615  0.008615  0.008615
       70.000000 75.000000   ...  0.008615  0.008615  0.008615  0.008615
       75.000000 80.000000   ...  0.008615  0.008615  0.008615  0.008615
       80.000000 85.000000   ...  0.008615  0.008615  0.008615  0.008615
       85.000000 90.000000   ...  0.008615  0.008615  0.008615  0.008615
       90.000000 95.000000   ...  0.008615  0.008615  0.008615  0.008615
       95.000000 125.000000  ...  0.008615  0.008615  0.008615  0.008615
Male   0.000000  0.019178    ...  0.009962  0.009962  0.009962  0.009962
       0.019178  0.076712    ...  0.009962  0.009962  0.009962  0.009962
       0.076712  0.500000    ...  0.009962  0.009962  0.009962  0.009962
       0.500000  1.000000    ...  0.009962  0.009962  0.009962  0.009962
       1.000000  2.000000    ...  0.009962  0.009962  0.009962  0.009962
       2.000000  5.000000    ...  0.009962  0.009962  0.009962  0.009962
       5.000000  10.000000   ...  0.009250  0.009250  0.009250  0.009250
       10.000000 15.000000   ...  0.009250  0.009250  0.009250  0.009250
       15.000000 20.000000   ...  0.008614  0.008614  0.008614  0.008614
       20.000000 25.000000   ...  0.008614  0.008614  0.008614  0.008614
       25.000000 30.000000   ...  0.008614  0.008614  0.008614  0.008614
       30.000000 35.000000   ...  0.008591  0.008591  0.008591  0.008591
       35.000000 40.000000   ...  0.008591  0.008591  0.008591  0.008591
       40.000000 45.000000   ...  0.008591  0.008591  0.008591  0.008591
       45.000000 50.000000   ...  0.008591  0.008591  0.008591  0.008591
       50.000000 55.000000   ...  0.008614  0.008614  0.008614  0.008614
       55.000000 60.000000   ...  0.008614  0.008614  0.008614  0.008614
       60.000000 65.000000   ...  0.008614  0.008614  0.008614  0.008614
       65.000000 70.000000   ...  0.008614  0.008614  0.008614  0.008614
       70.000000 75.000000   ...  0.008614  0.008614  0.008614  0.008614
       75.000000 80.000000   ...  0.008614  0.008614  0.008614  0.008614
       80.000000 85.000000   ...  0.008614  0.008614  0.008614  0.008614
       85.000000 90.000000   ...  0.008614  0.008614  0.008614  0.008614
       90.000000 95.000000   ...  0.008614  0.008614  0.008614  0.008614
       95.000000 125.000000  ...  0.008614  0.008614  0.008614  0.008614

                             draw_489  draw_490  draw_491  draw_492  draw_493  \
sex    age_start age_end
Female 0.000000  0.019178    0.009819  0.009819  0.009819  0.009819  0.009819
       0.019178  0.076712    0.009819  0.009819  0.009819  0.009819  0.009819
       0.076712  0.500000    0.009819  0.009819  0.009819  0.009819  0.009819
       0.500000  1.000000    0.009819  0.009819  0.009819  0.009819  0.009819
       1.000000  2.000000    0.009819  0.009819  0.009819  0.009819  0.009819
       2.000000  5.000000    0.009819  0.009819  0.009819  0.009819  0.009819
       5.000000  10.000000   0.009182  0.009182  0.009182  0.009182  0.009182
       10.000000 15.000000   0.009182  0.009182  0.009182  0.009182  0.009182
       15.000000 20.000000   0.008605  0.008605  0.008605  0.008605  0.008605
       20.000000 25.000000   0.008605  0.008605  0.008605  0.008605  0.008605
       25.000000 30.000000   0.008605  0.008605  0.008605  0.008605  0.008605
       30.000000 35.000000   0.008597  0.008597  0.008597  0.008597  0.008597
       35.000000 40.000000   0.008597  0.008597  0.008597  0.008597  0.008597
       40.000000 45.000000   0.008597  0.008597  0.008597  0.008597  0.008597
       45.000000 50.000000   0.008597  0.008597  0.008597  0.008597  0.008597
       50.000000 55.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       55.000000 60.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       60.000000 65.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       65.000000 70.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       70.000000 75.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       75.000000 80.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       80.000000 85.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       85.000000 90.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       90.000000 95.000000   0.008615  0.008615  0.008615  0.008615  0.008615
       95.000000 125.000000  0.008615  0.008615  0.008615  0.008615  0.008615
Male   0.000000  0.019178    0.009962  0.009962  0.009962  0.009962  0.009962
       0.019178  0.076712    0.009962  0.009962  0.009962  0.009962  0.009962
       0.076712  0.500000    0.009962  0.009962  0.009962  0.009962  0.009962
       0.500000  1.000000    0.009962  0.009962  0.009962  0.009962  0.009962
       1.000000  2.000000    0.009962  0.009962  0.009962  0.009962  0.009962
       2.000000  5.000000    0.009962  0.009962  0.009962  0.009962  0.009962
       5.000000  10.000000   0.009250  0.009250  0.009250  0.009250  0.009250
       10.000000 15.000000   0.009250  0.009250  0.009250  0.009250  0.009250
       15.000000 20.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       20.000000 25.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       25.000000 30.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       30.000000 35.000000   0.008591  0.008591  0.008591  0.008591  0.008591
       35.000000 40.000000   0.008591  0.008591  0.008591  0.008591  0.008591
       40.000000 45.000000   0.008591  0.008591  0.008591  0.008591  0.008591
       45.000000 50.000000   0.008591  0.008591  0.008591  0.008591  0.008591
       50.000000 55.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       55.000000 60.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       60.000000 65.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       65.000000 70.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       70.000000 75.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       75.000000 80.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       80.000000 85.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       85.000000 90.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       90.000000 95.000000   0.008614  0.008614  0.008614  0.008614  0.008614
       95.000000 125.000000  0.008614  0.008614  0.008614  0.008614  0.008614

                             draw_494  draw_495  draw_496  draw_497  draw_498  \
sex    age_start age_end
Female 0.000000  0.019178    0.009819  0.009819  0.009819  0.009819  0.009819

In [30]:
hgb_mean = hgb_mean * scale_factor

In [31]:
assert np.allclose(
    hgb_mean.mul(wealth_quintile_probabilities, axis=0).groupby([c for c in hgb_mean.index.names if c != 'wealth_quintile']).sum(),
    pre_disparity_groups,
)

In [32]:
counterfactual_hgb_mean = hgb_mean.add(delta_effective_coverage * fortification_hemoglobin_mean_difference, axis=0)
counterfactual_hgb_mean

                                                 draw_0      draw_1  \
sex    age_start age_end    wealth_quintile
Female 0.0       0.019178   fourth           143.295931  142.783659
                            highest          148.667085  148.135141
                            lowest           134.515409  134.036202
                            middle           141.817956  141.311282
                            second           137.847824  137.356013
...                                                 ...         ...
Male   95.0      125.000000 fourth           105.260577  104.955276
                            highest          107.136639  106.825538
                            lowest           102.884631  102.587537
                            middle           104.902207  104.598194
                            second           104.477659  104.175392

                                                 draw_2      draw_3  \
sex    age_start age_end    wealth_quintile
Female 0.0       0.019178   fourth           140.526689  146.898731
                            highest          145.791501  152.408236
                            lowest           131.924913  137.885659
                            middle           139.078978  145.381383
                            second           135.189189  141.306724
...                                                 ...         ...
Male   95.0      125.000000 fourth           100.307472  103.727010
                            highest          102.089437  105.573938
                            lowest            98.064663  101.392286
                            middle            99.969979  103.375104
                            second            99.573772  102.959331

                                                 draw_4      draw_5  \
sex    age_start age_end    wealth_quintile
Female 0.0       0.019178   fourth           151.875902  146.042591
                            highest          157.576537  151.519220
                            lowest           142.541568  137.084780
                            middle           150.304162  144.534600
                            second           146.085101  140.484779
...                                                 ...         ...
Male   95.0      125.000000 fourth           108.462520  106.309486
                            highest          110.399412  108.205475
                            lowest           106.000508  103.905347
                            middle           108.090656  105.946696
                            second           107.647786  105.516146

                                                 draw_6      draw_7  \
sex    age_start age_end    wealth_quintile
Female 0.0       0.019178   fourth           138.889582  150.080837
                            highest          144.091528  155.712539
                            lowest           130.393477  140.862369
                            middle           137.459762  148.528714
                            second           133.617470  144.361733
...                                                 ...         ...
Male   95.0      125.000000 fourth           104.096555  111.326653
                            highest          105.950503  113.317955
                            lowest           101.751898  108.787654
                            middle           103.743092  110.942716
                            second           103.325204  110.483458

                                                 draw_8      draw_9  \
sex    age_start age_end    wealth_quintile
Female 0.0       0.019178   fourth           151.691866  139.622355
                            highest          157.385434  144.852440
                            lowest           142.369412  131.078952
                            middle           150.122137  138.184527
                            second           145.908416  134.320975
...                                                 ...         ...
Male   95.0      125.000000 fourth           106.697823  114.609556
                            highest          108.601190  116.663226
                            lowest           104.283245  111.982314
                            middle           106.333396  114.211783
                            second           105.900624  113.733740

                                                draw_10     draw_11  \
sex    age_start age_end    wealth_quintile
Female 0.0       0.019178   fourth           144.583330  141.141317
                            highest          150.003922  146.429732
                            lowest           135.719710  132.499869
                            middle           143.091286  139.686889
                            second           139.083803  135.779268
...                                                 ...         ...
Male   95.0      125.000000 fourth            93.887456  107.876491
                            highest           95.547457  109.802249
                            lowest            91.817215  105.430231
                            middle            93.577022  107.507096
                            second            93.217551  107.067580

                                                draw_12     draw_13  \
sex    age_start age_end    wealth_quintile
Female 0.0       0.019178   fourth           141.460046  140.488015
                            highest          146.760700  145.751343
                            lowest           132.798025  131.888736
                            middle           140.002134  139.040727
                            second           136.085266  135.152060
...                                                 ...         ...
Male   95.0      125.000000 fourth           104.945612  102.734719
                            highest          106.815690  104.562796
                            lowest           102.578132  100.426667
                            middle           104.588570  102.386996
                            second           104.165824  101.976901

                                                draw_14  ...    draw_485  \
sex    age_start age_end    wealth_quintile              ...
Female 0.0       0.019178   fourth           148.888069  ...  151.403721
                            highest          154.473967  ...  157.086223
                            lowest           139.746591  ...  142.099865
                            middle           147.348981  ...  149.837141
                            second           143.216606  ...  145.631779
...                                                 ...  ...         ...
Male   95.0      125.000000 fourth           105.988825  ...  105.405151
                            highest          107.878722  ...  107.283960
                            lowest           103.593304  ...  103.025319
                            middle           105.627386  ...  105.046172
                            second           105.198671  ...  104.620797

                                               draw_486    draw_487  \
sex    age_start age_end    wealth_quintile
Female 0.0       0.019178   fourth           146.256938  144.295193
                            highest          151.741798  149.704721
                            lowest           137.285292  135.450172
                            middle           144.746604  142.806299
                            second           140.690565  138.807175
...                                                 ...         ...
Male   95.0      125.000000 fourth           100.617445  100.720729
                            highest          102.405299  102.510545
                            lowest            98.366304   98.466812
                            middle           100.278645  100.381494
                            second            99.880665   99.982923

                                               draw_488    draw_489  \
sex    age_start age_end    wealth_quintile
Female 0.0       0.019178   fourth           148.856567  141.141505
                            highest          154.441256  146.429927
                            lowest           139.717123  132.500045
                            middle           147.317823  139.687075
                            second           143.186362  135.779449
...                                                 ...         ...
Male   95.0      125.000000 fourth           103.173103   99.735903
                            highest          105.009508  101.507009
                            lowest           100.853268   97.508458
                            middle           102.823532   99.400819
                            second           102.410928   99.007882

                                               draw_490    draw_491  \
sex    age_start age_end    wealth_quintile
Female 0.0       0.019178   fourth           143.495665  146.332185
                            highest          148.874489  151.819935
                            lowest           134.702251  137.355682
                            middle           142.015507  144.821029
                            second           138.039580  140.762807
...                                                 ...         ...
Male   95.0      125.000000 fourth           107.165671  107.828102
                            highest          109.077925  109.752941
                            lowest           104.738518  105.383143
                            middle           106.799272  107.458911
                            second           106.363823  107.019672

                                               draw_492    draw_493  \
sex    age_start age_end    wealth_quintile
Female 0.0       0.019178   fourth           137.539899  147.361125
                            highest          142.690015  152.888387
                            lowest           129.130912  138.318207
                            middle           136.124829  145.838724
                            second           132.321694  141.750650
...                                                 ...         ...
Male   95.0      125.000000 fourth            96.721154  108.891014
                            highest           98.434988  110.836046
                            lowest            94.574744  106.417484
                            middle            96.398776  108.517343
                            second            96.023090  108.072022

                                               draw_494    draw_495  \
sex    age_start age_end    wealth_quintile
Female 0.0       0.019178   fourth           138.923917  143.226678
                            highest          144.127181  148.595173
                            lowest           130.425596  134.450627
                            middle           137.493722  141.749461
                            second           133.650434  137.781338
...                                                 ...         ...
Male   95.0      125.000000 fourth           103.367909   97.739348
                            highest          105.208015   99.472525
                            lowest           101.042837   95.565569
                            middle           103.017517   97.412679
                            second           102.603798   97.031167

                                               draw_496    draw_497  \
sex    age_start age_end    wealth_quintile
Female 0.0       0.019178   fourth           139.160203  142.647804
                            highest          144.372541  147.994069
                            lowest           130.646630  133.909117
                            middle           137.727426  141.176912
                            second           133.877282  137.225584
...                                                 ...         ...
Male   95.0      125.000000 fourth           106.938650  106.103594
                            highest          108.846591  107.995671
                            lowest           104.517598  103.704989
                            middle           106.573208  105.741672
                            second           106.139058  105.312300

                                               draw_498    draw_499
sex    age_start age_end    wealth_quintile
Female 0.0       0.019178   fourth           149.279568  145.179900
                            highest          154.880500  150.623401
                            lowest           140.112820  136.277773
                            middle           147.736201  143.681336
                            second           143.592468  139.656545
...                                                 ...         ...
Male   95.0      125.000000 fourth           100.023205  108.137248
                            highest          101.799770  110.067959
                            lowest            97.788038  105.683979
                            middle            99.686910  107.766754
                            second            99.292330  107.325746

[250 rows x 500 columns]

In [33]:
hgb_mean.columns.name = "draw"
hgb_mean = hgb_mean.stack().rename("mean").reset_index()

In [34]:
counterfactual_hgb_mean.columns.name = "draw"
counterfactual_hgb_mean = counterfactual_hgb_mean.stack().rename("mean").reset_index()

In [35]:
location_id = utility_data.get_location_id(location.title())
hgb_sd = gbd.get_modelable_entity_draws(me_id=me_ids["hemoglobin_sd"], location_id=location_id, year_id=2021)
hgb_sd = reshape_to_vivarium_format(hgb_sd, location.title()).droplevel(["year_start", "year_end", "measure_id", "metric_id", "model_version_id", "modelable_entity_id"])[DRAWS].copy()
hgb_sd

                                draw_0     draw_1     draw_2     draw_3  \
sex    age_start age_end
Female 0.000000  0.019178    26.026960  23.907182  16.403169  18.715768
       0.019178  0.076712    29.653984  25.132357  26.064191  35.471576
       0.076712  0.500000    22.493218  16.259081  17.452182  15.476258
       0.500000  1.000000    15.088749  16.763458  14.467460  14.968448
       1.000000  2.000000    15.397715  16.467520  16.931422  15.316047
       2.000000  5.000000    15.553860  13.236368  15.314247  15.205571
       5.000000  10.000000   24.246181   8.464774  13.511319  12.174676
       10.000000 15.000000   20.372010  17.600339  15.670304  18.874888
       15.000000 20.000000   13.849848  15.303821  13.412809  15.645587
       20.000000 25.000000   14.161841  13.816199  16.113706  13.064190
       25.000000 30.000000   13.951453  12.087523  13.960027  15.747683
       30.000000 35.000000   15.124416  13.912934  14.508748  14.284332
       35.000000 40.000000   14.537795  12.796153  11.977138  12.619102
       40.000000 45.000000   15.511511  15.320203  13.814969  15.477653
       45.000000 50.000000   14.740887  16.461188  14.795978  14.266428
       50.000000 55.000000   12.005022  19.946933  14.359695  22.342577
       55.000000 60.000000   15.457708   9.403534  17.510417  14.185617
       60.000000 65.000000   17.870134  23.535264  15.190874  19.820442
       65.000000 70.000000   18.274735  38.392728  27.115780  22.460828
       70.000000 75.000000   14.297770  12.642415  17.848045  11.580773
       75.000000 80.000000   15.552421  25.187471   9.408474  17.651964
       80.000000 85.000000   27.470516  25.512507  18.952878  25.817333
       85.000000 90.000000   18.088001  20.580833   5.178689  16.104535
       90.000000 95.000000   12.785354  20.398206  15.979831  13.495828
       95.000000 125.000000  23.461384  26.340875  35.452001  34.646552
Male   0.000000  0.019178     8.741365   8.444370  10.058485   9.269974
       0.019178  0.076712    45.945438  28.232303  33.884957  25.657119
       0.076712  0.500000    10.834561  14.464839  16.716692  13.781233
       0.500000  1.000000    17.866906  15.667957  15.926898  17.670570
       1.000000  2.000000    17.452899  16.689185  13.466597  16.075586
       2.000000  5.000000    11.124414  20.798399  13.040816  21.819873
       5.000000  10.000000   15.571013  12.788589  13.163620  10.470561
       10.000000 15.000000   20.593272   7.675260  11.134538  13.284772
       15.000000 20.000000   11.081504  22.556104  22.074298  21.838462
       20.000000 25.000000   18.281512   7.567572  14.716066   9.559315
       25.000000 30.000000    9.776189  17.322972  12.849834   7.167079
       30.000000 35.000000   12.832856  14.604296   8.867764  27.680958
       35.000000 40.000000    7.747828  16.962800  16.855032  10.901524
       40.000000 45.000000   11.482526  14.684343   8.398772  22.837871
       45.000000 50.000000   12.619049  13.035039  20.963212  15.980802
       50.000000 55.000000   15.864704  16.779504  15.424543  21.599276
       55.000000 60.000000   10.580076  27.129333  19.432159  17.335354
       60.000000 65.000000   15.722404  12.879010  20.046828  24.112250
       65.000000 70.000000   21.271206  16.053375  16.248970  17.207534
       70.000000 75.000000   24.062525  24.232873  13.549617  18.340322
       75.000000 80.000000    9.509731  13.080280   8.034360   9.796766
       80.000000 85.000000   20.360018  15.849824  13.075308  21.846383
       85.000000 90.000000   30.679256  12.187568  24.214234  24.380637
       90.000000 95.000000   12.432987  22.692279   9.217534   6.586342
       95.000000 125.000000  25.841204  20.160131  32.834640  21.792155

                                draw_4     draw_5     draw_6     draw_7  \
sex    age_start age_end
Female 0.000000  0.019178    17.036223  21.455689  13.328800  27.165364
       0.019178  0.076712    23.889709  32.649362  30.528820  37.106440
       0.076712  0.500000    20.107787  23.465305  22.878430  20.102228
       0.500000  1.000000    14.433290  15.700162  16.891376  14.383653
       1.000000  2.000000    16.490423  15.023267  16.321397  14.792130
       2.000000  5.000000    16.349138  14.993753  13.839953  16.117921
       5.000000  10.000000   10.864993  11.948106  15.346253  13.156982
       10.000000 15.000000   11.333060  12.762778  13.750615  17.674666
       15.000000 20.000000   17.479778  16.473595  15.236338  14.389182
       20.000000 25.000000   14.764773  14.204037  15.372209  14.866018
       25.000000 30.000000   13.465427  13.748768  14.450422  11.142297
       30.000000 35.000000   15.489245  14.152438  16.336814  11.949094
       35.000000 40.000000   14.257859  14.485341  14.384708  14.701560
       40.000000 45.000000   13.428191  14.829244  15.693401  16.447511
       45.000000 50.000000   17.795462  15.560622  14.036599  16.406834
       50.000000 55.000000   15.983748  10.721466  12.721868  16.411776
       55.000000 60.000000   12.645628  16.097135  10.540017  12.875278
       60.000000 65.000000   21.384044  15.268379  15.672606  27.913930
       65.000000 70.000000   32.121622  32.636321  28.906099  22.381887
       70.000000 75.000000   14.440966  28.464067  27.072494  21.407878
       75.000000 80.000000   22.529351  18.068591  19.838288  15.487765
       80.000000 85.000000   21.161202  23.963837  18.336671  23.949626
       85.000000 90.000000   13.526887  29.906430   9.459181  12.848075
       90.000000 95.000000    9.890216  22.949436  11.103946  17.341702
       95.000000 125.000000  51.883828  28.301982  23.624796  24.595012
Male   0.000000  0.019178    11.570569   8.714296   6.731408   7.346581
       0.019178  0.076712    50.958863  13.813219  44.070673  49.517416
       0.076712  0.500000    14.308120  18.266908  13.962939  16.882978
       0.500000  1.000000    14.772919  14.854953  30.422870  14.828441
       1.000000  2.000000    14.733455  15.869733  13.438547  14.845996
       2.000000  5.000000    12.510594  16.814314  26.435677  14.575605
       5.000000  10.000000    8.704261  17.069773  16.931352  15.310331
       10.000000 15.000000    8.938664   9.672081  23.142115  15.134940
       15.000000 20.000000   18.023055  17.039669  20.512647  11.511680
       20.000000 25.000000   18.513986  10.102183  12.364377  21.688491
       25.000000 30.000000   23.549008  19.298922  20.521597  19.517653
       30.000000 35.000000    9.368127   8.016110  14.714051  19.827004
       35.000000 40.000000   18.831655  10.986962   8.693896  24.270543
       40.000000 45.000000   10.335272  22.023615  10.867219  16.129543
       45.000000 50.000000   18.091420  25.639722  19.200388  20.596239
       50.000000 55.000000   11.365314  16.301323  15.211179  23.622858
       55.000000 60.000000   17.521112  21.386656  11.730338   8.837056
       60.000000 65.000000   10.727560  31.224591  15.453439  19.430508
       65.000000 70.000000   18.440987  24.012015  16.389367  21.128076
       70.000000 75.000000   20.548699  14.824379  19.807737   8.430459
       75.000000 80.000000   26.420632  12.179708  12.561871  22.634989
       80.000000 85.000000   20.469190  11.336161   8.377354  17.444565
       85.000000 90.000000   28.426279  41.550551  21.079612  17.661363
       90.000000 95.000000   17.094063  42.402599  10.537440  18.056715
       95.000000 125.000000  15.848244  18.240778  20.723524  11.541212

                                draw_8     draw_9    draw_10    draw_11  \
sex    age_start age_end
Female 0.000000  0.019178    32.583905   8.017943  13.193898  15.377817
       0.019178  0.076712    33.247088  26.832366  26.752537  25.712978
       0.076712  0.500000    19.558502  12.149664  13.365299  21.968284
       0.500000  1.000000    13.580970  13.668688  16.382398  14.118222
       1.000000  2.000000    17.059795  14.942118  14.558001  15.896364
       2.000000  5.000000    16.790731  17.054653  14.530395  15.164942
       5.000000  10.000000   16.971618  17.187792  11.662541   7.247431
       10.000000 15.000000   13.365310  11.229815  11.502834  15.517084
       15.000000 20.000000   16.192847  13.096408  15.698158  14.307556
       20.000000 25.000000   14.519282  15.761956  14.995197  11.849521
       25.000000 30.000000   15.347170  11.197064  15.963036  14.770517
       30.000000 35.000000   16.005197  13.138617  13.663705  12.633291
       35.000000 40.000000   14.585720  16.773507  14.568283  16.412436
       40.000000 45.000000   14.591325  14.465957  17.060467  15.173957
       45.000000 50.000000   13.176723  18.024444  14.718895  16.164547
       50.000000 55.000000   14.903536  10.860957  13.544385  14.284879
       55.000000 60.000000   14.658188  16.399216  16.563366   9.226783
       60.000000 65.000000   19.873950  23.237088   9.297262  13.254930
       65.000000 70.000000   18.123292  19.330122  29.718140  15.809211
       70.000000 75.000000   24.720074  23.243094  25.984802  16.637835
       75.000000 80.000000   20.939988  17.951267  23.124310  21.083847
       80.000000 85.000000   28.652201  16.468759  14.162803  20.250716
       85.000000 90.000000   17.214625  24.926142  14.929344  21.354166
       90.000000 95.000000   10.731815   9.130296   9.566579  18.783275
       95.000000 125.000000  33.460763  31.062596  21.625358  44.601971
Male   0.000000  0.019178     8.429818   6.594639   9.765369  11.332991
       0.019178  0.076712    41.090046  25.578775  19.195716  29.119090
       0.076712  0.500000    15.100336  13.834311  14.347296  20.918880
       0.500000  1.000000    11.787412  15.491633  16.501005  15.472750
       1.000000  2.000000    18.200341  13.381363  18.994916  15.180187
       2.000000  5.000000    13.039700  13.044513  22.376081  15.351500
       5.000000  10.000000   10.709290  13.577906  15.379431  17.294871
       10.000000 15.000000    7.801272  18.561373   8.218664  14.383090
       15.000000 20.000000   16.642888  24.691334  13.541353  25.177873
       20.000000 25.000000   13.778379  21.292798  16.556559  12.672520
       25.000000 30.000000    9.570230  14.851788   8.142577  21.225573
       30.000000 35.000000   19.581453  16.842868  18.477792  17.184592
       35.000000 40.000000    9.073837  15.148856  19.022423  15.824989
       40.000000 45.000000   24.061956  31.513725  15.868563  13.278226
       45.000000 50.000000   11.532464  14.584403  22.997867  15.198965
       50.000000 55.000000   16.440195  10.815763  12.155009  13.014829
       55.000000 60.000000   12.772952  10.346070   8.864645  16.563740
       60.000000 65.000000   20.174442  11.588851  15.364033  16.516665
       65.000000 70.000000   19.713377  15.438152  28.232080  18.200114
       70.000000 75.000000   16.663482  26.492694  17.897372  21.336307
       75.000000 80.000000   13.169449  16.078491  22.047346  19.125958
       80.000000 85.000000   18.344560  14.855097  29.772634  17.549397
       85.000000 90.000000   22.155728  22.142123  23.588206  35.477714
       90.000000 95.000000   10.732077  14.047546   8.522884  13.703498
       95.000000 125.000000  18.877219  10.699355  51.477742  16.306513

                               draw_12    draw_13    draw_14  ...   draw_485  \
sex    age_start age_end                                      ...
Female 0.000000  0.019178    20.418130  12.913853  38.341988  ...  31.014767
       0.019178  0.076712    42.911061  25.146868  36.012465  ...  31.761663
       0.076712  0.500000    13.234097  15.473990  20.489183  ...  14.651818
       0.500000  1.000000    18.520538  16.614916  13.644280  ...  13.576668
       1.000000  2.000000    16.241129  15.682234  15.293499  ...  15.500088
       2.000000  5.000000    17.221084  15.359852  14.187877  ...  15.519035
       5.000000  10.000000    9.871095  13.803533  12.175351  ...  16.292710
       10.000000 15.000000   14.187617  12.733054  14.569561  ...  15.581950
       15.000000 20.000000   16.235069  15.240651  13.435421  ...  15.077092
       20.000000 25.000000   14.111059  13.846007  15.301046  ...  13.714495
       25.000000 30.000000   13.754946  14.382719  12.583959  ...  13.016839
       30.000000 35.000000   12.476642  13.907982  13.279977  ...  16.503241
       35.000000 40.000000   14.154444  15.614457  14.287035  ...  14.801675
       40.000000 45.000000   13.397963  16.006259  13.335508  ...  14.090176
       45.000000 50.000000   13.753349  14.874200  14.044837  ...  16.457826
       50.000000 55.000000   22.037368  11.103697  20.727268  ...  12.417186
       55.000000 60.000000   15.977639  11.024197  14.865855  ...  15.464830
       60.000000 65.000000   20.966945  18.024476  25.623363  ...  37.453404
       65.000000 70.000000   31.595977  26.238641  23.806814  ...  25.639493
       70.000000 75.000000   29.925816  24.260078  28.980616  ...  18.261459
       75.000000 80.000000   14.032204  12.289442  17.369937  ...  15.050986
       80.000000 85.000000   11.938392  17.948097  28.008241  ...  20.760138
       85.000000 90.000000   11.974174  16.743266  17.449628  ...  19.170079
       90.000000 95.000000   19.712310  18.842449  17.450295  ...  14.474694
       95.000000 125.000000  42.551849  21.705819  31.132321  ...  15.225597
Male   0.000000  0.019178    12.325739  10.294415   7.721674  ...   8.315999
       0.019178  0.076712    53.854645  22.265912  27.808663  ...  21.182100
       0.076712  0.500000    21.377134  18.920487  17.573233  ...  16.863924
       0.500000  1.000000    13.395872  14.816865  13.670271  ...  14.862061
       1.000000  2.000000    15.330579  13.470131  21.684662  ...  18.796330
       2.000000  5.000000    13.107583  10.276767  14.802280  ...  17.583916
       5.000000  10.000000    9.549493  13.098769  16.301863  ...  12.726523
       10.000000 15.000000    8.444363   8.118860  10.646084  ...  14.430397
       15.000000 20.000000   16.666984  14.370719  28.021383  ...   7.823654
       20.000000 25.000000   15.007552  21.813863  12.194427  ...  13.843915
       25.000000 30.000000   15.303127  22.954421  10.461663  ...  12.419839
       30.000000 35.000000   11.765650  11.591596  16.651734  ...  13.029415
       35.000000 40.000000   14.899037  13.275111  13.109416  ...  15.716349
       40.000000 45.000000   14.437851  10.177687   9.601670  ...   9.702800
       45.000000 50.000000   28.374811  25.473670   9.139412  ...  10.911430
       50.000000 55.000000   18.527069  12.800601  19.974327  ...  17.661224
       55.000000 60.000000    7.350987  25.090269  12.101093  ...  14.887784
       60.000000 65.000000   11.655739  12.457222  12.422743  ...  24.551882
       65.000000 70.000000   18.305887  27.254506  28.895585  ...  11.598478
       70.000000 75.000000   19.320452  19.231288  21.245567  ...  23.362684
       75.000000 80.000000   17.791903  12.607380  17.825062  ...  23.052207
       80.000000 85.000000   12.305394  14.433927  21.124037  ...  23.672990
       85.000000 90.000000   28.325561  31.434500  30.576173  ...  33.607061
       90.000000 95.000000   18.569605  10.955424  15.410206  ...  19.567100
       95.000000 125.000000  21.278393  27.487776  20.235097  ...  24.126838

                              draw_486   draw_487   draw_488   draw_489  \
sex    age_start age_end
Female 0.000000  0.019178    19.609701  18.923131  24.816510  11.096069
       0.019178  0.076712    35.597856  24.846541  29.561491  30.173949
       0.076712  0.500000    16.911182  19.846823  12.793211  17.084966
       0.500000  1.000000    14.097008  14.594704  15.742621  15.654889
       1.000000  2.000000    18.352136  16.251479  15.903364  15.793122
       2.000000  5.000000    15.900644  15.735947  14.835611  15.569278
       5.000000  10.000000   17.522618  11.024919  13.995669   6.694638
       10.000000 15.000000   19.733917   8.364567  12.882239  14.240569
       15.000000 20.000000   16.232276  16.586902  16.783202  15.514441
       20.000000 25.000000   14.044243  11.966858  14.266150  16.073954
       25.000000 30.000000   14.094528  15.278635  13.667257  14.683267
       30.000000 35.000000   14.861569  14.479680  15.855114  14.818854
       35.000000 40.000000   15.122004  14.409548  14.392193  13.689674
       40.000000 45.000000   13.939744  13.450128  16.480351  16.290593
       45.000000 50.000000   16.253431  16.598407  14.341370  16.613520
       50.000000 55.000000   16.158535  10.658569  21.805690  14.263641
       55.000000 60.000000   11.503290  10.146202  18.142596  15.820596
       60.000000 65.000000   21.606673  25.062796  22.347356  24.518646
       65.000000 70.000000   26.230168  16.936422  23.154916  26.811477
       70.000000 75.000000   20.825601  19.591666  27.866167  16.000667
       75.000000 80.000000   23.349793  31.554163  12.589014  14.288458
       80.000000 85.000000   20.661932  28.592104  22.108756  21.718750
       85.000000 90.000000   17.304015  15.942402  10.199477  20.014831
       90.000000 95.000000   13.659008  21.479652  10.987107  11.552312
       95.000000 125.000000  24.438402  26.587950  11.531464  23.925303
Male   0.000000  0.019178    12.253192   8.180609  17.642488   8.326685
       0.019178  0.076712    46.786608  18.535857  45.339632  40.653387
       0.076712  0.500000    17.988959  15.785086  18.017537  16.264121
       0.500000  1.000000    18.417105  17.193226  13.157941  18.953052
       1.000000  2.000000    13.971895  15.015523  15.263047  15.235466
       2.000000  5.000000    22.764480  18.123574  20.718772  12.997390
       5.000000  10.000000   10.768032  10.827876  13.725460  13.069063
       10.000000 15.000000    9.232810   8.200188  10.808967  14.934367
       15.000000 20.000000   13.928602  11.895116  18.285454  13.575237
       20.000000 25.000000   14.444791  23.324104   8.414973   7.262205
       25.000000 30.000000   28.552899  13.935518  17.615022   9.698307
       30.000000 35.000000   28.644177  15.762463  16.616285  21.205207
       35.000000 40.000000   10.392172  13.136447  18.023011  18.611603
       40.000000 45.000000   15.674524  20.811913  18.078361  25.780385
       45.000000 50.000000   22.572695  32.967006   9.821913  16.786639
       50.000000 55.000000   20.893014  25.566206  23.234747   8.234377
       55.000000 60.000000   21.711025  16.809095  12.740930  14.794390
       60.000000 65.000000   18.145897  15.206696  16.648759  18.212627
       65.000000 70.000000   14.503443  14.676764  18.697999  17.894258
       70.000000 75.000000   15.470761  27.303970  36.693190  16.027411
       75.000000 80.000000   18.499474  25.325106  17.393793  11.118119
       80.000000 85.000000   16.246574  19.894143  29.009249  30.223670
       85.000000 90.000000   23.646424  20.657057  22.081541   9.430011
       90.000000 95.000000   10.397023  10.416302  14.754179   8.750719
       95.000000 125.000000  28.237512  35.152649  28.213250  41.436557

                              draw_490   draw_491   draw_492   draw_493  \
sex    age_start age_end
Female 0.000000  0.019178    25.491270  12.187820  14.047787  26.560128
       0.019178  0.076712    25.246103  23.558550  28.413902  30.561627
       0.076712  0.500000    14.180015  14.757910  19.195717  24.988649
       0.500000  1.000000    13.607053  14.132132  15.332481  15.166399
       1.000000  2.000000    16.186387  15.514738  15.634146  19.064929
       2.000000  5.000000    13.536685  18.700769  15.182119  15.036536
       5.000000  10.000000   10.927548  11.909380   9.451857  14.258122
       10.000000 15.000000   17.586643  16.970325  13.246272  18.751994
       15.000000 20.000000   14.585253  15.589722  16.735412  13.482141
       20.000000 25.000000   15.903950  12.597089  15.271267  13.652175
       25.000000 30.000000   13.442297  14.398629  12.577238  14.406567
       30.000000 35.000000   13.400333  13.371301  16.185133  13.732926
       35.000000 40.000000   14.537479  16.227261  13.692899  15.001701
       40.000000 45.000000   15.170557  14.704144  14.126026  15.916032
       45.000000 50.000000   16.393983  14.315702  17.500185  16.205695

In [36]:
hemoglobin_sd_disparities = pd.read_csv(f'../0100_data_prep/results/hemoglobin/sd_disparities/{location}.csv')
hemoglobin_sd_disparities = (
    map_to_population_age_groups(hemoglobin_sd_disparities[hemoglobin_sd_disparities.pregnant == "not_pregnant"].drop(columns=["pregnant"]))
        .set_index(["sex", "age_start", "age_end", "wealth_quintile"]).value
)
hemoglobin_sd_disparities

sex     age_start  age_end     wealth_quintile
Female  0.0        0.019178    lowest             16.607283
                               second             15.898899
                               middle             15.268520
                               fourth             14.286274
                               highest            13.194608
                                                    ...
Male    95.0       125.000000  lowest             15.148809
                               second             14.920351
                               middle             15.108541
                               fourth             14.792239
                               highest            14.222341
Name: value, Length: 250, dtype: float64

In [37]:
pre_disparity_groups = hgb_sd.mul(wealth_quintile_probabilities, axis=0).groupby([c for c in hgb_sd.index.names if c != 'wealth_quintile']).sum()
pre_disparity_groups

                                draw_0     draw_1     draw_2     draw_3  \
sex    age_start age_end
Female 0.000000  0.019178    26.026960  23.907182  16.403169  18.715768
       0.019178  0.076712    29.653984  25.132357  26.064191  35.471576
       0.076712  0.500000    22.493218  16.259081  17.452182  15.476258
       0.500000  1.000000    15.088749  16.763458  14.467460  14.968448
       1.000000  2.000000    15.397715  16.467520  16.931422  15.316047
       2.000000  5.000000    15.553860  13.236368  15.314247  15.205571
       5.000000  10.000000   24.246181   8.464774  13.511319  12.174676
       10.000000 15.000000   20.372010  17.600339  15.670304  18.874888
       15.000000 20.000000   13.849848  15.303821  13.412809  15.645587
       20.000000 25.000000   14.161841  13.816199  16.113706  13.064190
       25.000000 30.000000   13.951453  12.087523  13.960027  15.747683
       30.000000 35.000000   15.124416  13.912934  14.508748  14.284332
       35.000000 40.000000   14.537795  12.796153  11.977138  12.619102
       40.000000 45.000000   15.511511  15.320203  13.814969  15.477653
       45.000000 50.000000   14.740887  16.461188  14.795978  14.266428
       50.000000 55.000000   12.005022  19.946933  14.359695  22.342577
       55.000000 60.000000   15.457708   9.403534  17.510417  14.185617
       60.000000 65.000000   17.870134  23.535264  15.190874  19.820442
       65.000000 70.000000   18.274735  38.392728  27.115780  22.460828
       70.000000 75.000000   14.297770  12.642415  17.848045  11.580773
       75.000000 80.000000   15.552421  25.187471   9.408474  17.651964
       80.000000 85.000000   27.470516  25.512507  18.952878  25.817333
       85.000000 90.000000   18.088001  20.580833   5.178689  16.104535
       90.000000 95.000000   12.785354  20.398206  15.979831  13.495828
       95.000000 125.000000  23.461384  26.340875  35.452001  34.646552
Male   0.000000  0.019178     8.741365   8.444370  10.058485   9.269974
       0.019178  0.076712    45.945438  28.232303  33.884957  25.657119
       0.076712  0.500000    10.834561  14.464839  16.716692  13.781233
       0.500000  1.000000    17.866906  15.667957  15.926898  17.670570
       1.000000  2.000000    17.452899  16.689185  13.466597  16.075586
       2.000000  5.000000    11.124414  20.798399  13.040816  21.819873
       5.000000  10.000000   15.571013  12.788589  13.163620  10.470561
       10.000000 15.000000   20.593272   7.675260  11.134538  13.284772
       15.000000 20.000000   11.081504  22.556104  22.074298  21.838462
       20.000000 25.000000   18.281512   7.567572  14.716066   9.559315
       25.000000 30.000000    9.776189  17.322972  12.849834   7.167079
       30.000000 35.000000   12.832856  14.604296   8.867764  27.680958
       35.000000 40.000000    7.747828  16.962800  16.855032  10.901524
       40.000000 45.000000   11.482526  14.684343   8.398772  22.837871
       45.000000 50.000000   12.619049  13.035039  20.963212  15.980802
       50.000000 55.000000   15.864704  16.779504  15.424543  21.599276
       55.000000 60.000000   10.580076  27.129333  19.432159  17.335354
       60.000000 65.000000   15.722404  12.879010  20.046828  24.112250
       65.000000 70.000000   21.271206  16.053375  16.248970  17.207534
       70.000000 75.000000   24.062525  24.232873  13.549617  18.340322
       75.000000 80.000000    9.509731  13.080280   8.034360   9.796766
       80.000000 85.000000   20.360018  15.849824  13.075308  21.846383
       85.000000 90.000000   30.679256  12.187568  24.214234  24.380637
       90.000000 95.000000   12.432987  22.692279   9.217534   6.586342
       95.000000 125.000000  25.841204  20.160131  32.834640  21.792155

                                draw_4     draw_5     draw_6     draw_7  \
sex    age_start age_end
Female 0.000000  0.019178    17.036223  21.455689  13.328800  27.165364
       0.019178  0.076712    23.889709  32.649362  30.528820  37.106440
       0.076712  0.500000    20.107787  23.465305  22.878430  20.102228
       0.500000  1.000000    14.433290  15.700162  16.891376  14.383653
       1.000000  2.000000    16.490423  15.023267  16.321397  14.792130
       2.000000  5.000000    16.349138  14.993753  13.839953  16.117921
       5.000000  10.000000   10.864993  11.948106  15.346253  13.156982
       10.000000 15.000000   11.333060  12.762778  13.750615  17.674666
       15.000000 20.000000   17.479778  16.473595  15.236338  14.389182
       20.000000 25.000000   14.764773  14.204037  15.372209  14.866018
       25.000000 30.000000   13.465427  13.748768  14.450422  11.142297
       30.000000 35.000000   15.489245  14.152438  16.336814  11.949094
       35.000000 40.000000   14.257859  14.485341  14.384708  14.701560
       40.000000 45.000000   13.428191  14.829244  15.693401  16.447511
       45.000000 50.000000   17.795462  15.560622  14.036599  16.406834
       50.000000 55.000000   15.983748  10.721466  12.721868  16.411776
       55.000000 60.000000   12.645628  16.097135  10.540017  12.875278
       60.000000 65.000000   21.384044  15.268379  15.672606  27.913930
       65.000000 70.000000   32.121622  32.636321  28.906099  22.381887
       70.000000 75.000000   14.440966  28.464067  27.072494  21.407878
       75.000000 80.000000   22.529351  18.068591  19.838288  15.487765
       80.000000 85.000000   21.161202  23.963837  18.336671  23.949626
       85.000000 90.000000   13.526887  29.906430   9.459181  12.848075
       90.000000 95.000000    9.890216  22.949436  11.103946  17.341702
       95.000000 125.000000  51.883828  28.301982  23.624796  24.595012
Male   0.000000  0.019178    11.570569   8.714296   6.731408   7.346581
       0.019178  0.076712    50.958863  13.813219  44.070673  49.517416
       0.076712  0.500000    14.308120  18.266908  13.962939  16.882978
       0.500000  1.000000    14.772919  14.854953  30.422870  14.828441
       1.000000  2.000000    14.733455  15.869733  13.438547  14.845996
       2.000000  5.000000    12.510594  16.814314  26.435677  14.575605
       5.000000  10.000000    8.704261  17.069773  16.931352  15.310331
       10.000000 15.000000    8.938664   9.672081  23.142115  15.134940
       15.000000 20.000000   18.023055  17.039669  20.512647  11.511680
       20.000000 25.000000   18.513986  10.102183  12.364377  21.688491
       25.000000 30.000000   23.549008  19.298922  20.521597  19.517653
       30.000000 35.000000    9.368127   8.016110  14.714051  19.827004
       35.000000 40.000000   18.831655  10.986962   8.693896  24.270543
       40.000000 45.000000   10.335272  22.023615  10.867219  16.129543
       45.000000 50.000000   18.091420  25.639722  19.200388  20.596239
       50.000000 55.000000   11.365314  16.301323  15.211179  23.622858
       55.000000 60.000000   17.521112  21.386656  11.730338   8.837056
       60.000000 65.000000   10.727560  31.224591  15.453439  19.430508
       65.000000 70.000000   18.440987  24.012015  16.389367  21.128076
       70.000000 75.000000   20.548699  14.824379  19.807737   8.430459
       75.000000 80.000000   26.420632  12.179708  12.561871  22.634989
       80.000000 85.000000   20.469190  11.336161   8.377354  17.444565
       85.000000 90.000000   28.426279  41.550551  21.079612  17.661363
       90.000000 95.000000   17.094063  42.402599  10.537440  18.056715
       95.000000 125.000000  15.848244  18.240778  20.723524  11.541212

                                draw_8     draw_9    draw_10    draw_11  \
sex    age_start age_end
Female 0.000000  0.019178    32.583905   8.017943  13.193898  15.377817
       0.019178  0.076712    33.247088  26.832366  26.752537  25.712978
       0.076712  0.500000    19.558502  12.149664  13.365299  21.968284
       0.500000  1.000000    13.580970  13.668688  16.382398  14.118222
       1.000000  2.000000    17.059795  14.942118  14.558001  15.896364
       2.000000  5.000000    16.790731  17.054653  14.530395  15.164942
       5.000000  10.000000   16.971618  17.187792  11.662541   7.247431
       10.000000 15.000000   13.365310  11.229815  11.502834  15.517084
       15.000000 20.000000   16.192847  13.096408  15.698158  14.307556
       20.000000 25.000000   14.519282  15.761956  14.995197  11.849521
       25.000000 30.000000   15.347170  11.197064  15.963036  14.770517
       30.000000 35.000000   16.005197  13.138617  13.663705  12.633291
       35.000000 40.000000   14.585720  16.773507  14.568283  16.412436
       40.000000 45.000000   14.591325  14.465957  17.060467  15.173957
       45.000000 50.000000   13.176723  18.024444  14.718895  16.164547
       50.000000 55.000000   14.903536  10.860957  13.544385  14.284879
       55.000000 60.000000   14.658188  16.399216  16.563366   9.226783
       60.000000 65.000000   19.873950  23.237088   9.297262  13.254930
       65.000000 70.000000   18.123292  19.330122  29.718140  15.809211
       70.000000 75.000000   24.720074  23.243094  25.984802  16.637835
       75.000000 80.000000   20.939988  17.951267  23.124310  21.083847
       80.000000 85.000000   28.652201  16.468759  14.162803  20.250716
       85.000000 90.000000   17.214625  24.926142  14.929344  21.354166
       90.000000 95.000000   10.731815   9.130296   9.566579  18.783275
       95.000000 125.000000  33.460763  31.062596  21.625358  44.601971
Male   0.000000  0.019178     8.429818   6.594639   9.765369  11.332991
       0.019178  0.076712    41.090046  25.578775  19.195716  29.119090
       0.076712  0.500000    15.100336  13.834311  14.347296  20.918880
       0.500000  1.000000    11.787412  15.491633  16.501005  15.472750
       1.000000  2.000000    18.200341  13.381363  18.994916  15.180187
       2.000000  5.000000    13.039700  13.044513  22.376081  15.351500
       5.000000  10.000000   10.709290  13.577906  15.379431  17.294871
       10.000000 15.000000    7.801272  18.561373   8.218664  14.383090
       15.000000 20.000000   16.642888  24.691334  13.541353  25.177873
       20.000000 25.000000   13.778379  21.292798  16.556559  12.672520
       25.000000 30.000000    9.570230  14.851788   8.142577  21.225573
       30.000000 35.000000   19.581453  16.842868  18.477792  17.184592
       35.000000 40.000000    9.073837  15.148856  19.022423  15.824989
       40.000000 45.000000   24.061956  31.513725  15.868563  13.278226
       45.000000 50.000000   11.532464  14.584403  22.997867  15.198965
       50.000000 55.000000   16.440195  10.815763  12.155009  13.014829
       55.000000 60.000000   12.772952  10.346070   8.864645  16.563740
       60.000000 65.000000   20.174442  11.588851  15.364033  16.516665
       65.000000 70.000000   19.713377  15.438152  28.232080  18.200114
       70.000000 75.000000   16.663482  26.492694  17.897372  21.336307
       75.000000 80.000000   13.169449  16.078491  22.047346  19.125958
       80.000000 85.000000   18.344560  14.855097  29.772634  17.549397
       85.000000 90.000000   22.155728  22.142123  23.588206  35.477714
       90.000000 95.000000   10.732077  14.047546   8.522884  13.703498
       95.000000 125.000000  18.877219  10.699355  51.477742  16.306513

                               draw_12    draw_13    draw_14  ...   draw_485  \
sex    age_start age_end                                      ...
Female 0.000000  0.019178    20.418130  12.913853  38.341988  ...  31.014767
       0.019178  0.076712    42.911061  25.146868  36.012465  ...  31.761663
       0.076712  0.500000    13.234097  15.473990  20.489183  ...  14.651818
       0.500000  1.000000    18.520538  16.614916  13.644280  ...  13.576668
       1.000000  2.000000    16.241129  15.682234  15.293499  ...  15.500088
       2.000000  5.000000    17.221084  15.359852  14.187877  ...  15.519035
       5.000000  10.000000    9.871095  13.803533  12.175351  ...  16.292710
       10.000000 15.000000   14.187617  12.733054  14.569561  ...  15.581950
       15.000000 20.000000   16.235069  15.240651  13.435421  ...  15.077092
       20.000000 25.000000   14.111059  13.846007  15.301046  ...  13.714495
       25.000000 30.000000   13.754946  14.382719  12.583959  ...  13.016839
       30.000000 35.000000   12.476642  13.907982  13.279977  ...  16.503241
       35.000000 40.000000   14.154444  15.614457  14.287035  ...  14.801675
       40.000000 45.000000   13.397963  16.006259  13.335508  ...  14.090176
       45.000000 50.000000   13.753349  14.874200  14.044837  ...  16.457826
       50.000000 55.000000   22.037368  11.103697  20.727268  ...  12.417186
       55.000000 60.000000   15.977639  11.024197  14.865855  ...  15.464830
       60.000000 65.000000   20.966945  18.024476  25.623363  ...  37.453404
       65.000000 70.000000   31.595977  26.238641  23.806814  ...  25.639493
       70.000000 75.000000   29.925816  24.260078  28.980616  ...  18.261459
       75.000000 80.000000   14.032204  12.289442  17.369937  ...  15.050986
       80.000000 85.000000   11.938392  17.948097  28.008241  ...  20.760138
       85.000000 90.000000   11.974174  16.743266  17.449628  ...  19.170079
       90.000000 95.000000   19.712310  18.842449  17.450295  ...  14.474694
       95.000000 125.000000  42.551849  21.705819  31.132321  ...  15.225597
Male   0.000000  0.019178    12.325739  10.294415   7.721674  ...   8.315999
       0.019178  0.076712    53.854645  22.265912  27.808663  ...  21.182100
       0.076712  0.500000    21.377134  18.920487  17.573233  ...  16.863924
       0.500000  1.000000    13.395872  14.816865  13.670271  ...  14.862061
       1.000000  2.000000    15.330579  13.470131  21.684662  ...  18.796330
       2.000000  5.000000    13.107583  10.276767  14.802280  ...  17.583916
       5.000000  10.000000    9.549493  13.098769  16.301863  ...  12.726523
       10.000000 15.000000    8.444363   8.118860  10.646084  ...  14.430397
       15.000000 20.000000   16.666984  14.370719  28.021383  ...   7.823654
       20.000000 25.000000   15.007552  21.813863  12.194427  ...  13.843915
       25.000000 30.000000   15.303127  22.954421  10.461663  ...  12.419839
       30.000000 35.000000   11.765650  11.591596  16.651734  ...  13.029415
       35.000000 40.000000   14.899037  13.275111  13.109416  ...  15.716349
       40.000000 45.000000   14.437851  10.177687   9.601670  ...   9.702800
       45.000000 50.000000   28.374811  25.473670   9.139412  ...  10.911430
       50.000000 55.000000   18.527069  12.800601  19.974327  ...  17.661224
       55.000000 60.000000    7.350987  25.090269  12.101093  ...  14.887784
       60.000000 65.000000   11.655739  12.457222  12.422743  ...  24.551882
       65.000000 70.000000   18.305887  27.254506  28.895585  ...  11.598478
       70.000000 75.000000   19.320452  19.231288  21.245567  ...  23.362684
       75.000000 80.000000   17.791903  12.607380  17.825062  ...  23.052207
       80.000000 85.000000   12.305394  14.433927  21.124037  ...  23.672990
       85.000000 90.000000   28.325561  31.434500  30.576173  ...  33.607061
       90.000000 95.000000   18.569605  10.955424  15.410206  ...  19.567100
       95.000000 125.000000  21.278393  27.487776  20.235097  ...  24.126838

                              draw_486   draw_487   draw_488   draw_489  \
sex    age_start age_end
Female 0.000000  0.019178    19.609701  18.923131  24.816510  11.096069
       0.019178  0.076712    35.597856  24.846541  29.561491  30.173949
       0.076712  0.500000    16.911182  19.846823  12.793211  17.084966
       0.500000  1.000000    14.097008  14.594704  15.742621  15.654889
       1.000000  2.000000    18.352136  16.251479  15.903364  15.793122
       2.000000  5.000000    15.900644  15.735947  14.835611  15.569278
       5.000000  10.000000   17.522618  11.024919  13.995669   6.694638
       10.000000 15.000000   19.733917   8.364567  12.882239  14.240569
       15.000000 20.000000   16.232276  16.586902  16.783202  15.514441
       20.000000 25.000000   14.044243  11.966858  14.266150  16.073954
       25.000000 30.000000   14.094528  15.278635  13.667257  14.683267
       30.000000 35.000000   14.861569  14.479680  15.855114  14.818854
       35.000000 40.000000   15.122004  14.409548  14.392193  13.689674
       40.000000 45.000000   13.939744  13.450128  16.480351  16.290593
       45.000000 50.000000   16.253431  16.598407  14.341370  16.613520
       50.000000 55.000000   16.158535  10.658569  21.805690  14.263641
       55.000000 60.000000   11.503290  10.146202  18.142596  15.820596
       60.000000 65.000000   21.606673  25.062796  22.347356  24.518646
       65.000000 70.000000   26.230168  16.936422  23.154916  26.811477
       70.000000 75.000000   20.825601  19.591666  27.866167  16.000667
       75.000000 80.000000   23.349793  31.554163  12.589014  14.288458
       80.000000 85.000000   20.661932  28.592104  22.108756  21.718750
       85.000000 90.000000   17.304015  15.942402  10.199477  20.014831
       90.000000 95.000000   13.659008  21.479652  10.987107  11.552312
       95.000000 125.000000  24.438402  26.587950  11.531464  23.925303
Male   0.000000  0.019178    12.253192   8.180609  17.642488   8.326685
       0.019178  0.076712    46.786608  18.535857  45.339632  40.653387
       0.076712  0.500000    17.988959  15.785086  18.017537  16.264121
       0.500000  1.000000    18.417105  17.193226  13.157941  18.953052
       1.000000  2.000000    13.971895  15.015523  15.263047  15.235466
       2.000000  5.000000    22.764480  18.123574  20.718772  12.997390
       5.000000  10.000000   10.768032  10.827876  13.725460  13.069063
       10.000000 15.000000    9.232810   8.200188  10.808967  14.934367
       15.000000 20.000000   13.928602  11.895116  18.285454  13.575237
       20.000000 25.000000   14.444791  23.324104   8.414973   7.262205
       25.000000 30.000000   28.552899  13.935518  17.615022   9.698307
       30.000000 35.000000   28.644177  15.762463  16.616285  21.205207
       35.000000 40.000000   10.392172  13.136447  18.023011  18.611603
       40.000000 45.000000   15.674524  20.811913  18.078361  25.780385
       45.000000 50.000000   22.572695  32.967006   9.821913  16.786639
       50.000000 55.000000   20.893014  25.566206  23.234747   8.234377
       55.000000 60.000000   21.711025  16.809095  12.740930  14.794390
       60.000000 65.000000   18.145897  15.206696  16.648759  18.212627
       65.000000 70.000000   14.503443  14.676764  18.697999  17.894258
       70.000000 75.000000   15.470761  27.303970  36.693190  16.027411
       75.000000 80.000000   18.499474  25.325106  17.393793  11.118119
       80.000000 85.000000   16.246574  19.894143  29.009249  30.223670
       85.000000 90.000000   23.646424  20.657057  22.081541   9.430011
       90.000000 95.000000   10.397023  10.416302  14.754179   8.750719
       95.000000 125.000000  28.237512  35.152649  28.213250  41.436557

                              draw_490   draw_491   draw_492   draw_493  \
sex    age_start age_end
Female 0.000000  0.019178    25.491270  12.187820  14.047787  26.560128
       0.019178  0.076712    25.246103  23.558550  28.413902  30.561627
       0.076712  0.500000    14.180015  14.757910  19.195717  24.988649
       0.500000  1.000000    13.607053  14.132132  15.332481  15.166399
       1.000000  2.000000    16.186387  15.514738  15.634146  19.064929
       2.000000  5.000000    13.536685  18.700769  15.182119  15.036536
       5.000000  10.000000   10.927548  11.909380   9.451857  14.258122
       10.000000 15.000000   17.586643  16.970325  13.246272  18.751994
       15.000000 20.000000   14.585253  15.589722  16.735412  13.482141
       20.000000 25.000000   15.903950  12.597089  15.271267  13.652175
       25.000000 30.000000   13.442297  14.398629  12.577238  14.406567
       30.000000 35.000000   13.400333  13.371301  16.185133  13.732926
       35.000000 40.000000   14.537479  16.227261  13.692899  15.001701
       40.000000 45.000000   15.170557  14.704144  14.126026  15.916032
       45.000000 50.000000   16.393983  14.315702  17.500185  16.205695

In [38]:
hgb_sd = hgb_sd.mul(hemoglobin_sd_disparities, axis=0)

In [39]:
scale_factor = pre_disparity_groups / hgb_sd.mul(wealth_quintile_probabilities, axis=0).groupby([c for c in hgb_sd.index.names if c != 'wealth_quintile']).sum()
scale_factor

                               draw_0    draw_1    draw_2    draw_3    draw_4  \
sex    age_start age_end
Female 0.000000  0.019178    0.065912  0.065912  0.065912  0.065912  0.065912
       0.019178  0.076712    0.065912  0.065912  0.065912  0.065912  0.065912
       0.076712  0.500000    0.065912  0.065912  0.065912  0.065912  0.065912
       0.500000  1.000000    0.065912  0.065912  0.065912  0.065912  0.065912
       1.000000  2.000000    0.065912  0.065912  0.065912  0.065912  0.065912
       2.000000  5.000000    0.065912  0.065912  0.065912  0.065912  0.065912
       5.000000  10.000000   0.066637  0.066637  0.066637  0.066637  0.066637
       10.000000 15.000000   0.066637  0.066637  0.066637  0.066637  0.066637
       15.000000 20.000000   0.067493  0.067493  0.067493  0.067493  0.067493
       20.000000 25.000000   0.067493  0.067493  0.067493  0.067493  0.067493
       25.000000 30.000000   0.067493  0.067493  0.067493  0.067493  0.067493
       30.000000 35.000000   0.067615  0.067615  0.067615  0.067615  0.067615
       35.000000 40.000000   0.067615  0.067615  0.067615  0.067615  0.067615
       40.000000 45.000000   0.067615  0.067615  0.067615  0.067615  0.067615
       45.000000 50.000000   0.067615  0.067615  0.067615  0.067615  0.067615
       50.000000 55.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       55.000000 60.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       60.000000 65.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       65.000000 70.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       70.000000 75.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       75.000000 80.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       80.000000 85.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       85.000000 90.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       90.000000 95.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       95.000000 125.000000  0.067359  0.067359  0.067359  0.067359  0.067359
Male   0.000000  0.019178    0.066669  0.066669  0.066669  0.066669  0.066669
       0.019178  0.076712    0.066669  0.066669  0.066669  0.066669  0.066669
       0.076712  0.500000    0.066669  0.066669  0.066669  0.066669  0.066669
       0.500000  1.000000    0.066669  0.066669  0.066669  0.066669  0.066669
       1.000000  2.000000    0.066669  0.066669  0.066669  0.066669  0.066669
       2.000000  5.000000    0.066669  0.066669  0.066669  0.066669  0.066669
       5.000000  10.000000   0.066943  0.066943  0.066943  0.066943  0.066943
       10.000000 15.000000   0.066943  0.066943  0.066943  0.066943  0.066943
       15.000000 20.000000   0.067407  0.067407  0.067407  0.067407  0.067407
       20.000000 25.000000   0.067407  0.067407  0.067407  0.067407  0.067407
       25.000000 30.000000   0.067407  0.067407  0.067407  0.067407  0.067407
       30.000000 35.000000   0.067687  0.067687  0.067687  0.067687  0.067687
       35.000000 40.000000   0.067687  0.067687  0.067687  0.067687  0.067687
       40.000000 45.000000   0.067687  0.067687  0.067687  0.067687  0.067687
       45.000000 50.000000   0.067687  0.067687  0.067687  0.067687  0.067687
       50.000000 55.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       55.000000 60.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       60.000000 65.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       65.000000 70.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       70.000000 75.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       75.000000 80.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       80.000000 85.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       85.000000 90.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       90.000000 95.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       95.000000 125.000000  0.067442  0.067442  0.067442  0.067442  0.067442

                               draw_5    draw_6    draw_7    draw_8    draw_9  \
sex    age_start age_end
Female 0.000000  0.019178    0.065912  0.065912  0.065912  0.065912  0.065912
       0.019178  0.076712    0.065912  0.065912  0.065912  0.065912  0.065912
       0.076712  0.500000    0.065912  0.065912  0.065912  0.065912  0.065912
       0.500000  1.000000    0.065912  0.065912  0.065912  0.065912  0.065912
       1.000000  2.000000    0.065912  0.065912  0.065912  0.065912  0.065912
       2.000000  5.000000    0.065912  0.065912  0.065912  0.065912  0.065912
       5.000000  10.000000   0.066637  0.066637  0.066637  0.066637  0.066637
       10.000000 15.000000   0.066637  0.066637  0.066637  0.066637  0.066637
       15.000000 20.000000   0.067493  0.067493  0.067493  0.067493  0.067493
       20.000000 25.000000   0.067493  0.067493  0.067493  0.067493  0.067493
       25.000000 30.000000   0.067493  0.067493  0.067493  0.067493  0.067493
       30.000000 35.000000   0.067615  0.067615  0.067615  0.067615  0.067615
       35.000000 40.000000   0.067615  0.067615  0.067615  0.067615  0.067615
       40.000000 45.000000   0.067615  0.067615  0.067615  0.067615  0.067615
       45.000000 50.000000   0.067615  0.067615  0.067615  0.067615  0.067615
       50.000000 55.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       55.000000 60.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       60.000000 65.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       65.000000 70.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       70.000000 75.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       75.000000 80.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       80.000000 85.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       85.000000 90.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       90.000000 95.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       95.000000 125.000000  0.067359  0.067359  0.067359  0.067359  0.067359
Male   0.000000  0.019178    0.066669  0.066669  0.066669  0.066669  0.066669
       0.019178  0.076712    0.066669  0.066669  0.066669  0.066669  0.066669
       0.076712  0.500000    0.066669  0.066669  0.066669  0.066669  0.066669
       0.500000  1.000000    0.066669  0.066669  0.066669  0.066669  0.066669
       1.000000  2.000000    0.066669  0.066669  0.066669  0.066669  0.066669
       2.000000  5.000000    0.066669  0.066669  0.066669  0.066669  0.066669
       5.000000  10.000000   0.066943  0.066943  0.066943  0.066943  0.066943
       10.000000 15.000000   0.066943  0.066943  0.066943  0.066943  0.066943
       15.000000 20.000000   0.067407  0.067407  0.067407  0.067407  0.067407
       20.000000 25.000000   0.067407  0.067407  0.067407  0.067407  0.067407
       25.000000 30.000000   0.067407  0.067407  0.067407  0.067407  0.067407
       30.000000 35.000000   0.067687  0.067687  0.067687  0.067687  0.067687
       35.000000 40.000000   0.067687  0.067687  0.067687  0.067687  0.067687
       40.000000 45.000000   0.067687  0.067687  0.067687  0.067687  0.067687
       45.000000 50.000000   0.067687  0.067687  0.067687  0.067687  0.067687
       50.000000 55.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       55.000000 60.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       60.000000 65.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       65.000000 70.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       70.000000 75.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       75.000000 80.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       80.000000 85.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       85.000000 90.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       90.000000 95.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       95.000000 125.000000  0.067442  0.067442  0.067442  0.067442  0.067442

                              draw_10   draw_11   draw_12   draw_13   draw_14  \
sex    age_start age_end
Female 0.000000  0.019178    0.065912  0.065912  0.065912  0.065912  0.065912
       0.019178  0.076712    0.065912  0.065912  0.065912  0.065912  0.065912
       0.076712  0.500000    0.065912  0.065912  0.065912  0.065912  0.065912
       0.500000  1.000000    0.065912  0.065912  0.065912  0.065912  0.065912
       1.000000  2.000000    0.065912  0.065912  0.065912  0.065912  0.065912
       2.000000  5.000000    0.065912  0.065912  0.065912  0.065912  0.065912
       5.000000  10.000000   0.066637  0.066637  0.066637  0.066637  0.066637
       10.000000 15.000000   0.066637  0.066637  0.066637  0.066637  0.066637
       15.000000 20.000000   0.067493  0.067493  0.067493  0.067493  0.067493
       20.000000 25.000000   0.067493  0.067493  0.067493  0.067493  0.067493
       25.000000 30.000000   0.067493  0.067493  0.067493  0.067493  0.067493
       30.000000 35.000000   0.067615  0.067615  0.067615  0.067615  0.067615
       35.000000 40.000000   0.067615  0.067615  0.067615  0.067615  0.067615
       40.000000 45.000000   0.067615  0.067615  0.067615  0.067615  0.067615
       45.000000 50.000000   0.067615  0.067615  0.067615  0.067615  0.067615
       50.000000 55.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       55.000000 60.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       60.000000 65.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       65.000000 70.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       70.000000 75.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       75.000000 80.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       80.000000 85.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       85.000000 90.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       90.000000 95.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       95.000000 125.000000  0.067359  0.067359  0.067359  0.067359  0.067359
Male   0.000000  0.019178    0.066669  0.066669  0.066669  0.066669  0.066669
       0.019178  0.076712    0.066669  0.066669  0.066669  0.066669  0.066669
       0.076712  0.500000    0.066669  0.066669  0.066669  0.066669  0.066669
       0.500000  1.000000    0.066669  0.066669  0.066669  0.066669  0.066669
       1.000000  2.000000    0.066669  0.066669  0.066669  0.066669  0.066669
       2.000000  5.000000    0.066669  0.066669  0.066669  0.066669  0.066669
       5.000000  10.000000   0.066943  0.066943  0.066943  0.066943  0.066943
       10.000000 15.000000   0.066943  0.066943  0.066943  0.066943  0.066943
       15.000000 20.000000   0.067407  0.067407  0.067407  0.067407  0.067407
       20.000000 25.000000   0.067407  0.067407  0.067407  0.067407  0.067407
       25.000000 30.000000   0.067407  0.067407  0.067407  0.067407  0.067407
       30.000000 35.000000   0.067687  0.067687  0.067687  0.067687  0.067687
       35.000000 40.000000   0.067687  0.067687  0.067687  0.067687  0.067687
       40.000000 45.000000   0.067687  0.067687  0.067687  0.067687  0.067687
       45.000000 50.000000   0.067687  0.067687  0.067687  0.067687  0.067687
       50.000000 55.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       55.000000 60.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       60.000000 65.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       65.000000 70.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       70.000000 75.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       75.000000 80.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       80.000000 85.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       85.000000 90.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       90.000000 95.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       95.000000 125.000000  0.067442  0.067442  0.067442  0.067442  0.067442

                             ...  draw_485  draw_486  draw_487  draw_488  \
sex    age_start age_end     ...
Female 0.000000  0.019178    ...  0.065912  0.065912  0.065912  0.065912
       0.019178  0.076712    ...  0.065912  0.065912  0.065912  0.065912
       0.076712  0.500000    ...  0.065912  0.065912  0.065912  0.065912
       0.500000  1.000000    ...  0.065912  0.065912  0.065912  0.065912
       1.000000  2.000000    ...  0.065912  0.065912  0.065912  0.065912
       2.000000  5.000000    ...  0.065912  0.065912  0.065912  0.065912
       5.000000  10.000000   ...  0.066637  0.066637  0.066637  0.066637
       10.000000 15.000000   ...  0.066637  0.066637  0.066637  0.066637
       15.000000 20.000000   ...  0.067493  0.067493  0.067493  0.067493
       20.000000 25.000000   ...  0.067493  0.067493  0.067493  0.067493
       25.000000 30.000000   ...  0.067493  0.067493  0.067493  0.067493
       30.000000 35.000000   ...  0.067615  0.067615  0.067615  0.067615
       35.000000 40.000000   ...  0.067615  0.067615  0.067615  0.067615
       40.000000 45.000000   ...  0.067615  0.067615  0.067615  0.067615
       45.000000 50.000000   ...  0.067615  0.067615  0.067615  0.067615
       50.000000 55.000000   ...  0.067359  0.067359  0.067359  0.067359
       55.000000 60.000000   ...  0.067359  0.067359  0.067359  0.067359
       60.000000 65.000000   ...  0.067359  0.067359  0.067359  0.067359
       65.000000 70.000000   ...  0.067359  0.067359  0.067359  0.067359
       70.000000 75.000000   ...  0.067359  0.067359  0.067359  0.067359
       75.000000 80.000000   ...  0.067359  0.067359  0.067359  0.067359
       80.000000 85.000000   ...  0.067359  0.067359  0.067359  0.067359
       85.000000 90.000000   ...  0.067359  0.067359  0.067359  0.067359
       90.000000 95.000000   ...  0.067359  0.067359  0.067359  0.067359
       95.000000 125.000000  ...  0.067359  0.067359  0.067359  0.067359
Male   0.000000  0.019178    ...  0.066669  0.066669  0.066669  0.066669
       0.019178  0.076712    ...  0.066669  0.066669  0.066669  0.066669
       0.076712  0.500000    ...  0.066669  0.066669  0.066669  0.066669
       0.500000  1.000000    ...  0.066669  0.066669  0.066669  0.066669
       1.000000  2.000000    ...  0.066669  0.066669  0.066669  0.066669
       2.000000  5.000000    ...  0.066669  0.066669  0.066669  0.066669
       5.000000  10.000000   ...  0.066943  0.066943  0.066943  0.066943
       10.000000 15.000000   ...  0.066943  0.066943  0.066943  0.066943
       15.000000 20.000000   ...  0.067407  0.067407  0.067407  0.067407
       20.000000 25.000000   ...  0.067407  0.067407  0.067407  0.067407
       25.000000 30.000000   ...  0.067407  0.067407  0.067407  0.067407
       30.000000 35.000000   ...  0.067687  0.067687  0.067687  0.067687
       35.000000 40.000000   ...  0.067687  0.067687  0.067687  0.067687
       40.000000 45.000000   ...  0.067687  0.067687  0.067687  0.067687
       45.000000 50.000000   ...  0.067687  0.067687  0.067687  0.067687
       50.000000 55.000000   ...  0.067442  0.067442  0.067442  0.067442
       55.000000 60.000000   ...  0.067442  0.067442  0.067442  0.067442
       60.000000 65.000000   ...  0.067442  0.067442  0.067442  0.067442
       65.000000 70.000000   ...  0.067442  0.067442  0.067442  0.067442
       70.000000 75.000000   ...  0.067442  0.067442  0.067442  0.067442
       75.000000 80.000000   ...  0.067442  0.067442  0.067442  0.067442
       80.000000 85.000000   ...  0.067442  0.067442  0.067442  0.067442
       85.000000 90.000000   ...  0.067442  0.067442  0.067442  0.067442
       90.000000 95.000000   ...  0.067442  0.067442  0.067442  0.067442
       95.000000 125.000000  ...  0.067442  0.067442  0.067442  0.067442

                             draw_489  draw_490  draw_491  draw_492  draw_493  \
sex    age_start age_end
Female 0.000000  0.019178    0.065912  0.065912  0.065912  0.065912  0.065912
       0.019178  0.076712    0.065912  0.065912  0.065912  0.065912  0.065912
       0.076712  0.500000    0.065912  0.065912  0.065912  0.065912  0.065912
       0.500000  1.000000    0.065912  0.065912  0.065912  0.065912  0.065912
       1.000000  2.000000    0.065912  0.065912  0.065912  0.065912  0.065912
       2.000000  5.000000    0.065912  0.065912  0.065912  0.065912  0.065912
       5.000000  10.000000   0.066637  0.066637  0.066637  0.066637  0.066637
       10.000000 15.000000   0.066637  0.066637  0.066637  0.066637  0.066637
       15.000000 20.000000   0.067493  0.067493  0.067493  0.067493  0.067493
       20.000000 25.000000   0.067493  0.067493  0.067493  0.067493  0.067493
       25.000000 30.000000   0.067493  0.067493  0.067493  0.067493  0.067493
       30.000000 35.000000   0.067615  0.067615  0.067615  0.067615  0.067615
       35.000000 40.000000   0.067615  0.067615  0.067615  0.067615  0.067615
       40.000000 45.000000   0.067615  0.067615  0.067615  0.067615  0.067615
       45.000000 50.000000   0.067615  0.067615  0.067615  0.067615  0.067615
       50.000000 55.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       55.000000 60.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       60.000000 65.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       65.000000 70.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       70.000000 75.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       75.000000 80.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       80.000000 85.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       85.000000 90.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       90.000000 95.000000   0.067359  0.067359  0.067359  0.067359  0.067359
       95.000000 125.000000  0.067359  0.067359  0.067359  0.067359  0.067359
Male   0.000000  0.019178    0.066669  0.066669  0.066669  0.066669  0.066669
       0.019178  0.076712    0.066669  0.066669  0.066669  0.066669  0.066669
       0.076712  0.500000    0.066669  0.066669  0.066669  0.066669  0.066669
       0.500000  1.000000    0.066669  0.066669  0.066669  0.066669  0.066669
       1.000000  2.000000    0.066669  0.066669  0.066669  0.066669  0.066669
       2.000000  5.000000    0.066669  0.066669  0.066669  0.066669  0.066669
       5.000000  10.000000   0.066943  0.066943  0.066943  0.066943  0.066943
       10.000000 15.000000   0.066943  0.066943  0.066943  0.066943  0.066943
       15.000000 20.000000   0.067407  0.067407  0.067407  0.067407  0.067407
       20.000000 25.000000   0.067407  0.067407  0.067407  0.067407  0.067407
       25.000000 30.000000   0.067407  0.067407  0.067407  0.067407  0.067407
       30.000000 35.000000   0.067687  0.067687  0.067687  0.067687  0.067687
       35.000000 40.000000   0.067687  0.067687  0.067687  0.067687  0.067687
       40.000000 45.000000   0.067687  0.067687  0.067687  0.067687  0.067687
       45.000000 50.000000   0.067687  0.067687  0.067687  0.067687  0.067687
       50.000000 55.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       55.000000 60.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       60.000000 65.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       65.000000 70.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       70.000000 75.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       75.000000 80.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       80.000000 85.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       85.000000 90.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       90.000000 95.000000   0.067442  0.067442  0.067442  0.067442  0.067442
       95.000000 125.000000  0.067442  0.067442  0.067442  0.067442  0.067442

                             draw_494  draw_495  draw_496  draw_497  draw_498  \
sex    age_start age_end
Female 0.000000  0.019178    0.065912  0.065912  0.065912  0.065912  0.065912

In [40]:
hgb_sd = hgb_sd * scale_factor

In [41]:
assert np.allclose(
    hgb_sd.mul(wealth_quintile_probabilities, axis=0).groupby([c for c in hgb_sd.index.names if c != 'wealth_quintile']).sum(),
    pre_disparity_groups,
)

In [42]:
hgb_sd.columns.name = "draw"
hgb_sd = hgb_sd.stack().rename("sd").reset_index()
hgb_sd

           sex  age_start     age_end wealth_quintile      draw         sd
0       Female        0.0    0.019178          lowest    draw_0  28.489640
1       Female        0.0    0.019178          lowest    draw_1  26.169288
2       Female        0.0    0.019178          lowest    draw_2  17.955243
3       Female        0.0    0.019178          lowest    draw_3  20.486661
4       Female        0.0    0.019178          lowest    draw_4  18.648197
...        ...        ...         ...             ...       ...        ...
124995    Male       95.0  125.000000         highest  draw_495  33.780207
124996    Male       95.0  125.000000         highest  draw_496  18.376878
124997    Male       95.0  125.000000         highest  draw_497  22.113952
124998    Male       95.0  125.000000         highest  draw_498  35.369247
124999    Male       95.0  125.000000         highest  draw_499  16.712756

[125000 rows x 6 columns]

In [43]:
mean_and_sd_hgb = pd.concat([
    hgb_mean.merge(hgb_sd, how="outer", validate="m:1").assign(scenario='baseline'),
    counterfactual_hgb_mean.merge(hgb_sd, how="outer", validate="m:1").assign(scenario='intervention')
])
mean_and_sd_hgb

,sex,age_start,age_end,wealth_quintile,draw,mean,sd,scenario
0,Female,0.0,0.019178,lowest,draw_0,133.664070,28.489640,baseline
1,Female,0.0,0.019178,lowest,draw_1,133.184863,26.169288,baseline
2,Female,0.0,0.019178,lowest,draw_2,131.073574,17.955243,baseline
3,Female,0.0,0.019178,lowest,draw_3,137.034319,20.486661,baseline
4,Female,0.0,0.019178,lowest,draw_4,141.690229,18.648197,baseline
...,...,...,...,...,...,...,...,...
124995,Male,95.0,125.000000,second,draw_495,97.031167,35.438084,intervention
124996,Male,95.0,125.000000,second,draw_496,106.139058,19.278785,intervention
124997,Male,95.0,125.000000,second,draw_497,105.312300,23.199269,intervention
124998,Male,95.0,125.000000,second,draw_498,99.292330,37.105111,intervention
124999,Male,95.0,125.000000,second,draw_499,107.325746,17.532990,intervention

In [44]:
thresholds = reshape_to_vivarium_format(pd.read_csv('/share/mnch/anemia/code/reference/model/anemia_thresholds.csv'), location.title()).droplevel(["age_group_name", "grp"]).reset_index()
thresholds

,sex,age_start,age_end,hgb_lower_anemic,hgb_lower_mild,hgb_lower_moderate,hgb_lower_severe,hgb_upper_anemic,hgb_upper_mild,hgb_upper_moderate,hgb_upper_severe,pregnant
0,Female,0.000000,0.019178,0,145,100,0,160,160,145,100,0
1,Female,0.019178,0.076712,0,120,85,0,135,135,120,85,0
2,Female,0.076712,0.500000,0,100,70,0,110,110,100,70,0
3,Female,0.500000,1.000000,0,100,70,0,110,110,100,70,0
4,Female,1.000000,2.000000,0,100,70,0,110,110,100,70,0
5,Female,2.000000,5.000000,0,100,70,0,110,110,100,70,0
6,Female,5.000000,10.000000,0,110,80,0,115,115,110,80,0
7,Female,10.000000,15.000000,0,100,70,0,110,110,100,70,1
8,Female,10.000000,15.000000,0,110,80,0,115,115,110,80,0
9,Female,15.000000,20.000000,0,110,80,0,120,120,110,80,0
10,Female,15.000000,20.000000,0,100,70,0,110,110,100,70,1
11,Female,20.000000,25.000000,0,110,80,0,120,120,110,80,0
12,Female,20.000000,25.000000,0,100,70,0,110,110,100,70,1
13,Female,25.000000,30.000000,0,110,80,0,120,120,110,80,0
14,Female,25.000000,30.000000,0,100,70,0,110,110,100,70,1
15,Female,30.000000,35.000000,0,110,80,0,120,120,110,80,0
16,Female,30.000000,35.000000,0,100,70,0,110,110,100,70,1
17,Female,35.000000,40.000000,0,110,80,0,120,120,110,80,0
18,Female,35.000000,40.000000,0,100,70,0,110,110,100,70,1
19,Female,40.000000,45.000000,0,110,80,0,120,120,110,80,0
20,Female,40.000000,45.000000,0,100,70,0,110,110,100,70,1
21,Female,45.000000,50.000000,0,110,80,0,120,120,110,80,0
22,Female,45.000000,50.000000,0,100,70,0,110,110,100,70,1
23,Female,50.000000,55.000000,0,110,80,0,120,120,110,80,0
24,Female,50.000000,55.000000,0,100,70,0,110,110,100,70,1
25,Female,55.000000,60.000000,0,110,80,0,120,120,110,80,0
26,Female,60.000000,65.000000,0,110,80,0,120,120,110,80,0
27,Female,65.000000,70.000000,0,110,80,0,120,120,110,80,0
28,Female,70.000000,75.000000,0,110,80,0,120,120,110,80,0
29,Female,75.000000,80.000000,0,110,80,0,120,120,110,80,0
30,Female,80.000000,85.000000,0,110,80,0,120,120,110,80,0
31,Female,85.000000,90.000000,0,110,80,0,120,120,110,80,0
32,Female,90.000000,95.000000,0,110,80,0,120,120,110,80,0
33,Female,95.000000,125.000000,0,110,80,0,120,120,110,80,0
34,Male,0.000000,0.019178,0,145,100,0,160,160,145,100,0
35,Male,0.019178,0.076712,0,120,85,0,135,135,120,85,0
36,Male,0.076712,0.500000,0,100,70,0,110,110,100,70,0
37,Male,0.500000,1.000000,0,100,70,0,110,110,100,70,0
38,Male,1.000000,2.000000,0,100,70,0,110,110,100,70,0
39,Male,2.000000,5.000000,0,100,70,0,110,110,100,70,0
40,Male,5.000000,10.000000,0,110,80,0,115,115,110,80,0
41,Male,10.000000,15.000000,0,110,80,0,115,115,110,80,0
42,Male,15.000000,20.000000,0,110,80,0,130,130,110,80,0
43,Male,20.000000,25.000000,0,110,80,0,130,130,110,80,0
44,Male,25.000000,30.000000,0,110,80,0,130,130,110,80,0
45,Male,30.000000,35.000000,0,110,80,0,130,130,110,80,0
46,Male,35.000000,40.000000,0,110,80,0,130,130,110,80,0
47,Male,40.000000,45.000000,0,110,80,0,130,130,110,80,0
48,Male,45.000000,50.000000,0,110,80,0,130,130,110,80,0
49,Male,50.000000,55.000000,0,110,80,0,130,130,110,80,0
50,Male,55.000000,60.000000,0,110,80,0,130,130,110,80,0
51,Male,60.000000,65.000000,0,110,80,0,130,130,110,80,0
52,Male,65.000000,70.000000,0,110,80,0,130,130,110,80,0
53,Male,70.000000,75.000000,0,110,80,0,130,130,110,80,0
54,Male,75.000000,80.000000,0,110,80,0,130,130,110,80,0
55,Male,80.000000,85.000000,0,110,80,0,130,130,110,80,0
56,Male,85.000000,90.000000,0,110,80,0,130,130,110,80,0
57,Male,90.000000,95.000000,0,110,80,0,130,130,110,80,0
58,Male,95.000000,125.000000,0,110,80,0,130,130,110,80,0

In [45]:
mean_and_sd_hgb = mean_and_sd_hgb.assign(pregnant=0).merge(thresholds, on=["sex", "age_start", "age_end", "pregnant"], how="left", validate="m:1")
mean_and_sd_hgb

,sex,age_start,age_end,wealth_quintile,draw,mean,sd,scenario,pregnant,hgb_lower_anemic,hgb_lower_mild,hgb_lower_moderate,hgb_lower_severe,hgb_upper_anemic,hgb_upper_mild,hgb_upper_moderate,hgb_upper_severe
0,Female,0.0,0.019178,lowest,draw_0,133.664070,28.489640,baseline,0,0,145,100,0,160,160,145,100
1,Female,0.0,0.019178,lowest,draw_1,133.184863,26.169288,baseline,0,0,145,100,0,160,160,145,100
2,Female,0.0,0.019178,lowest,draw_2,131.073574,17.955243,baseline,0,0,145,100,0,160,160,145,100
3,Female,0.0,0.019178,lowest,draw_3,137.034319,20.486661,baseline,0,0,145,100,0,160,160,145,100
4,Female,0.0,0.019178,lowest,draw_4,141.690229,18.648197,baseline,0,0,145,100,0,160,160,145,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,Male,95.0,125.000000,second,draw_495,97.031167,35.438084,intervention,0,0,110,80,0,130,130,110,80
249996,Male,95.0,125.000000,second,draw_496,106.139058,19.278785,intervention,0,0,110,80,0,130,130,110,80
249997,Male,95.0,125.000000,second,draw_497,105.312300,23.199269,intervention,0,0,110,80,0,130,130,110,80
249998,Male,95.0,125.000000,second,draw_498,99.292330,37.105111,intervention,0,0,110,80,0,130,130,110,80
249999,Male,95.0,125.000000,second,draw_499,107.325746,17.532990,intervention,0,0,110,80,0,130,130,110,80

In [46]:
assert (
    (mean_and_sd_hgb.hgb_upper_mild == mean_and_sd_hgb.hgb_upper_anemic).all() &
    (mean_and_sd_hgb.hgb_lower_severe == mean_and_sd_hgb.hgb_lower_anemic).all()
)
mean_and_sd_hgb = mean_and_sd_hgb.drop(columns=["hgb_upper_anemic", "hgb_lower_anemic"])

In [47]:
assert (
    (mean_and_sd_hgb.hgb_lower_mild == mean_and_sd_hgb.hgb_upper_moderate).all() &
    (mean_and_sd_hgb.hgb_lower_moderate == mean_and_sd_hgb.hgb_upper_severe).all()
)
mean_and_sd_hgb = mean_and_sd_hgb.drop(columns=["hgb_lower_mild", "hgb_lower_moderate"])

In [48]:
def _hemoglobin_distribution_parts_from_mean_sd(mean, sd):
    # NOTE: This is an unusual ensemble distribution. We should add functionality to the
    # EnsembleDistribution class to make this easier.
    x_min = 0
    x_max = 220
    gamma_params = risk_distributions.risk_distributions.Gamma.get_parameters(
        mean=mean, sd=sd
    )
    # NOTE: We have to override these, otherwise Gamma is overly conservative in what values
    # are computable
    # https://github.com/ihmeuw/risk_distributions/issues/61
    gamma_params["x_min"] = x_min
    gamma_params["x_max"] = x_max
    hemoglobin_distribution_gamma_part = risk_distributions.risk_distributions.Gamma(
        gamma_params
    )

    # NOTE: Forced to duplicate https://github.com/ihmeuw/risk_distributions/blob/a9ed9d7e8372590018355012a7a7ffefa87b0819/src/risk_distributions/risk_distributions.py#L428-L434
    # because it doesn't permit the custom x_min and x_max, and these are used in calculating the others
    mgumbel_params = pd.DataFrame({
        "loc": x_max - mean - (np.euler_gamma * np.sqrt(6) / np.pi * sd),
        "scale": np.sqrt(6) / np.pi * sd,
        "x_min": x_min,
        "x_max": x_max,
    })
    hemoglobin_distribution_mgumbel_part = (
        risk_distributions.risk_distributions.MirroredGumbel(mgumbel_params)
    )
    return hemoglobin_distribution_gamma_part, hemoglobin_distribution_mgumbel_part

(
    hemoglobin_distribution_gamma_part,
    hemoglobin_distribution_mgumbel_part,
) = _hemoglobin_distribution_parts_from_mean_sd(mean_and_sd_hgb['mean'], mean_and_sd_hgb.sd)

def cdf(x):
    gamma_cdf = hemoglobin_distribution_gamma_part.cdf(x)
    # NOTE: There is a bug in this CDF function -- it is reversed!
    # https://github.com/ihmeuw/risk_distributions/issues/62
    mgumbel_cdf = 1 - hemoglobin_distribution_mgumbel_part.cdf(x)
    return (
        0.4
        * gamma_cdf
        + 0.6
        * mgumbel_cdf
    )

In [49]:
mean_and_sd_hgb["severe"] = cdf(mean_and_sd_hgb.hgb_upper_severe.copy()) - cdf(mean_and_sd_hgb.hgb_lower_severe.copy())
mean_and_sd_hgb["moderate"] = cdf(mean_and_sd_hgb.hgb_upper_moderate.copy()) - mean_and_sd_hgb["severe"].copy()
mean_and_sd_hgb["mild"] = cdf(mean_and_sd_hgb.hgb_upper_mild.copy()) - mean_and_sd_hgb["moderate"].copy() - mean_and_sd_hgb["severe"].copy()
mean_and_sd_hgb["anemic"] = mean_and_sd_hgb["mild"] + mean_and_sd_hgb["moderate"] + mean_and_sd_hgb["severe"]
mean_and_sd_hgb

,sex,age_start,age_end,wealth_quintile,draw,mean,sd,scenario,pregnant,hgb_lower_severe,hgb_upper_mild,hgb_upper_moderate,hgb_upper_severe,severe,moderate,mild,anemic
0,Female,0.0,0.019178,lowest,draw_0,133.664070,28.489640,baseline,0,0,160,145,100,0.112862,0.522239,0.199909,0.835009
1,Female,0.0,0.019178,lowest,draw_1,133.184863,26.169288,baseline,0,0,160,145,100,0.099261,0.557548,0.208117,0.864926
2,Female,0.0,0.019178,lowest,draw_2,131.073574,17.955243,baseline,0,0,160,145,100,0.048532,0.734690,0.185452,0.968674
3,Female,0.0,0.019178,lowest,draw_3,137.034319,20.486661,baseline,0,0,160,145,100,0.042398,0.586287,0.261777,0.890462
4,Female,0.0,0.019178,lowest,draw_4,141.690229,18.648197,baseline,0,0,160,145,100,0.021629,0.516715,0.313810,0.852154
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,Male,95.0,125.000000,second,draw_495,97.031167,35.438084,intervention,0,0,130,110,80,0.286526,0.341548,0.210403,0.838477
249996,Male,95.0,125.000000,second,draw_496,106.139058,19.278785,intervention,0,0,130,110,80,0.086932,0.463496,0.366191,0.916619
249997,Male,95.0,125.000000,second,draw_497,105.312300,23.199269,intervention,0,0,130,110,80,0.129326,0.423757,0.322755,0.875838
249998,Male,95.0,125.000000,second,draw_498,99.292330,37.105111,intervention,0,0,130,110,80,0.272747,0.323687,0.209075,0.805509
249999,Male,95.0,125.000000,second,draw_499,107.325746,17.532990,intervention,0,0,130,110,80,0.063240,0.466220,0.397966,0.927426

In [50]:
disability_weights = pd.read_hdf('/mnt/team/simulation_science/costeffectiveness/auxiliary_data/GBD_2021/02_processed_data/disability_weight/sequela/all/all.hdf')
disability_weights = disability_weights[disability_weights.healthstate.isin(['anemia_mild', 'anemia_mod', 'anemia_sev'])].set_index('healthstate').filter(like='draw_')
disability_weights.columns.name = 'draw'
disability_weights = disability_weights.stack().rename('disability_weight').reset_index()
disability_weights

      healthstate      draw  disability_weight
0     anemia_mild    draw_0           0.002420
1     anemia_mild    draw_1           0.003172
2     anemia_mild    draw_2           0.002644
3     anemia_mild    draw_3           0.003085
4     anemia_mild    draw_4           0.001845
...           ...       ...                ...
2995   anemia_sev  draw_995           0.174969
2996   anemia_sev  draw_996           0.086798
2997   anemia_sev  draw_997           0.131996
2998   anemia_sev  draw_998           0.124427
2999   anemia_sev  draw_999           0.138260

[3000 rows x 3 columns]

In [51]:
mean_and_sd_hgb = mean_and_sd_hgb.merge(
    disability_weights[disability_weights.healthstate == 'anemia_mild'][['draw', 'disability_weight']].rename(columns={'disability_weight': 'mild_dw'}),
    validate="m:1",
).merge(
    disability_weights[disability_weights.healthstate == 'anemia_mod'][['draw', 'disability_weight']].rename(columns={'disability_weight': 'moderate_dw'}),
    validate="m:1",
).merge(
    disability_weights[disability_weights.healthstate == 'anemia_sev'][['draw', 'disability_weight']].rename(columns={'disability_weight': 'severe_dw'}),
    validate="m:1",
)

In [52]:
mean_and_sd_hgb["mild_ylds"] = mean_and_sd_hgb.mild * mean_and_sd_hgb.mild_dw
mean_and_sd_hgb["moderate_ylds"] = mean_and_sd_hgb.moderate * mean_and_sd_hgb.moderate_dw
mean_and_sd_hgb["severe_ylds"] = mean_and_sd_hgb.severe * mean_and_sd_hgb.severe_dw
mean_and_sd_hgb['anemic_ylds'] = mean_and_sd_hgb['mild_ylds'] + mean_and_sd_hgb['moderate_ylds'] + mean_and_sd_hgb['severe_ylds']

In [53]:
index_cols = ['age_start', 'age_end', 'sex', 'draw', "wealth_quintile"]
value_cols = ["mild", "moderate", "severe", "anemic", "mild_ylds", "moderate_ylds", "severe_ylds", "anemic_ylds"]

baseline_anemia = mean_and_sd_hgb[mean_and_sd_hgb.scenario == 'baseline'].set_index(index_cols)[value_cols]
counterfactual_anemia = mean_and_sd_hgb[mean_and_sd_hgb.scenario == 'intervention'].set_index(index_cols)[value_cols]

In [54]:
baseline_anemia.sort_index()

                                                         mild  moderate  \
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth           0.252803  0.456425
                                    highest          0.274127  0.382060
                                    lowest           0.199909  0.522239
                                    middle           0.235473  0.465088
                                    second           0.218151  0.502540
...                                                       ...       ...
95.0      125.000000 Male   draw_99 fourth           0.309215  0.469073
                                    highest          0.334532  0.460566
                                    lowest           0.277172  0.484854
                                    middle           0.302442  0.465940
                                    second           0.297510  0.475769

                                                       severe    anemic  \
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth           0.045826  0.755054
                                    highest          0.024782  0.680969
                                    lowest           0.112862  0.835009
                                    middle           0.060370  0.760930
                                    second           0.085165  0.805856
...                                                       ...       ...
95.0      125.000000 Male   draw_99 fourth           0.141330  0.919618
                                    highest          0.115949  0.911047
                                    lowest           0.174130  0.936156
                                    middle           0.149854  0.918237
                                    second           0.152991  0.926270

                                                     mild_ylds  moderate_ylds  \
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth            0.000612       0.027066
                                    highest           0.000664       0.022656
                                    lowest            0.000484       0.030969
                                    middle            0.000570       0.027580
                                    second            0.000528       0.029801
...                                                        ...            ...
95.0      125.000000 Male   draw_99 fourth            0.001299       0.019551
                                    highest           0.001405       0.019197
                                    lowest            0.001164       0.020209
                                    middle            0.001270       0.019421
                                    second            0.001250       0.019831

                                                     severe_ylds  anemic_ylds
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth              0.009117     0.036795
                                    highest             0.004930     0.028250
                                    lowest              0.022453     0.053906
                                    middle              0.012010     0.040160
                                    second              0.016943     0.047272
...                                                          ...          ...
95.0      125.000000 Male   draw_99 fourth              0.016788     0.037638
                                    highest             0.013773     0.034375
                                    lowest              0.020684     0.042057
                                    middle              0.017800     0.038492
                                    second              0.018173     0.039253

[125000 rows x 8 columns]

In [55]:
counterfactual_anemia.sort_index()

                                                         mild  moderate  \
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth           0.253327  0.450738
                                    highest          0.273763  0.377561
                                    lowest           0.202885  0.514738
                                    middle           0.236209  0.459044
                                    second           0.220001  0.495437
...                                                       ...       ...
95.0      125.000000 Male   draw_99 fourth           0.313415  0.464981
                                    highest          0.337451  0.457096
                                    lowest           0.286703  0.477961
                                    middle           0.307318  0.461326
                                    second           0.304615  0.469525

                                                       severe    anemic  \
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth           0.044591  0.748656
                                    highest          0.024286  0.675610
                                    lowest           0.107780  0.825403
                                    middle           0.058538  0.753791
                                    second           0.081890  0.797329
...                                                       ...       ...
95.0      125.000000 Male   draw_99 fourth           0.137514  0.915909
                                    highest          0.113515  0.908062
                                    lowest           0.165153  0.929817
                                    middle           0.145152  0.913797
                                    second           0.146467  0.920607

                                                     mild_ylds  moderate_ylds  \
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth            0.000613       0.026729
                                    highest           0.000663       0.022390
                                    lowest            0.000491       0.030524
                                    middle            0.000572       0.027222
                                    second            0.000533       0.029380
...                                                        ...            ...
95.0      125.000000 Male   draw_99 fourth            0.001316       0.019381
                                    highest           0.001417       0.019052
                                    lowest            0.001204       0.019922
                                    middle            0.001291       0.019229
                                    second            0.001279       0.019570

                                                     severe_ylds  anemic_ylds
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth              0.008871     0.036213
                                    highest             0.004831     0.027884
                                    lowest              0.021442     0.052457
                                    middle              0.011646     0.039439
                                    second              0.016291     0.046203
...                                                          ...          ...
95.0      125.000000 Male   draw_99 fourth              0.016335     0.037032
                                    highest             0.013484     0.033954
                                    lowest              0.019618     0.040744
                                    middle              0.017242     0.037761
                                    second              0.017398     0.038248

[125000 rows x 8 columns]

In [56]:
baseline_anemia - counterfactual_anemia

                                                         mild  moderate  \
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth          -0.000525  0.005687
                                    highest          0.000364  0.004499
                                    lowest          -0.002976  0.007500
                                    middle          -0.000736  0.006044
                                    second          -0.001850  0.007103
...                                                       ...       ...
95.0      125.000000 Male   draw_99 fourth          -0.004200  0.004093
                                    highest         -0.002919  0.003470
                                    lowest          -0.009531  0.006893
                                    middle          -0.004876  0.004614
                                    second          -0.007105  0.006244

                                                       severe    anemic  \
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth           0.001235  0.006398
                                    highest          0.000496  0.005359
                                    lowest           0.005082  0.009606
                                    middle           0.001832  0.007139
                                    second           0.003274  0.008527
...                                                       ...       ...
95.0      125.000000 Male   draw_99 fourth           0.003816  0.003709
                                    highest          0.002434  0.002985
                                    lowest           0.008977  0.006339
                                    middle           0.004702  0.004441
                                    second           0.006524  0.005663

                                                        mild_ylds  \
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth          -1.270008e-06
                                    highest          8.819852e-07
                                    lowest          -7.203445e-06
                                    middle          -1.781471e-06
                                    second          -4.478496e-06
...                                                           ...
95.0      125.000000 Male   draw_99 fourth          -1.764184e-05
                                    highest         -1.226141e-05
                                    lowest          -4.003201e-05
                                    middle          -2.048020e-05
                                    second          -2.984204e-05

                                                     moderate_ylds  \
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth                0.000337
                                    highest               0.000267
                                    lowest                0.000445
                                    middle                0.000358
                                    second                0.000421
...                                                            ...
95.0      125.000000 Male   draw_99 fourth                0.000171
                                    highest               0.000145
                                    lowest                0.000287
                                    middle                0.000192
                                    second                0.000260

                                                     severe_ylds  anemic_ylds
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth              0.000246     0.000582
                                    highest             0.000099     0.000366
                                    lowest              0.001011     0.001449
                                    middle              0.000364     0.000721
                                    second              0.000651     0.001068
...                                                          ...          ...
95.0      125.000000 Male   draw_99 fourth              0.000453     0.000606
                                    highest             0.000289     0.000421
                                    lowest              0.001066     0.001314
                                    middle              0.000559     0.000730
                                    second              0.000775     0.001005

[125000 rows x 8 columns]

In [57]:
# BUT our counterfactual is only in a world where everyone is iron-responsive.
# Cleaned this up from https://github.com/ihmeuw/vivarium_research_lsff/blob/1cb465a752d299401ae366db537dc8d557162184/multiplication_models/iron_model_U5.ipynb,
# but have not checked it in extreme detail.
iron_responsive_anemia_sequelae = [
    gbd_mapping.sequelae.mild_anemia_due_to_schistosomiasis,
    gbd_mapping.sequelae.moderate_anemia_due_to_schistosomiasis,
    gbd_mapping.sequelae.severe_anemia_due_to_schistosomiasis,
    gbd_mapping.sequelae.mild_anemia_due_to_hookworm_disease,
    gbd_mapping.sequelae.moderate_anemia_due_to_hookworm_disease,
    gbd_mapping.sequelae.severe_anemia_due_to_hookworm_disease,
    gbd_mapping.sequelae.mild_anemia_due_to_other_neglected_tropical_diseases,
    gbd_mapping.sequelae.moderate_anemia_due_to_other_neglected_tropical_diseases,
    gbd_mapping.sequelae.severe_anemia_due_to_other_neglected_tropical_diseases,
    gbd_mapping.sequelae.mild_anemia_due_to_maternal_hemorrhage,
    gbd_mapping.sequelae.moderate_anemia_due_to_maternal_hemorrhage,
    gbd_mapping.sequelae.severe_anemia_due_to_maternal_hemorrhage,
    gbd_mapping.sequelae.mild_iron_deficiency_anemia,
    gbd_mapping.sequelae.moderate_iron_deficiency_anemia,
    gbd_mapping.sequelae.severe_iron_deficiency_anemia,
    gbd_mapping.sequelae.mild_anemia_due_to_other_infectious_diseases,
    gbd_mapping.sequelae.moderate_anemia_due_to_other_infectious_diseases,
    gbd_mapping.sequelae.severe_anemia_due_to_other_infectious_diseases,
    gbd_mapping.sequelae.menstrual_disorders_with_mild_anemia,
    gbd_mapping.sequelae.menstrual_disorders_with_moderate_anemia,
    gbd_mapping.sequelae.menstrual_disorders_with_severe_anemia,
    gbd_mapping.sequelae.stage_3_chronic_kidney_disease_due_to_hypertension_with_mild_anemia,
    gbd_mapping.sequelae.stage_3_chronic_kidney_disease_due_to_hypertension_with_moderate_anemia,
    gbd_mapping.sequelae.stage_3_chronic_kidney_disease_due_to_hypertension_with_severe_anemia,
    gbd_mapping.sequelae.stage_3_chronic_kidney_disease_due_to_glomerulonephritis_with_mild_anemia,
    gbd_mapping.sequelae.stage_3_chronic_kidney_disease_due_to_glomerulonephritis_with_moderate_anemia,
    gbd_mapping.sequelae.stage_3_chronic_kidney_disease_due_to_glomerulonephritis_with_severe_anemia,
    gbd_mapping.sequelae.stage_3_chronic_kidney_disease_due_to_other_and_unspecified_causes_with_mild_anemia,
    gbd_mapping.sequelae.stage_3_chronic_kidney_disease_due_to_other_and_unspecified_causes_with_moderate_anemia,
    gbd_mapping.sequelae.stage_3_chronic_kidney_disease_due_to_other_and_unspecified_causes_with_severe_anemia,
    gbd_mapping.sequelae.uterine_fibroids_symptomatic_with_mild_anemia,
    gbd_mapping.sequelae.uterine_fibroids_symptomatic_with_moderate_anemia,
    gbd_mapping.sequelae.uterine_fibroids_symptomatic_with_severe_anemia,
    gbd_mapping.sequelae.stage_5_chronic_kidney_disease_untreated_due_to_hypertension_with_mild_anemia,
    gbd_mapping.sequelae.stage_5_chronic_kidney_disease_untreated_due_to_hypertension_with_moderate_anemia,
    gbd_mapping.sequelae.stage_5_chronic_kidney_disease_untreated_due_to_hypertension_with_severe_anemia,
    gbd_mapping.sequelae.stage_5_chronic_kidney_disease_untreated_due_to_glomerulonephritis_with_mild_anemia,
    gbd_mapping.sequelae.stage_5_chronic_kidney_disease_untreated_due_to_glomerulonephritis_with_moderate_anemia,
    gbd_mapping.sequelae.stage_5_chronic_kidney_disease_untreated_due_to_glomerulonephritis_with_severe_anemia,
    gbd_mapping.sequelae.stage_5_chronic_kidney_disease_untreated_due_to_other_and_unspecified_causes_with_mild_anemia,
    gbd_mapping.sequelae.stage_5_chronic_kidney_disease_untreated_due_to_other_and_unspecified_causes_with_moderate_anemia,
    gbd_mapping.sequelae.stage_5_chronic_kidney_disease_untreated_due_to_other_and_unspecified_causes_with_severe_anemia,
    gbd_mapping.sequelae.stage_4_chronic_kidney_disease_untreated_due_to_hypertension_with_mild_anemia,
    gbd_mapping.sequelae.stage_4_chronic_kidney_disease_untreated_due_to_hypertension_with_moderate_anemia,
    gbd_mapping.sequelae.stage_4_chronic_kidney_disease_untreated_due_to_hypertension_with_severe_anemia,
    gbd_mapping.sequelae.stage_4_chronic_kidney_disease_untreated_due_to_glomerulonephritis_with_mild_anemia,
    gbd_mapping.sequelae.stage_4_chronic_kidney_disease_untreated_due_to_glomerulonephritis_with_moderate_anemia,
    gbd_mapping.sequelae.stage_4_chronic_kidney_disease_untreated_due_to_glomerulonephritis_with_severe_anemia,
    gbd_mapping.sequelae.stage_4_chronic_kidney_disease_untreated_due_to_other_and_unspecified_causes_with_mild_anemia,
    gbd_mapping.sequelae.stage_4_chronic_kidney_disease_untreated_due_to_other_and_unspecified_causes_with_moderate_anemia,
    gbd_mapping.sequelae.stage_4_chronic_kidney_disease_untreated_due_to_other_and_unspecified_causes_with_severe_anemia,
    gbd_mapping.sequelae.mildly_symptomatic_pud_with_mild_anemia,
    gbd_mapping.sequelae.moderately_symptomatic_pud_with_mild_anemia,
    gbd_mapping.sequelae.mildly_symptomatic_pud_with_moderate_anemia,
    gbd_mapping.sequelae.moderately_symptomatic_pud_with_moderate_anemia,
    gbd_mapping.sequelae.mildly_symptomatic_pud_with_severe_anemia,
    gbd_mapping.sequelae.moderately_symptomatic_pud_with_severe_anemia,
    gbd_mapping.sequelae.asymptomatic_pud_with_mild_anemia,
    gbd_mapping.sequelae.asymptomatic_pud_with_moderate_anemia,
    gbd_mapping.sequelae.asymptomatic_pud_with_severe_anemia,
    gbd_mapping.sequelae.mildy_symptomatic_gastritis_duodenitis_with_mild_anemia,
    gbd_mapping.sequelae.moderately_symptomatic_gastritis_duodenitis_with_mild_anemia,
    gbd_mapping.sequelae.mildly_symptomatic_gastritis_duodenitis_with_moderate_anemia,
    gbd_mapping.sequelae.moderately_symptomatic_gastritis_duodenitis_with_moderate_anemia,
    gbd_mapping.sequelae.mildy_symptomatic_gastritis_duodenitis_with_severe_anemia,
    gbd_mapping.sequelae.moderately_symptomatic_gastritis_duodenitis_with_severe_anemia,
    gbd_mapping.sequelae.asymptomatic_gastritis_duodenitis_with_mild_anemia,
    gbd_mapping.sequelae.asymptomatic_gastritis_duodenitis_with_moderate_anemia,
    gbd_mapping.sequelae.asymptomatic_gastritis_duodenitis_with_severe_anemia,
    gbd_mapping.sequelae.stage_3_chronic_kidney_disease_due_to_type_1_diabetes_mellitus_with_severe_anemia,
    gbd_mapping.sequelae.stage_3_chronic_kidney_disease_due_to_type_2_diabetes_mellitus_with_severe_anemia,
    gbd_mapping.sequelae.stage_3_chronic_kidney_disease_due_to_type_1_diabetes_mellitus_with_moderate_anemia,
    gbd_mapping.sequelae.stage_3_chronic_kidney_disease_due_to_type_2_diabetes_mellitus_with_mdoerate_anemia,
    gbd_mapping.sequelae.stage_3_chronic_kidney_disease_due_to_type_1_diabetes_mellitus_with_mild_anemia,
    gbd_mapping.sequelae.stage_3_chronic_kidney_disease_due_to_type_2_diabetes_mellitus_with_mild_anemia,
    gbd_mapping.sequelae.stage_4_chronic_kidney_disease_untreated_due_to_type_1_diabetes_mellitus_with_severe_anemia,
    gbd_mapping.sequelae.stage_4_chronic_kidney_disease_untreated_due_to_type_2_diabetes_mellitus_with_severe_anemia,
    gbd_mapping.sequelae.stage_4_chronic_kidney_disease_untreated_due_to_type_1_diabetes_mellitus_with_moderate_anemia,
    gbd_mapping.sequelae.stage_4_chronic_kidney_disease_untreated_due_to_type_2_diabetes_mellitus_with_mdoerate_anemia,
    gbd_mapping.sequelae.stage_4_chronic_kidney_disease_untreated_due_to_type_1_diabetes_mellitus_with_mild_anemia,
    gbd_mapping.sequelae.stage_4_chronic_kidney_disease_untreated_due_to_type_2_diabetes_mellitus_with_mild_anemia,
    gbd_mapping.sequelae.stage_5_chronic_kidney_disease_untreated_due_to_type_1_diabetes_mellitus_with_severe_anemia,
    gbd_mapping.sequelae.stage_5_chronic_kidney_disease_untreated_due_to_type_2_diabetes_mellitus_with_severe_anemia,
    gbd_mapping.sequelae.stage_5_chronic_kidney_disease_untreated_due_to_type_1_diabetes_mellitus_with_moderate_anemia,
    gbd_mapping.sequelae.stage_5_chronic_kidney_disease_untreated_due_to_type_2_diabetes_mellitus_with_moderate_anemia,
    gbd_mapping.sequelae.stage_5_chronic_kidney_disease_untreated_due_to_type_1_diabetes_mellitus_with_mild_anemia,
    gbd_mapping.sequelae.stage_5_chronic_kidney_disease_untreated_due_to_type_2_diabetes_mellitus_with_mild_anemia,
    gbd_mapping.sequelae.vitamin_a_deficiency_with_mild_anemia,
    gbd_mapping.sequelae.vitamin_a_deficiency_with_moderate_anemia,
    gbd_mapping.sequelae.vitamin_a_deficiency_with_severe_anemia,
    gbd_mapping.sequelae.ulcerative_colitis_with_mild_anemia,
    gbd_mapping.sequelae.ulcerative_colitis_with_moderate_anemia,
    gbd_mapping.sequelae.ulcerative_colitis_with_severe_anemia,
    gbd_mapping.sequelae.crohns_disease_with_mild_anemia,
    gbd_mapping.sequelae.crohns_disease_with_moderate_anemia,
    gbd_mapping.sequelae.crohns_disease_with_severe_anemia,
    gbd_mapping.sequelae.complicated_pud_with_mild_anemia,
    gbd_mapping.sequelae.complicated_pud_with_moderate_anemia,
    gbd_mapping.sequelae.complicated_pud_with_severe_anemia,
    gbd_mapping.sequelae.complicated_gastritis_duodenitis_with_mild_anemia,
    gbd_mapping.sequelae.complicated_gastritis_duodenitis_with_moderate_anemia,
    gbd_mapping.sequelae.complicated_gastritis_duodenitis_with_severe_anemia,
    gbd_mapping.sequelae.severe_acute_uncomplicated_pud_with_mild_anemia,
    gbd_mapping.sequelae.severe_acute_uncomplicated_pud_with_moderate_anemia,
    gbd_mapping.sequelae.severe_acute_uncomplicated_pud_with_severe_anemia,
    gbd_mapping.sequelae.severe_acute_uncomplicated_gastritis_duodenitis_with_mild_anemia,
    gbd_mapping.sequelae.severe_acute_uncomplicated_gastritis_duodenitis_with_moderate_anemia,
    gbd_mapping.sequelae.severe_acute_uncomplicated_gastritis_duodenitis_with_severe_anemia,
    gbd_mapping.sequelae.end_stage_renal_disease_on_dialysis_due_to_type_1_diabetes_mellitus_with_mild_anemia,
    gbd_mapping.sequelae.end_stage_renal_disease_on_dialysis_due_to_type_2_diabetes_mellitus_with_mild_anemia,
    gbd_mapping.sequelae.end_stage_renal_disease_on_dialysis_due_to_hypertension_with_mild_anemia,
    gbd_mapping.sequelae.end_stage_renal_disease_on_dialysis_due_to_glomerulonephritis_with_mild_anemia,
    gbd_mapping.sequelae.end_stage_renal_disease_on_dialysis_due_to_other_and_unspecified_causes_with_mild_anemia,
    gbd_mapping.sequelae.end_stage_renal_disease_on_dialysis_due_to_type_1_diabetes_mellitus_with_moderate_anemia,
    gbd_mapping.sequelae.end_stage_renal_disease_on_dialysis_due_to_type_2_diabetes_mellitus_with_moderate_anemia,
    gbd_mapping.sequelae.end_stage_renal_disease_on_dialysis_due_to_hypertension_with_moderate_anemia,
    gbd_mapping.sequelae.end_stage_renal_disease_on_dialysis_due_to_glomerulonephritis_with_moderate_anemia,
    gbd_mapping.sequelae.end_stage_renal_disease_on_dialysis_due_to_other_and_unspecified_causes_with_moderate_anemia,
    gbd_mapping.sequelae.end_stage_renal_disease_on_dialysis_due_to_type_1_diabetes_mellitus_with_severe_anemia,
    gbd_mapping.sequelae.end_stage_renal_disease_on_dialysis_due_to_type_2_diabetes_mellitus_with_severe_anemia,
    gbd_mapping.sequelae.end_stage_renal_disease_on_dialysis_due_to_hypertension_with_severe_anemia,
    gbd_mapping.sequelae.end_stage_renal_disease_on_dialysis_due_to_glomerulonephritis_with_severe_anemia,
    gbd_mapping.sequelae.end_stage_renal_disease_on_dialysis_due_to_other_and_unspecified_causes_with_severe_anemia,
    gbd_mapping.sequelae.cirrhosis_and_other_chronic_liver_diseases_due_to_hepatitis_b_decompensated_with_mild_anemia,
    gbd_mapping.sequelae.cirrhosis_and_other_chronic_liver_diseases_due_to_hepatitis_b_decompensated_with_moderate_anemia,
    gbd_mapping.sequelae.cirrhosis_and_other_chronic_liver_diseases_due_to_hepatitis_b_decompensated_with_severe_anemia,
    gbd_mapping.sequelae.cirrhosis_and_other_chronic_liver_diseases_due_to_hepatitis_c_decompensated_with_mild_anemia,
    gbd_mapping.sequelae.cirrhosis_and_other_chronic_liver_diseases_due_to_hepatitis_c_decompensated_with_moderate_anemia,
    gbd_mapping.sequelae.cirrhosis_and_other_chronic_liver_diseases_due_to_hepatitis_c_decompensated_with_severe_anemia,
    gbd_mapping.sequelae.cirrhosis_and_other_chronic_liver_diseases_due_to_alcohol_decompensated_with_mild_anemia,
    gbd_mapping.sequelae.cirrhosis_and_other_chronic_liver_diseases_due_to_alcohol_decompensated_with_moderate_anemia,
    gbd_mapping.sequelae.cirrhosis_and_other_chronic_liver_diseases_due_to_alcohol_decompensated_with_severe_anemia,
    gbd_mapping.sequelae.cirrhosis_and_other_chronic_liver_diseases_due_to_other_decompensated_with_mild_anemia,
    gbd_mapping.sequelae.cirrhosis_and_other_chronic_liver_diseases_due_to_other_decompensated_with_moderate_anemia,
    gbd_mapping.sequelae.cirrhosis_and_other_chronic_liver_diseases_due_to_other_decompensated_with_severe_anemia,
    gbd_mapping.sequelae.cirrhosis_and_other_chronic_liver_diseases_due_to_nash_decompensated_with_mild_anemia,
    gbd_mapping.sequelae.cirrhosis_and_other_chronic_liver_diseases_due_to_nash_decompensated_with_moderate_anemia,
    gbd_mapping.sequelae.cirrhosis_and_other_chronic_liver_diseases_due_to_nash_decompensated_with_severe_anemia,
]

In [58]:
non_iron_responsive_anemia_sequelae = [
    gbd_mapping.sequelae.mild_anemia_due_to_other_hemoglobinopathies_and_hemolytic_anemias,
    gbd_mapping.sequelae.moderate_anemia_due_to_other_hemoglobinopathies_and_hemolytic_anemias,
    gbd_mapping.sequelae.severe_anemia_due_to_other_hemoglobinopathies_and_hemolytic_anemias,
    gbd_mapping.sequelae.mild_anemia_due_to_b_thalassemia_trait,
    gbd_mapping.sequelae.moderate_anemia_due_to_b_thalassemia_trait,
    gbd_mapping.sequelae.severe_anemia_due_to_b_thalassemia_trait,
    gbd_mapping.sequelae.mild_anemia_due_to_hemoglobin_e_trait,
    gbd_mapping.sequelae.moderate_anemia_due_to_hemoglobin_e_trait,
    gbd_mapping.sequelae.severe_anemia_due_to_hemoglobin_e_trait,
    gbd_mapping.sequelae.mild_anemia_due_to_sickle_cell_trait,
    gbd_mapping.sequelae.moderate_anemia_due_to_sickle_cell_trait,
    gbd_mapping.sequelae.severe_anemia_due_to_sickle_cell_trait,
    gbd_mapping.sequelae.hemizygous_g6pd_deficiency_with_mild_anemia,
    gbd_mapping.sequelae.hemizygous_g6pd_deficiency_with_moderate_anemia,
    gbd_mapping.sequelae.hemizygous_g6pd_deficiency_with_severe_anemia,
    gbd_mapping.sequelae.mild_anemia_due_to_malaria_parasitemia_pfpr,
    gbd_mapping.sequelae.moderate_anemia_due_to_malaria_parasitemia_pfpr,
    gbd_mapping.sequelae.severe_anemia_due_to_malaria_parasitemia_pfpr,
    gbd_mapping.sequelae.mild_anemia_due_to_homozygous_sickle_cell_and_severe_sickle_cell_beta_thalassemia,
    gbd_mapping.sequelae.moderate_anemia_due_to_homozygous_sickle_cell_and_severe_sickle_cell_beta_thalassemia,
    gbd_mapping.sequelae.severe_anemia_due_to_homozygous_sickle_cell_and_severe_sickle_cell_beta_thalassemia,
    gbd_mapping.sequelae.mild_anemia_due_to_hemoglobin_sc_disease,
    gbd_mapping.sequelae.moderate_anemia_due_to_hemoglobin_sc_disease,
    gbd_mapping.sequelae.severe_anemia_due_to_hemoglobin_sc_disease,
    gbd_mapping.sequelae.mild_anemia_due_to_mild_sickle_cell_beta_thalassemia,
    gbd_mapping.sequelae.moderate_anemia_due_to_mild_sickle_cell_beta_thalassemia,
    gbd_mapping.sequelae.severe_anemia_due_to_mild_sickle_cell_beta_thalassemia,
    gbd_mapping.sequelae.severe_malaria_with_mild_anemia,
    gbd_mapping.sequelae.severe_malaria_with_moderate_anemia,
    gbd_mapping.sequelae.severe_malaria_with_severe_anemia,
    gbd_mapping.sequelae.mild_malaria_with_mild_anemia,
    gbd_mapping.sequelae.mild_malaria_with_moderate_anemia,
    gbd_mapping.sequelae.mild_malaria_with_severe_anemia,
    gbd_mapping.sequelae.moderate_malaria_with_mild_anemia,
    gbd_mapping.sequelae.moderate_malaria_with_moderate_anemia,
    gbd_mapping.sequelae.moderate_malaria_with_severe_anemia,
    gbd_mapping.sequelae.early_hiv_with_mild_anemia,
    gbd_mapping.sequelae.early_hiv_with_moderate_anemia,
    gbd_mapping.sequelae.early_hiv_with_severe_anemia,
    gbd_mapping.sequelae.symptomatic_hiv_with_mild_anemia,
    gbd_mapping.sequelae.symptomatic_hiv_with_moderate_anemia,
    gbd_mapping.sequelae.symptomatic_hiv_with_severe_anemia,
    gbd_mapping.sequelae.hiv_aids_with_antiretroviral_treatment_with_mild_anemia,
    gbd_mapping.sequelae.hiv_aids_with_antiretroviral_treatment_with_moderate_anemia,
    gbd_mapping.sequelae.hiv_aids_with_antiretroviral_treatment_with_severe_anemia,
    gbd_mapping.sequelae.aids_with_mild_anemia,
    gbd_mapping.sequelae.aids_with_moderate_anemia,
    gbd_mapping.sequelae.aids_with_severe_anemia,
    gbd_mapping.sequelae.hiv_aids_drug_susceptible_tuberculosis_with_mild_anemia,
    gbd_mapping.sequelae.hiv_aids_drug_susceptible_tuberculosis_with_moderate_anemia,
    gbd_mapping.sequelae.hiv_aids_drug_susceptible_tuberculosis_with_severe_anemia,
    gbd_mapping.sequelae.hiv_aids_multidrug_resistant_tuberculosis_without_extensive_drug_resistance_with_mild_anemia,
    gbd_mapping.sequelae.hiv_aids_multidrug_resistant_tuberculosis_without_extensive_drug_resistance_with_moderate_anemia,
    gbd_mapping.sequelae.hiv_aids_multidrug_resistant_tuberculosis_without_extensive_drug_resistance_with_severe_anemia,
    gbd_mapping.sequelae.hiv_aids_extensively_drug_resistant_tuberculosis_with_mild_anemia,
    gbd_mapping.sequelae.hiv_aids_extensively_drug_resistant_tuberculosis_with_moderate_anemia,
    gbd_mapping.sequelae.hiv_aids_extensively_drug_resistant_tuberculosis_with_severe_anemia,
    gbd_mapping.sequelae.mild_anemia_due_to_malaria_vivax_pvpr,
    gbd_mapping.sequelae.moderate_anemia_due_to_malaria_vivax_pvpr,
    gbd_mapping.sequelae.severe_anemia_due_to_malaria_vivax_pvpr,
]

In [59]:
len(iron_responsive_anemia_sequelae)

138

In [60]:
len(non_iron_responsive_anemia_sequelae)

60

In [61]:
loguru.logger.disable("vivarium_inputs.validation.raw")

In [62]:
iron_responsive_prevalence = None

for sequela in tqdm(iron_responsive_anemia_sequelae):
    try:
        sequela_prevalence = vivarium_inputs.get_measure(sequela, "prevalence", location.title()).droplevel(["location", "year_start", "year_end"])
    except DataDoesNotExistError as e:
        assert 'zero' in str(e)
        continue
    except DataAbnormalError as e:
        assert 'zero' in str(e)
        continue

    if iron_responsive_prevalence is None:
        iron_responsive_prevalence = sequela_prevalence
    else:
        iron_responsive_prevalence += sequela_prevalence

  0%|          | 0/138 [00:00<?, ?it/s]

In [63]:
non_iron_responsive_prevalence = None

for sequela in tqdm(non_iron_responsive_anemia_sequelae):
    try:
        sequela_prevalence = vivarium_inputs.get_measure(sequela, "prevalence", location.title()).droplevel(["location", "year_start", "year_end"])
    except DataDoesNotExistError as e:
        assert 'zero' in str(e)
        continue
    except DataAbnormalError as e:
        assert 'zero' in str(e)
        continue

    if non_iron_responsive_prevalence is None:
        non_iron_responsive_prevalence = sequela_prevalence
    else:
        non_iron_responsive_prevalence += sequela_prevalence

  0%|          | 0/60 [00:00<?, ?it/s]

In [64]:
loguru.logger.enable("vivarium_inputs.validation.raw")

In [65]:
iron_responsive_prevalence.columns.name = "draw"
iron_responsive_prevalence = iron_responsive_prevalence.stack().pipe(lambda s: s[s.index.get_level_values("draw").isin(DRAWS)])
iron_responsive_prevalence

sex     age_start  age_end     draw
Female  0.0        0.019178    draw_0      0.811025
                               draw_1      0.698829
                               draw_2      0.727310
                               draw_3      0.843570
                               draw_4      0.832664
                                             ...
Male    95.0       125.000000  draw_495    0.655482
                               draw_496    0.787855
                               draw_497    0.838763
                               draw_498    0.804139
                               draw_499    0.781115
Length: 25000, dtype: float64

In [66]:
non_iron_responsive_prevalence.columns.name = "draw"
non_iron_responsive_prevalence = non_iron_responsive_prevalence.stack().pipe(lambda s: s[s.index.get_level_values("draw").isin(DRAWS)])
non_iron_responsive_prevalence

sex     age_start  age_end     draw
Female  0.0        0.019178    draw_0      0.118866
                               draw_1      0.107433
                               draw_2      0.138745
                               draw_3      0.085699
                               draw_4      0.138585
                                             ...
Male    95.0       125.000000  draw_495    0.112535
                               draw_496    0.142128
                               draw_497    0.206873
                               draw_498    0.146891
                               draw_499    0.133303
Length: 25000, dtype: float64

In [67]:
iron_responsive_proportion = iron_responsive_prevalence / (iron_responsive_prevalence + non_iron_responsive_prevalence)
iron_responsive_proportion

sex     age_start  age_end     draw
Female  0.0        0.019178    draw_0      0.872172
                               draw_1      0.866752
                               draw_2      0.839797
                               draw_3      0.907778
                               draw_4      0.857313
                                             ...
Male    95.0       125.000000  draw_495    0.853473
                               draw_496    0.847171
                               draw_497    0.802156
                               draw_498    0.845546
                               draw_499    0.854221
Length: 25000, dtype: float64

In [68]:
assert (iron_responsive_proportion <= 1).all()

In [69]:
iron_responsive_proportion.sort_values()

sex     age_start  age_end    draw
Male    10.0       15.000000  draw_352    0.388719
                              draw_123    0.405524
                              draw_74     0.405664
                              draw_25     0.411639
                              draw_343    0.427580
                                            ...
        0.0        0.019178   draw_22     0.924246
                              draw_335    0.924433
                              draw_160    0.924635
Female  0.0        0.019178   draw_459    0.927894
                              draw_256    0.931564
Length: 25000, dtype: float64

In [70]:
# NOTE: I am pretty sure this is correct, but it is quite difficult to think through *why*.

# First, observe that people in the population who start as non-anemic never factor into
# any of these metrics. If they started non-anemic, our counterfactual can only shift them up,
# so they did not change anemia categories between scenarios and hence have no importance to
# anemia prevalence or YLDs.

# So you can think of our hemoglobin distributions as only being of interest in the part
# of them below the anemia threshold.

# *Within* this subpopulation, we make the assumption that iron-responsive and non-iron-responsive
# anemic people have the same distributions of hemoglobin. This is probably not true, but GBD doesn't
# give us anything better.

# So you can think of our original distribution as a mixture of two parts, which are the same.
# Then we shift one of those parts (the iron-responsive part) and calculate all these stats from
# that new distribution.

# Our *actual* result should be about a mixture distribution that has the non-iron-responsive part
# the same as in baseline, with the shifted iron-responsive part.
# For all these metrics, it is pretty straightforward to see that the metric in such a mixture is
# just a weighted average of the metrics in each part, since they all depend on CDFs which combine
# this way.

counterfactual_anemia_accounting_for_non_response = (
    counterfactual_anemia.mul(iron_responsive_proportion, axis=0) +
    baseline_anemia.mul(1 - iron_responsive_proportion, axis=0)
)
counterfactual_anemia_accounting_for_non_response

                                                         mild  moderate  \
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth           0.253260  0.451465
                                    highest          0.273810  0.378136
                                    lowest           0.202504  0.515697
                                    middle           0.236115  0.459817
                                    second           0.219765  0.496345
...                                                       ...       ...
95.0      125.000000 Male   draw_99 fourth           0.312665  0.465711
                                    highest          0.336930  0.457715
                                    lowest           0.285002  0.479192
                                    middle           0.306448  0.462150
                                    second           0.303347  0.470640

                                                       severe    anemic  \
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth           0.044749  0.749474
                                    highest          0.024349  0.676295
                                    lowest           0.108429  0.826631
                                    middle           0.058772  0.754703
                                    second           0.082309  0.798419
...                                                       ...       ...
95.0      125.000000 Male   draw_99 fourth           0.138195  0.916572
                                    highest          0.113950  0.908595
                                    lowest           0.166756  0.930949
                                    middle           0.145992  0.914589
                                    second           0.147631  0.921618

                                                     mild_ylds  moderate_ylds  \
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth            0.000613       0.026772
                                    highest           0.000663       0.022424
                                    lowest            0.000490       0.030581
                                    middle            0.000572       0.027267
                                    second            0.000532       0.029434
...                                                        ...            ...
95.0      125.000000 Male   draw_99 fourth            0.001313       0.019411
                                    highest           0.001415       0.019078
                                    lowest            0.001197       0.019973
                                    middle            0.001287       0.019263
                                    second            0.001274       0.019617

                                                     severe_ylds  anemic_ylds
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth              0.008902     0.036287
                                    highest             0.004844     0.027930
                                    lowest              0.021571     0.052642
                                    middle              0.011692     0.039531
                                    second              0.016375     0.046340
...                                                          ...          ...
95.0      125.000000 Male   draw_99 fourth              0.016416     0.037140
                                    highest             0.013536     0.034029
                                    lowest              0.019808     0.040978
                                    middle              0.017342     0.037892
                                    second              0.017536     0.038427

[125000 rows x 8 columns]

In [71]:
assert ((baseline_anemia - counterfactual_anemia_accounting_for_non_response).anemic_ylds > 0).all()

In [72]:
baseline_ylds = (baseline_anemia.anemic_ylds.unstack("draw").mean(axis=1) * non_pregnant_pop)
baseline_ylds

age_start  age_end     sex     wealth_quintile
0.0        0.019178    Female  fourth             424.729902
                               highest            291.089988
                               lowest             736.111714
                               middle             521.550200
                               second             650.757670
                                                     ...
95.0       125.000000  Male    fourth              76.888359
                               highest             74.821911
                               lowest              89.386189
                               middle              73.428445
                               second              72.903842
Length: 250, dtype: float64

In [73]:
intervention_ylds = (counterfactual_anemia_accounting_for_non_response.anemic_ylds.unstack("draw").mean(axis=1) * non_pregnant_pop)

In [74]:
baseline_ylds.groupby(["wealth_quintile"]).sum() - intervention_ylds.groupby(["wealth_quintile"]).sum()

wealth_quintile
fourth     14112.720064
highest     8264.440896
lowest     36104.236694
middle     17569.786970
second     25944.580011
dtype: float64

In [75]:
ylds = pd.concat([
    baseline_ylds.rename("value").reset_index().assign(scenario="baseline"),
    intervention_ylds.rename("value").reset_index().assign(scenario="intervention")
], ignore_index=True)
ylds

     age_start     age_end     sex wealth_quintile       value      scenario
0          0.0    0.019178  Female          fourth  424.729902      baseline
1          0.0    0.019178  Female         highest  291.089988      baseline
2          0.0    0.019178  Female          lowest  736.111714      baseline
3          0.0    0.019178  Female          middle  521.550200      baseline
4          0.0    0.019178  Female          second  650.757670      baseline
..         ...         ...     ...             ...         ...           ...
495       95.0  125.000000    Male          fourth   75.850598  intervention
496       95.0  125.000000    Male         highest   74.056934  intervention
497       95.0  125.000000    Male          lowest   87.028308  intervention
498       95.0  125.000000    Male          middle   72.260735  intervention
499       95.0  125.000000    Male          second   71.334603  intervention

[500 rows x 6 columns]

In [76]:
results_dir = f'./results/{vehicle.lower()}/{location.lower()}/{intervention_scenario.lower()}'

In [77]:
path = f'{results_dir}/ylds.parquet'
pathlib.Path(path).parent.mkdir(exist_ok=True, parents=True)
ylds.to_parquet(path)

In [78]:
baseline_anemia_prevalence = baseline_anemia['anemic'].unstack("draw").mean(axis=1)
baseline_anemia_prevalence

age_start  age_end     sex     wealth_quintile
0.0        0.019178    Female  fourth             0.828338
                               highest            0.748522
                               lowest             0.900708
                               middle             0.835819
                               second             0.876689
                                                    ...
95.0       125.000000  Male    fourth             0.891835
                               highest            0.880907
                               lowest             0.910303
                               middle             0.890964
                               second             0.899321
Length: 250, dtype: float64

In [79]:
baseline_anemia_cases = baseline_anemia_prevalence.mul(non_pregnant_pop, axis=0)
baseline_anemia_cases

age_start  age_end     sex     wealth_quintile
0.0        0.019178    Female  fourth             11611.609394
                               highest             9753.105130
                               lowest             15276.458404
                               middle             13328.773023
                               second             14808.048479
                                                      ...
95.0       125.000000  Male    fourth              1586.629929
                               highest             1671.057535
                               lowest              1681.299915
                               middle              1480.290163
                               second              1453.600055
Length: 250, dtype: float64

In [80]:
baseline_anemia_cases.sum() / non_pregnant_pop.sum()

0.45867407015636436

In [81]:
baseline_anemia_cases.groupby(["wealth_quintile"]).sum() / non_pregnant_pop.groupby(["wealth_quintile"]).sum()

wealth_quintile
fourth     0.434832
highest    0.350655
lowest     0.556781
middle     0.454171
second     0.498840
dtype: float64

In [82]:
intervention_anemia_prevalence = counterfactual_anemia_accounting_for_non_response['anemic'].unstack("draw").mean(axis=1)
intervention_anemia_prevalence

age_start  age_end     sex     wealth_quintile
0.0        0.019178    Female  fourth             0.822986
                               highest            0.743238
                               lowest             0.894374
                               middle             0.829923
                               second             0.870501
                                                    ...
95.0       125.000000  Male    fourth             0.888494
                               highest            0.878136
                               lowest             0.904701
                               middle             0.887005
                               second             0.894267
Length: 250, dtype: float64

In [83]:
anemia_prevalence = pd.concat([
    baseline_anemia_prevalence.rename("value").reset_index().assign(scenario="baseline"),
    intervention_anemia_prevalence.rename("value").reset_index().assign(scenario="intervention")
], ignore_index=True)
anemia_prevalence

     age_start     age_end     sex wealth_quintile     value      scenario
0          0.0    0.019178  Female          fourth  0.828338      baseline
1          0.0    0.019178  Female         highest  0.748522      baseline
2          0.0    0.019178  Female          lowest  0.900708      baseline
3          0.0    0.019178  Female          middle  0.835819      baseline
4          0.0    0.019178  Female          second  0.876689      baseline
..         ...         ...     ...             ...       ...           ...
495       95.0  125.000000    Male          fourth  0.888494  intervention
496       95.0  125.000000    Male         highest  0.878136  intervention
497       95.0  125.000000    Male          lowest  0.904701  intervention
498       95.0  125.000000    Male          middle  0.887005  intervention
499       95.0  125.000000    Male          second  0.894267  intervention

[500 rows x 6 columns]

In [84]:
path = f'{results_dir}/anemia_prevalence.parquet'
pathlib.Path(path).parent.mkdir(exist_ok=True, parents=True)
anemia_prevalence.to_parquet(path)

In [85]:
intervention_anemia_cases = intervention_anemia_prevalence.mul(non_pregnant_pop, axis=0)
intervention_anemia_cases

age_start  age_end     sex     wealth_quintile
0.0        0.019178    Female  fourth             11536.584576
                               highest             9684.248311
                               lowest             15169.022189
                               middle             13234.743021
                               second             14703.538673
                                                      ...
95.0       125.000000  Male    fourth              1580.686026
                               highest             1665.801103
                               lowest              1670.953722
                               middle              1473.711399
                               second              1445.429859
Length: 250, dtype: float64

In [86]:
intervention_anemia_cases.sum() / non_pregnant_pop.sum()

0.44896102525225096

In [87]:
intervention_anemia_cases.groupby(["wealth_quintile"]).sum() / non_pregnant_pop.groupby(["wealth_quintile"]).sum()

wealth_quintile
fourth     0.427379
highest    0.345507
lowest     0.541633
middle     0.445316
second     0.486771
dtype: float64

In [88]:
(baseline_anemia_cases.groupby(["wealth_quintile"]).sum() - intervention_anemia_cases.groupby(["wealth_quintile"]).sum()).map(lambda x: f'{round(x):,.0f}')

wealth_quintile
fourth     336,497
highest    231,349
lowest     670,752
middle     396,040
second     537,272
dtype: object

In [89]:
anemia_cases = pd.concat([
    baseline_anemia_cases.rename("value").reset_index().assign(scenario="baseline"),
    intervention_anemia_cases.rename("value").reset_index().assign(scenario="intervention")
], ignore_index=True)
anemia_cases

     age_start     age_end     sex wealth_quintile         value      scenario
0          0.0    0.019178  Female          fourth  11611.609394      baseline
1          0.0    0.019178  Female         highest   9753.105130      baseline
2          0.0    0.019178  Female          lowest  15276.458404      baseline
3          0.0    0.019178  Female          middle  13328.773023      baseline
4          0.0    0.019178  Female          second  14808.048479      baseline
..         ...         ...     ...             ...           ...           ...
495       95.0  125.000000    Male          fourth   1580.686026  intervention
496       95.0  125.000000    Male         highest   1665.801103  intervention
497       95.0  125.000000    Male          lowest   1670.953722  intervention
498       95.0  125.000000    Male          middle   1473.711399  intervention
499       95.0  125.000000    Male          second   1445.429859  intervention

[500 rows x 6 columns]

In [90]:
path = f'{results_dir}/anemia_cases.parquet'
pathlib.Path(path).parent.mkdir(exist_ok=True, parents=True)
anemia_cases.to_parquet(path)