In [1]:
import pandas as pd, numpy as np
import vivarium_inputs
import vivarium.gbd_mapping as gbd_mapping
from lsff_utils import paths, gbd_data
import pathlib

In [2]:
location = "India"
vehicle = "rice"

In [3]:
# Parameters
location = "india"
vehicle = "rice"

In [4]:
location = location.title()

In [5]:
# Simulation output lives in per-run, timestamp-named directories, so the runs
# are resolved rather than hardcoded. The child rescaling divides through by
# pregnancy outcome counts, so it reads the maternal run as well as the child one.
maternal_results = paths.latest_results(paths.MATERNAL_RESULTS_ROOT, location, vehicle)
child_results = paths.latest_results(paths.CHILD_RESULTS_ROOT, location, vehicle)
child_results

PosixPath('/mnt/share/code/ndbs/vivarium_gates_lsff_2026/0300_child_sim/sim_results/rice/india/2026_10_05_02_42_21/results')

In [6]:
with gbd_data.quiet_gbd_logs():
    pop = vivarium_inputs.get_population_structure(location).value
pop[pop > 0]

location  sex     age_start  age_end     year_start  year_end
India     Female  0.000000   0.019178    2023        2024        1.936945e+05
                  0.019178   0.076712    2023        2024        5.766332e+05
                  0.076712   0.500000    2023        2024        4.257480e+06
                  0.500000   1.000000    2023        2024        5.021249e+06
                  1.000000   2.000000    2023        2024        1.024770e+07
                  2.000000   5.000000    2023        2024        3.231858e+07
                  5.000000   10.000000   2023        2024        5.835119e+07
                  10.000000  15.000000   2023        2024        6.286521e+07
                  15.000000  20.000000   2023        2024        6.432311e+07
                  20.000000  25.000000   2023        2024        6.374038e+07
                  25.000000  30.000000   2023        2024        6.159864e+07
                  30.000000  35.000000   2023        2024        5.733795e+07
                  35.000000  40.000000   2023        2024        5.319119e+07
                  40.000000  45.000000   2023        2024        4.683697e+07
                  45.000000  50.000000   2023        2024        3.996526e+07
                  50.000000  55.000000   2023        2024        3.484048e+07
                  55.000000  60.000000   2023        2024        2.993952e+07
                  60.000000  65.000000   2023        2024        2.582036e+07
                  65.000000  70.000000   2023        2024        2.035355e+07
                  70.000000  75.000000   2023        2024        1.511558e+07
                  75.000000  80.000000   2023        2024        9.683317e+06
                  80.000000  85.000000   2023        2024        5.632096e+06
                  85.000000  90.000000   2023        2024        2.700635e+06
                  90.000000  95.000000   2023        2024        8.338075e+05
                  95.000000  125.000000  2023        2024        2.024809e+05
          Male    0.000000   0.019178    2023        2024        2.126282e+05
                  0.019178   0.076712    2023        2024        6.315723e+05
                  0.076712   0.500000    2023        2024        4.661302e+06
                  0.500000   1.000000    2023        2024        5.496262e+06
                  1.000000   2.000000    2023        2024        1.120286e+07
                  2.000000   5.000000    2023        2024        3.521447e+07
                  5.000000   10.000000   2023        2024        6.345063e+07
                  10.000000  15.000000   2023        2024        6.792384e+07
                  15.000000  20.000000   2023        2024        6.960478e+07
                  20.000000  25.000000   2023        2024        6.793476e+07
                  25.000000  30.000000   2023        2024        6.448848e+07
                  30.000000  35.000000   2023        2024        6.061820e+07
                  35.000000  40.000000   2023        2024        5.658866e+07
                  40.000000  45.000000   2023        2024        4.950707e+07
                  45.000000  50.000000   2023        2024        4.184714e+07
                  50.000000  55.000000   2023        2024        3.562267e+07
                  55.000000  60.000000   2023        2024        2.926650e+07
                  60.000000  65.000000   2023        2024        2.467622e+07
                  65.000000  70.000000   2023        2024        1.914904e+07
                  70.000000  75.000000   2023        2024        1.382503e+07
                  75.000000  80.000000   2023        2024        8.592744e+06
                  80.000000  85.000000   2023        2024        4.496315e+06
                  85.000000  90.000000   2023        2024        1.811393e+06
                  90.000000  95.000000   2023        2024        5.116994e+05
                  95.000000  125.000000  2023        2024        1.038020e+05
Name: value, dtype: float64

In [7]:
with gbd_data.quiet_gbd_logs():
    asfr = vivarium_inputs.get_measure(
        gbd_mapping.covariates.age_specific_fertility_rate, "estimate", location
    ).value
asfr[asfr > 0]

location  sex     age_start  age_end  year_start  year_end  parameter
India     Female  10.0       15.0     2023        2024      lower_value    0.000159
                                                            mean_value     0.000349
                                                            upper_value    0.000705
                  15.0       20.0     2023        2024      lower_value    0.007324
                                                            mean_value     0.008912
                                                            upper_value    0.010701
                  20.0       25.0     2023        2024      lower_value    0.080282
                                                            mean_value     0.094863
                                                            upper_value    0.111437
                  25.0       30.0     2023        2024      lower_value    0.113628
                                                            mean_value     0.124175
                                                            upper_value    0.135619
                  30.0       35.0     2023        2024      lower_value    0.068355
                                                            mean_value     0.079277
                                                            upper_value    0.090671
                  35.0       40.0     2023        2024      lower_value    0.027249
                                                            mean_value     0.033097
                                                            upper_value    0.040125
                  40.0       45.0     2023        2024      lower_value    0.009139
                                                            mean_value     0.011589
                                                            upper_value    0.014707
                  45.0       50.0     2023        2024      lower_value    0.002101
                                                            mean_value     0.003006
                                                            upper_value    0.004170
                  50.0       55.0     2023        2024      lower_value    0.000266
                                                            mean_value     0.000273
                                                            upper_value    0.000279
Name: value, dtype: float64

In [8]:
asfr = asfr[asfr.index.get_level_values("parameter") == "mean_value"].droplevel(
    "parameter"
)
asfr

location  sex     age_start  age_end     year_start  year_end
India     Female  0.000000   0.019178    2023        2024        0.000000
                  0.019178   0.076712    2023        2024        0.000000
                  0.076712   0.500000    2023        2024        0.000000
                  0.500000   1.000000    2023        2024        0.000000
                  1.000000   2.000000    2023        2024        0.000000
                  2.000000   5.000000    2023        2024        0.000000
                  5.000000   10.000000   2023        2024        0.000000
                  10.000000  15.000000   2023        2024        0.000349
                  15.000000  20.000000   2023        2024        0.008912
                  20.000000  25.000000   2023        2024        0.094863
                  25.000000  30.000000   2023        2024        0.124175
                  30.000000  35.000000   2023        2024        0.079277
                  35.000000  40.000000   2023        2024        0.033097
                  40.000000  45.000000   2023        2024        0.011589
                  45.000000  50.000000   2023        2024        0.003006
                  50.000000  55.000000   2023        2024        0.000273
                  55.000000  60.000000   2023        2024        0.000000
                  60.000000  65.000000   2023        2024        0.000000
                  65.000000  70.000000   2023        2024        0.000000
                  70.000000  75.000000   2023        2024        0.000000
                  75.000000  80.000000   2023        2024        0.000000
                  80.000000  85.000000   2023        2024        0.000000
                  85.000000  90.000000   2023        2024        0.000000
                  90.000000  95.000000   2023        2024        0.000000
                  95.000000  125.000000  2023        2024        0.000000
          Male    0.000000   0.019178    2023        2024        0.000000
                  0.019178   0.076712    2023        2024        0.000000
                  0.076712   0.500000    2023        2024        0.000000
                  0.500000   1.000000    2023        2024        0.000000
                  1.000000   2.000000    2023        2024        0.000000
                  2.000000   5.000000    2023        2024        0.000000
                  5.000000   10.000000   2023        2024        0.000000
                  10.000000  15.000000   2023        2024        0.000000
                  15.000000  20.000000   2023        2024        0.000000
                  20.000000  25.000000   2023        2024        0.000000
                  25.000000  30.000000   2023        2024        0.000000
                  30.000000  35.000000   2023        2024        0.000000
                  35.000000  40.000000   2023        2024        0.000000
                  40.000000  45.000000   2023        2024        0.000000
                  45.000000  50.000000   2023        2024        0.000000
                  50.000000  55.000000   2023        2024        0.000000
                  55.000000  60.000000   2023        2024        0.000000
                  60.000000  65.000000   2023        2024        0.000000
                  65.000000  70.000000   2023        2024        0.000000
                  70.000000  75.000000   2023        2024        0.000000
                  75.000000  80.000000   2023        2024        0.000000
                  80.000000  85.000000   2023        2024        0.000000
                  85.000000  90.000000   2023        2024        0.000000
                  90.000000  95.000000   2023        2024        0.000000
                  95.000000  125.000000  2023        2024        0.000000
Name: value, dtype: float64

In [9]:
births = pop * asfr
births[births > 0]

location  sex     age_start  age_end  year_start  year_end
India     Female  10.0       15.0     2023        2024        2.194007e+04
                  15.0       20.0     2023        2024        5.732639e+05
                  20.0       25.0     2023        2024        6.046632e+06
                  25.0       30.0     2023        2024        7.648997e+06
                  30.0       35.0     2023        2024        4.545600e+06
                  35.0       40.0     2023        2024        1.760489e+06
                  40.0       45.0     2023        2024        5.427846e+05
                  45.0       50.0     2023        2024        1.201325e+05
                  50.0       55.0     2023        2024        9.494763e+03
Name: value, dtype: float64

In [10]:
births = births.sum()
f"{int(births):,}"

'21,269,334'

In [11]:
sim_baseline_births = pd.read_parquet(
    paths.measure_path(maternal_results, "pregnancy_outcome_count")
)
sim_baseline_births

,measure,entity_type,entity,sub_entity,age_group,anemia_status_at_birth,wealth_quintile,scenario,input_draw,random_seed,value
0,pregnancy_outcome_count,custom_fertility,pregnancy_outcome,partial_term,10_to_14,invalid,1,baseline,0,141,1.0
1,pregnancy_outcome_count,custom_fertility,pregnancy_outcome,partial_term,10_to_14,invalid,2,baseline,0,141,3.0
2,pregnancy_outcome_count,custom_fertility,pregnancy_outcome,partial_term,10_to_14,invalid,3,baseline,0,141,4.0
3,pregnancy_outcome_count,custom_fertility,pregnancy_outcome,partial_term,10_to_14,invalid,4,baseline,0,141,1.0
4,pregnancy_outcome_count,custom_fertility,pregnancy_outcome,partial_term,10_to_14,invalid,5,baseline,0,141,1.0
...,...,...,...,...,...,...,...,...,...,...,...
809995,pregnancy_outcome_count,custom_fertility,pregnancy_outcome,stillbirth,95_plus,severe,1,zero,0,129,0.0
809996,pregnancy_outcome_count,custom_fertility,pregnancy_outcome,stillbirth,95_plus,severe,2,zero,0,129,0.0
809997,pregnancy_outcome_count,custom_fertility,pregnancy_outcome,stillbirth,95_plus,severe,3,zero,0,129,0.0
809998,pregnancy_outcome_count,custom_fertility,pregnancy_outcome,stillbirth,95_plus,severe,4,zero,0,129,0.0
809999,pregnancy_outcome_count,custom_fertility,pregnancy_outcome,stillbirth,95_plus,severe,5,zero,0,129,0.0

In [12]:
sim_baseline_births = sim_baseline_births[
    (sim_baseline_births.scenario == "baseline")
    & (sim_baseline_births.sub_entity == "live_birth")
]
sim_baseline_births

,measure,entity_type,entity,sub_entity,age_group,anemia_status_at_birth,wealth_quintile,scenario,input_draw,random_seed,value
5,pregnancy_outcome_count,custom_fertility,pregnancy_outcome,live_birth,10_to_14,invalid,1,baseline,0,141,10.0
6,pregnancy_outcome_count,custom_fertility,pregnancy_outcome,live_birth,10_to_14,invalid,2,baseline,0,141,6.0
7,pregnancy_outcome_count,custom_fertility,pregnancy_outcome,live_birth,10_to_14,invalid,3,baseline,0,141,12.0
8,pregnancy_outcome_count,custom_fertility,pregnancy_outcome,live_birth,10_to_14,invalid,4,baseline,0,141,10.0
9,pregnancy_outcome_count,custom_fertility,pregnancy_outcome,live_birth,10_to_14,invalid,5,baseline,0,141,7.0
...,...,...,...,...,...,...,...,...,...,...,...
807290,pregnancy_outcome_count,custom_fertility,pregnancy_outcome,live_birth,95_plus,severe,1,baseline,0,54,0.0
807291,pregnancy_outcome_count,custom_fertility,pregnancy_outcome,live_birth,95_plus,severe,2,baseline,0,54,0.0
807292,pregnancy_outcome_count,custom_fertility,pregnancy_outcome,live_birth,95_plus,severe,3,baseline,0,54,0.0
807293,pregnancy_outcome_count,custom_fertility,pregnancy_outcome,live_birth,95_plus,severe,4,baseline,0,54,0.0
807294,pregnancy_outcome_count,custom_fertility,pregnancy_outcome,live_birth,95_plus,severe,5,baseline,0,54,0.0

In [13]:
sim_baseline_births = sim_baseline_births.groupby("input_draw").value.sum().mean()
sim_baseline_births

8828900.0

In [14]:
births

21269334.701552395

In [15]:
scalar = births / sim_baseline_births
scalar

2.4090582860325065

In [16]:
# NOTE: 'person_time' was renamed to 'person_time_population' when PersonTimeObserver
# became a PublicHealthObserver, so the automated V&V loader can discover it.
for result in ["ylds", "ylls", "deaths", "person_time_population"]:
    df = pd.read_parquet(
        paths.measure_path(child_results, result)
    )
    df.value *= scalar
    path = pathlib.Path(
        f"../results/rescaled_child_results/{vehicle}/{location.lower()}/{result}.parquet"
    )
    path.parent.mkdir(exist_ok=True, parents=True)
    df.to_parquet(path)