In [1]:
import numpy as np, matplotlib.pyplot as plt, pandas as pd

pd.set_option("display.max_rows", 8)
!date

Mon Aug 24 17:21:11 PDT 2026

# Mean deaths and stillbirths averted by adding folate by wealth quintile

In [2]:
import vivarium_inputs
import db_queries
import vivarium.gbd_mapping as gbd_mapping
import pathlib
from lsff_utils import config_utils

In [3]:
location = "india"
vehicle = "rice"

In [4]:
# Parameters
location = "nigeria"
vehicle = "bouillon"

In [5]:
intervention_scenarios = config_utils.get_config()["custom_intervention_scenarios"].get(
    location, ["intervention"]
)
intervention_scenarios

['intervention']

## Forecasted births and stillbirths

In [6]:
asfr = vivarium_inputs.get_measure(
    gbd_mapping.covariates.age_specific_fertility_rate,
    "estimate",
    location.title(),
    years=2022,
).value

2026-08-24 17:21:16.952 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:17.036 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:17.052 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 17:21:17.080 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:17.082 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:17.097 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 17:21:17.105 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:17.108 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:17.112 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_annual_years'

2026-08-24 17:21:17.117 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:17.119 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:17.146 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_covariate_estimate'

2026-08-24 17:21:17.175 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:17.178 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:17.184 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_age_group_id'

2026-08-24 17:21:17.190 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:17.192 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:17.200 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_path_to_global'

2026-08-24 17:21:17.229 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:17.232 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:17.236 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_estimation_years'

2026-08-24 17:21:17.242 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:17.243 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:17.248 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_annual_years'

2026-08-24 17:21:17.255 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:17.257 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:17.261 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_age_bins'

2026-08-24 17:21:17.282 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:17.284 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:17.288 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_estimation_years'

2026-08-24 17:21:17.294 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:17.296 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:17.301 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_annual_years'

2026-08-24 17:21:17.307 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:17.309 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:17.313 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_age_group_id'

2026-08-24 17:21:17.341 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:17.343 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:17.347 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 17:21:17.355 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:17.356 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:17.360 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 17:21:17.378 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:17.380 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:17.386 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_age_bins'

2026-08-24 17:21:17.412 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:17.414 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:17.418 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 17:21:17.425 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:17.427 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:17.431 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 17:21:17.439 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:17.440 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:17.444 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_age_bins'

In [7]:
asfr = asfr[asfr.index.get_level_values("parameter") == "mean_value"].droplevel(
    "parameter"
)

In [8]:
# Scale ASFR in each category down proportionally to the scale-down in TFR forecasted from GBD 2017
if location == "india":
    asfr_2030_to_2022_ratio = 1.61 / 1.91  # http://ihmeuw.org/6j8s
elif location == "nigeria":
    asfr_2030_to_2022_ratio = 4.43 / 4.96  # http://ihmeuw.org/6jqx
elif location == "ethiopia":
    asfr_2030_to_2022_ratio = 3.27 / 4.10  # http://ihmeuw.org/6j7d

asfr = asfr * asfr_2030_to_2022_ratio
asfr[asfr > 0]

location  sex     age_start  age_end  year_start  year_end
Nigeria   Female  10.0       15.0     2022        2023        0.005266
                  15.0       20.0     2022        2023        0.065712
                  20.0       25.0     2022        2023        0.178290
                  25.0       30.0     2022        2023        0.191866
                                                                ...
                  35.0       40.0     2022        2023        0.117014
                  40.0       45.0     2022        2023        0.062042
                  45.0       50.0     2022        2023        0.028299
                  50.0       55.0     2022        2023        0.002566
Name: value, Length: 9, dtype: float64

In [9]:
asfr = (
    asfr.reset_index()
    .assign(year_start=2030, year_end=2031)
    .set_index(asfr.index.names)
    .value
)
asfr.sort_values()

location  sex     age_start  age_end    year_start  year_end
Nigeria   Female  0.000000   0.019178   2030        2031        0.000000
                  0.019178   0.076712   2030        2031        0.000000
                  0.076712   0.500000   2030        2031        0.000000
                  0.500000   1.000000   2030        2031        0.000000
                                                                  ...
                  35.000000  40.000000  2030        2031        0.117014
                  30.000000  35.000000  2030        2031        0.176792
                  20.000000  25.000000  2030        2031        0.178290
                  25.000000  30.000000  2030        2031        0.191866
Name: value, Length: 50, dtype: float64

In [10]:
from vivarium_inputs import utilities
from vivarium_inputs.utility_data import get_location_id
from vivarium_gbd_access.gbd import get_age_group_id, SEX, RELEASE_IDS

In [11]:
def get_population_future(location, year):
    # Cobbled together from pieces of vivarium_inputs and vivarium_gbd_access
    # TODO: vivarium_inputs should be able to get forecasted pop!
    location_id = get_location_id(location)
    year_id = year
    data = db_queries.get_population(
        age_group_id=get_age_group_id(),
        location_id=location_id,
        year_id=year_id,
        sex_id=SEX.MALE + SEX.FEMALE + SEX.COMBINED,
        release_id=RELEASE_IDS.GBD_2021,
        forecasted_pop=True,
    )
    data = utilities.normalize_sex(
        data.drop("run_id", axis="columns").rename(columns={"population": "value"}),
        fill_value=None,
        cols_to_fill=utilities.DRAW_COLUMNS,
    )
    data = utilities.reshape(data, ["value"])
    data = utilities.scrub_gbd_conventions(data, location)
    data = utilities.split_interval(
        data, interval_column="age", split_column_prefix="age"
    )
    data = utilities.split_interval(
        data, interval_column="year", split_column_prefix="year"
    )
    return utilities.sort_hierarchical_data(data)

In [12]:
pop = get_population_future(location.title(), 2030).value.reindex(asfr.index)
pop

/tmp/ipykernel_3463858/2995218429.py:4: DeprecationWarning: get_location_id is deprecated. Use resolve_location instead.
  location_id = get_location_id(location)
2026-08-24 17:21:18.141 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:18.143 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:18.147 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 17:21:18.156 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:18.158 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:18.162 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_age_group_id'

2026-08-24 17:21:18.447 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:18.448 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:18.452 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 17:21:18.459 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:18.460 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:18.466 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 17:21:18.481 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:18.483 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:18.496 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_age_bins'

location  sex     age_start  age_end     year_start  year_end
Nigeria   Female  0.000000   0.019178    2030        2031         76752.699967
                  0.019178   0.076712    2030        2031        227071.059445
                  0.076712   0.500000    2030        2031                  NaN
                  0.500000   1.000000    2030        2031                  NaN
                                                                     ...
          Male    80.000000  85.000000   2030        2031        354428.130049
                  85.000000  90.000000   2030        2031        177910.014136
                  90.000000  95.000000   2030        2031         62189.478603
                  95.000000  125.000000  2030        2031         16933.452258
Name: value, Length: 50, dtype: float64

In [13]:
# Forecasted population does not have younger ages, but luckily none of these are WRA
assert (pop.index.get_level_values("age_end")[pop.isna()] < 10).all()
pop[pop.isna()]

location  sex     age_start  age_end  year_start  year_end
Nigeria   Female  0.076712   0.5      2030        2031       NaN
                  0.500000   1.0      2030        2031       NaN
                  1.000000   2.0      2030        2031       NaN
                  2.000000   5.0      2030        2031       NaN
          Male    0.076712   0.5      2030        2031       NaN
                  0.500000   1.0      2030        2031       NaN
                  1.000000   2.0      2030        2031       NaN
                  2.000000   5.0      2030        2031       NaN
Name: value, dtype: float64

In [14]:
pop = pop.fillna(0)

In [15]:
n_births = (pop * asfr).sum()
n_births

9745557.876500718

In [16]:
sbr = vivarium_inputs.get_measure(
    gbd_mapping.covariates.stillbirth_28_weeks_to_live_birth_ratio,
    "estimate",
    location.title(),
    years=2022,
).value
sbr

2026-08-24 17:21:18.971 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:18.972 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:18.984 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 17:21:18.994 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:18.999 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:19.013 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 17:21:19.030 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:19.035 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:19.052 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_annual_years'

2026-08-24 17:21:19.061 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:19.063 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:19.084 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_covariate_estimate'

2026-08-24 17:21:19.110 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:19.112 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:19.116 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_age_group_id'

2026-08-24 17:21:19.126 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:19.129 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:19.135 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_path_to_global'

2026-08-24 17:21:19.150 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:19.153 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:19.165 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_estimation_years'

2026-08-24 17:21:19.173 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:19.174 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:19.184 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_annual_years'

2026-08-24 17:21:19.194 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:19.196 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:19.204 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_estimation_years'

2026-08-24 17:21:19.216 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:19.218 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:19.226 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_annual_years'

2026-08-24 17:21:19.234 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:19.240 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:19.249 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_age_group_id'

2026-08-24 17:21:19.269 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:19.271 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:19.286 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 17:21:19.295 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:19.297 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:19.309 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 17:21:19.347 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:19.349 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:19.355 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 17:21:19.365 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:19.367 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:19.379 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 17:21:19.390 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:19.394 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:19.404 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_age_bins'

location  year_start  year_end  parameter
Nigeria   2022        2023      lower_value    0.020758
                                mean_value     0.026265
                                upper_value    0.032433
Name: value, dtype: float64

In [17]:
sbr = sbr[sbr.index.get_level_values("parameter") == "mean_value"].droplevel(
    "parameter"
)
sbr

location  year_start  year_end
Nigeria   2022        2023        0.026265
Name: value, dtype: float64

In [18]:
sbr = sbr.values[0]

In [19]:
births_and_stillbirths = n_births + n_births * sbr
births_and_stillbirths / 1e6

10.001529152022622

## Fertility (technically birth-and-stillbirth) disparities

In [20]:
if location == "india":
    dist_births_and_stillbirths_by_wealth = pd.Series(  # from file:///J:/DATA/DHS_PROG_DHS/IND/2019_2021/IND_DHS7_2019_2021_REP_FINAL_Y2022M05D11.PDF
        {  # Table 8.4 Perinatal mortality -- using "Number of pregnancies of 7 or more months' duration" as a proxy
            1: 56_979,
            2: 50_335,
            3: 45_189,
            4: 42_611,
            5: 36_290,
        }
    )
elif location == "nigeria":
    dist_births_and_stillbirths_by_wealth = pd.Series(  # from file:///J:/DATA/DHS_PROG_DHS/NGA/2018/NGA_DHS7_2018_REP_QUEST_Y2019M11D05.PDF
        {  # Table 8.4 Perinatal mortality
            1: 7_712,
            2: 7_886,
            3: 7_139,
            4: 6_328,
            5: 5_558,
        }
    )
elif location == "ethiopia":
    dist_births_and_stillbirths_by_wealth = pd.Series(  # from file:///J:/DATA/DHS_PROG_DHS/ETH/2016/ETH_DHS7_2016_REP_QUEST_Y2017M08D15.PDF
        {  # Table 8.4 Perinatal mortality
            1: 2_645,
            2: 2_516,
            3: 2_290,
            4: 2_018,
            5: 1_592,
        }
    )

dist_births_and_stillbirths_by_wealth.index.name = "wealth_quintile"

s_births = (
    n_births
    * dist_births_and_stillbirths_by_wealth
    / dist_births_and_stillbirths_by_wealth.sum()
)
s_births

wealth_quintile
1    2.170746e+06
2    2.219723e+06
3    2.009460e+06
4    1.781183e+06
5    1.564446e+06
dtype: float64

In [21]:
s_births_and_stillbirths_by_wealth = (
    births_and_stillbirths
    * dist_births_and_stillbirths_by_wealth
    / dist_births_and_stillbirths_by_wealth.sum()
)
s_births_and_stillbirths_by_wealth

wealth_quintile
1    2.227762e+06
2    2.278025e+06
3    2.062239e+06
4    1.827966e+06
5    1.605537e+06
dtype: float64

In [22]:
# http://ihmeuw.org/6jr2 -- extracted from GBD Foresight, count of NTD deaths in 2030 for under-1 year olds
# from GBD 2021
if location == "india":
    ntd_deaths = 4_273.37
elif location == "nigeria":
    ntd_deaths = 5_373.52
elif location == "ethiopia":
    ntd_deaths = 1_883.76


ntd_death_rate_per_birth = ntd_deaths / n_births
10_000 * ntd_death_rate_per_birth

5.513814671356135

In [23]:
# Assumed does not vary by wealth
champs_ntd_stillbirth_per_livebirth = 51 / (69 - 51)
ntd_stillbirths = ntd_deaths * champs_ntd_stillbirth_per_livebirth
10_000 * (
    ntd_deaths + ntd_stillbirths
) / n_births  # ntd rate, compare with 41 per 10,000 from Bhide et al https://pubmed.ncbi.nlm.nih.gov/23873811/

21.13628957353185

We could not find a good source for folate intake by wealth in India, or even a representative source for overall folate intake.  [This paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10755415/pdf/S1368980023002112a.pdf) has an overall number of 220 mcg/day for women, and since it is not too different from the values we found in Ethiopia and Nigeria, we are going to use it for now. (It also has standard deviation of 50, which we can use when we introduce heterogeneity)

In [24]:
if location == "india":
    folate_intake_by_wealth = pd.Series(
        {
            1: 220,
            2: 220,
            3: 220,
            4: 220,
            5: 220,  # NRV is 400 mcg/day
        }
    )
elif location == "nigeria":
    # Table 95 of NFCMS 2021 Report
    folate_intake_by_wealth = pd.Series(
        {
            1: 189,
            2: 198,
            3: 197,
            4: 203,
            5: 208,  # NRV is 400 mcg/day
        }
    )  # how can we use this to estimate disparities in NTD?
elif location == "ethiopia":
    # Table 6 of https://cdn.nutrition.org/article/S2475-2991%2824%2901728-1/fulltext
    folate_intake_by_wealth = pd.Series(
        {
            1: 166,
            2: 152,
            3: 137,
            4: 350,
            5: 469,  # NRV is 400 mcg/day
        }
    )  # how can we use this to estimate disparities in NTD?

folate_intake_by_wealth.index.name = "wealth_quintile"

In [25]:
if location == "india":
    s_dist_deaths_by_wealth = pd.Series(  # Table 7.9 on page 201 of the CNNS report has RBC folate deficiency rates;
        {  # it includes wealth stratification, but has a very low threshold for insufficiency
            1: 1,  # so I am assuming that most everyone is in the danger zone for low folate
            2: 1,
            3: 1,
            4: 1,
            5: 1,
        }
    )
elif location == "nigeria":
    s_dist_deaths_by_wealth = pd.Series(  # assume same rate for all, for now;
        {  # can CHAMPS offer more detail?  Need to infer wealth somehow
            1: 1,
            2: 1,
            3: 1,
            4: 1,
            5: 1,
        }
    )
elif location == "ethiopia":
    s_dist_deaths_by_wealth = pd.Series(
        {  # supplementation studies don't make this easy, but here is a guess
            1: 1,
            2: 1,
            3: 1,
            4: 1,
            5: 1,
        }
    )
    s_dist_deaths_by_wealth /= s_dist_deaths_by_wealth.mean()

s_dist_deaths_by_wealth.index.name = "wealth_quintile"
s_dist_deaths_by_wealth

wealth_quintile
1    1
2    1
3    1
4    1
5    1
dtype: int64

In [26]:
s_ntd_death_rate_per_birth = ntd_deaths / n_births * s_dist_deaths_by_wealth
10_000 * s_ntd_death_rate_per_birth

wealth_quintile
1    5.513815
2    5.513815
3    5.513815
4    5.513815
5    5.513815
dtype: float64

In [27]:
s_ntd_death_count = s_ntd_death_rate_per_birth * s_births
s_ntd_death_count

wealth_quintile
1    1196.909171
2    1223.914124
3    1107.979068
4     982.111156
5     862.606480
dtype: float64

In [28]:
assert np.isclose(s_ntd_death_count.sum(), ntd_deaths)

In [29]:
s_ntd_stillbirth_count = s_ntd_death_count * champs_ntd_stillbirth_per_livebirth
s_ntd_stillbirth_count

wealth_quintile
1    3391.242652
2    3467.756685
3    3139.274027
4    2782.648276
5    2444.051694
dtype: float64

In [30]:
s_ntd_death_or_stillbirth_count = s_ntd_death_count + s_ntd_stillbirth_count
s_ntd_death_or_stillbirth_count

wealth_quintile
1    4588.151824
2    4691.670809
3    4247.253095
4    3764.759432
5    3306.658174
dtype: float64

In [31]:
# NOTE: NTD risk here means risk of having an "NTD-affected pregnancy",
# which is a stillbirth due to NTD, OR a birth with NTD (not necessarily fatal!)
# See Kirke 1993 ("Maternal plasma folate and vitamin B12 are independent risk factors for neural tube defects")
# where it says: "Early foetal
# deaths (<23 weeks gestation) attributable to NTDs
# were excluded because of the incomplete ascertain-
# ment of such cases and the difficulty of obtaining a
# valid control group."
# This implies that late foetal deaths, roughly equivalent to stillbirths,
# are included.
def backcalc_rbc(ntd_risk, method):
    """
    ln (odds of NTD risk) = 1.6563 − 1.2193 × ln (RBC) (Daly et al, 1995)
    ln (odds of NTD risk) = 4.57 − 1.70 × ln (RBC) (Crider et al, 2014)
    """

    odds = ntd_risk / (1 - ntd_risk)
    ln_odds = np.log(odds)
    if method == "daly":
        neg_ln_rbc = (ln_odds - 1.6563) / 1.2193
    elif method == "crider":
        neg_ln_rbc = (ln_odds - 4.57) / 1.70
    rbc = np.exp(-neg_ln_rbc)
    return rbc

In [32]:
# From GBD 2021 using GBD Compare, for year 2021
# NTD incident cases / NTD deaths in <1 year olds
# (all of GBD's incident cases are those who survived birth)
if location == "india":
    ntd_death_to_live_birth_case_ratio = 11_796.34 / 5_492.68
elif location == "nigeria":
    ntd_death_to_live_birth_case_ratio = 21_756.56 / 6_231.21
elif location == "ethiopia":
    ntd_death_to_live_birth_case_ratio = 3_982.63 / 2_255.6

ntd_death_to_live_birth_case_ratio

3.4915465856551138

In [33]:
s_ntd_live_birth_cases = s_ntd_death_count * ntd_death_to_live_birth_case_ratio
s_ntd_live_birth_cases

wealth_quintile
1    4179.064131
2    4273.353181
3    3868.560533
4    3429.086854
5    3011.830710
dtype: float64

In [34]:
s_ntd_affected_pregnancies = s_ntd_stillbirth_count + s_ntd_live_birth_cases

In [35]:
ntd_affected_pregnancy_risk = (
    s_ntd_affected_pregnancies / s_births_and_stillbirths_by_wealth
)
ntd_affected_pregnancy_risk

wealth_quintile
1    0.003398
2    0.003398
3    0.003398
4    0.003398
5    0.003398
dtype: float64

In [36]:
s_ntd_death_or_stillbirth_count / s_births

wealth_quintile
1    0.002114
2    0.002114
3    0.002114
4    0.002114
5    0.002114
dtype: float64

In [37]:
backcalc_rbc(ntd_affected_pregnancy_risk, "daly")

wealth_quintile
1    410.644326
2    410.644326
3    410.644326
4    410.644326
5    410.644326
dtype: float64

In [38]:
backcalc_rbc(
    ntd_affected_pregnancy_risk, "crider"
)  # compare with CNNS, https://www.unicef.org/india/media/2646/file/CNNS-report.pdf in Table 7.9
# NOTE: It's a bit hard to compare, due to units issues. That table reports
# proportions under 151 ng/ml. In our units (nmol/L), that is ~342.
# https://www.wolframalpha.com/input?i=151+ng%2Fml+of+folate+to+nmol%2FL

wealth_quintile
1    415.743173
2    415.743173
3    415.743173
4    415.743173
5    415.743173
dtype: float64

In [39]:
pop

location  sex     age_start  age_end     year_start  year_end
Nigeria   Female  0.000000   0.019178    2030        2031         76752.699967
                  0.019178   0.076712    2030        2031        227071.059445
                  0.076712   0.500000    2030        2031             0.000000
                  0.500000   1.000000    2030        2031             0.000000
                                                                     ...
          Male    80.000000  85.000000   2030        2031        354428.130049
                  85.000000  90.000000   2030        2031        177910.014136
                  90.000000  95.000000   2030        2031         62189.478603
                  95.000000  125.000000  2030        2031         16933.452258
Name: value, Length: 50, dtype: float64

In [40]:
s_pop = pd.read_csv(f"../0100_data_prep/results/population/stratified/{location}.csv")
s_pop = s_pop.set_index([c for c in s_pop.columns if c != "value"])
s_pop

                                                                 value
sex    age_start age_end    pregnant     wealth_quintile
Female 0.0       0.019178   not_pregnant 1                17452.628925
                                         2                17380.997496
                                         3                16409.683914
                                         4                14424.706826
...                                                                ...
Male   95.0      125.000000 not_pregnant 2                 4424.735951
                                         3                 4548.244848
                                         4                 4870.219344
                                         5                 5193.002126

[285 rows x 1 columns]

In [41]:
# WRA only
s_pop = s_pop[
    (s_pop.index.get_level_values("sex") == "Female")
    & (s_pop.index.get_level_values("age_start") >= 15)
    & (s_pop.index.get_level_values("age_end") <= 50)
].copy()

In [42]:
s_daily_vehicle = pd.read_csv(
    f"../0100_data_prep/results/{vehicle}/vehicle_consumption/amount/mean/{location}.csv"
)
assert (s_daily_vehicle.vehicle_name == vehicle).all()
s_daily_vehicle = s_daily_vehicle.drop(columns=["vehicle_name"])
s_daily_vehicle = s_daily_vehicle.set_index(
    [c for c in s_daily_vehicle.columns if c != "value"]
).value
s_daily_vehicle

sex     age_start  age_end  wealth_quintile
Female  0          5        1                  8.200000
                            2                  7.809524
                            3                  5.759524
                            4                  4.783333
                                                 ...
Male    15         125      2                  8.390244
                            3                  6.187805
                            4                  5.139024
                            5                  4.824390
Name: value, Length: 30, dtype: float64

In [43]:
from lsff_utils import data_processing

In [44]:
s_daily_vehicle = (
    s_pop.value
    * data_processing.reindex_series_onto_df_by_age_groups(s_pop, s_daily_vehicle)
).groupby("wealth_quintile").sum() / s_pop.value.groupby("wealth_quintile").sum()
s_daily_vehicle

wealth_quintile
1    8.4
2    8.0
3    5.9
4    4.9
5    4.6
Name: value, dtype: float64

In [45]:
any_consumers = pd.read_csv(
    f"../0100_data_prep/results/{vehicle}/vehicle_consumption/any/{location}.csv"
)
assert (any_consumers.vehicle_name == vehicle).all()
any_consumers = any_consumers.drop(columns=["vehicle_name"])
any_consumers = any_consumers.set_index(
    [c for c in any_consumers.columns if c != "value"]
).value
any_consumers

wealth_quintile  sex     age_start  age_end
1                Female  15         50         0.963
2                Female  15         50         0.981
3                Female  15         50         0.992
4                Female  15         50         0.986
5                Female  15         50         0.986
Name: value, dtype: float64

In [46]:
any_consumers = (
    s_pop.value
    * data_processing.reindex_series_onto_df_by_age_groups(s_pop, any_consumers)
).groupby("wealth_quintile").sum() / s_pop.value.groupby("wealth_quintile").sum()
any_consumers

wealth_quintile
1    0.963
2    0.981
3    0.992
4    0.986
5    0.986
Name: value, dtype: float64

In [47]:
s_daily_vehicle_among_consumers = s_daily_vehicle / any_consumers
s_daily_vehicle_among_consumers

wealth_quintile
1    8.722741
2    8.154944
3    5.947581
4    4.969574
5    4.665314
Name: value, dtype: float64

In [48]:
baseline_concentration_mcg_per_gram = pd.read_csv(
    f"../0100_data_prep/results/folate/{vehicle}/baseline_fortification/concentration/{location}.csv"
)
assert (baseline_concentration_mcg_per_gram.vehicle_name == vehicle).all()
assert baseline_concentration_mcg_per_gram.value.nunique() == 1
baseline_concentration_mcg_per_gram = baseline_concentration_mcg_per_gram.value.iloc[0]
baseline_concentration_mcg_per_gram

0.0

In [49]:
intervention_concentration_mcg_per_gram = pd.concat(
    [
        pd.read_csv(
            f"../0100_data_prep/results/folate/{vehicle}/{intervention_scenario}/intervention_fortification/concentration/{location}.csv"
        ).assign(scenario=intervention_scenario)
        for intervention_scenario in intervention_scenarios
    ]
)
assert (intervention_concentration_mcg_per_gram.vehicle_name == vehicle).all()
intervention_concentration_mcg_per_gram = (
    intervention_concentration_mcg_per_gram.drop(columns=["vehicle_name"])
    .set_index("scenario")
    .value
)
intervention_concentration_mcg_per_gram

scenario
intervention    24.0
Name: value, dtype: float64

In [50]:
eff_fort_baseline_path = f"../0100_data_prep/results/folate/{vehicle}/baseline_fortification/effective_coverage/{location}.csv"

df_eff_fort_baseline = pd.read_csv(eff_fort_baseline_path)
assert (df_eff_fort_baseline.vehicle_name == vehicle).all()

In [51]:
if location == "india" and vehicle == "rice":
    # Confusingly, our baseline scenario (our best guess about the present)
    # is *not* a good guess about 2019-2020 (which is when our baseline folate estimate is from),
    # because this program has rolled out entirely since then:
    # In the phase-I of the roll out, the fortified rice was introduced in the social welfare schemes such as Integrated Child Development Scheme (ICDS)
    # and Pradhan Mantri Poshan Shakti Nirman (PM POSHAN, earlier known as the National Program of Mid-Day Meal in Schools)
    # throughout India during 2021–22 [18].
    # Phase-II has covered aspirational and high burden districts for anemia (total 291 districts) under Public Distribution System (PDS) and other welfare schemes,
    # in addition to Phase-I districts, by March 2023 [18].
    # All the remaining districts in India will be covered in Phase III by March 2024 [19].
    # ~ https://pmc.ncbi.nlm.nih.gov/articles/PMC11305529/
    df_eff_fort_baseline_2019_2020 = df_eff_fort_baseline.assign(value=0)
else:
    df_eff_fort_baseline_2019_2020 = df_eff_fort_baseline

In [52]:
df_eff_fort_intervention = pd.concat(
    [
        pd.read_csv(
            f"../0100_data_prep/results/folate/{vehicle}/{intervention_scenario}/intervention_fortification/effective_coverage/{location}.csv"
        ).assign(scenario=intervention_scenario)
        for intervention_scenario in intervention_scenarios
    ]
)
assert (df_eff_fort_intervention.vehicle_name == vehicle).all()
df_eff_fort_intervention = df_eff_fort_intervention.drop(columns=["vehicle_name"])
df_eff_fort_intervention

    wealth_quintile     sex    value      scenario
0                 1  Female  0.75330  intervention
1                 1    Male  0.75330  intervention
2                 2  Female  0.77760  intervention
3                 2    Male  0.77760  intervention
..              ...     ...      ...           ...
6                 4  Female  0.78975  intervention
7                 4    Male  0.78975  intervention
8                 5  Female  0.78570  intervention
9                 5    Male  0.78570  intervention

[10 rows x 4 columns]

In [53]:
# NOTE: Using DHS definition of WRA
population = (
    pd.read_csv(f"../0100_data_prep/results/population/stratified/{location}.csv")
    .groupby(["sex", "age_start", "age_end", "wealth_quintile"])
    .value.sum()
    .reset_index()
)
population = population[
    (population.sex == "Female")
    & (population.age_start >= 15)
    & (population.age_end <= 50)
]
population

       sex  age_start  age_end  wealth_quintile         value
40  Female       15.0     20.0                1  2.538048e+06
41  Female       15.0     20.0                2  2.988632e+06
42  Female       15.0     20.0                3  2.997132e+06
43  Female       15.0     20.0                4  3.244674e+06
..     ...        ...      ...              ...           ...
71  Female       45.0     50.0                2  8.013029e+05
72  Female       45.0     50.0                3  8.513975e+05
73  Female       45.0     50.0                4  9.617532e+05
74  Female       45.0     50.0                5  1.138775e+06

[35 rows x 5 columns]

In [54]:
if "sex" in df_eff_fort_baseline_2019_2020.columns:
    df_eff_fort_baseline_2019_2020 = df_eff_fort_baseline_2019_2020[
        (df_eff_fort_baseline_2019_2020.sex == "Female")
    ]

if "age_start" in df_eff_fort_baseline_2019_2020.columns:
    df_eff_fort_baseline_2019_2020 = df_eff_fort_baseline_2019_2020[
        (df_eff_fort_baseline_2019_2020.age_start >= 15)
        & (df_eff_fort_baseline_2019_2020.age_end <= 50)
    ]

In [55]:
if "sex" in df_eff_fort_intervention.columns:
    df_eff_fort_intervention = df_eff_fort_intervention[
        (df_eff_fort_intervention.sex == "Female")
    ]

if "age_start" in df_eff_fort_intervention.columns:
    df_eff_fort_intervention = df_eff_fort_intervention[
        (df_eff_fort_intervention.age_start >= 15)
        & (df_eff_fort_intervention.age_end <= 50)
    ]

In [56]:
def aggregate_using_population(effective_fort):
    merge_cols = [
        c
        for c in ["sex", "wealth_quintile", "age_start", "age_end"]
        if c in effective_fort.columns
    ]
    merged = effective_fort.merge(
        population.reset_index(),
        on=[c for c in merge_cols if "age" not in c],
        suffixes=("_fort", "_pop"),
    )
    assert ("age_start" in merge_cols) == ("age_end" in merge_cols)
    if "age_start" in merge_cols:
        merged = merged[
            (merged.age_start_pop >= merged.age_start_fort)
            & (merged.age_end_pop <= merged.age_end_fort)
        ]
    print(merged)
    assert len(merged) == len(population) * (
        1
        if "scenario" not in effective_fort.columns
        else effective_fort.scenario.nunique()
    )
    group_cols = [c for c in ["scenario", "wealth_quintile"] if c in merged]
    return merged.groupby(group_cols).apply(
        lambda df: (df.value_fort * df.value_pop).sum() / df.value_pop.sum()
    )

In [57]:
df_eff_fort_baseline_2019_2020 = aggregate_using_population(
    df_eff_fort_baseline_2019_2020
)
df_eff_fort_baseline_2019_2020

   vehicle_name  wealth_quintile  value_fort  index     sex  age_start  \
0      bouillon                1         0.0     40  Female       15.0
1      bouillon                1         0.0     45  Female       20.0
2      bouillon                1         0.0     50  Female       25.0
3      bouillon                1         0.0     55  Female       30.0
..          ...              ...         ...    ...     ...        ...
31     bouillon                5         0.0     59  Female       30.0
32     bouillon                5         0.0     64  Female       35.0
33     bouillon                5         0.0     69  Female       40.0
34     bouillon                5         0.0     74  Female       45.0

    age_end     value_pop
0      20.0  2.538048e+06
1      25.0  2.206803e+06
2      30.0  1.805742e+06
3      35.0  1.479843e+06
..      ...           ...
31     35.0  1.945402e+06
32     40.0  1.615082e+06
33     45.0  1.337273e+06
34     50.0  1.138775e+06

[35 rows x 8 columns]

wealth_quintile
1    0.0
2    0.0
3    0.0
4    0.0
5    0.0
dtype: float64

In [58]:
df_eff_fort_baseline = aggregate_using_population(df_eff_fort_baseline)
df_eff_fort_baseline

   vehicle_name  wealth_quintile  value_fort  index     sex  age_start  \
0      bouillon                1         0.0     40  Female       15.0
1      bouillon                1         0.0     45  Female       20.0
2      bouillon                1         0.0     50  Female       25.0
3      bouillon                1         0.0     55  Female       30.0
..          ...              ...         ...    ...     ...        ...
31     bouillon                5         0.0     59  Female       30.0
32     bouillon                5         0.0     64  Female       35.0
33     bouillon                5         0.0     69  Female       40.0
34     bouillon                5         0.0     74  Female       45.0

    age_end     value_pop
0      20.0  2.538048e+06
1      25.0  2.206803e+06
2      30.0  1.805742e+06
3      35.0  1.479843e+06
..      ...           ...
31     35.0  1.945402e+06
32     40.0  1.615082e+06
33     45.0  1.337273e+06
34     50.0  1.138775e+06

[35 rows x 8 columns]

wealth_quintile
1    0.0
2    0.0
3    0.0
4    0.0
5    0.0
dtype: float64

In [59]:
df_eff_fort_intervention = aggregate_using_population(df_eff_fort_intervention)
df_eff_fort_intervention

    wealth_quintile     sex  value_fort      scenario  index  age_start  \
0                 1  Female      0.7533  intervention     40       15.0
1                 1  Female      0.7533  intervention     45       20.0
2                 1  Female      0.7533  intervention     50       25.0
3                 1  Female      0.7533  intervention     55       30.0
..              ...     ...         ...           ...    ...        ...
31                5  Female      0.7857  intervention     59       30.0
32                5  Female      0.7857  intervention     64       35.0
33                5  Female      0.7857  intervention     69       40.0
34                5  Female      0.7857  intervention     74       45.0

    age_end     value_pop
0      20.0  2.538048e+06
1      25.0  2.206803e+06
2      30.0  1.805742e+06
3      35.0  1.479843e+06
..      ...           ...
31     35.0  1.945402e+06
32     40.0  1.615082e+06
33     45.0  1.337273e+06
34     50.0  1.138775e+06

[35 rows x 8 columns]

scenario      wealth_quintile
intervention  1                  0.75330
              2                  0.77760
              3                  0.78813
              4                  0.78975
              5                  0.78570
dtype: float64

In [60]:
RBC_baseline = backcalc_rbc(ntd_affected_pregnancy_risk, "crider")
RBC_baseline

wealth_quintile
1    415.743173
2    415.743173
3    415.743173
4    415.743173
5    415.743173
dtype: float64

In [61]:
# Fortification folate needs to be converted into dietary folate equivalents (DFEs)
# for use with our effect size.
# https://www.jandonline.org/article/S0002-8223(00)00027-4/pdf
fortification_mcg_to_dfe = 1.7

In [62]:
# Delete fortification effect baked into our baseline folate estimate.
# In non-India locations, this is going to be zero.
# For India, our current source for baseline folate is very rough,
# but it does appear to be from before the fortification program (2019-2020).
s_zero_folate = folate_intake_by_wealth - (
    df_eff_fort_baseline_2019_2020
    * s_daily_vehicle_among_consumers
    * baseline_concentration_mcg_per_gram
    * fortification_mcg_to_dfe
)

In [63]:
s_baseline_folate = s_zero_folate + (
    df_eff_fort_baseline
    * s_daily_vehicle_among_consumers
    * baseline_concentration_mcg_per_gram
    * fortification_mcg_to_dfe
)
s_baseline_folate

wealth_quintile
1    189.0
2    198.0
3    197.0
4    203.0
5    208.0
dtype: float64

In [64]:
s_intervention_folate = s_zero_folate + (
    df_eff_fort_intervention
    * s_daily_vehicle_among_consumers
    * intervention_concentration_mcg_per_gram
    * fortification_mcg_to_dfe
)
s_intervention_folate

scenario      wealth_quintile
intervention  1                  457.090318
              2                  456.724404
              3                  388.248643
              4                  363.128621
              5                  357.553931
dtype: float64

In [65]:
zero_folate_pct_decrease = (
    folate_intake_by_wealth - s_zero_folate
) / folate_intake_by_wealth

In [66]:
baseline_folate_pct_increase_from_zero = (
    s_baseline_folate - s_zero_folate
) / folate_intake_by_wealth
baseline_folate_pct_increase_from_zero

wealth_quintile
1    0.0
2    0.0
3    0.0
4    0.0
5    0.0
dtype: float64

In [67]:
intevention_folate_pct_increase_from_zero = (
    s_intervention_folate - s_zero_folate
) / folate_intake_by_wealth
intevention_folate_pct_increase_from_zero

scenario      wealth_quintile
intervention  1                  1.418467
              2                  1.306689
              3                  0.970805
              4                  0.788811
              5                  0.719009
dtype: float64

In [68]:
RBC_zero = RBC_baseline / (1 + ((6 / 10) * zero_folate_pct_decrease))
RBC_zero

wealth_quintile
1    415.743173
2    415.743173
3    415.743173
4    415.743173
5    415.743173
dtype: float64

In [69]:
RBC_baseline = RBC_zero * (1 + ((6 / 10) * baseline_folate_pct_increase_from_zero))
RBC_baseline

wealth_quintile
1    415.743173
2    415.743173
3    415.743173
4    415.743173
5    415.743173
dtype: float64

In [70]:
RBC_intervention = RBC_zero * (
    1 + ((6 / 10) * intevention_folate_pct_increase_from_zero)
)
RBC_intervention

scenario      wealth_quintile
intervention  1                  769.574028
              2                  741.691368
              3                  657.906577
              4                  612.508831
              5                  595.097094
dtype: float64

In [71]:
def calc_ntd_pr(df, method):
    ln_rbc = np.log(df)
    if method == "daly":
        ln_odds = 1.6563 - 1.2193 * ln_rbc
    elif method == "crider":
        ln_odds = 4.57 - 1.70 * ln_rbc
    p = np.exp(ln_odds)  # TODO: better transformation
    return p

In [72]:
# NOTE: All rates here are per birth!
s_ntd_affected_pregnancy_rate_zero = calc_ntd_pr(RBC_zero, "crider")
10_000 * s_ntd_affected_pregnancy_rate_zero

wealth_quintile
1    34.097542
2    34.097542
3    34.097542
4    34.097542
5    34.097542
dtype: float64

In [73]:
s_ntd_affected_pregnancy_rate_baseline = calc_ntd_pr(RBC_baseline, "crider")
10_000 * s_ntd_affected_pregnancy_rate_baseline

wealth_quintile
1    34.097542
2    34.097542
3    34.097542
4    34.097542
5    34.097542
dtype: float64

In [74]:
s_ntd_affected_pregnancy_rate_intervention = calc_ntd_pr(RBC_intervention, "crider")
10_000 * s_ntd_affected_pregnancy_rate_intervention

scenario      wealth_quintile
intervention  1                  11.970164
              2                  12.745190
              3                  15.625956
              4                  17.645533
              5                  18.532178
dtype: float64

In [75]:
s_ntd_affected_pregnancies_zero = (
    s_ntd_affected_pregnancy_rate_zero * s_births_and_stillbirths_by_wealth
)
s_ntd_affected_pregnancies_zero

wealth_quintile
1    7596.119668
2    7767.505148
3    7031.729552
4    6232.915620
5    5474.485622
dtype: float64

In [76]:
s_ntd_affected_pregnancies_baseline = (
    s_ntd_affected_pregnancy_rate_baseline * s_births_and_stillbirths_by_wealth
)
s_ntd_affected_pregnancies_baseline

wealth_quintile
1    7596.119668
2    7767.505148
3    7031.729552
4    6232.915620
5    5474.485622
dtype: float64

In [77]:
s_ntd_affected_pregnancies_intervention = (
    s_ntd_affected_pregnancy_rate_intervention * s_births_and_stillbirths_by_wealth
)
s_ntd_affected_pregnancies_intervention

scenario      wealth_quintile
intervention  1                  2666.667257
              2                  2903.386025
              3                  3222.446282
              4                  3225.543920
              5                  2975.409357
dtype: float64

In [78]:
ntd_cases_by_scenario = pd.concat(
    [
        s_ntd_affected_pregnancies_zero.rename("value")
        .to_frame()
        .assign(entity="ntd", scenario="zero")
        .set_index(["entity", "scenario"], append=True)
        .value,
        s_ntd_affected_pregnancies_baseline.rename("value")
        .to_frame()
        .assign(entity="ntd", scenario="baseline")
        .set_index(["entity", "scenario"], append=True)
        .value,
        *[
            s_ntd_affected_pregnancies_intervention.loc[intervention_scenario]
            .rename("value")
            .to_frame()
            .assign(entity="ntd", scenario=intervention_scenario)
            .set_index(["entity", "scenario"], append=True)
            .value
            for intervention_scenario in intervention_scenarios
        ],
    ]
)
ntd_cases_by_scenario

wealth_quintile  entity  scenario
1                ntd     zero            7596.119668
2                ntd     zero            7767.505148
3                ntd     zero            7031.729552
4                ntd     zero            6232.915620
                                            ...
2                ntd     intervention    2903.386025
3                ntd     intervention    3222.446282
4                ntd     intervention    3225.543920
5                ntd     intervention    2975.409357
Name: value, Length: 15, dtype: float64

In [79]:
(
    ntd_cases_by_scenario[
        ntd_cases_by_scenario.index.get_level_values("scenario") == "baseline"
    ].droplevel("scenario")
    - ntd_cases_by_scenario[
        ntd_cases_by_scenario.index.get_level_values("scenario") == "intervention"
    ].droplevel("scenario")
)

wealth_quintile  entity
1                ntd       4929.452411
2                ntd       4864.119122
3                ntd       3809.283271
4                ntd       3007.371700
5                ntd       2499.076264
Name: value, dtype: float64

In [80]:
(
    ntd_cases_by_scenario[
        ntd_cases_by_scenario.index.get_level_values("scenario") == "zero"
    ].droplevel("scenario")
    - ntd_cases_by_scenario[
        ntd_cases_by_scenario.index.get_level_values("scenario") == "baseline"
    ].droplevel("scenario")
)

wealth_quintile  entity
1                ntd       0.0
2                ntd       0.0
3                ntd       0.0
4                ntd       0.0
5                ntd       0.0
Name: value, dtype: float64

In [81]:
path = f"./results/{location}/{vehicle}/ntd_cases_by_scenario.csv"
pathlib.Path(path).parent.mkdir(exist_ok=True, parents=True)
ntd_cases_by_scenario.to_csv(path)

In [82]:
ntd_deaths_and_stillbirths_by_scenario = ntd_cases_by_scenario * (
    s_ntd_death_or_stillbirth_count / s_ntd_affected_pregnancies
)

In [83]:
(
    ntd_deaths_and_stillbirths_by_scenario[
        ntd_deaths_and_stillbirths_by_scenario.index.get_level_values("scenario")
        == "baseline"
    ].droplevel("scenario")
    - ntd_deaths_and_stillbirths_by_scenario[
        ntd_deaths_and_stillbirths_by_scenario.index.get_level_values("scenario")
        == "intervention"
    ].droplevel("scenario")
)

wealth_quintile  entity
1                ntd       2987.603636
2                ntd       2948.006952
3                ntd       2308.700359
4                ntd       1822.684119
5                ntd       1514.620431
dtype: float64

In [84]:
(
    ntd_deaths_and_stillbirths_by_scenario[
        ntd_deaths_and_stillbirths_by_scenario.index.get_level_values("scenario")
        == "zero"
    ].droplevel("scenario")
    - ntd_deaths_and_stillbirths_by_scenario[
        ntd_deaths_and_stillbirths_by_scenario.index.get_level_values("scenario")
        == "baseline"
    ].droplevel("scenario")
)

wealth_quintile  entity
1                ntd       0.0
2                ntd       0.0
3                ntd       0.0
4                ntd       0.0
5                ntd       0.0
dtype: float64

In [85]:
# For calculating YLLs
tmrle = vivarium_inputs.get_theoretical_minimum_risk_life_expectancy()
tmrle

2026-08-24 17:21:28.008 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:28.009 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:28.014 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 17:21:28.028 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:28.030 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:28.036 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 17:21:28.056 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:28.058 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:28.065 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_most_recent_year'

2026-08-24 17:21:28.072 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:28.073 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:28.103 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_theoretical_minimum_risk_life_expectancy'

2026-08-24 17:21:28.115 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:28.117 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:28.121 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_age_group_id'

2026-08-24 17:21:28.126 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:28.128 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:28.132 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_path_to_global'

2026-08-24 17:21:28.425 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:28.428 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:28.432 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_most_recent_year'

2026-08-24 17:21:28.438 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:28.440 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:28.444 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 17:21:28.452 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:28.454 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:28.465 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 17:21:28.472 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 17:21:28.473 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 17:21:28.477 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_age_bins'

                       value
age_start age_end
0.00      0.01     89.958040
0.01      0.02     89.975474
0.02      0.03     89.990990
0.03      0.04     89.985077
...                      ...
109.97    109.98    4.509941
109.98    109.99    4.504631
109.99    110.00    4.499321
110.00    125.00    4.494011

[11001 rows x 1 columns]

In [86]:
# NOTE: Treating stillbirths as a death!
yll_per_stillbirth_or_death = float(tmrle.iloc[0])
yll_per_stillbirth_or_death

89.95803974533831

In [87]:
ylls_by_scenario = (
    ntd_deaths_and_stillbirths_by_scenario * yll_per_stillbirth_or_death
).rename("value")
ylls_by_scenario

wealth_quintile  entity  scenario
1                ntd     zero            414148.489932
2                ntd     zero            423492.607833
3                ntd     zero            383377.343053
4                ntd     zero            339825.161345
                                             ...
2                ntd     intervention    158295.681313
3                ntd     intervention    175691.184426
4                ntd     intervention    175860.070935
5                ntd     intervention    162222.469646
Name: value, Length: 15, dtype: float64

In [88]:
path = f"./results/{location}/{vehicle}/ylls_by_scenario.csv"
pathlib.Path(path).parent.mkdir(exist_ok=True, parents=True)
ylls_by_scenario.to_csv(path)