In [1]:
import gbd_mapping
import risk_distributions
import pathlib
import pandas as pd, numpy as np
import vivarium_inputs
from vivarium_inputs import utility_data, globals as vi_globals, utilities as vi_utils
from vivarium_gbd_access import gbd
import os, contextlib, warnings, loguru

from vivarium_inputs.validation.raw import DataDoesNotExistError, DataAbnormalError
from tqdm.notebook import tqdm

Config: 'input_data:
    cache_data:
        base: True
    intermediary_data_cache_path:
        base: /share/scratch/users/{username}/cache'
Cache Dir: '/share/scratch/users/zmbc/cache'

In [2]:
pd.set_option("display.max_columns", 30)

In [3]:
warnings.simplefilter(action='ignore', category=pd.errors.PerformanceWarning)

In [4]:
location = "india"
vehicle = "rice"
intervention_scenario = "intervention"

In [5]:
# Parameters
location = "india"
vehicle = "rice"
intervention_scenario = "intervention"

In [6]:
index_cols = ["sex", "age_start", "age_end", "wealth_quintile"]

age_group_ids = [
    2,3,
    388,389,
    6,7,8,9,10,11,12,13,14,15,16,17,18,19,20, 30, 31, 32, 235
]
sex_ids = [1,2]

DRAWS = [f'draw_{i}' for i in range(500)] # NOTE: Some GBD 2021 things return 1,000 but others don't

In [7]:
fortification_hemoglobin_mean_difference = (
    pd.read_csv('../0100_data_prep/results/iron/fortification_hemoglobin_effects.csv')
        .set_index('vehicle_name').value
        .loc[vehicle]
)
fortification_hemoglobin_mean_difference

3.25

In [8]:
effective_baseline_coverage = (
    pd.read_csv(f'../0100_data_prep/results/iron/{vehicle}/baseline_fortification/effective_coverage/{location}.csv')
)
assert (effective_baseline_coverage.vehicle_name == vehicle).all()
effective_baseline_coverage = effective_baseline_coverage.drop(columns=["vehicle_name"])
effective_baseline_coverage

   wealth_quintile     sex  age_start  age_end     value
0           fourth  Female          0        5  0.239271
1           fourth  Female          5       15  0.298223
2           fourth  Female         15       30  0.278779
3           fourth  Female         30       50  0.282996
4           fourth  Female         50      125  0.282733
5           fourth    Male          0        5  0.239590
6           fourth    Male          5       15  0.298466
7           fourth    Male         15       30  0.281030
8           fourth    Male         30       50  0.275204
9           fourth    Male         50      125  0.280098
10         highest  Female          0        5  0.137355
11         highest  Female          5       15  0.170117
12         highest  Female         15       30  0.166026
13         highest  Female         30       50  0.151076
14         highest  Female         50      125  0.145850
15         highest    Male          0        5  0.136388
16         highest    Male          5       15  0.165816
17         highest    Male         15       30  0.164437
18         highest    Male         30       50  0.148838
19         highest    Male         50      125  0.145402
20          lowest  Female          0        5  0.294750
21          lowest  Female          5       15  0.384923
22          lowest  Female         15       30  0.340118
23          lowest  Female         30       50  0.367724
24          lowest  Female         50      125  0.384701
25          lowest    Male          0        5  0.301125
26          lowest    Male          5       15  0.388070
27          lowest    Male         15       30  0.361587
28          lowest    Male         30       50  0.354325
29          lowest    Male         50      125  0.379405
30          middle  Female          0        5  0.278976
31          middle  Female          5       15  0.344120
32          middle  Female         15       30  0.308190
33          middle  Female         30       50  0.329747
34          middle  Female         50      125  0.335275
35          middle    Male          0        5  0.276643
36          middle    Male          5       15  0.337651
37          middle    Male         15       30  0.305303
38          middle    Male         30       50  0.311270
39          middle    Male         50      125  0.328931
40          second  Female          0        5  0.298731
41          second  Female          5       15  0.372437
42          second  Female         15       30  0.347715
43          second  Female         30       50  0.365385
44          second  Female         50      125  0.371430
45          second    Male          0        5  0.304958
46          second    Male          5       15  0.375826
47          second    Male         15       30  0.347710
48          second    Male         30       50  0.351664
49          second    Male         50      125  0.366006

In [9]:
def expand(df):
    for col in sorted(list(set(df.columns) - {'value'})):
        if df[col].isnull().any():
            df = pd.concat([
                df[df[col].notnull()],
                *[df[df[col].isnull()].assign(**{col: value}) for value in df[df[col].notnull()][col].unique()]
            ])
    
    return df

In [10]:
for col, fill_value in [("age_start", 0), ("age_end", 125)]:
    if col not in effective_baseline_coverage.columns:
        effective_baseline_coverage[col] = fill_value
    else:
        effective_baseline_coverage[col] = effective_baseline_coverage[col].fillna(fill_value)

In [11]:
effective_baseline_coverage = expand(effective_baseline_coverage)
effective_baseline_coverage

   wealth_quintile     sex  age_start  age_end     value
0           fourth  Female          0        5  0.239271
1           fourth  Female          5       15  0.298223
2           fourth  Female         15       30  0.278779
3           fourth  Female         30       50  0.282996
4           fourth  Female         50      125  0.282733
5           fourth    Male          0        5  0.239590
6           fourth    Male          5       15  0.298466
7           fourth    Male         15       30  0.281030
8           fourth    Male         30       50  0.275204
9           fourth    Male         50      125  0.280098
10         highest  Female          0        5  0.137355
11         highest  Female          5       15  0.170117
12         highest  Female         15       30  0.166026
13         highest  Female         30       50  0.151076
14         highest  Female         50      125  0.145850
15         highest    Male          0        5  0.136388
16         highest    Male          5       15  0.165816
17         highest    Male         15       30  0.164437
18         highest    Male         30       50  0.148838
19         highest    Male         50      125  0.145402
20          lowest  Female          0        5  0.294750
21          lowest  Female          5       15  0.384923
22          lowest  Female         15       30  0.340118
23          lowest  Female         30       50  0.367724
24          lowest  Female         50      125  0.384701
25          lowest    Male          0        5  0.301125
26          lowest    Male          5       15  0.388070
27          lowest    Male         15       30  0.361587
28          lowest    Male         30       50  0.354325
29          lowest    Male         50      125  0.379405
30          middle  Female          0        5  0.278976
31          middle  Female          5       15  0.344120
32          middle  Female         15       30  0.308190
33          middle  Female         30       50  0.329747
34          middle  Female         50      125  0.335275
35          middle    Male          0        5  0.276643
36          middle    Male          5       15  0.337651
37          middle    Male         15       30  0.305303
38          middle    Male         30       50  0.311270
39          middle    Male         50      125  0.328931
40          second  Female          0        5  0.298731
41          second  Female          5       15  0.372437
42          second  Female         15       30  0.347715
43          second  Female         30       50  0.365385
44          second  Female         50      125  0.371430
45          second    Male          0        5  0.304958
46          second    Male          5       15  0.375826
47          second    Male         15       30  0.347710
48          second    Male         30       50  0.351664
49          second    Male         50      125  0.366006

In [12]:
effective_counterfactual_coverage = (
    pd.read_csv(f'../0100_data_prep/results/iron/{vehicle}/{intervention_scenario}/intervention_fortification/effective_coverage/{location}.csv')
)
assert (effective_counterfactual_coverage.vehicle_name == vehicle).all()
effective_counterfactual_coverage = effective_counterfactual_coverage.drop(columns=["vehicle_name"])
effective_counterfactual_coverage

       sex  age_start  age_end wealth_quintile     value
0   Female          0        5          lowest  0.480408
1   Female          0        5          second  0.489627
2   Female          0        5          middle  0.485258
3   Female          0        5          fourth  0.465105
4   Female          0        5         highest  0.414790
5   Female          5       15          lowest  0.518085
6   Female          5       15          second  0.516195
7   Female          5       15          middle  0.503735
8   Female          5       15          fourth  0.480685
9   Female          5       15         highest  0.422331
10  Female         15       30          lowest  0.490003
11  Female         15       30          second  0.501242
12  Female         15       30          middle  0.487282
13  Female         15       30          fourth  0.469488
14  Female         15       30         highest  0.419794
15  Female         30       50          lowest  0.503899
16  Female         30       50          second  0.507552
17  Female         30       50          middle  0.494017
18  Female         30       50          fourth  0.471462
19  Female         30       50         highest  0.412701
20  Female         50      125          lowest  0.512782
21  Female         50      125          second  0.511740
22  Female         50      125          middle  0.496182
23  Female         50      125          fourth  0.470049
24  Female         50      125         highest  0.409329
25    Male          0        5          lowest  0.483840
26    Male          0        5          second  0.494610
27    Male          0        5          middle  0.481948
28    Male          0        5          fourth  0.465634
29    Male          0        5         highest  0.413391
30    Male          5       15          lowest  0.519112
31    Male          5       15          second  0.516850
32    Male          5       15          middle  0.500769
33    Male          5       15          fourth  0.480829
34    Male          5       15         highest  0.419768
35    Male         15       30          lowest  0.501617
36    Male         15       30          second  0.502133
37    Male         15       30          middle  0.486073
38    Male         15       30          fourth  0.471224
39    Male         15       30         highest  0.418452
40    Male         30       50          lowest  0.497345
41    Male         30       50          second  0.501661
42    Male         30       50          middle  0.485615
43    Male         30       50          fourth  0.468667
44    Male         30       50         highest  0.411959
45    Male         50      125          lowest  0.508892
46    Male         50      125          second  0.506941
47    Male         50      125          middle  0.492142
48    Male         50      125          fourth  0.468019
49    Male         50      125         highest  0.408934

In [13]:
for col, fill_value in [("age_start", 0), ("age_end", 125)]:
    if col not in effective_counterfactual_coverage.columns:
        effective_counterfactual_coverage[col] = fill_value
    else:
        effective_counterfactual_coverage[col] = effective_counterfactual_coverage[col].fillna(fill_value)

In [14]:
effective_counterfactual_coverage = expand(effective_counterfactual_coverage)
effective_counterfactual_coverage

       sex  age_start  age_end wealth_quintile     value
0   Female          0        5          lowest  0.480408
1   Female          0        5          second  0.489627
2   Female          0        5          middle  0.485258
3   Female          0        5          fourth  0.465105
4   Female          0        5         highest  0.414790
5   Female          5       15          lowest  0.518085
6   Female          5       15          second  0.516195
7   Female          5       15          middle  0.503735
8   Female          5       15          fourth  0.480685
9   Female          5       15         highest  0.422331
10  Female         15       30          lowest  0.490003
11  Female         15       30          second  0.501242
12  Female         15       30          middle  0.487282
13  Female         15       30          fourth  0.469488
14  Female         15       30         highest  0.419794
15  Female         30       50          lowest  0.503899
16  Female         30       50          second  0.507552
17  Female         30       50          middle  0.494017
18  Female         30       50          fourth  0.471462
19  Female         30       50         highest  0.412701
20  Female         50      125          lowest  0.512782
21  Female         50      125          second  0.511740
22  Female         50      125          middle  0.496182
23  Female         50      125          fourth  0.470049
24  Female         50      125         highest  0.409329
25    Male          0        5          lowest  0.483840
26    Male          0        5          second  0.494610
27    Male          0        5          middle  0.481948
28    Male          0        5          fourth  0.465634
29    Male          0        5         highest  0.413391
30    Male          5       15          lowest  0.519112
31    Male          5       15          second  0.516850
32    Male          5       15          middle  0.500769
33    Male          5       15          fourth  0.480829
34    Male          5       15         highest  0.419768
35    Male         15       30          lowest  0.501617
36    Male         15       30          second  0.502133
37    Male         15       30          middle  0.486073
38    Male         15       30          fourth  0.471224
39    Male         15       30         highest  0.418452
40    Male         30       50          lowest  0.497345
41    Male         30       50          second  0.501661
42    Male         30       50          middle  0.485615
43    Male         30       50          fourth  0.468667
44    Male         30       50         highest  0.411959
45    Male         50      125          lowest  0.508892
46    Male         50      125          second  0.506941
47    Male         50      125          middle  0.492142
48    Male         50      125          fourth  0.468019
49    Male         50      125         highest  0.408934

In [15]:
non_pregnant_pop = (
    pd.read_csv(f'../0100_data_prep/results/population/stratified/{location}.csv')
).pipe(lambda df: df[df.pregnant == "not_pregnant"]).drop(columns="pregnant")
non_pregnant_pop = non_pregnant_pop.set_index([c for c in non_pregnant_pop.columns if c != 'value']).value
non_pregnant_pop

sex     age_start  age_end     wealth_quintile
Female  0.0        0.019178    lowest             49649.700497
                               second             43575.622144
                               middle             38689.356750
                               fourth             36440.833935
                               highest            29202.585338
                                                      ...
Male    95.0       125.000000  lowest             15176.692284
                               second             15848.509818
                               middle             16370.176208
                               fourth             17265.313670
                               highest            21289.473456
Name: value, Length: 250, dtype: float64

In [16]:
population_age_groups = non_pregnant_pop.reset_index()[["age_start", "age_end"]].drop_duplicates().sort_values("age_start")
population_age_groups

     age_start     age_end
0     0.000000    0.019178
5     0.019178    0.076712
10    0.076712    0.500000
15    0.500000    1.000000
20    1.000000    2.000000
25    2.000000    5.000000
30    5.000000   10.000000
35   10.000000   15.000000
40   15.000000   20.000000
45   20.000000   25.000000
50   25.000000   30.000000
55   30.000000   35.000000
60   35.000000   40.000000
65   40.000000   45.000000
70   45.000000   50.000000
75   50.000000   55.000000
80   55.000000   60.000000
85   60.000000   65.000000
90   65.000000   70.000000
95   70.000000   75.000000
100  75.000000   80.000000
105  80.000000   85.000000
110  85.000000   90.000000
115  90.000000   95.000000
120  95.000000  125.000000

In [17]:
def map_to_population_age_groups(df):
    return (
        population_age_groups.merge(df, how="cross", suffixes=("", "_orig"))
            .pipe(lambda df: df[(df.age_end <= df.age_end_orig) & (df.age_start >= df.age_start_orig)])
            .drop(columns=["age_start_orig", "age_end_orig"])
    )

In [18]:
effective_baseline_coverage = map_to_population_age_groups(effective_baseline_coverage).set_index([c for c in effective_baseline_coverage.columns if c != 'value']).value
effective_counterfactual_coverage = map_to_population_age_groups(effective_counterfactual_coverage).set_index([c for c in effective_counterfactual_coverage.columns if c != 'value']).value

In [19]:
delta_effective_coverage = effective_counterfactual_coverage.sub(effective_baseline_coverage)
delta_effective_coverage

sex     age_start  age_end     wealth_quintile
Female  0.0        0.019178    fourth             0.225834
                               highest            0.277436
                               lowest             0.185658
                               middle             0.206281
                               second             0.190897
                                                    ...
Male    95.0       125.000000  fourth             0.187922
                               highest            0.263533
                               lowest             0.129487
                               middle             0.163211
                               second             0.140935
Name: value, Length: 250, dtype: float64

In [20]:
def reshape_to_vivarium_format(df, location):
    df = vi_utils.reshape(df, value_cols=[c for c in df.columns if 'draw_' in c])
    df = vi_utils.scrub_gbd_conventions(df, location)
    df = vi_utils.split_interval(df, interval_column="age", split_column_prefix="age")
    df = vi_utils.split_interval(df, interval_column="year", split_column_prefix="year")
    df = vi_utils.sort_hierarchical_data(df)
    df.index = df.index.droplevel("location")
    return df

In [21]:
me_ids = {
    "hemoglobin_mean": 10487,
    "hemoglobin_sd": 10488,
}

In [22]:
location_id = utility_data.get_location_id(location.title())
hgb_mean = gbd.get_modelable_entity_draws(me_id=me_ids["hemoglobin_mean"], location_id=location_id, year_id=2021)
hgb_mean = reshape_to_vivarium_format(hgb_mean, location.title()).droplevel(["year_start", "year_end", "measure_id", "metric_id", "model_version_id", "modelable_entity_id"])[DRAWS].copy()
hgb_mean

                                 draw_0      draw_1      draw_2      draw_3  \
sex    age_start age_end
Female 0.000000  0.019178    141.027303  141.174892  143.047093  142.497768
       0.019178  0.076712    128.185915  129.096397  129.130806  127.546092
       0.076712  0.500000    103.541148  104.218523  102.321094  104.327579
       0.500000  1.000000    101.917809   99.823676  100.483745  100.428266
       1.000000  2.000000    101.808200  103.457343  102.146844  103.058795
       2.000000  5.000000    106.297867  106.219133  105.789212  107.260720
       5.000000  10.000000   112.932920  111.768831  112.598540  114.147894
       10.000000 15.000000   115.889117  117.854010  116.651884  116.435834
       15.000000 20.000000   117.312802  117.869717  117.696658  118.290512
       20.000000 25.000000   118.617583  117.381244  117.562883  116.463839
       25.000000 30.000000   118.136225  118.984193  118.330466  117.484197
       30.000000 35.000000   118.468947  117.409679  117.886880  119.228899
       35.000000 40.000000   117.893922  117.756202  118.469227  118.035053
       40.000000 45.000000   117.705099  117.438677  117.891058  117.526008
       45.000000 50.000000   118.863416  118.956356  117.862423  118.694166
       50.000000 55.000000   117.380298  115.684488  117.082839  117.521103
       55.000000 60.000000   115.610201  115.858632  116.824778  116.971145
       60.000000 65.000000   115.852172  115.273742  114.679645  115.057166
       65.000000 70.000000   112.799956  114.029249  112.513289  113.319053
       70.000000 75.000000   111.763028  110.907571  111.248801  110.229346
       75.000000 80.000000   106.694860  105.688161  106.061586  105.665603
       80.000000 85.000000   105.375787  105.408475  105.314517  107.634883
       85.000000 90.000000   100.573661  100.988738   98.813280   99.706145
       90.000000 95.000000    97.373246   97.761692   97.824092   97.656022
       95.000000 125.000000   95.150708   95.688588   94.653440   94.380913
Male   0.000000  0.019178    146.600654  149.103908  146.074897  145.748027
       0.019178  0.076712    128.593451  128.987080  131.564522  129.046613
       0.076712  0.500000    102.882001  103.484281  102.379468  102.302975
       0.500000  1.000000     98.720550  100.044084   99.267918  100.076804
       1.000000  2.000000    101.799264  101.036897  102.067002  102.340244
       2.000000  5.000000    107.195733  107.108687  106.303427  107.176671
       5.000000  10.000000   115.943763  116.573107  114.252198  113.966774
       10.000000 15.000000   125.861685  126.103005  123.731518  125.853467
       15.000000 20.000000   138.148186  139.196158  138.577766  140.412738
       20.000000 25.000000   145.705670  143.628038  144.447657  145.036625
       25.000000 30.000000   143.206791  144.192168  144.708908  142.243978
       30.000000 35.000000   143.104472  145.407658  144.512082  143.314688
       35.000000 40.000000   143.022415  141.891966  143.895938  141.822267
       40.000000 45.000000   142.575032  141.418982  142.295188  141.503041
       45.000000 50.000000   141.450799  142.687529  139.176123  140.952480
       50.000000 55.000000   138.187591  140.164931  139.259715  141.275545
       55.000000 60.000000   135.036605  134.464782  134.025679  133.016133
       60.000000 65.000000   131.931505  132.888573  130.701815  131.483537
       65.000000 70.000000   128.500505  127.922563  128.410141  128.344826
       70.000000 75.000000   122.092349  122.015506  121.558645  122.075910
       75.000000 80.000000   113.648012  114.150699  114.133169  113.393346
       80.000000 85.000000   111.213129  111.511647  111.224695  113.696862
       85.000000 90.000000   108.957315  109.468162  107.835589  108.453981
       90.000000 95.000000   104.826207  102.838567  103.076523  105.765753
       95.000000 125.000000  101.521743  104.483642  103.680272  103.542354

                                 draw_4      draw_5      draw_6      draw_7  \
sex    age_start age_end
Female 0.000000  0.019178    141.204487  141.832669  140.942772  142.891759
       0.019178  0.076712    129.886294  129.778156  127.898826  129.079936
       0.076712  0.500000    103.623847  103.637978  103.094638  103.816330
       0.500000  1.000000    100.642931  100.292157   99.313897  100.007150
       1.000000  2.000000    102.385404  102.072763  101.291160  100.946377
       2.000000  5.000000    106.627044  106.898147  106.226154  106.842262
       5.000000  10.000000   113.027698  112.048307  112.435412  112.251242
       10.000000 15.000000   117.758511  116.982931  118.398544  117.928240
       15.000000 20.000000   117.803942  117.556792  116.771422  117.697237
       20.000000 25.000000   116.793474  116.336518  118.114212  118.189122
       25.000000 30.000000   118.651435  117.555397  119.056904  118.335091
       30.000000 35.000000   118.637946  118.625425  118.021097  118.265905
       35.000000 40.000000   118.327368  117.174609  117.142662  116.789616
       40.000000 45.000000   117.279712  118.111248  116.245581  116.481699
       45.000000 50.000000   118.710554  117.661171  118.976629  119.242165
       50.000000 55.000000   116.927923  115.048771  115.028490  117.123570
       55.000000 60.000000   114.954114  115.014273  116.467325  117.461808
       60.000000 65.000000   116.005948  115.774992  116.256878  116.384270
       65.000000 70.000000   112.547930  112.505298  112.265050  111.738417
       70.000000 75.000000   111.778821  111.131903  111.282069  111.484353
       75.000000 80.000000   106.999055  106.969619  106.957023  106.245748
       80.000000 85.000000   106.520142  107.422522  107.206633  106.786306
       85.000000 90.000000   100.935375  100.047660  101.048082  101.034639
       90.000000 95.000000    97.826422   97.882052   97.610320   96.969268
       95.000000 125.000000   94.715810   94.832461   94.500846   93.744579
Male   0.000000  0.019178    149.507916  145.964431  146.225025  145.316586
       0.019178  0.076712    130.818723  129.015779  131.134078  131.613459
       0.076712  0.500000    103.082213  102.058335  102.592054  102.677256
       0.500000  1.000000    100.198902   99.619711  100.155947   99.160058
       1.000000  2.000000    101.307376  101.008974  102.034328  101.236737
       2.000000  5.000000    106.168652  107.516017  107.968186  107.209576
       5.000000  10.000000   114.595027  114.003191  114.288712  115.156255
       10.000000 15.000000   123.453578  125.320761  126.092438  122.838715
       15.000000 20.000000   139.823752  137.900611  137.879467  139.446326
       20.000000 25.000000   144.687465  146.713869  144.449472  145.807908
       25.000000 30.000000   143.711213  145.134503  145.321307  144.703317
       30.000000 35.000000   144.125244  143.971921  143.716459  144.497229
       35.000000 40.000000   143.509035  142.702415  143.007036  143.714419
       40.000000 45.000000   140.659993  140.331404  141.218319  143.880802
       45.000000 50.000000   140.981894  141.171235  140.824666  141.095513
       50.000000 55.000000   139.015285  138.390449  140.163927  139.752444
       55.000000 60.000000   131.832313  132.183183  132.775385  134.303723
       60.000000 65.000000   132.355779  131.646361  130.830151  131.257054
       65.000000 70.000000   128.691358  129.092882  127.755495  128.408282
       70.000000 75.000000   123.353119  120.160507  121.131516  120.301521
       75.000000 80.000000   113.021046  114.998081  112.171637  116.215670
       80.000000 85.000000   111.760726  110.509071  112.740967  112.420528
       85.000000 90.000000   107.789270  106.449757  108.587054  107.951513
       90.000000 95.000000   102.870361  105.206229  103.671423  103.993018
       95.000000 125.000000  106.030026  104.282835  104.282065  104.558520

                                 draw_8      draw_9     draw_10     draw_11  \
sex    age_start age_end
Female 0.000000  0.019178    141.388006  143.166841  141.690094  141.898000
       0.019178  0.076712    129.428546  128.289116  129.760068  125.588031
       0.076712  0.500000    101.953160  104.552078  103.102808  103.636228
       0.500000  1.000000     99.623193   99.082577   98.896518  100.185511
       1.000000  2.000000    101.550301  101.265943  101.979446  102.341151
       2.000000  5.000000    105.557078  106.524002  106.104216  105.204816
       5.000000  10.000000   114.540273  112.764552  112.826118  113.109683
       10.000000 15.000000   118.830370  117.453360  118.007278  117.807850
       15.000000 20.000000   117.938688  116.838995  116.178469  117.594046
       20.000000 25.000000   118.042701  116.589943  117.390448  116.698454
       25.000000 30.000000   118.553975  117.216931  117.995222  117.717864
       30.000000 35.000000   118.252681  118.331253  116.276940  117.814956
       35.000000 40.000000   118.047525  117.597061  116.728484  117.156535
       40.000000 45.000000   117.381327  118.576236  118.155997  118.027648
       45.000000 50.000000   119.707658  117.877997  117.469466  118.755627
       50.000000 55.000000   116.219699  115.923873  116.620485  116.118045
       55.000000 60.000000   116.433896  114.081531  115.615040  116.139035
       60.000000 65.000000   115.293043  115.804246  115.944958  115.767223
       65.000000 70.000000   113.796545  112.949549  113.532621  112.031522
       70.000000 75.000000   112.076247  111.198581  111.617306  111.411395
       75.000000 80.000000   105.760788  106.609933  105.298037  106.875900
       80.000000 85.000000   107.138111  107.581337  106.344844  106.131632
       85.000000 90.000000   100.353719  100.462210  100.088225  100.293545
       90.000000 95.000000    97.355357   97.310407   98.807708   98.125130
       95.000000 125.000000   94.691690   94.882934   94.136528   94.388211
Male   0.000000  0.019178    149.278837  147.447709  145.893429  146.379704
       0.019178  0.076712    130.514048  130.238115  130.477048  129.151519
       0.076712  0.500000    102.428315  102.461533  103.200837  103.125114
       0.500000  1.000000     99.632622  100.092466   99.216832   99.968373
       1.000000  2.000000    101.725485  101.330192  103.543759  100.948091
       2.000000  5.000000    107.226192  106.473558  107.524531  106.817522
       5.000000  10.000000   115.818374  114.768091  115.526383  115.173475
       10.000000 15.000000   127.319340  124.044043  125.457342  124.664340
       15.000000 20.000000   139.069579  139.532361  140.323330  136.383686
       20.000000 25.000000   144.225768  144.616586  144.930233  144.698293
       25.000000 30.000000   143.924935  144.603368  145.036502  146.138172
       30.000000 35.000000   144.564106  143.259009  143.230610  144.696911
       35.000000 40.000000   144.305263  142.899962  142.773071  143.049930
       40.000000 45.000000   141.725583  142.086397  142.357475  141.429862
       45.000000 50.000000   139.712886  140.401537  141.092169  142.744025
       50.000000 55.000000   138.578497  139.302891  138.916024  139.719056
       55.000000 60.000000   133.951623  134.938991  132.490779  133.753828
       60.000000 65.000000   129.672427  131.976445  129.135785  133.028587
       65.000000 70.000000   128.431021  128.926739  128.764072  128.113330
       70.000000 75.000000   123.008685  124.280302  122.665397  123.673619
       75.000000 80.000000   110.833941  112.985214  114.056846  114.014498
       80.000000 85.000000   111.899483  112.601548  111.811692  111.463856
       85.000000 90.000000   108.255677  109.286690  106.426424  108.028784
       90.000000 95.000000   104.369785  104.927585  104.548579  105.845457
       95.000000 125.000000  105.468161  104.377732  104.561692  103.878670

                                draw_12     draw_13     draw_14  ...  \
sex    age_start age_end                                         ...
Female 0.000000  0.019178    140.621895  141.533315  142.216214  ...
       0.019178  0.076712    127.422365  128.971676  129.503325  ...
       0.076712  0.500000    102.925970  103.450337  102.391462  ...
       0.500000  1.000000    100.442880  101.094978   99.764511  ...
       1.000000  2.000000    101.799015  102.331132  102.429842  ...
       2.000000  5.000000    105.418535  106.710777  105.798378  ...
       5.000000  10.000000   113.876197  113.261589  112.991322  ...
       10.000000 15.000000   117.147779  116.355426  118.801191  ...
       15.000000 20.000000   116.837181  117.807530  116.774899  ...
       20.000000 25.000000   116.703471  116.611711  117.317490  ...
       25.000000 30.000000   117.301202  117.744061  117.449045  ...
       30.000000 35.000000   117.312997  116.450486  117.345167  ...
       35.000000 40.000000   118.550386  117.731492  118.146719  ...
       40.000000 45.000000   117.284904  118.201250  117.096616  ...
       45.000000 50.000000   118.401036  120.133273  119.271110  ...
       50.000000 55.000000   115.537091  116.794102  116.144150  ...
       55.000000 60.000000   115.081944  116.898367  115.544684  ...
       60.000000 65.000000   115.222907  117.187678  115.486985  ...
       65.000000 70.000000   112.708685  113.056502  112.434715  ...
       70.000000 75.000000   111.546276  112.212507  111.863416  ...
       75.000000 80.000000   106.135631  107.896933  105.732484  ...
       80.000000 85.000000   105.824800  105.592398  107.610558  ...
       85.000000 90.000000   100.235353  101.018216   99.686392  ...
       90.000000 95.000000    98.340921   97.708524   97.196355  ...
       95.000000 125.000000   95.251432   94.874892   95.127562  ...
Male   0.000000  0.019178    145.852841  145.543729  145.889905  ...
       0.019178  0.076712    129.031464  131.353565  129.236988  ...
       0.076712  0.500000    102.997030  102.550327  102.202584  ...
       0.500000  1.000000     98.538916   99.952793   98.288587  ...
       1.000000  2.000000    101.903381  102.679912  102.149508  ...
       2.000000  5.000000    107.875446  107.755126  107.266214  ...
       5.000000  10.000000   114.069494  113.201291  115.898319  ...
       10.000000 15.000000   127.346822  123.275046  124.347649  ...
       15.000000 20.000000   140.043410  140.112651  139.196092  ...
       20.000000 25.000000   144.894072  144.588676  144.986145  ...
       25.000000 30.000000   145.730684  143.822078  143.525368  ...
       30.000000 35.000000   143.749210  144.060994  144.259680  ...
       35.000000 40.000000   141.756879  142.596305  140.492059  ...
       40.000000 45.000000   142.055592  141.918080  143.221959  ...
       45.000000 50.000000   140.871621  140.446348  140.641803  ...
       50.000000 55.000000   139.724773  138.957599  138.988532  ...
       55.000000 60.000000   133.379626  134.161593  129.919218  ...
       60.000000 65.000000   130.882905  132.197605  130.475960  ...
       65.000000 70.000000   128.762959  129.966417  127.213084  ...
       70.000000 75.000000   120.761839  123.730549  122.334112  ...
       75.000000 80.000000   114.781453  114.711730  114.045582  ...
       80.000000 85.000000   112.177827  113.719700  110.941619  ...
       85.000000 90.000000   108.875183  108.055727  105.361526  ...
       90.000000 95.000000   104.082985  104.971889  104.024593  ...
       95.000000 125.000000  106.290751  101.180182  104.497068  ...

                               draw_485    draw_486    draw_487    draw_488  \
sex    age_start age_end
Female 0.000000  0.019178    141.526624  141.615584  140.622443  141.348720
       0.019178  0.076712    127.632987  127.167051  128.973940  128.526843
       0.076712  0.500000    102.871314  103.349640  102.785109  102.688157
       0.500000  1.000000    101.207382  100.466487   99.706193  100.301116
       1.000000  2.000000    103.016288  102.057419  101.942665  102.926913
       2.000000  5.000000    105.376963  106.889429  105.758588  106.659558
       5.000000  10.000000   113.323371  113.127759  112.711601  112.289644
       10.000000 15.000000   116.004982  117.648196  116.361801  118.730593
       15.000000 20.000000   118.124960  117.762122  117.651794  118.413047
       20.000000 25.000000   116.981337  118.125566  115.891134  115.718870
       25.000000 30.000000   118.017267  118.307304  118.030769  118.076347
       30.000000 35.000000   118.017861  116.455042  118.420726  117.120270
       35.000000 40.000000   117.545678  116.797938  117.068524  117.048244
       40.000000 45.000000   118.738176  117.464379  117.302787  118.418955
       45.000000 50.000000   117.692401  117.652390  118.616530  119.577384
       50.000000 55.000000   116.014972  116.604590  117.003533  115.956143
       55.000000 60.000000   115.565071  116.114133  115.657599  115.437449
       60.000000 65.000000   116.142880  117.493969  116.416154  115.798953
       65.000000 70.000000   112.808520  112.419718  113.649074  112.865661
       70.000000 75.000000   111.564236  111.479226  110.894730  111.579805
       75.000000 80.000000   105.010724  106.615722  106.835070  106.395686
       80.000000 85.000000   107.614681  105.896787  106.802596  106.104507
       85.000000 90.000000   100.213562  101.554015  100.905434  100.430955
       90.000000 95.000000    97.680638   97.337414   97.500094   97.022495
       95.000000 125.000000   94.800832   93.987715   94.542641   96.100699
Male   0.000000  0.019178    147.359782  145.677340  149.941084  146.631742
       0.019178  0.076712    131.636753  129.332522  128.288935  130.051749
       0.076712  0.500000    103.168283  102.496944  103.630806  101.562242
       0.500000  1.000000    100.490251   98.014017   99.382627   98.938737
       1.000000  2.000000    101.154555  101.198991  102.204984  101.974834
       2.000000  5.000000    108.350435  107.502177  107.384874  107.241410
       5.000000  10.000000   115.334624  115.057690  116.424377  115.663752
       10.000000 15.000000   127.939771  123.525776  124.772641  126.782981
       15.000000 20.000000   137.731709  139.410310  140.505007  140.402920
       20.000000 25.000000   144.034254  143.980817  143.108393  144.713313
       25.000000 30.000000   146.848899  145.180650  143.095719  144.589025
       30.000000 35.000000   143.940483  142.637628  143.990044  143.544533
       35.000000 40.000000   143.996111  142.241957  142.857362  142.290025
       40.000000 45.000000   140.680638  141.820849  141.823775  141.552092
       45.000000 50.000000   141.110455  142.756312  141.089497  139.573937
       50.000000 55.000000   138.761479  139.165054  141.249419  138.551211
       55.000000 60.000000   135.063542  132.359468  132.582882  132.181788
       60.000000 65.000000   131.705284  133.602928  131.995006  132.181162
       65.000000 70.000000   130.728895  128.768856  126.159529  126.561371
       70.000000 75.000000   120.864494  120.526509  122.915923  123.084680
       75.000000 80.000000   113.575106  112.374502  115.378185  112.620064
       80.000000 85.000000   113.357581  113.244647  113.025809  112.627442
       85.000000 90.000000   107.850430  110.350913  108.413680  108.444964
       90.000000 95.000000   102.287426  104.994304  104.430357  103.339152
       95.000000 125.000000  106.109872  105.700915  106.118128  103.547613

                               draw_489    draw_490    draw_491    draw_492  \
sex    age_start age_end
Female 0.000000  0.019178    141.252097  140.459189  140.765055  142.503501
       0.019178  0.076712    128.432802  128.716439  129.137330  128.530514
       0.076712  0.500000    102.511993  102.776895  103.279928  104.036275
       0.500000  1.000000    100.789760  101.271734  100.142204  101.161263
       1.000000  2.000000    101.216868  101.386336  102.584354  101.600325
       2.000000  5.000000    107.022587  106.181268  106.832692  106.510844
       5.000000  10.000000   114.263669  113.947008  111.993490  112.378643
       10.000000 15.000000   117.399848  115.670224  117.460511  117.405846
       15.000000 20.000000   117.921447  117.497554  118.291326  117.559981

In [23]:
hemoglobin_mean_disparities = pd.read_csv(f'../0100_data_prep/results/hemoglobin/mean_disparities/{location}.csv')
hemoglobin_mean_disparities = (
    map_to_population_age_groups(hemoglobin_mean_disparities[hemoglobin_mean_disparities.pregnant == "not_pregnant"].drop(columns=["pregnant"]))
        .set_index(["sex", "age_start", "age_end", "wealth_quintile"]).value
)
hemoglobin_mean_disparities

sex     age_start  age_end     wealth_quintile
Female  0.0        0.019178    lowest             103.655561
                               second             105.257986
                               middle             105.397530
                               fourth             106.765336
                               highest            107.989017
                                                     ...
Male    95.0       125.000000  lowest             115.022635
                               second             116.108207
                               middle             116.488978
                               fourth             117.310740
                               highest            118.402649
Name: value, Length: 250, dtype: float64

In [24]:
wealth_quintile_probabilities = pd.read_csv(f'../0100_data_prep/results/wealth_quintile_probabilities/{location}.csv')
wealth_quintile_probabilities

,sex,age_start,age_end,pregnant,lowest,second,middle,fourth,highest
0,Female,0.0,5.0,not_pregnant,0.251317,0.220571,0.195838,0.184456,0.147818
1,Female,5.0,15.0,not_pregnant,0.269038,0.219459,0.193766,0.172569,0.145167
2,Female,15.0,30.0,not_pregnant,0.177853,0.202279,0.211418,0.210441,0.198009
3,Female,15.0,30.0,pregnant,0.221117,0.222530,0.215087,0.182296,0.158970
4,Female,30.0,50.0,not_pregnant,0.172597,0.187138,0.199031,0.213495,0.227738
5,Female,30.0,50.0,pregnant,0.316131,0.181401,0.129805,0.169147,0.203517
6,Female,50.0,125.0,not_pregnant,0.188708,0.187540,0.191253,0.199636,0.232863
7,Male,0.0,5.0,not_pregnant,0.242600,0.215610,0.200229,0.183923,0.157639
8,Male,5.0,15.0,not_pregnant,0.261604,0.217675,0.190718,0.176545,0.153458
9,Male,15.0,30.0,not_pregnant,0.169172,0.205794,0.214029,0.208330,0.202675
10,Male,30.0,50.0,not_pregnant,0.167563,0.183939,0.203419,0.219906,0.225173
11,Male,50.0,125.0,not_pregnant,0.176575,0.184392,0.190461,0.200876,0.247696

In [25]:
wealth_quintile_probabilities = (
    map_to_population_age_groups(wealth_quintile_probabilities[wealth_quintile_probabilities.pregnant == "not_pregnant"].drop(columns=["pregnant"]))
        .set_index(["sex", "age_start", "age_end"])
)
wealth_quintile_probabilities.columns.name = 'wealth_quintile'
wealth_quintile_probabilities = wealth_quintile_probabilities.stack()
wealth_quintile_probabilities

sex     age_start  age_end     wealth_quintile
Female  0.0        0.019178    lowest             0.251317
                               second             0.220571
                               middle             0.195838
                               fourth             0.184456
                               highest            0.147818
                                                    ...
Male    95.0       125.000000  lowest             0.176575
                               second             0.184392
                               middle             0.190461
                               fourth             0.200876
                               highest            0.247696
Length: 250, dtype: float64

In [26]:
assert np.allclose(wealth_quintile_probabilities.groupby(["sex", "age_start", "age_end"]).sum(), 1.0)

In [27]:
pre_disparity_groups = hgb_mean.mul(wealth_quintile_probabilities, axis=0).groupby([c for c in hgb_mean.index.names if c != 'wealth_quintile']).sum()
pre_disparity_groups

                                 draw_0      draw_1      draw_2      draw_3  \
sex    age_start age_end
Female 0.000000  0.019178    141.027303  141.174892  143.047093  142.497768
       0.019178  0.076712    128.185915  129.096397  129.130806  127.546092
       0.076712  0.500000    103.541148  104.218523  102.321094  104.327579
       0.500000  1.000000    101.917809   99.823676  100.483745  100.428266
       1.000000  2.000000    101.808200  103.457343  102.146844  103.058795
       2.000000  5.000000    106.297867  106.219133  105.789212  107.260720
       5.000000  10.000000   112.932920  111.768831  112.598540  114.147894
       10.000000 15.000000   115.889117  117.854010  116.651884  116.435834
       15.000000 20.000000   117.312802  117.869717  117.696658  118.290512
       20.000000 25.000000   118.617583  117.381244  117.562883  116.463839
       25.000000 30.000000   118.136225  118.984193  118.330466  117.484197
       30.000000 35.000000   118.468947  117.409679  117.886880  119.228899
       35.000000 40.000000   117.893922  117.756202  118.469227  118.035053
       40.000000 45.000000   117.705099  117.438677  117.891058  117.526008
       45.000000 50.000000   118.863416  118.956356  117.862423  118.694166
       50.000000 55.000000   117.380298  115.684488  117.082839  117.521103
       55.000000 60.000000   115.610201  115.858632  116.824778  116.971145
       60.000000 65.000000   115.852172  115.273742  114.679645  115.057166
       65.000000 70.000000   112.799956  114.029249  112.513289  113.319053
       70.000000 75.000000   111.763028  110.907571  111.248801  110.229346
       75.000000 80.000000   106.694860  105.688161  106.061586  105.665603
       80.000000 85.000000   105.375787  105.408475  105.314517  107.634883
       85.000000 90.000000   100.573661  100.988738   98.813280   99.706145
       90.000000 95.000000    97.373246   97.761692   97.824092   97.656022
       95.000000 125.000000   95.150708   95.688588   94.653440   94.380913
Male   0.000000  0.019178    146.600654  149.103908  146.074897  145.748027
       0.019178  0.076712    128.593451  128.987080  131.564522  129.046613
       0.076712  0.500000    102.882001  103.484281  102.379468  102.302975
       0.500000  1.000000     98.720550  100.044084   99.267918  100.076804
       1.000000  2.000000    101.799264  101.036897  102.067002  102.340244
       2.000000  5.000000    107.195733  107.108687  106.303427  107.176671
       5.000000  10.000000   115.943763  116.573107  114.252198  113.966774
       10.000000 15.000000   125.861685  126.103005  123.731518  125.853467
       15.000000 20.000000   138.148186  139.196158  138.577766  140.412738
       20.000000 25.000000   145.705670  143.628038  144.447657  145.036625
       25.000000 30.000000   143.206791  144.192168  144.708908  142.243978
       30.000000 35.000000   143.104472  145.407658  144.512082  143.314688
       35.000000 40.000000   143.022415  141.891966  143.895938  141.822267
       40.000000 45.000000   142.575032  141.418982  142.295188  141.503041
       45.000000 50.000000   141.450799  142.687529  139.176123  140.952480
       50.000000 55.000000   138.187591  140.164931  139.259715  141.275545
       55.000000 60.000000   135.036605  134.464782  134.025679  133.016133
       60.000000 65.000000   131.931505  132.888573  130.701815  131.483537
       65.000000 70.000000   128.500505  127.922563  128.410141  128.344826
       70.000000 75.000000   122.092349  122.015506  121.558645  122.075910
       75.000000 80.000000   113.648012  114.150699  114.133169  113.393346
       80.000000 85.000000   111.213129  111.511647  111.224695  113.696862
       85.000000 90.000000   108.957315  109.468162  107.835589  108.453981
       90.000000 95.000000   104.826207  102.838567  103.076523  105.765753
       95.000000 125.000000  101.521743  104.483642  103.680272  103.542354

                                 draw_4      draw_5      draw_6      draw_7  \
sex    age_start age_end
Female 0.000000  0.019178    141.204487  141.832669  140.942772  142.891759
       0.019178  0.076712    129.886294  129.778156  127.898826  129.079936
       0.076712  0.500000    103.623847  103.637978  103.094638  103.816330
       0.500000  1.000000    100.642931  100.292157   99.313897  100.007150
       1.000000  2.000000    102.385404  102.072763  101.291160  100.946377
       2.000000  5.000000    106.627044  106.898147  106.226154  106.842262
       5.000000  10.000000   113.027698  112.048307  112.435412  112.251242
       10.000000 15.000000   117.758511  116.982931  118.398544  117.928240
       15.000000 20.000000   117.803942  117.556792  116.771422  117.697237
       20.000000 25.000000   116.793474  116.336518  118.114212  118.189122
       25.000000 30.000000   118.651435  117.555397  119.056904  118.335091
       30.000000 35.000000   118.637946  118.625425  118.021097  118.265905
       35.000000 40.000000   118.327368  117.174609  117.142662  116.789616
       40.000000 45.000000   117.279712  118.111248  116.245581  116.481699
       45.000000 50.000000   118.710554  117.661171  118.976629  119.242165
       50.000000 55.000000   116.927923  115.048771  115.028490  117.123570
       55.000000 60.000000   114.954114  115.014273  116.467325  117.461808
       60.000000 65.000000   116.005948  115.774992  116.256878  116.384270
       65.000000 70.000000   112.547930  112.505298  112.265050  111.738417
       70.000000 75.000000   111.778821  111.131903  111.282069  111.484353
       75.000000 80.000000   106.999055  106.969619  106.957023  106.245748
       80.000000 85.000000   106.520142  107.422522  107.206633  106.786306
       85.000000 90.000000   100.935375  100.047660  101.048082  101.034639
       90.000000 95.000000    97.826422   97.882052   97.610320   96.969268
       95.000000 125.000000   94.715810   94.832461   94.500846   93.744579
Male   0.000000  0.019178    149.507916  145.964431  146.225025  145.316586
       0.019178  0.076712    130.818723  129.015779  131.134078  131.613459
       0.076712  0.500000    103.082213  102.058335  102.592054  102.677256
       0.500000  1.000000    100.198902   99.619711  100.155947   99.160058
       1.000000  2.000000    101.307376  101.008974  102.034328  101.236737
       2.000000  5.000000    106.168652  107.516017  107.968186  107.209576
       5.000000  10.000000   114.595027  114.003191  114.288712  115.156255
       10.000000 15.000000   123.453578  125.320761  126.092438  122.838715
       15.000000 20.000000   139.823752  137.900611  137.879467  139.446326
       20.000000 25.000000   144.687465  146.713869  144.449472  145.807908
       25.000000 30.000000   143.711213  145.134503  145.321307  144.703317
       30.000000 35.000000   144.125244  143.971921  143.716459  144.497229
       35.000000 40.000000   143.509035  142.702415  143.007036  143.714419
       40.000000 45.000000   140.659993  140.331404  141.218319  143.880802
       45.000000 50.000000   140.981894  141.171235  140.824666  141.095513
       50.000000 55.000000   139.015285  138.390449  140.163927  139.752444
       55.000000 60.000000   131.832313  132.183183  132.775385  134.303723
       60.000000 65.000000   132.355779  131.646361  130.830151  131.257054
       65.000000 70.000000   128.691358  129.092882  127.755495  128.408282
       70.000000 75.000000   123.353119  120.160507  121.131516  120.301521
       75.000000 80.000000   113.021046  114.998081  112.171637  116.215670
       80.000000 85.000000   111.760726  110.509071  112.740967  112.420528
       85.000000 90.000000   107.789270  106.449757  108.587054  107.951513
       90.000000 95.000000   102.870361  105.206229  103.671423  103.993018
       95.000000 125.000000  106.030026  104.282835  104.282065  104.558520

                                 draw_8      draw_9     draw_10     draw_11  \
sex    age_start age_end
Female 0.000000  0.019178    141.388006  143.166841  141.690094  141.898000
       0.019178  0.076712    129.428546  128.289116  129.760068  125.588031
       0.076712  0.500000    101.953160  104.552078  103.102808  103.636228
       0.500000  1.000000     99.623193   99.082577   98.896518  100.185511
       1.000000  2.000000    101.550301  101.265943  101.979446  102.341151
       2.000000  5.000000    105.557078  106.524002  106.104216  105.204816
       5.000000  10.000000   114.540273  112.764552  112.826118  113.109683
       10.000000 15.000000   118.830370  117.453360  118.007278  117.807850
       15.000000 20.000000   117.938688  116.838995  116.178469  117.594046
       20.000000 25.000000   118.042701  116.589943  117.390448  116.698454
       25.000000 30.000000   118.553975  117.216931  117.995222  117.717864
       30.000000 35.000000   118.252681  118.331253  116.276940  117.814956
       35.000000 40.000000   118.047525  117.597061  116.728484  117.156535
       40.000000 45.000000   117.381327  118.576236  118.155997  118.027648
       45.000000 50.000000   119.707658  117.877997  117.469466  118.755627
       50.000000 55.000000   116.219699  115.923873  116.620485  116.118045
       55.000000 60.000000   116.433896  114.081531  115.615040  116.139035
       60.000000 65.000000   115.293043  115.804246  115.944958  115.767223
       65.000000 70.000000   113.796545  112.949549  113.532621  112.031522
       70.000000 75.000000   112.076247  111.198581  111.617306  111.411395
       75.000000 80.000000   105.760788  106.609933  105.298037  106.875900
       80.000000 85.000000   107.138111  107.581337  106.344844  106.131632
       85.000000 90.000000   100.353719  100.462210  100.088225  100.293545
       90.000000 95.000000    97.355357   97.310407   98.807708   98.125130
       95.000000 125.000000   94.691690   94.882934   94.136528   94.388211
Male   0.000000  0.019178    149.278837  147.447709  145.893429  146.379704
       0.019178  0.076712    130.514048  130.238115  130.477048  129.151519
       0.076712  0.500000    102.428315  102.461533  103.200837  103.125114
       0.500000  1.000000     99.632622  100.092466   99.216832   99.968373
       1.000000  2.000000    101.725485  101.330192  103.543759  100.948091
       2.000000  5.000000    107.226192  106.473558  107.524531  106.817522
       5.000000  10.000000   115.818374  114.768091  115.526383  115.173475
       10.000000 15.000000   127.319340  124.044043  125.457342  124.664340
       15.000000 20.000000   139.069579  139.532361  140.323330  136.383686
       20.000000 25.000000   144.225768  144.616586  144.930233  144.698293
       25.000000 30.000000   143.924935  144.603368  145.036502  146.138172
       30.000000 35.000000   144.564106  143.259009  143.230610  144.696911
       35.000000 40.000000   144.305263  142.899962  142.773071  143.049930
       40.000000 45.000000   141.725583  142.086397  142.357475  141.429862
       45.000000 50.000000   139.712886  140.401537  141.092169  142.744025
       50.000000 55.000000   138.578497  139.302891  138.916024  139.719056
       55.000000 60.000000   133.951623  134.938991  132.490779  133.753828
       60.000000 65.000000   129.672427  131.976445  129.135785  133.028587
       65.000000 70.000000   128.431021  128.926739  128.764072  128.113330
       70.000000 75.000000   123.008685  124.280302  122.665397  123.673619
       75.000000 80.000000   110.833941  112.985214  114.056846  114.014498
       80.000000 85.000000   111.899483  112.601548  111.811692  111.463856
       85.000000 90.000000   108.255677  109.286690  106.426424  108.028784
       90.000000 95.000000   104.369785  104.927585  104.548579  105.845457
       95.000000 125.000000  105.468161  104.377732  104.561692  103.878670

                                draw_12     draw_13     draw_14  ...  \
sex    age_start age_end                                         ...
Female 0.000000  0.019178    140.621895  141.533315  142.216214  ...
       0.019178  0.076712    127.422365  128.971676  129.503325  ...
       0.076712  0.500000    102.925970  103.450337  102.391462  ...
       0.500000  1.000000    100.442880  101.094978   99.764511  ...
       1.000000  2.000000    101.799015  102.331132  102.429842  ...
       2.000000  5.000000    105.418535  106.710777  105.798378  ...
       5.000000  10.000000   113.876197  113.261589  112.991322  ...
       10.000000 15.000000   117.147779  116.355426  118.801191  ...
       15.000000 20.000000   116.837181  117.807530  116.774899  ...
       20.000000 25.000000   116.703471  116.611711  117.317490  ...
       25.000000 30.000000   117.301202  117.744061  117.449045  ...
       30.000000 35.000000   117.312997  116.450486  117.345167  ...
       35.000000 40.000000   118.550386  117.731492  118.146719  ...
       40.000000 45.000000   117.284904  118.201250  117.096616  ...
       45.000000 50.000000   118.401036  120.133273  119.271110  ...
       50.000000 55.000000   115.537091  116.794102  116.144150  ...
       55.000000 60.000000   115.081944  116.898367  115.544684  ...
       60.000000 65.000000   115.222907  117.187678  115.486985  ...
       65.000000 70.000000   112.708685  113.056502  112.434715  ...
       70.000000 75.000000   111.546276  112.212507  111.863416  ...
       75.000000 80.000000   106.135631  107.896933  105.732484  ...
       80.000000 85.000000   105.824800  105.592398  107.610558  ...
       85.000000 90.000000   100.235353  101.018216   99.686392  ...
       90.000000 95.000000    98.340921   97.708524   97.196355  ...
       95.000000 125.000000   95.251432   94.874892   95.127562  ...
Male   0.000000  0.019178    145.852841  145.543729  145.889905  ...
       0.019178  0.076712    129.031464  131.353565  129.236988  ...
       0.076712  0.500000    102.997030  102.550327  102.202584  ...
       0.500000  1.000000     98.538916   99.952793   98.288587  ...
       1.000000  2.000000    101.903381  102.679912  102.149508  ...
       2.000000  5.000000    107.875446  107.755126  107.266214  ...
       5.000000  10.000000   114.069494  113.201291  115.898319  ...
       10.000000 15.000000   127.346822  123.275046  124.347649  ...
       15.000000 20.000000   140.043410  140.112651  139.196092  ...
       20.000000 25.000000   144.894072  144.588676  144.986145  ...
       25.000000 30.000000   145.730684  143.822078  143.525368  ...
       30.000000 35.000000   143.749210  144.060994  144.259680  ...
       35.000000 40.000000   141.756879  142.596305  140.492059  ...
       40.000000 45.000000   142.055592  141.918080  143.221959  ...
       45.000000 50.000000   140.871621  140.446348  140.641803  ...
       50.000000 55.000000   139.724773  138.957599  138.988532  ...
       55.000000 60.000000   133.379626  134.161593  129.919218  ...
       60.000000 65.000000   130.882905  132.197605  130.475960  ...
       65.000000 70.000000   128.762959  129.966417  127.213084  ...
       70.000000 75.000000   120.761839  123.730549  122.334112  ...
       75.000000 80.000000   114.781453  114.711730  114.045582  ...
       80.000000 85.000000   112.177827  113.719700  110.941619  ...
       85.000000 90.000000   108.875183  108.055727  105.361526  ...
       90.000000 95.000000   104.082985  104.971889  104.024593  ...
       95.000000 125.000000  106.290751  101.180182  104.497068  ...

                               draw_485    draw_486    draw_487    draw_488  \
sex    age_start age_end
Female 0.000000  0.019178    141.526624  141.615584  140.622443  141.348720
       0.019178  0.076712    127.632987  127.167051  128.973940  128.526843
       0.076712  0.500000    102.871314  103.349640  102.785109  102.688157
       0.500000  1.000000    101.207382  100.466487   99.706193  100.301116
       1.000000  2.000000    103.016288  102.057419  101.942665  102.926913
       2.000000  5.000000    105.376963  106.889429  105.758588  106.659558
       5.000000  10.000000   113.323371  113.127759  112.711601  112.289644
       10.000000 15.000000   116.004982  117.648196  116.361801  118.730593
       15.000000 20.000000   118.124960  117.762122  117.651794  118.413047
       20.000000 25.000000   116.981337  118.125566  115.891134  115.718870
       25.000000 30.000000   118.017267  118.307304  118.030769  118.076347
       30.000000 35.000000   118.017861  116.455042  118.420726  117.120270
       35.000000 40.000000   117.545678  116.797938  117.068524  117.048244
       40.000000 45.000000   118.738176  117.464379  117.302787  118.418955
       45.000000 50.000000   117.692401  117.652390  118.616530  119.577384
       50.000000 55.000000   116.014972  116.604590  117.003533  115.956143
       55.000000 60.000000   115.565071  116.114133  115.657599  115.437449
       60.000000 65.000000   116.142880  117.493969  116.416154  115.798953
       65.000000 70.000000   112.808520  112.419718  113.649074  112.865661
       70.000000 75.000000   111.564236  111.479226  110.894730  111.579805
       75.000000 80.000000   105.010724  106.615722  106.835070  106.395686
       80.000000 85.000000   107.614681  105.896787  106.802596  106.104507
       85.000000 90.000000   100.213562  101.554015  100.905434  100.430955
       90.000000 95.000000    97.680638   97.337414   97.500094   97.022495
       95.000000 125.000000   94.800832   93.987715   94.542641   96.100699
Male   0.000000  0.019178    147.359782  145.677340  149.941084  146.631742
       0.019178  0.076712    131.636753  129.332522  128.288935  130.051749
       0.076712  0.500000    103.168283  102.496944  103.630806  101.562242
       0.500000  1.000000    100.490251   98.014017   99.382627   98.938737
       1.000000  2.000000    101.154555  101.198991  102.204984  101.974834
       2.000000  5.000000    108.350435  107.502177  107.384874  107.241410
       5.000000  10.000000   115.334624  115.057690  116.424377  115.663752
       10.000000 15.000000   127.939771  123.525776  124.772641  126.782981
       15.000000 20.000000   137.731709  139.410310  140.505007  140.402920
       20.000000 25.000000   144.034254  143.980817  143.108393  144.713313
       25.000000 30.000000   146.848899  145.180650  143.095719  144.589025
       30.000000 35.000000   143.940483  142.637628  143.990044  143.544533
       35.000000 40.000000   143.996111  142.241957  142.857362  142.290025
       40.000000 45.000000   140.680638  141.820849  141.823775  141.552092
       45.000000 50.000000   141.110455  142.756312  141.089497  139.573937
       50.000000 55.000000   138.761479  139.165054  141.249419  138.551211
       55.000000 60.000000   135.063542  132.359468  132.582882  132.181788
       60.000000 65.000000   131.705284  133.602928  131.995006  132.181162
       65.000000 70.000000   130.728895  128.768856  126.159529  126.561371
       70.000000 75.000000   120.864494  120.526509  122.915923  123.084680
       75.000000 80.000000   113.575106  112.374502  115.378185  112.620064
       80.000000 85.000000   113.357581  113.244647  113.025809  112.627442
       85.000000 90.000000   107.850430  110.350913  108.413680  108.444964
       90.000000 95.000000   102.287426  104.994304  104.430357  103.339152
       95.000000 125.000000  106.109872  105.700915  106.118128  103.547613

                               draw_489    draw_490    draw_491    draw_492  \
sex    age_start age_end
Female 0.000000  0.019178    141.252097  140.459189  140.765055  142.503501
       0.019178  0.076712    128.432802  128.716439  129.137330  128.530514
       0.076712  0.500000    102.511993  102.776895  103.279928  104.036275
       0.500000  1.000000    100.789760  101.271734  100.142204  101.161263
       1.000000  2.000000    101.216868  101.386336  102.584354  101.600325
       2.000000  5.000000    107.022587  106.181268  106.832692  106.510844
       5.000000  10.000000   114.263669  113.947008  111.993490  112.378643
       10.000000 15.000000   117.399848  115.670224  117.460511  117.405846
       15.000000 20.000000   117.921447  117.497554  118.291326  117.559981

In [28]:
hgb_mean = hgb_mean.mul(hemoglobin_mean_disparities, axis=0)

In [29]:
scale_factor = pre_disparity_groups / hgb_mean.mul(wealth_quintile_probabilities, axis=0).groupby([c for c in hgb_mean.index.names if c != 'wealth_quintile']).sum()
scale_factor

                               draw_0    draw_1    draw_2    draw_3    draw_4  \
sex    age_start age_end
Female 0.000000  0.019178    0.009473  0.009473  0.009473  0.009473  0.009473
       0.019178  0.076712    0.009473  0.009473  0.009473  0.009473  0.009473
       0.076712  0.500000    0.009473  0.009473  0.009473  0.009473  0.009473
       0.500000  1.000000    0.009473  0.009473  0.009473  0.009473  0.009473
       1.000000  2.000000    0.009473  0.009473  0.009473  0.009473  0.009473
       2.000000  5.000000    0.009473  0.009473  0.009473  0.009473  0.009473
       5.000000  10.000000   0.009011  0.009011  0.009011  0.009011  0.009011
       10.000000 15.000000   0.009011  0.009011  0.009011  0.009011  0.009011
       15.000000 20.000000   0.008569  0.008569  0.008569  0.008569  0.008569
       20.000000 25.000000   0.008569  0.008569  0.008569  0.008569  0.008569
       25.000000 30.000000   0.008569  0.008569  0.008569  0.008569  0.008569
       30.000000 35.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       35.000000 40.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       40.000000 45.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       45.000000 50.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       50.000000 55.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       55.000000 60.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       60.000000 65.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       65.000000 70.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       70.000000 75.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       75.000000 80.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       80.000000 85.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       85.000000 90.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       90.000000 95.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       95.000000 125.000000  0.008565  0.008565  0.008565  0.008565  0.008565
Male   0.000000  0.019178    0.009480  0.009480  0.009480  0.009480  0.009480
       0.019178  0.076712    0.009480  0.009480  0.009480  0.009480  0.009480
       0.076712  0.500000    0.009480  0.009480  0.009480  0.009480  0.009480
       0.500000  1.000000    0.009480  0.009480  0.009480  0.009480  0.009480
       1.000000  2.000000    0.009480  0.009480  0.009480  0.009480  0.009480
       2.000000  5.000000    0.009480  0.009480  0.009480  0.009480  0.009480
       5.000000  10.000000   0.009013  0.009013  0.009013  0.009013  0.009013
       10.000000 15.000000   0.009013  0.009013  0.009013  0.009013  0.009013
       15.000000 20.000000   0.008567  0.008567  0.008567  0.008567  0.008567
       20.000000 25.000000   0.008567  0.008567  0.008567  0.008567  0.008567
       25.000000 30.000000   0.008567  0.008567  0.008567  0.008567  0.008567
       30.000000 35.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       35.000000 40.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       40.000000 45.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       45.000000 50.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       50.000000 55.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       55.000000 60.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       60.000000 65.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       65.000000 70.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       70.000000 75.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       75.000000 80.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       80.000000 85.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       85.000000 90.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       90.000000 95.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       95.000000 125.000000  0.008562  0.008562  0.008562  0.008562  0.008562

                               draw_5    draw_6    draw_7    draw_8    draw_9  \
sex    age_start age_end
Female 0.000000  0.019178    0.009473  0.009473  0.009473  0.009473  0.009473
       0.019178  0.076712    0.009473  0.009473  0.009473  0.009473  0.009473
       0.076712  0.500000    0.009473  0.009473  0.009473  0.009473  0.009473
       0.500000  1.000000    0.009473  0.009473  0.009473  0.009473  0.009473
       1.000000  2.000000    0.009473  0.009473  0.009473  0.009473  0.009473
       2.000000  5.000000    0.009473  0.009473  0.009473  0.009473  0.009473
       5.000000  10.000000   0.009011  0.009011  0.009011  0.009011  0.009011
       10.000000 15.000000   0.009011  0.009011  0.009011  0.009011  0.009011
       15.000000 20.000000   0.008569  0.008569  0.008569  0.008569  0.008569
       20.000000 25.000000   0.008569  0.008569  0.008569  0.008569  0.008569
       25.000000 30.000000   0.008569  0.008569  0.008569  0.008569  0.008569
       30.000000 35.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       35.000000 40.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       40.000000 45.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       45.000000 50.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       50.000000 55.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       55.000000 60.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       60.000000 65.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       65.000000 70.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       70.000000 75.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       75.000000 80.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       80.000000 85.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       85.000000 90.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       90.000000 95.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       95.000000 125.000000  0.008565  0.008565  0.008565  0.008565  0.008565
Male   0.000000  0.019178    0.009480  0.009480  0.009480  0.009480  0.009480
       0.019178  0.076712    0.009480  0.009480  0.009480  0.009480  0.009480
       0.076712  0.500000    0.009480  0.009480  0.009480  0.009480  0.009480
       0.500000  1.000000    0.009480  0.009480  0.009480  0.009480  0.009480
       1.000000  2.000000    0.009480  0.009480  0.009480  0.009480  0.009480
       2.000000  5.000000    0.009480  0.009480  0.009480  0.009480  0.009480
       5.000000  10.000000   0.009013  0.009013  0.009013  0.009013  0.009013
       10.000000 15.000000   0.009013  0.009013  0.009013  0.009013  0.009013
       15.000000 20.000000   0.008567  0.008567  0.008567  0.008567  0.008567
       20.000000 25.000000   0.008567  0.008567  0.008567  0.008567  0.008567
       25.000000 30.000000   0.008567  0.008567  0.008567  0.008567  0.008567
       30.000000 35.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       35.000000 40.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       40.000000 45.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       45.000000 50.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       50.000000 55.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       55.000000 60.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       60.000000 65.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       65.000000 70.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       70.000000 75.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       75.000000 80.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       80.000000 85.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       85.000000 90.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       90.000000 95.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       95.000000 125.000000  0.008562  0.008562  0.008562  0.008562  0.008562

                              draw_10   draw_11   draw_12   draw_13   draw_14  \
sex    age_start age_end
Female 0.000000  0.019178    0.009473  0.009473  0.009473  0.009473  0.009473
       0.019178  0.076712    0.009473  0.009473  0.009473  0.009473  0.009473
       0.076712  0.500000    0.009473  0.009473  0.009473  0.009473  0.009473
       0.500000  1.000000    0.009473  0.009473  0.009473  0.009473  0.009473
       1.000000  2.000000    0.009473  0.009473  0.009473  0.009473  0.009473
       2.000000  5.000000    0.009473  0.009473  0.009473  0.009473  0.009473
       5.000000  10.000000   0.009011  0.009011  0.009011  0.009011  0.009011
       10.000000 15.000000   0.009011  0.009011  0.009011  0.009011  0.009011
       15.000000 20.000000   0.008569  0.008569  0.008569  0.008569  0.008569
       20.000000 25.000000   0.008569  0.008569  0.008569  0.008569  0.008569
       25.000000 30.000000   0.008569  0.008569  0.008569  0.008569  0.008569
       30.000000 35.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       35.000000 40.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       40.000000 45.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       45.000000 50.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       50.000000 55.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       55.000000 60.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       60.000000 65.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       65.000000 70.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       70.000000 75.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       75.000000 80.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       80.000000 85.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       85.000000 90.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       90.000000 95.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       95.000000 125.000000  0.008565  0.008565  0.008565  0.008565  0.008565
Male   0.000000  0.019178    0.009480  0.009480  0.009480  0.009480  0.009480
       0.019178  0.076712    0.009480  0.009480  0.009480  0.009480  0.009480
       0.076712  0.500000    0.009480  0.009480  0.009480  0.009480  0.009480
       0.500000  1.000000    0.009480  0.009480  0.009480  0.009480  0.009480
       1.000000  2.000000    0.009480  0.009480  0.009480  0.009480  0.009480
       2.000000  5.000000    0.009480  0.009480  0.009480  0.009480  0.009480
       5.000000  10.000000   0.009013  0.009013  0.009013  0.009013  0.009013
       10.000000 15.000000   0.009013  0.009013  0.009013  0.009013  0.009013
       15.000000 20.000000   0.008567  0.008567  0.008567  0.008567  0.008567
       20.000000 25.000000   0.008567  0.008567  0.008567  0.008567  0.008567
       25.000000 30.000000   0.008567  0.008567  0.008567  0.008567  0.008567
       30.000000 35.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       35.000000 40.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       40.000000 45.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       45.000000 50.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       50.000000 55.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       55.000000 60.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       60.000000 65.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       65.000000 70.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       70.000000 75.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       75.000000 80.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       80.000000 85.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       85.000000 90.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       90.000000 95.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       95.000000 125.000000  0.008562  0.008562  0.008562  0.008562  0.008562

                             ...  draw_485  draw_486  draw_487  draw_488  \
sex    age_start age_end     ...
Female 0.000000  0.019178    ...  0.009473  0.009473  0.009473  0.009473
       0.019178  0.076712    ...  0.009473  0.009473  0.009473  0.009473
       0.076712  0.500000    ...  0.009473  0.009473  0.009473  0.009473
       0.500000  1.000000    ...  0.009473  0.009473  0.009473  0.009473
       1.000000  2.000000    ...  0.009473  0.009473  0.009473  0.009473
       2.000000  5.000000    ...  0.009473  0.009473  0.009473  0.009473
       5.000000  10.000000   ...  0.009011  0.009011  0.009011  0.009011
       10.000000 15.000000   ...  0.009011  0.009011  0.009011  0.009011
       15.000000 20.000000   ...  0.008569  0.008569  0.008569  0.008569
       20.000000 25.000000   ...  0.008569  0.008569  0.008569  0.008569
       25.000000 30.000000   ...  0.008569  0.008569  0.008569  0.008569
       30.000000 35.000000   ...  0.008563  0.008563  0.008563  0.008563
       35.000000 40.000000   ...  0.008563  0.008563  0.008563  0.008563
       40.000000 45.000000   ...  0.008563  0.008563  0.008563  0.008563
       45.000000 50.000000   ...  0.008563  0.008563  0.008563  0.008563
       50.000000 55.000000   ...  0.008565  0.008565  0.008565  0.008565
       55.000000 60.000000   ...  0.008565  0.008565  0.008565  0.008565
       60.000000 65.000000   ...  0.008565  0.008565  0.008565  0.008565
       65.000000 70.000000   ...  0.008565  0.008565  0.008565  0.008565
       70.000000 75.000000   ...  0.008565  0.008565  0.008565  0.008565
       75.000000 80.000000   ...  0.008565  0.008565  0.008565  0.008565
       80.000000 85.000000   ...  0.008565  0.008565  0.008565  0.008565
       85.000000 90.000000   ...  0.008565  0.008565  0.008565  0.008565
       90.000000 95.000000   ...  0.008565  0.008565  0.008565  0.008565
       95.000000 125.000000  ...  0.008565  0.008565  0.008565  0.008565
Male   0.000000  0.019178    ...  0.009480  0.009480  0.009480  0.009480
       0.019178  0.076712    ...  0.009480  0.009480  0.009480  0.009480
       0.076712  0.500000    ...  0.009480  0.009480  0.009480  0.009480
       0.500000  1.000000    ...  0.009480  0.009480  0.009480  0.009480
       1.000000  2.000000    ...  0.009480  0.009480  0.009480  0.009480
       2.000000  5.000000    ...  0.009480  0.009480  0.009480  0.009480
       5.000000  10.000000   ...  0.009013  0.009013  0.009013  0.009013
       10.000000 15.000000   ...  0.009013  0.009013  0.009013  0.009013
       15.000000 20.000000   ...  0.008567  0.008567  0.008567  0.008567
       20.000000 25.000000   ...  0.008567  0.008567  0.008567  0.008567
       25.000000 30.000000   ...  0.008567  0.008567  0.008567  0.008567
       30.000000 35.000000   ...  0.008563  0.008563  0.008563  0.008563
       35.000000 40.000000   ...  0.008563  0.008563  0.008563  0.008563
       40.000000 45.000000   ...  0.008563  0.008563  0.008563  0.008563
       45.000000 50.000000   ...  0.008563  0.008563  0.008563  0.008563
       50.000000 55.000000   ...  0.008562  0.008562  0.008562  0.008562
       55.000000 60.000000   ...  0.008562  0.008562  0.008562  0.008562
       60.000000 65.000000   ...  0.008562  0.008562  0.008562  0.008562
       65.000000 70.000000   ...  0.008562  0.008562  0.008562  0.008562
       70.000000 75.000000   ...  0.008562  0.008562  0.008562  0.008562
       75.000000 80.000000   ...  0.008562  0.008562  0.008562  0.008562
       80.000000 85.000000   ...  0.008562  0.008562  0.008562  0.008562
       85.000000 90.000000   ...  0.008562  0.008562  0.008562  0.008562
       90.000000 95.000000   ...  0.008562  0.008562  0.008562  0.008562
       95.000000 125.000000  ...  0.008562  0.008562  0.008562  0.008562

                             draw_489  draw_490  draw_491  draw_492  draw_493  \
sex    age_start age_end
Female 0.000000  0.019178    0.009473  0.009473  0.009473  0.009473  0.009473
       0.019178  0.076712    0.009473  0.009473  0.009473  0.009473  0.009473
       0.076712  0.500000    0.009473  0.009473  0.009473  0.009473  0.009473
       0.500000  1.000000    0.009473  0.009473  0.009473  0.009473  0.009473
       1.000000  2.000000    0.009473  0.009473  0.009473  0.009473  0.009473
       2.000000  5.000000    0.009473  0.009473  0.009473  0.009473  0.009473
       5.000000  10.000000   0.009011  0.009011  0.009011  0.009011  0.009011
       10.000000 15.000000   0.009011  0.009011  0.009011  0.009011  0.009011
       15.000000 20.000000   0.008569  0.008569  0.008569  0.008569  0.008569
       20.000000 25.000000   0.008569  0.008569  0.008569  0.008569  0.008569
       25.000000 30.000000   0.008569  0.008569  0.008569  0.008569  0.008569
       30.000000 35.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       35.000000 40.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       40.000000 45.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       45.000000 50.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       50.000000 55.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       55.000000 60.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       60.000000 65.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       65.000000 70.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       70.000000 75.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       75.000000 80.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       80.000000 85.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       85.000000 90.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       90.000000 95.000000   0.008565  0.008565  0.008565  0.008565  0.008565
       95.000000 125.000000  0.008565  0.008565  0.008565  0.008565  0.008565
Male   0.000000  0.019178    0.009480  0.009480  0.009480  0.009480  0.009480
       0.019178  0.076712    0.009480  0.009480  0.009480  0.009480  0.009480
       0.076712  0.500000    0.009480  0.009480  0.009480  0.009480  0.009480
       0.500000  1.000000    0.009480  0.009480  0.009480  0.009480  0.009480
       1.000000  2.000000    0.009480  0.009480  0.009480  0.009480  0.009480
       2.000000  5.000000    0.009480  0.009480  0.009480  0.009480  0.009480
       5.000000  10.000000   0.009013  0.009013  0.009013  0.009013  0.009013
       10.000000 15.000000   0.009013  0.009013  0.009013  0.009013  0.009013
       15.000000 20.000000   0.008567  0.008567  0.008567  0.008567  0.008567
       20.000000 25.000000   0.008567  0.008567  0.008567  0.008567  0.008567
       25.000000 30.000000   0.008567  0.008567  0.008567  0.008567  0.008567
       30.000000 35.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       35.000000 40.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       40.000000 45.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       45.000000 50.000000   0.008563  0.008563  0.008563  0.008563  0.008563
       50.000000 55.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       55.000000 60.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       60.000000 65.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       65.000000 70.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       70.000000 75.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       75.000000 80.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       80.000000 85.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       85.000000 90.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       90.000000 95.000000   0.008562  0.008562  0.008562  0.008562  0.008562
       95.000000 125.000000  0.008562  0.008562  0.008562  0.008562  0.008562

                             draw_494  draw_495  draw_496  draw_497  draw_498  \
sex    age_start age_end
Female 0.000000  0.019178    0.009473  0.009473  0.009473  0.009473  0.009473

In [30]:
hgb_mean = hgb_mean * scale_factor

In [31]:
assert np.allclose(
    hgb_mean.mul(wealth_quintile_probabilities, axis=0).groupby([c for c in hgb_mean.index.names if c != 'wealth_quintile']).sum(),
    pre_disparity_groups,
)

In [32]:
counterfactual_hgb_mean = hgb_mean.add(delta_effective_coverage * fortification_hemoglobin_mean_difference, axis=0)
counterfactual_hgb_mean

                                                 draw_0      draw_1  \
sex    age_start age_end    wealth_quintile
Female 0.0       0.019178   fourth           143.365729  143.514997
                            highest          145.168195  145.319174
                            lowest           139.080694  139.225614
                            middle           141.474880  141.622236
                            second           141.238458  141.385618
...                                                 ...         ...
Male   95.0      125.000000 fourth           102.577358  105.552235
                            highest          103.772182  106.774749
                            lowest           100.398621  103.315474
                            middle           101.782771  104.736810
                            second           101.379407  104.323790

                                                 draw_2      draw_3  \
sex    age_start age_end    wealth_quintile
Female 0.0       0.019178   fourth           145.408498  144.852923
                            highest          147.234377  146.672434
                            lowest           141.063962  140.524570
                            middle           143.491478  142.943021
                            second           143.252386  142.704655
...                                                 ...         ...
Male   95.0      125.000000 fourth           104.745345  104.606823
                            highest          105.960348  105.820537
                            lowest           102.524322  102.388502
                            middle           103.935572  103.798020
                            second           103.525170  103.388069

                                                 draw_4      draw_5  \
sex    age_start age_end    wealth_quintile
Female 0.0       0.019178   fourth           143.544929  144.180258
                            highest          145.349448  145.992059
                            lowest           139.254674  139.871497
                            middle           141.651784  142.278973
                            second           141.415128  142.041486
...                                                 ...         ...
Male   95.0      125.000000 fourth           107.105396  105.350549
                            highest          108.342366  106.571185
                            lowest           104.838341  103.117722
                            middle           106.279091  104.536536
                            second           105.861029  104.124171

                                                 draw_6      draw_7  \
sex    age_start age_end    wealth_quintile
Female 0.0       0.019178   fourth           143.280236  145.251397
                            highest          145.081722  147.075475
                            lowest           138.997691  140.911437
                            middle           141.390483  143.336390
                            second           141.154172  143.097503
...                                                 ...         ...
Male   95.0      125.000000 fourth           105.349775  105.627442
                            highest          106.570404  106.850655
                            lowest           103.116963  103.389214
                            middle           104.535768  104.811489
                            second           104.123405  104.398225

                                                 draw_8      draw_9  \
sex    age_start age_end    wealth_quintile
Female 0.0       0.019178   fourth           143.730536  145.529608
                            highest          145.537183  147.356875
                            lowest           139.434874  141.181545
                            middle           141.835013  143.611037
                            second           141.598114  143.371787
...                                                 ...         ...
Male   95.0      125.000000 fourth           106.541069  105.445862
                            highest          107.772786  106.667385
                            lowest           104.285021  103.211175
                            middle           105.718717  104.631181
                            second           105.302487  104.218506

                                                draw_10     draw_11  \
sex    age_start age_end    wealth_quintile
Female 0.0       0.019178   fourth           144.036061  144.246332
                            highest          145.846209  146.058891
                            lowest           139.731500  139.935647
                            middle           142.136624  142.344201
                            second           141.899325  142.106628
...                                                 ...         ...
Male   95.0      125.000000 fourth           105.630628  104.944613
                            highest          106.853871  106.161471
                            lowest           103.392338  102.719703
                            middle           104.814653  104.133443
                            second           104.401378  103.722396

                                                draw_12     draw_13  \
sex    age_start age_end    wealth_quintile
Female 0.0       0.019178   fourth           142.955708  143.877498
                            highest          144.753475  145.685829
                            lowest           138.682615  139.577556
                            middle           141.070112  141.980092
                            second           140.834226  141.743001
...                                                 ...         ...
Male   95.0      125.000000 fourth           107.367263  102.234300
                            highest          108.606671  103.425931
                            lowest           105.095100  100.062254
                            middle           106.539123  101.442116
                            second           106.120212  101.039866

                                                draw_14  ...    draw_485  \
sex    age_start age_end    wealth_quintile              ...
Female 0.0       0.019178   fourth           144.568166  ...  143.870730
                            highest          146.384413  ...  145.678984
                            lowest           140.248106  ...  139.570985
                            middle           142.661912  ...  141.973412
                            second           142.423918  ...  141.736329
...                                                 ...  ...         ...
Male   95.0      125.000000 fourth           105.565720  ...  107.185592
                            highest          106.788359  ...  108.423309
                            lowest           103.328696  ...  104.916973
                            middle           104.750200  ...  106.358725
                            second           104.337136  ...  105.940403

                                               draw_486    draw_487  \
sex    age_start age_end    wealth_quintile
Female 0.0       0.019178   fourth           143.960703  142.956263
                            highest          145.769988  144.754035
                            lowest           139.658337  138.683154
                            middle           142.062232  141.070660
                            second           141.825032  140.834772
...                                                 ...         ...
Male   95.0      125.000000 fourth           106.774843  107.193884
                            highest          108.008736  108.431678
                            lowest           104.514235  104.925103
                            middle           105.950853  106.366959
                            second           105.533864  105.948610

                                               draw_488    draw_489  \
sex    age_start age_end    wealth_quintile
Female 0.0       0.019178   fourth           143.690803  143.593080
                            highest          145.496994  145.398152
                            lowest           139.396299  139.301423
                            middle           141.795789  141.699319
                            second           141.558942  141.462599
...                                                 ...         ...
Male   95.0      125.000000 fourth           104.612105  105.130533
                            highest          105.825868  106.349121
                            lowest           102.393681  102.901997
                            middle           103.803265  104.318061
                            second           103.393296  103.906410

                                               draw_490    draw_491  \
sex    age_start age_end    wealth_quintile
Female 0.0       0.019178   fourth           142.791152  143.100497
                            highest          144.587032  144.899923
                            lowest           138.522852  138.823187
                            middle           140.907664  141.213046
                            second           140.671993  140.976970
...                                                 ...         ...
Male   95.0      125.000000 fourth           103.111824  105.035521
                            highest          104.311622  106.253225
                            lowest           100.922662  102.808838
                            middle           102.313493  104.223715
                            second           101.908394  103.812372

                                               draw_492    draw_493  \
sex    age_start age_end    wealth_quintile
Female 0.0       0.019178   fourth           144.858721  142.892056
                            highest          146.678299  144.689093
                            lowest           140.530199  138.620817
                            middle           142.948745  141.007275
                            second           142.710371  140.771472
...                                                 ...         ...
Male   95.0      125.000000 fourth           104.455400  102.998676
                            highest          105.667705  104.197421
                            lowest           102.240033  100.811721
                            middle           103.647658  102.201138
                            second           103.238198  101.796406

                                               draw_494    draw_495  \
sex    age_start age_end    wealth_quintile
Female 0.0       0.019178   fourth           144.042307  142.898844
                            highest          145.852527  144.695959
                            lowest           139.737565  138.627407
                            middle           142.142790  141.013977
                            second           141.905484  140.778164
...                                                 ...         ...
Male   95.0      125.000000 fourth           105.325863  103.471959
                            highest          106.546269  104.675110
                            lowest           103.093517  101.275773
                            middle           104.512023  102.671106
                            second           104.099737  102.264838

                                               draw_496    draw_497  \
sex    age_start age_end    wealth_quintile
Female 0.0       0.019178   fourth           144.233617  144.788250
                            highest          146.046030  146.607020
                            lowest           139.923302  140.461780
                            middle           142.331650  142.879177
                            second           142.094093  142.640895
...                                                 ...         ...
Male   95.0      125.000000 fourth           103.758503  103.074810
                            highest          104.964321  104.274264
                            lowest           101.556728  100.886370
                            middle           102.955643  102.276738
                            second           102.548445  101.871760

                                               draw_498    draw_499
sex    age_start age_end    wealth_quintile
Female 0.0       0.019178   fourth           142.701055  144.819509
                            highest          144.495903  146.638637
                            lowest           138.435379  140.492129
                            middle           140.818721  142.910035
                            second           140.583168  142.671713
...                                                 ...         ...
Male   95.0      125.000000 fourth           104.403729  104.469642
                            highest          105.615552  105.682079
                            lowest           102.189369  102.253997
                            middle           103.596348  103.661800
                            second           103.187056  103.252294

[250 rows x 500 columns]

In [33]:
hgb_mean.columns.name = "draw"
hgb_mean = hgb_mean.stack().rename("mean").reset_index()

In [34]:
counterfactual_hgb_mean.columns.name = "draw"
counterfactual_hgb_mean = counterfactual_hgb_mean.stack().rename("mean").reset_index()

In [35]:
location_id = utility_data.get_location_id(location.title())
hgb_sd = gbd.get_modelable_entity_draws(me_id=me_ids["hemoglobin_sd"], location_id=location_id, year_id=2021)
hgb_sd = reshape_to_vivarium_format(hgb_sd, location.title()).droplevel(["year_start", "year_end", "measure_id", "metric_id", "model_version_id", "modelable_entity_id"])[DRAWS].copy()
hgb_sd

                                draw_0     draw_1     draw_2     draw_3  \
sex    age_start age_end
Female 0.000000  0.019178    11.056572  15.419496  12.937057  14.108613
       0.019178  0.076712    18.143206  17.170122  18.638921  21.675732
       0.076712  0.500000    11.519491  14.027332  13.723109  14.417308
       0.500000  1.000000    13.756756  14.711771  13.648304  13.187534
       1.000000  2.000000    14.325459  16.843282  16.709555  15.864417
       2.000000  5.000000    16.864334  16.488876  16.574293  16.946859
       5.000000  10.000000   14.225182  14.168108  12.948419  12.913613
       10.000000 15.000000   13.709243  13.495770  11.389442  15.925441
       15.000000 20.000000   13.561928  15.733414  13.751380  15.264811
       20.000000 25.000000   17.877538  15.796879  16.381351  14.863829
       25.000000 30.000000   16.815011  16.994822  15.316674  15.690873
       30.000000 35.000000   16.621743  15.047877  16.867962  15.976469
       35.000000 40.000000   14.396311  15.728416  16.175030  15.550384
       40.000000 45.000000   16.718798  15.378787  17.134685  16.801107
       45.000000 50.000000   17.032453  15.404674  16.578969  18.835821
       50.000000 55.000000   15.717267  15.389592  14.263427  15.514466
       55.000000 60.000000   12.958764  14.368135  16.001020  15.681634
       60.000000 65.000000   14.203046  14.792499  14.244354  14.557884
       65.000000 70.000000   12.468907  15.525386  14.499738  14.166835
       70.000000 75.000000   16.333369  16.631346  16.833404  15.235709
       75.000000 80.000000   22.254054  24.403128  20.115561  23.155481
       80.000000 85.000000   24.100034  24.539483  24.989374  26.511926
       85.000000 90.000000   36.306586  33.251947  37.348512  32.257547
       90.000000 95.000000   38.914197  41.875007  39.460541  40.321736
       95.000000 125.000000  38.019009  39.773450  39.091306  40.811093
Male   0.000000  0.019178     7.610899   6.575979   7.453095   6.250333
       0.019178  0.076712    16.977021  18.465539  16.510252  21.378982
       0.076712  0.500000     9.721262  12.425339  14.429252  13.617889
       0.500000  1.000000    14.652405  12.306607  13.147011  14.384103
       1.000000  2.000000    13.806197  12.868476  13.713812  14.321067
       2.000000  5.000000    14.572863  13.560881  13.249884  13.447389
       5.000000  10.000000   12.573757   7.057425   9.593659   9.916708
       10.000000 15.000000   11.260913  12.769954   9.948129  11.258765
       15.000000 20.000000   11.470756  15.361375  13.757213  15.839422
       20.000000 25.000000   16.818841  15.146760  14.406426  15.531786
       25.000000 30.000000   14.325444  14.905894  14.724530  12.324918
       30.000000 35.000000   16.155267  16.364407  15.748614  15.395269
       35.000000 40.000000   17.000588  14.962367  16.688472  15.727331
       40.000000 45.000000   16.215645  16.148306  15.713011  15.286601
       45.000000 50.000000   16.866309  17.598236  14.838259  17.183189
       50.000000 55.000000   16.298999  17.308050  17.941748  18.389619
       55.000000 60.000000   19.614086  19.237907  18.023727  18.054980
       60.000000 65.000000   17.017625  19.435720  17.143083  16.953227
       65.000000 70.000000   17.246434  17.477513  19.252672  18.443892
       70.000000 75.000000   18.666848  17.255199  17.201503  17.486489
       75.000000 80.000000   19.081333  16.399954  20.715293  21.595394
       80.000000 85.000000   21.153456  22.487688  23.106116  22.546762
       85.000000 90.000000   23.662495  24.946716  26.106795  23.226613
       90.000000 95.000000   27.527042  30.766501  28.349045  28.340500
       95.000000 125.000000  39.559564  39.138167  37.453939  35.318036

                                draw_4     draw_5     draw_6     draw_7  \
sex    age_start age_end
Female 0.000000  0.019178    13.020095  12.577809  17.754828  13.099648
       0.019178  0.076712    17.362276  18.653702  20.182212  17.627105
       0.076712  0.500000    13.217808  13.026038  14.444848  13.017687
       0.500000  1.000000    13.376081  14.524967  13.737699  14.473522
       1.000000  2.000000    15.124064  14.493894  16.528408  15.202250
       2.000000  5.000000    16.571890  17.305266  14.511235  17.740968
       5.000000  10.000000   14.731795  14.601781  12.012659  11.527454
       10.000000 15.000000   16.126926  12.631853  16.717010  14.298076
       15.000000 20.000000   14.127997  14.013979  15.329002  15.397312
       20.000000 25.000000   14.447182  14.735706  15.662016  18.748018
       25.000000 30.000000   17.736549  17.074363  19.213781  17.147339
       30.000000 35.000000   17.430898  15.631113  16.463113  18.105185
       35.000000 40.000000   16.496092  16.065123  15.017911  15.369356
       40.000000 45.000000   16.166835  17.622009  14.428781  14.963834
       45.000000 50.000000   16.780592  15.737449  16.435845  16.031816
       50.000000 55.000000   15.106636  14.267999  12.426291  15.664131
       55.000000 60.000000   12.257894  12.690514  15.910059  13.956875
       60.000000 65.000000   16.303096  13.536360  15.255340  14.497954
       65.000000 70.000000   16.799314  15.882442  14.829333  14.335778
       70.000000 75.000000   17.538595  17.938588  16.735632  17.604786
       75.000000 80.000000   21.808174  19.783694  20.679099  24.045183
       80.000000 85.000000   25.140651  24.068674  25.506386  26.024679
       85.000000 90.000000   35.130583  35.850669  34.987728  35.460821
       90.000000 95.000000   37.414906  39.360273  40.628148  43.794461
       95.000000 125.000000  40.515326  36.987378  40.861064  38.973924
Male   0.000000  0.019178     7.920491   6.340217   6.466164   6.139428
       0.019178  0.076712    15.861589  18.344707  14.142126  13.631602
       0.076712  0.500000     9.980601  12.249892  14.091311  13.694185
       0.500000  1.000000    13.694239  15.034635  12.720333  14.333813
       1.000000  2.000000    15.868509  13.837486  14.719694  14.593099
       2.000000  5.000000    12.019735  14.006495  11.768375  15.466440
       5.000000  10.000000    7.976543   8.718254   9.152801   9.313380
       10.000000 15.000000   11.137392  11.149098  12.718914  10.055498
       15.000000 20.000000   14.880081  11.879994  13.589567  14.474176
       20.000000 25.000000   15.666944  16.268696  16.196663  16.445528
       25.000000 30.000000   15.314376  15.113747  15.023463  15.393740
       30.000000 35.000000   16.038528  16.942015  15.929371  16.101042
       35.000000 40.000000   18.088510  16.125549  15.799825  17.127050
       40.000000 45.000000   15.457510  14.181011  16.366586  16.586916
       45.000000 50.000000   15.255021  16.513771  17.164343  16.774604
       50.000000 55.000000   16.817437  16.554355  18.656778  18.894118
       55.000000 60.000000   16.523410  16.104365  17.987870  17.062202
       60.000000 65.000000   17.860338  17.714065  17.170993  16.814463
       65.000000 70.000000   18.305607  18.143936  15.547391  18.148081
       70.000000 75.000000   17.297645  17.895579  18.040125  18.033667
       75.000000 80.000000   18.175629  16.791251  20.236707  18.821965
       80.000000 85.000000   17.955075  23.479958  23.470485  20.610145
       85.000000 90.000000   23.165737  25.619051  28.887955  26.441548
       90.000000 95.000000   30.220151  29.927618  32.666743  34.961008
       95.000000 125.000000  32.753194  35.956872  34.403757  37.928030

                                draw_8     draw_9    draw_10    draw_11  \
sex    age_start age_end
Female 0.000000  0.019178    11.912721  13.534418  15.250904  13.089309
       0.019178  0.076712    18.478847  19.942071  18.480448  26.123070
       0.076712  0.500000    15.242591  14.713188  13.551734  12.921939
       0.500000  1.000000    14.511934  14.818950  13.653111  13.482305
       1.000000  2.000000    14.221149  15.209534  14.536429  15.205116
       2.000000  5.000000    16.619492  16.571673  16.856932  17.195478
       5.000000  10.000000   10.846907  13.933340  11.788947  13.362020
       10.000000 15.000000   15.839117  15.625613  14.883322  12.584534
       15.000000 20.000000   16.466307  11.996041  16.521571  14.357632
       20.000000 25.000000   16.600911  15.385754  16.130704  15.309814
       25.000000 30.000000   16.323214  16.294265  16.306756  17.068850
       30.000000 35.000000   14.995013  16.883843  15.766927  16.766155
       35.000000 40.000000   17.468354  16.088688  14.604199  13.174420
       40.000000 45.000000   14.368247  17.720018  15.223568  16.544181
       45.000000 50.000000   18.936978  16.419509  15.305525  15.575902
       50.000000 55.000000   15.024812  15.138730  17.147760  13.221135
       55.000000 60.000000   16.379446  15.497368  15.231634  14.880113
       60.000000 65.000000   15.875441  13.848493  15.479695  14.029023
       65.000000 70.000000   16.793297  16.239228  15.754097  12.131503
       70.000000 75.000000   17.094404  16.380356  16.166625  16.308952
       75.000000 80.000000   20.913422  17.769351  21.553431  20.721305
       80.000000 85.000000   22.276074  22.829394  27.261264  25.864497
       85.000000 90.000000   32.095693  36.082627  32.560548  33.853125
       90.000000 95.000000   40.087374  42.096789  41.942134  44.235362
       95.000000 125.000000  39.797842  42.849962  39.484918  41.161548
Male   0.000000  0.019178     5.691987   7.091346   6.402940   6.747872
       0.019178  0.076712    12.477566  17.467950  17.889057  19.905498
       0.076712  0.500000    10.599262  11.966199  13.746249  13.087760
       0.500000  1.000000    14.068139  13.625568  13.935288  15.186487
       1.000000  2.000000    15.587080  13.312045  15.559659  14.269923
       2.000000  5.000000    11.309049  12.260267  12.971750  13.176335
       5.000000  10.000000    9.601694   8.174270   7.913442   8.310538
       10.000000 15.000000   16.874654  10.429230  11.770886  11.021590
       15.000000 20.000000   13.956274  14.539298  16.829695  13.307860
       20.000000 25.000000   15.154534  15.671597  16.276785  14.892207
       25.000000 30.000000   14.417136  13.955752  17.038566  15.955352
       30.000000 35.000000   16.065982  16.306538  14.049113  16.552980
       35.000000 40.000000   17.451215  15.057925  16.391333  19.301976
       40.000000 45.000000   15.542826  15.803241  17.272135  15.251573
       45.000000 50.000000   14.214086  16.454712  16.517748  17.999063
       50.000000 55.000000   16.011912  17.637154  17.660521  16.628725
       55.000000 60.000000   19.284436  18.687474  18.557785  16.600751
       60.000000 65.000000   15.925692  18.227418  16.585964  18.511906
       65.000000 70.000000   17.757204  18.786740  18.149067  17.558208
       70.000000 75.000000   18.977417  19.703393  21.511518  18.993971
       75.000000 80.000000   17.311613  16.313725  18.447740  18.502688
       80.000000 85.000000   23.653412  20.728578  22.162447  24.969668
       85.000000 90.000000   25.162466  21.455901  26.402712  24.129777
       90.000000 95.000000   28.784333  32.471610  32.448238  27.340270
       95.000000 125.000000  34.986669  36.813595  36.203463  41.761803

                               draw_12    draw_13    draw_14  ...   draw_485  \
sex    age_start age_end                                      ...
Female 0.000000  0.019178    11.698468  13.944615  12.968311  ...  12.172186
       0.019178  0.076712    19.292006  17.894884  18.536767  ...  18.854338
       0.076712  0.500000    14.771674  12.216773  13.723598  ...  14.221293
       0.500000  1.000000    13.071927  10.878399  13.538518  ...  12.313299
       1.000000  2.000000    13.076259  13.863574  15.013913  ...  15.543186
       2.000000  5.000000    16.165612  17.041200  15.445089  ...  15.799757
       5.000000  10.000000   12.541725  12.660770  11.161442  ...  13.975803
       10.000000 15.000000   13.628142  14.160368  16.822192  ...  13.992595
       15.000000 20.000000   15.003546  15.873917  12.730538  ...  14.500338
       20.000000 25.000000   14.185374  16.320625  15.405858  ...  14.864683
       25.000000 30.000000   17.280868  15.695182  16.875562  ...  15.915891
       30.000000 35.000000   15.087403  14.452967  17.114253  ...  16.399671
       35.000000 40.000000   17.541935  14.989713  16.061756  ...  15.271765
       40.000000 45.000000   17.344403  16.536191  15.619087  ...  18.096751
       45.000000 50.000000   16.515168  19.294747  18.095457  ...  14.838483
       50.000000 55.000000   13.645099  13.770616  15.815230  ...  13.926071
       55.000000 60.000000   14.580799  17.620255  12.134836  ...  15.390221
       60.000000 65.000000   14.628691  17.812089  14.921815  ...  15.178644
       65.000000 70.000000   15.435082  15.634770  14.391361  ...  15.792841
       70.000000 75.000000   18.955998  16.231075  18.404108  ...  17.322680
       75.000000 80.000000   21.298369  19.615355  23.021914  ...  20.844932
       80.000000 85.000000   24.617628  23.773455  27.731977  ...  24.909039
       85.000000 90.000000   38.626604  32.079645  35.037743  ...  36.765097
       90.000000 95.000000   39.684359  38.818593  42.094596  ...  42.935176
       95.000000 125.000000  41.840806  42.270201  39.586573  ...  38.142674
Male   0.000000  0.019178     6.791699   5.809352   6.938802  ...   7.240774
       0.019178  0.076712    18.629369  13.139183  17.540888  ...  12.878999
       0.076712  0.500000    13.139513  14.568086  13.524392  ...  13.267248
       0.500000  1.000000    14.922199  12.271635  15.927740  ...  14.677553
       1.000000  2.000000    12.273306  15.013445  15.201227  ...  13.813997
       2.000000  5.000000    12.671689  11.474396  13.228545  ...  11.930761
       5.000000  10.000000    9.351394  11.582570   8.347038  ...   7.081553
       10.000000 15.000000   13.049290   9.595911  11.598644  ...  13.622000
       15.000000 20.000000   14.958834  14.097620  15.084565  ...  13.284964
       20.000000 25.000000   15.265481  15.161863  16.416929  ...  15.418041
       25.000000 30.000000   15.007560  14.227289  14.457016  ...  16.152938
       30.000000 35.000000   15.317437  15.622383  15.157442  ...  15.895173
       35.000000 40.000000   15.768175  15.865815  14.615222  ...  16.684203
       40.000000 45.000000   16.167001  15.923844  16.458809  ...  15.404894
       45.000000 50.000000   16.635981  14.962696  15.807011  ...  17.945107
       50.000000 55.000000   17.256656  17.275432  17.505294  ...  15.712603
       55.000000 60.000000   18.077812  18.294788  14.342322  ...  18.811305
       60.000000 65.000000   16.114486  17.200815  17.327638  ...  17.371669
       65.000000 70.000000   18.541200  20.968104  18.418815  ...  20.481004
       70.000000 75.000000   15.247137  21.028243  19.649548  ...  16.359186
       75.000000 80.000000   20.566355  19.880885  21.086847  ...  16.258103
       80.000000 85.000000   22.174757  22.691070  20.029234  ...  23.457237
       85.000000 90.000000   22.855954  26.903121  26.560958  ...  26.493087
       90.000000 95.000000   31.174407  28.655398  29.190495  ...  28.939243
       95.000000 125.000000  30.437841  35.369767  35.180846  ...  36.441043

                              draw_486   draw_487   draw_488   draw_489  \
sex    age_start age_end
Female 0.000000  0.019178    12.327443  10.713326  15.001014  13.824811
       0.019178  0.076712    19.857466  19.241883  19.544912  20.609662
       0.076712  0.500000    14.234269  15.657114  14.792087  13.905731
       0.500000  1.000000    13.716565  14.003392  14.738192  13.973929
       1.000000  2.000000    14.834818  13.696490  15.820430  15.176029
       2.000000  5.000000    17.022416  15.874117  14.704499  17.482008
       5.000000  10.000000   14.133345  13.558921  12.259638  12.439979
       10.000000 15.000000   13.672172  12.610043  16.154006  14.075381
       15.000000 20.000000   14.144277  14.197223  15.725285  14.681504
       20.000000 25.000000   16.767909  13.248012  16.339642  15.131863
       25.000000 30.000000   17.669303  16.738076  15.075536  17.823539
       30.000000 35.000000   14.426570  16.071797  16.806593  18.935009
       35.000000 40.000000   15.383412  14.520184  13.418833  17.281017
       40.000000 45.000000   16.387465  16.917742  17.062296  16.072295
       45.000000 50.000000   14.902757  16.776988  17.468847  16.403468
       50.000000 55.000000   14.592241  13.799966  14.973280  16.050551
       55.000000 60.000000   16.368539  16.094332  15.804400  15.078729
       60.000000 65.000000   15.262867  15.195140  17.074264  14.658112
       65.000000 70.000000   13.337074  15.208650  16.585585  13.920420
       70.000000 75.000000   16.668697  17.246553  17.524653  17.260109
       75.000000 80.000000   25.163023  19.642040  19.286091  23.055177
       80.000000 85.000000   27.352358  25.604258  25.462338  26.159587
       85.000000 90.000000   32.754093  34.149292  35.032011  28.472815
       90.000000 95.000000   43.112264  40.804636  38.087450  38.982986
       95.000000 125.000000  43.545351  40.428324  39.540398  38.730121
Male   0.000000  0.019178     8.311788   7.393801   6.218421   6.421989
       0.019178  0.076712    17.382217  18.975632  18.312220  18.833729
       0.076712  0.500000    14.129835  12.905281  12.880018  13.073209
       0.500000  1.000000    15.341112  16.089164  14.155589  15.122908
       1.000000  2.000000    13.813008  13.683558  14.332377  13.342373
       2.000000  5.000000    12.703132  11.421468  13.462312  14.543106
       5.000000  10.000000    8.785975   8.999302   8.353347  10.488638
       10.000000 15.000000   10.557269  11.476305  12.502932  10.870881
       15.000000 20.000000   13.045639  16.887046  14.611066  13.163921
       20.000000 25.000000   13.826352  13.727950  15.061997  15.197269
       25.000000 30.000000   15.369862  14.207762  15.316245  13.782395
       30.000000 35.000000   15.308369  15.048679  16.093503  14.982002
       35.000000 40.000000   16.435502  15.535524  16.096824  15.993248
       40.000000 45.000000   15.201416  16.416025  15.445314  13.547648
       45.000000 50.000000   17.532509  17.355728  15.430561  17.043694
       50.000000 55.000000   18.009675  18.744892  16.606316  17.711642
       55.000000 60.000000   15.875381  18.053698  15.467750  18.296869
       60.000000 65.000000   18.871070  18.580104  18.255672  16.879404
       65.000000 70.000000   18.886082  16.379937  17.273643  20.214424
       70.000000 75.000000   16.105195  17.900408  16.972902  18.857366
       75.000000 80.000000   18.424475  17.495561  19.409267  19.658221
       80.000000 85.000000   25.460635  22.386611  20.761918  21.410822
       85.000000 90.000000   23.227566  22.062322  25.478065  26.331594
       90.000000 95.000000   27.838665  26.787924  29.194111  28.873320
       95.000000 125.000000  35.903946  29.764145  40.281583  36.888608

                              draw_490   draw_491   draw_492   draw_493  \
sex    age_start age_end
Female 0.000000  0.019178    10.329697  10.668878  13.046126  10.782160
       0.019178  0.076712    18.396669  19.537466  16.708525  20.642018
       0.076712  0.500000    15.597243  11.261161  13.873938  14.719846
       0.500000  1.000000    13.570370  14.580505  13.474202  14.509005
       1.000000  2.000000    14.035583  15.124152  14.956328  15.328136
       2.000000  5.000000    16.856568  16.721737  17.986021  16.809365
       5.000000  10.000000   12.666946  11.115035  11.686151  13.421744
       10.000000 15.000000   14.299624  14.091810  13.872200  17.720165
       15.000000 20.000000   14.884398  15.107632  13.951086  18.230387
       20.000000 25.000000   16.333919  15.553801  15.234769  16.902130
       25.000000 30.000000   19.295556  16.068527  15.713953  14.422652
       30.000000 35.000000   13.251110  16.702347  15.697319  14.397919
       35.000000 40.000000   14.758076  17.705012  16.765372  15.707159
       40.000000 45.000000   15.738051  18.219590  16.683556  14.615536
       45.000000 50.000000   18.795181  15.734756  18.447955  16.981487

In [36]:
hemoglobin_sd_disparities = pd.read_csv(f'../0100_data_prep/results/hemoglobin/sd_disparities/{location}.csv')
hemoglobin_sd_disparities = (
    map_to_population_age_groups(hemoglobin_sd_disparities[hemoglobin_sd_disparities.pregnant == "not_pregnant"].drop(columns=["pregnant"]))
        .set_index(["sex", "age_start", "age_end", "wealth_quintile"]).value
)
hemoglobin_sd_disparities

sex     age_start  age_end     wealth_quintile
Female  0.0        0.019178    lowest             14.697789
                               second             14.743958
                               middle             15.145306
                               fourth             15.145327
                               highest            14.592007
                                                    ...
Male    95.0       125.000000  lowest             16.135241
                               second             16.281235
                               middle             16.559569
                               fourth             16.266386
                               highest            15.538198
Name: value, Length: 250, dtype: float64

In [37]:
pre_disparity_groups = hgb_sd.mul(wealth_quintile_probabilities, axis=0).groupby([c for c in hgb_sd.index.names if c != 'wealth_quintile']).sum()
pre_disparity_groups

                                draw_0     draw_1     draw_2     draw_3  \
sex    age_start age_end
Female 0.000000  0.019178    11.056572  15.419496  12.937057  14.108613
       0.019178  0.076712    18.143206  17.170122  18.638921  21.675732
       0.076712  0.500000    11.519491  14.027332  13.723109  14.417308
       0.500000  1.000000    13.756756  14.711771  13.648304  13.187534
       1.000000  2.000000    14.325459  16.843282  16.709555  15.864417
       2.000000  5.000000    16.864334  16.488876  16.574293  16.946859
       5.000000  10.000000   14.225182  14.168108  12.948419  12.913613
       10.000000 15.000000   13.709243  13.495770  11.389442  15.925441
       15.000000 20.000000   13.561928  15.733414  13.751380  15.264811
       20.000000 25.000000   17.877538  15.796879  16.381351  14.863829
       25.000000 30.000000   16.815011  16.994822  15.316674  15.690873
       30.000000 35.000000   16.621743  15.047877  16.867962  15.976469
       35.000000 40.000000   14.396311  15.728416  16.175030  15.550384
       40.000000 45.000000   16.718798  15.378787  17.134685  16.801107
       45.000000 50.000000   17.032453  15.404674  16.578969  18.835821
       50.000000 55.000000   15.717267  15.389592  14.263427  15.514466
       55.000000 60.000000   12.958764  14.368135  16.001020  15.681634
       60.000000 65.000000   14.203046  14.792499  14.244354  14.557884
       65.000000 70.000000   12.468907  15.525386  14.499738  14.166835
       70.000000 75.000000   16.333369  16.631346  16.833404  15.235709
       75.000000 80.000000   22.254054  24.403128  20.115561  23.155481
       80.000000 85.000000   24.100034  24.539483  24.989374  26.511926
       85.000000 90.000000   36.306586  33.251947  37.348512  32.257547
       90.000000 95.000000   38.914197  41.875007  39.460541  40.321736
       95.000000 125.000000  38.019009  39.773450  39.091306  40.811093
Male   0.000000  0.019178     7.610899   6.575979   7.453095   6.250333
       0.019178  0.076712    16.977021  18.465539  16.510252  21.378982
       0.076712  0.500000     9.721262  12.425339  14.429252  13.617889
       0.500000  1.000000    14.652405  12.306607  13.147011  14.384103
       1.000000  2.000000    13.806197  12.868476  13.713812  14.321067
       2.000000  5.000000    14.572863  13.560881  13.249884  13.447389
       5.000000  10.000000   12.573757   7.057425   9.593659   9.916708
       10.000000 15.000000   11.260913  12.769954   9.948129  11.258765
       15.000000 20.000000   11.470756  15.361375  13.757213  15.839422
       20.000000 25.000000   16.818841  15.146760  14.406426  15.531786
       25.000000 30.000000   14.325444  14.905894  14.724530  12.324918
       30.000000 35.000000   16.155267  16.364407  15.748614  15.395269
       35.000000 40.000000   17.000588  14.962367  16.688472  15.727331
       40.000000 45.000000   16.215645  16.148306  15.713011  15.286601
       45.000000 50.000000   16.866309  17.598236  14.838259  17.183189
       50.000000 55.000000   16.298999  17.308050  17.941748  18.389619
       55.000000 60.000000   19.614086  19.237907  18.023727  18.054980
       60.000000 65.000000   17.017625  19.435720  17.143083  16.953227
       65.000000 70.000000   17.246434  17.477513  19.252672  18.443892
       70.000000 75.000000   18.666848  17.255199  17.201503  17.486489
       75.000000 80.000000   19.081333  16.399954  20.715293  21.595394
       80.000000 85.000000   21.153456  22.487688  23.106116  22.546762
       85.000000 90.000000   23.662495  24.946716  26.106795  23.226613
       90.000000 95.000000   27.527042  30.766501  28.349045  28.340500
       95.000000 125.000000  39.559564  39.138167  37.453939  35.318036

                                draw_4     draw_5     draw_6     draw_7  \
sex    age_start age_end
Female 0.000000  0.019178    13.020095  12.577809  17.754828  13.099648
       0.019178  0.076712    17.362276  18.653702  20.182212  17.627105
       0.076712  0.500000    13.217808  13.026038  14.444848  13.017687
       0.500000  1.000000    13.376081  14.524967  13.737699  14.473522
       1.000000  2.000000    15.124064  14.493894  16.528408  15.202250
       2.000000  5.000000    16.571890  17.305266  14.511235  17.740968
       5.000000  10.000000   14.731795  14.601781  12.012659  11.527454
       10.000000 15.000000   16.126926  12.631853  16.717010  14.298076
       15.000000 20.000000   14.127997  14.013979  15.329002  15.397312
       20.000000 25.000000   14.447182  14.735706  15.662016  18.748018
       25.000000 30.000000   17.736549  17.074363  19.213781  17.147339
       30.000000 35.000000   17.430898  15.631113  16.463113  18.105185
       35.000000 40.000000   16.496092  16.065123  15.017911  15.369356
       40.000000 45.000000   16.166835  17.622009  14.428781  14.963834
       45.000000 50.000000   16.780592  15.737449  16.435845  16.031816
       50.000000 55.000000   15.106636  14.267999  12.426291  15.664131
       55.000000 60.000000   12.257894  12.690514  15.910059  13.956875
       60.000000 65.000000   16.303096  13.536360  15.255340  14.497954
       65.000000 70.000000   16.799314  15.882442  14.829333  14.335778
       70.000000 75.000000   17.538595  17.938588  16.735632  17.604786
       75.000000 80.000000   21.808174  19.783694  20.679099  24.045183
       80.000000 85.000000   25.140651  24.068674  25.506386  26.024679
       85.000000 90.000000   35.130583  35.850669  34.987728  35.460821
       90.000000 95.000000   37.414906  39.360273  40.628148  43.794461
       95.000000 125.000000  40.515326  36.987378  40.861064  38.973924
Male   0.000000  0.019178     7.920491   6.340217   6.466164   6.139428
       0.019178  0.076712    15.861589  18.344707  14.142126  13.631602
       0.076712  0.500000     9.980601  12.249892  14.091311  13.694185
       0.500000  1.000000    13.694239  15.034635  12.720333  14.333813
       1.000000  2.000000    15.868509  13.837486  14.719694  14.593099
       2.000000  5.000000    12.019735  14.006495  11.768375  15.466440
       5.000000  10.000000    7.976543   8.718254   9.152801   9.313380
       10.000000 15.000000   11.137392  11.149098  12.718914  10.055498
       15.000000 20.000000   14.880081  11.879994  13.589567  14.474176
       20.000000 25.000000   15.666944  16.268696  16.196663  16.445528
       25.000000 30.000000   15.314376  15.113747  15.023463  15.393740
       30.000000 35.000000   16.038528  16.942015  15.929371  16.101042
       35.000000 40.000000   18.088510  16.125549  15.799825  17.127050
       40.000000 45.000000   15.457510  14.181011  16.366586  16.586916
       45.000000 50.000000   15.255021  16.513771  17.164343  16.774604
       50.000000 55.000000   16.817437  16.554355  18.656778  18.894118
       55.000000 60.000000   16.523410  16.104365  17.987870  17.062202
       60.000000 65.000000   17.860338  17.714065  17.170993  16.814463
       65.000000 70.000000   18.305607  18.143936  15.547391  18.148081
       70.000000 75.000000   17.297645  17.895579  18.040125  18.033667
       75.000000 80.000000   18.175629  16.791251  20.236707  18.821965
       80.000000 85.000000   17.955075  23.479958  23.470485  20.610145
       85.000000 90.000000   23.165737  25.619051  28.887955  26.441548
       90.000000 95.000000   30.220151  29.927618  32.666743  34.961008
       95.000000 125.000000  32.753194  35.956872  34.403757  37.928030

                                draw_8     draw_9    draw_10    draw_11  \
sex    age_start age_end
Female 0.000000  0.019178    11.912721  13.534418  15.250904  13.089309
       0.019178  0.076712    18.478847  19.942071  18.480448  26.123070
       0.076712  0.500000    15.242591  14.713188  13.551734  12.921939
       0.500000  1.000000    14.511934  14.818950  13.653111  13.482305
       1.000000  2.000000    14.221149  15.209534  14.536429  15.205116
       2.000000  5.000000    16.619492  16.571673  16.856932  17.195478
       5.000000  10.000000   10.846907  13.933340  11.788947  13.362020
       10.000000 15.000000   15.839117  15.625613  14.883322  12.584534
       15.000000 20.000000   16.466307  11.996041  16.521571  14.357632
       20.000000 25.000000   16.600911  15.385754  16.130704  15.309814
       25.000000 30.000000   16.323214  16.294265  16.306756  17.068850
       30.000000 35.000000   14.995013  16.883843  15.766927  16.766155
       35.000000 40.000000   17.468354  16.088688  14.604199  13.174420
       40.000000 45.000000   14.368247  17.720018  15.223568  16.544181
       45.000000 50.000000   18.936978  16.419509  15.305525  15.575902
       50.000000 55.000000   15.024812  15.138730  17.147760  13.221135
       55.000000 60.000000   16.379446  15.497368  15.231634  14.880113
       60.000000 65.000000   15.875441  13.848493  15.479695  14.029023
       65.000000 70.000000   16.793297  16.239228  15.754097  12.131503
       70.000000 75.000000   17.094404  16.380356  16.166625  16.308952
       75.000000 80.000000   20.913422  17.769351  21.553431  20.721305
       80.000000 85.000000   22.276074  22.829394  27.261264  25.864497
       85.000000 90.000000   32.095693  36.082627  32.560548  33.853125
       90.000000 95.000000   40.087374  42.096789  41.942134  44.235362
       95.000000 125.000000  39.797842  42.849962  39.484918  41.161548
Male   0.000000  0.019178     5.691987   7.091346   6.402940   6.747872
       0.019178  0.076712    12.477566  17.467950  17.889057  19.905498
       0.076712  0.500000    10.599262  11.966199  13.746249  13.087760
       0.500000  1.000000    14.068139  13.625568  13.935288  15.186487
       1.000000  2.000000    15.587080  13.312045  15.559659  14.269923
       2.000000  5.000000    11.309049  12.260267  12.971750  13.176335
       5.000000  10.000000    9.601694   8.174270   7.913442   8.310538
       10.000000 15.000000   16.874654  10.429230  11.770886  11.021590
       15.000000 20.000000   13.956274  14.539298  16.829695  13.307860
       20.000000 25.000000   15.154534  15.671597  16.276785  14.892207
       25.000000 30.000000   14.417136  13.955752  17.038566  15.955352
       30.000000 35.000000   16.065982  16.306538  14.049113  16.552980
       35.000000 40.000000   17.451215  15.057925  16.391333  19.301976
       40.000000 45.000000   15.542826  15.803241  17.272135  15.251573
       45.000000 50.000000   14.214086  16.454712  16.517748  17.999063
       50.000000 55.000000   16.011912  17.637154  17.660521  16.628725
       55.000000 60.000000   19.284436  18.687474  18.557785  16.600751
       60.000000 65.000000   15.925692  18.227418  16.585964  18.511906
       65.000000 70.000000   17.757204  18.786740  18.149067  17.558208
       70.000000 75.000000   18.977417  19.703393  21.511518  18.993971
       75.000000 80.000000   17.311613  16.313725  18.447740  18.502688
       80.000000 85.000000   23.653412  20.728578  22.162447  24.969668
       85.000000 90.000000   25.162466  21.455901  26.402712  24.129777
       90.000000 95.000000   28.784333  32.471610  32.448238  27.340270
       95.000000 125.000000  34.986669  36.813595  36.203463  41.761803

                               draw_12    draw_13    draw_14  ...   draw_485  \
sex    age_start age_end                                      ...
Female 0.000000  0.019178    11.698468  13.944615  12.968311  ...  12.172186
       0.019178  0.076712    19.292006  17.894884  18.536767  ...  18.854338
       0.076712  0.500000    14.771674  12.216773  13.723598  ...  14.221293
       0.500000  1.000000    13.071927  10.878399  13.538518  ...  12.313299
       1.000000  2.000000    13.076259  13.863574  15.013913  ...  15.543186
       2.000000  5.000000    16.165612  17.041200  15.445089  ...  15.799757
       5.000000  10.000000   12.541725  12.660770  11.161442  ...  13.975803
       10.000000 15.000000   13.628142  14.160368  16.822192  ...  13.992595
       15.000000 20.000000   15.003546  15.873917  12.730538  ...  14.500338
       20.000000 25.000000   14.185374  16.320625  15.405858  ...  14.864683
       25.000000 30.000000   17.280868  15.695182  16.875562  ...  15.915891
       30.000000 35.000000   15.087403  14.452967  17.114253  ...  16.399671
       35.000000 40.000000   17.541935  14.989713  16.061756  ...  15.271765
       40.000000 45.000000   17.344403  16.536191  15.619087  ...  18.096751
       45.000000 50.000000   16.515168  19.294747  18.095457  ...  14.838483
       50.000000 55.000000   13.645099  13.770616  15.815230  ...  13.926071
       55.000000 60.000000   14.580799  17.620255  12.134836  ...  15.390221
       60.000000 65.000000   14.628691  17.812089  14.921815  ...  15.178644
       65.000000 70.000000   15.435082  15.634770  14.391361  ...  15.792841
       70.000000 75.000000   18.955998  16.231075  18.404108  ...  17.322680
       75.000000 80.000000   21.298369  19.615355  23.021914  ...  20.844932
       80.000000 85.000000   24.617628  23.773455  27.731977  ...  24.909039
       85.000000 90.000000   38.626604  32.079645  35.037743  ...  36.765097
       90.000000 95.000000   39.684359  38.818593  42.094596  ...  42.935176
       95.000000 125.000000  41.840806  42.270201  39.586573  ...  38.142674
Male   0.000000  0.019178     6.791699   5.809352   6.938802  ...   7.240774
       0.019178  0.076712    18.629369  13.139183  17.540888  ...  12.878999
       0.076712  0.500000    13.139513  14.568086  13.524392  ...  13.267248
       0.500000  1.000000    14.922199  12.271635  15.927740  ...  14.677553
       1.000000  2.000000    12.273306  15.013445  15.201227  ...  13.813997
       2.000000  5.000000    12.671689  11.474396  13.228545  ...  11.930761
       5.000000  10.000000    9.351394  11.582570   8.347038  ...   7.081553
       10.000000 15.000000   13.049290   9.595911  11.598644  ...  13.622000
       15.000000 20.000000   14.958834  14.097620  15.084565  ...  13.284964
       20.000000 25.000000   15.265481  15.161863  16.416929  ...  15.418041
       25.000000 30.000000   15.007560  14.227289  14.457016  ...  16.152938
       30.000000 35.000000   15.317437  15.622383  15.157442  ...  15.895173
       35.000000 40.000000   15.768175  15.865815  14.615222  ...  16.684203
       40.000000 45.000000   16.167001  15.923844  16.458809  ...  15.404894
       45.000000 50.000000   16.635981  14.962696  15.807011  ...  17.945107
       50.000000 55.000000   17.256656  17.275432  17.505294  ...  15.712603
       55.000000 60.000000   18.077812  18.294788  14.342322  ...  18.811305
       60.000000 65.000000   16.114486  17.200815  17.327638  ...  17.371669
       65.000000 70.000000   18.541200  20.968104  18.418815  ...  20.481004
       70.000000 75.000000   15.247137  21.028243  19.649548  ...  16.359186
       75.000000 80.000000   20.566355  19.880885  21.086847  ...  16.258103
       80.000000 85.000000   22.174757  22.691070  20.029234  ...  23.457237
       85.000000 90.000000   22.855954  26.903121  26.560958  ...  26.493087
       90.000000 95.000000   31.174407  28.655398  29.190495  ...  28.939243
       95.000000 125.000000  30.437841  35.369767  35.180846  ...  36.441043

                              draw_486   draw_487   draw_488   draw_489  \
sex    age_start age_end
Female 0.000000  0.019178    12.327443  10.713326  15.001014  13.824811
       0.019178  0.076712    19.857466  19.241883  19.544912  20.609662
       0.076712  0.500000    14.234269  15.657114  14.792087  13.905731
       0.500000  1.000000    13.716565  14.003392  14.738192  13.973929
       1.000000  2.000000    14.834818  13.696490  15.820430  15.176029
       2.000000  5.000000    17.022416  15.874117  14.704499  17.482008
       5.000000  10.000000   14.133345  13.558921  12.259638  12.439979
       10.000000 15.000000   13.672172  12.610043  16.154006  14.075381
       15.000000 20.000000   14.144277  14.197223  15.725285  14.681504
       20.000000 25.000000   16.767909  13.248012  16.339642  15.131863
       25.000000 30.000000   17.669303  16.738076  15.075536  17.823539
       30.000000 35.000000   14.426570  16.071797  16.806593  18.935009
       35.000000 40.000000   15.383412  14.520184  13.418833  17.281017
       40.000000 45.000000   16.387465  16.917742  17.062296  16.072295
       45.000000 50.000000   14.902757  16.776988  17.468847  16.403468
       50.000000 55.000000   14.592241  13.799966  14.973280  16.050551
       55.000000 60.000000   16.368539  16.094332  15.804400  15.078729
       60.000000 65.000000   15.262867  15.195140  17.074264  14.658112
       65.000000 70.000000   13.337074  15.208650  16.585585  13.920420
       70.000000 75.000000   16.668697  17.246553  17.524653  17.260109
       75.000000 80.000000   25.163023  19.642040  19.286091  23.055177
       80.000000 85.000000   27.352358  25.604258  25.462338  26.159587
       85.000000 90.000000   32.754093  34.149292  35.032011  28.472815
       90.000000 95.000000   43.112264  40.804636  38.087450  38.982986
       95.000000 125.000000  43.545351  40.428324  39.540398  38.730121
Male   0.000000  0.019178     8.311788   7.393801   6.218421   6.421989
       0.019178  0.076712    17.382217  18.975632  18.312220  18.833729
       0.076712  0.500000    14.129835  12.905281  12.880018  13.073209
       0.500000  1.000000    15.341112  16.089164  14.155589  15.122908
       1.000000  2.000000    13.813008  13.683558  14.332377  13.342373
       2.000000  5.000000    12.703132  11.421468  13.462312  14.543106
       5.000000  10.000000    8.785975   8.999302   8.353347  10.488638
       10.000000 15.000000   10.557269  11.476305  12.502932  10.870881
       15.000000 20.000000   13.045639  16.887046  14.611066  13.163921
       20.000000 25.000000   13.826352  13.727950  15.061997  15.197269
       25.000000 30.000000   15.369862  14.207762  15.316245  13.782395
       30.000000 35.000000   15.308369  15.048679  16.093503  14.982002
       35.000000 40.000000   16.435502  15.535524  16.096824  15.993248
       40.000000 45.000000   15.201416  16.416025  15.445314  13.547648
       45.000000 50.000000   17.532509  17.355728  15.430561  17.043694
       50.000000 55.000000   18.009675  18.744892  16.606316  17.711642
       55.000000 60.000000   15.875381  18.053698  15.467750  18.296869
       60.000000 65.000000   18.871070  18.580104  18.255672  16.879404
       65.000000 70.000000   18.886082  16.379937  17.273643  20.214424
       70.000000 75.000000   16.105195  17.900408  16.972902  18.857366
       75.000000 80.000000   18.424475  17.495561  19.409267  19.658221
       80.000000 85.000000   25.460635  22.386611  20.761918  21.410822
       85.000000 90.000000   23.227566  22.062322  25.478065  26.331594
       90.000000 95.000000   27.838665  26.787924  29.194111  28.873320
       95.000000 125.000000  35.903946  29.764145  40.281583  36.888608

                              draw_490   draw_491   draw_492   draw_493  \
sex    age_start age_end
Female 0.000000  0.019178    10.329697  10.668878  13.046126  10.782160
       0.019178  0.076712    18.396669  19.537466  16.708525  20.642018
       0.076712  0.500000    15.597243  11.261161  13.873938  14.719846
       0.500000  1.000000    13.570370  14.580505  13.474202  14.509005
       1.000000  2.000000    14.035583  15.124152  14.956328  15.328136
       2.000000  5.000000    16.856568  16.721737  17.986021  16.809365
       5.000000  10.000000   12.666946  11.115035  11.686151  13.421744
       10.000000 15.000000   14.299624  14.091810  13.872200  17.720165
       15.000000 20.000000   14.884398  15.107632  13.951086  18.230387
       20.000000 25.000000   16.333919  15.553801  15.234769  16.902130
       25.000000 30.000000   19.295556  16.068527  15.713953  14.422652
       30.000000 35.000000   13.251110  16.702347  15.697319  14.397919
       35.000000 40.000000   14.758076  17.705012  16.765372  15.707159
       40.000000 45.000000   15.738051  18.219590  16.683556  14.615536
       45.000000 50.000000   18.795181  15.734756  18.447955  16.981487

In [38]:
hgb_sd = hgb_sd.mul(hemoglobin_sd_disparities, axis=0)

In [39]:
scale_factor = pre_disparity_groups / hgb_sd.mul(wealth_quintile_probabilities, axis=0).groupby([c for c in hgb_sd.index.names if c != 'wealth_quintile']).sum()
scale_factor

                               draw_0    draw_1    draw_2    draw_3    draw_4  \
sex    age_start age_end
Female 0.000000  0.019178    0.067283  0.067283  0.067283  0.067283  0.067283
       0.019178  0.076712    0.067283  0.067283  0.067283  0.067283  0.067283
       0.076712  0.500000    0.067283  0.067283  0.067283  0.067283  0.067283
       0.500000  1.000000    0.067283  0.067283  0.067283  0.067283  0.067283
       1.000000  2.000000    0.067283  0.067283  0.067283  0.067283  0.067283
       2.000000  5.000000    0.067283  0.067283  0.067283  0.067283  0.067283
       5.000000  10.000000   0.064429  0.064429  0.064429  0.064429  0.064429
       10.000000 15.000000   0.064429  0.064429  0.064429  0.064429  0.064429
       15.000000 20.000000   0.061866  0.061866  0.061866  0.061866  0.061866
       20.000000 25.000000   0.061866  0.061866  0.061866  0.061866  0.061866
       25.000000 30.000000   0.061866  0.061866  0.061866  0.061866  0.061866
       30.000000 35.000000   0.061962  0.061962  0.061962  0.061962  0.061962
       35.000000 40.000000   0.061962  0.061962  0.061962  0.061962  0.061962
       40.000000 45.000000   0.061962  0.061962  0.061962  0.061962  0.061962
       45.000000 50.000000   0.061962  0.061962  0.061962  0.061962  0.061962
       50.000000 55.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       55.000000 60.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       60.000000 65.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       65.000000 70.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       70.000000 75.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       75.000000 80.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       80.000000 85.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       85.000000 90.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       90.000000 95.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       95.000000 125.000000  0.061993  0.061993  0.061993  0.061993  0.061993
Male   0.000000  0.019178    0.066264  0.066264  0.066264  0.066264  0.066264
       0.019178  0.076712    0.066264  0.066264  0.066264  0.066264  0.066264
       0.076712  0.500000    0.066264  0.066264  0.066264  0.066264  0.066264
       0.500000  1.000000    0.066264  0.066264  0.066264  0.066264  0.066264
       1.000000  2.000000    0.066264  0.066264  0.066264  0.066264  0.066264
       2.000000  5.000000    0.066264  0.066264  0.066264  0.066264  0.066264
       5.000000  10.000000   0.063976  0.063976  0.063976  0.063976  0.063976
       10.000000 15.000000   0.063976  0.063976  0.063976  0.063976  0.063976
       15.000000 20.000000   0.061872  0.061872  0.061872  0.061872  0.061872
       20.000000 25.000000   0.061872  0.061872  0.061872  0.061872  0.061872
       25.000000 30.000000   0.061872  0.061872  0.061872  0.061872  0.061872
       30.000000 35.000000   0.061947  0.061947  0.061947  0.061947  0.061947
       35.000000 40.000000   0.061947  0.061947  0.061947  0.061947  0.061947
       40.000000 45.000000   0.061947  0.061947  0.061947  0.061947  0.061947
       45.000000 50.000000   0.061947  0.061947  0.061947  0.061947  0.061947
       50.000000 55.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       55.000000 60.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       60.000000 65.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       65.000000 70.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       70.000000 75.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       75.000000 80.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       80.000000 85.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       85.000000 90.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       90.000000 95.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       95.000000 125.000000  0.062029  0.062029  0.062029  0.062029  0.062029

                               draw_5    draw_6    draw_7    draw_8    draw_9  \
sex    age_start age_end
Female 0.000000  0.019178    0.067283  0.067283  0.067283  0.067283  0.067283
       0.019178  0.076712    0.067283  0.067283  0.067283  0.067283  0.067283
       0.076712  0.500000    0.067283  0.067283  0.067283  0.067283  0.067283
       0.500000  1.000000    0.067283  0.067283  0.067283  0.067283  0.067283
       1.000000  2.000000    0.067283  0.067283  0.067283  0.067283  0.067283
       2.000000  5.000000    0.067283  0.067283  0.067283  0.067283  0.067283
       5.000000  10.000000   0.064429  0.064429  0.064429  0.064429  0.064429
       10.000000 15.000000   0.064429  0.064429  0.064429  0.064429  0.064429
       15.000000 20.000000   0.061866  0.061866  0.061866  0.061866  0.061866
       20.000000 25.000000   0.061866  0.061866  0.061866  0.061866  0.061866
       25.000000 30.000000   0.061866  0.061866  0.061866  0.061866  0.061866
       30.000000 35.000000   0.061962  0.061962  0.061962  0.061962  0.061962
       35.000000 40.000000   0.061962  0.061962  0.061962  0.061962  0.061962
       40.000000 45.000000   0.061962  0.061962  0.061962  0.061962  0.061962
       45.000000 50.000000   0.061962  0.061962  0.061962  0.061962  0.061962
       50.000000 55.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       55.000000 60.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       60.000000 65.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       65.000000 70.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       70.000000 75.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       75.000000 80.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       80.000000 85.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       85.000000 90.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       90.000000 95.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       95.000000 125.000000  0.061993  0.061993  0.061993  0.061993  0.061993
Male   0.000000  0.019178    0.066264  0.066264  0.066264  0.066264  0.066264
       0.019178  0.076712    0.066264  0.066264  0.066264  0.066264  0.066264
       0.076712  0.500000    0.066264  0.066264  0.066264  0.066264  0.066264
       0.500000  1.000000    0.066264  0.066264  0.066264  0.066264  0.066264
       1.000000  2.000000    0.066264  0.066264  0.066264  0.066264  0.066264
       2.000000  5.000000    0.066264  0.066264  0.066264  0.066264  0.066264
       5.000000  10.000000   0.063976  0.063976  0.063976  0.063976  0.063976
       10.000000 15.000000   0.063976  0.063976  0.063976  0.063976  0.063976
       15.000000 20.000000   0.061872  0.061872  0.061872  0.061872  0.061872
       20.000000 25.000000   0.061872  0.061872  0.061872  0.061872  0.061872
       25.000000 30.000000   0.061872  0.061872  0.061872  0.061872  0.061872
       30.000000 35.000000   0.061947  0.061947  0.061947  0.061947  0.061947
       35.000000 40.000000   0.061947  0.061947  0.061947  0.061947  0.061947
       40.000000 45.000000   0.061947  0.061947  0.061947  0.061947  0.061947
       45.000000 50.000000   0.061947  0.061947  0.061947  0.061947  0.061947
       50.000000 55.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       55.000000 60.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       60.000000 65.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       65.000000 70.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       70.000000 75.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       75.000000 80.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       80.000000 85.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       85.000000 90.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       90.000000 95.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       95.000000 125.000000  0.062029  0.062029  0.062029  0.062029  0.062029

                              draw_10   draw_11   draw_12   draw_13   draw_14  \
sex    age_start age_end
Female 0.000000  0.019178    0.067283  0.067283  0.067283  0.067283  0.067283
       0.019178  0.076712    0.067283  0.067283  0.067283  0.067283  0.067283
       0.076712  0.500000    0.067283  0.067283  0.067283  0.067283  0.067283
       0.500000  1.000000    0.067283  0.067283  0.067283  0.067283  0.067283
       1.000000  2.000000    0.067283  0.067283  0.067283  0.067283  0.067283
       2.000000  5.000000    0.067283  0.067283  0.067283  0.067283  0.067283
       5.000000  10.000000   0.064429  0.064429  0.064429  0.064429  0.064429
       10.000000 15.000000   0.064429  0.064429  0.064429  0.064429  0.064429
       15.000000 20.000000   0.061866  0.061866  0.061866  0.061866  0.061866
       20.000000 25.000000   0.061866  0.061866  0.061866  0.061866  0.061866
       25.000000 30.000000   0.061866  0.061866  0.061866  0.061866  0.061866
       30.000000 35.000000   0.061962  0.061962  0.061962  0.061962  0.061962
       35.000000 40.000000   0.061962  0.061962  0.061962  0.061962  0.061962
       40.000000 45.000000   0.061962  0.061962  0.061962  0.061962  0.061962
       45.000000 50.000000   0.061962  0.061962  0.061962  0.061962  0.061962
       50.000000 55.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       55.000000 60.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       60.000000 65.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       65.000000 70.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       70.000000 75.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       75.000000 80.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       80.000000 85.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       85.000000 90.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       90.000000 95.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       95.000000 125.000000  0.061993  0.061993  0.061993  0.061993  0.061993
Male   0.000000  0.019178    0.066264  0.066264  0.066264  0.066264  0.066264
       0.019178  0.076712    0.066264  0.066264  0.066264  0.066264  0.066264
       0.076712  0.500000    0.066264  0.066264  0.066264  0.066264  0.066264
       0.500000  1.000000    0.066264  0.066264  0.066264  0.066264  0.066264
       1.000000  2.000000    0.066264  0.066264  0.066264  0.066264  0.066264
       2.000000  5.000000    0.066264  0.066264  0.066264  0.066264  0.066264
       5.000000  10.000000   0.063976  0.063976  0.063976  0.063976  0.063976
       10.000000 15.000000   0.063976  0.063976  0.063976  0.063976  0.063976
       15.000000 20.000000   0.061872  0.061872  0.061872  0.061872  0.061872
       20.000000 25.000000   0.061872  0.061872  0.061872  0.061872  0.061872
       25.000000 30.000000   0.061872  0.061872  0.061872  0.061872  0.061872
       30.000000 35.000000   0.061947  0.061947  0.061947  0.061947  0.061947
       35.000000 40.000000   0.061947  0.061947  0.061947  0.061947  0.061947
       40.000000 45.000000   0.061947  0.061947  0.061947  0.061947  0.061947
       45.000000 50.000000   0.061947  0.061947  0.061947  0.061947  0.061947
       50.000000 55.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       55.000000 60.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       60.000000 65.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       65.000000 70.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       70.000000 75.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       75.000000 80.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       80.000000 85.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       85.000000 90.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       90.000000 95.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       95.000000 125.000000  0.062029  0.062029  0.062029  0.062029  0.062029

                             ...  draw_485  draw_486  draw_487  draw_488  \
sex    age_start age_end     ...
Female 0.000000  0.019178    ...  0.067283  0.067283  0.067283  0.067283
       0.019178  0.076712    ...  0.067283  0.067283  0.067283  0.067283
       0.076712  0.500000    ...  0.067283  0.067283  0.067283  0.067283
       0.500000  1.000000    ...  0.067283  0.067283  0.067283  0.067283
       1.000000  2.000000    ...  0.067283  0.067283  0.067283  0.067283
       2.000000  5.000000    ...  0.067283  0.067283  0.067283  0.067283
       5.000000  10.000000   ...  0.064429  0.064429  0.064429  0.064429
       10.000000 15.000000   ...  0.064429  0.064429  0.064429  0.064429
       15.000000 20.000000   ...  0.061866  0.061866  0.061866  0.061866
       20.000000 25.000000   ...  0.061866  0.061866  0.061866  0.061866
       25.000000 30.000000   ...  0.061866  0.061866  0.061866  0.061866
       30.000000 35.000000   ...  0.061962  0.061962  0.061962  0.061962
       35.000000 40.000000   ...  0.061962  0.061962  0.061962  0.061962
       40.000000 45.000000   ...  0.061962  0.061962  0.061962  0.061962
       45.000000 50.000000   ...  0.061962  0.061962  0.061962  0.061962
       50.000000 55.000000   ...  0.061993  0.061993  0.061993  0.061993
       55.000000 60.000000   ...  0.061993  0.061993  0.061993  0.061993
       60.000000 65.000000   ...  0.061993  0.061993  0.061993  0.061993
       65.000000 70.000000   ...  0.061993  0.061993  0.061993  0.061993
       70.000000 75.000000   ...  0.061993  0.061993  0.061993  0.061993
       75.000000 80.000000   ...  0.061993  0.061993  0.061993  0.061993
       80.000000 85.000000   ...  0.061993  0.061993  0.061993  0.061993
       85.000000 90.000000   ...  0.061993  0.061993  0.061993  0.061993
       90.000000 95.000000   ...  0.061993  0.061993  0.061993  0.061993
       95.000000 125.000000  ...  0.061993  0.061993  0.061993  0.061993
Male   0.000000  0.019178    ...  0.066264  0.066264  0.066264  0.066264
       0.019178  0.076712    ...  0.066264  0.066264  0.066264  0.066264
       0.076712  0.500000    ...  0.066264  0.066264  0.066264  0.066264
       0.500000  1.000000    ...  0.066264  0.066264  0.066264  0.066264
       1.000000  2.000000    ...  0.066264  0.066264  0.066264  0.066264
       2.000000  5.000000    ...  0.066264  0.066264  0.066264  0.066264
       5.000000  10.000000   ...  0.063976  0.063976  0.063976  0.063976
       10.000000 15.000000   ...  0.063976  0.063976  0.063976  0.063976
       15.000000 20.000000   ...  0.061872  0.061872  0.061872  0.061872
       20.000000 25.000000   ...  0.061872  0.061872  0.061872  0.061872
       25.000000 30.000000   ...  0.061872  0.061872  0.061872  0.061872
       30.000000 35.000000   ...  0.061947  0.061947  0.061947  0.061947
       35.000000 40.000000   ...  0.061947  0.061947  0.061947  0.061947
       40.000000 45.000000   ...  0.061947  0.061947  0.061947  0.061947
       45.000000 50.000000   ...  0.061947  0.061947  0.061947  0.061947
       50.000000 55.000000   ...  0.062029  0.062029  0.062029  0.062029
       55.000000 60.000000   ...  0.062029  0.062029  0.062029  0.062029
       60.000000 65.000000   ...  0.062029  0.062029  0.062029  0.062029
       65.000000 70.000000   ...  0.062029  0.062029  0.062029  0.062029
       70.000000 75.000000   ...  0.062029  0.062029  0.062029  0.062029
       75.000000 80.000000   ...  0.062029  0.062029  0.062029  0.062029
       80.000000 85.000000   ...  0.062029  0.062029  0.062029  0.062029
       85.000000 90.000000   ...  0.062029  0.062029  0.062029  0.062029
       90.000000 95.000000   ...  0.062029  0.062029  0.062029  0.062029
       95.000000 125.000000  ...  0.062029  0.062029  0.062029  0.062029

                             draw_489  draw_490  draw_491  draw_492  draw_493  \
sex    age_start age_end
Female 0.000000  0.019178    0.067283  0.067283  0.067283  0.067283  0.067283
       0.019178  0.076712    0.067283  0.067283  0.067283  0.067283  0.067283
       0.076712  0.500000    0.067283  0.067283  0.067283  0.067283  0.067283
       0.500000  1.000000    0.067283  0.067283  0.067283  0.067283  0.067283
       1.000000  2.000000    0.067283  0.067283  0.067283  0.067283  0.067283
       2.000000  5.000000    0.067283  0.067283  0.067283  0.067283  0.067283
       5.000000  10.000000   0.064429  0.064429  0.064429  0.064429  0.064429
       10.000000 15.000000   0.064429  0.064429  0.064429  0.064429  0.064429
       15.000000 20.000000   0.061866  0.061866  0.061866  0.061866  0.061866
       20.000000 25.000000   0.061866  0.061866  0.061866  0.061866  0.061866
       25.000000 30.000000   0.061866  0.061866  0.061866  0.061866  0.061866
       30.000000 35.000000   0.061962  0.061962  0.061962  0.061962  0.061962
       35.000000 40.000000   0.061962  0.061962  0.061962  0.061962  0.061962
       40.000000 45.000000   0.061962  0.061962  0.061962  0.061962  0.061962
       45.000000 50.000000   0.061962  0.061962  0.061962  0.061962  0.061962
       50.000000 55.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       55.000000 60.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       60.000000 65.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       65.000000 70.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       70.000000 75.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       75.000000 80.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       80.000000 85.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       85.000000 90.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       90.000000 95.000000   0.061993  0.061993  0.061993  0.061993  0.061993
       95.000000 125.000000  0.061993  0.061993  0.061993  0.061993  0.061993
Male   0.000000  0.019178    0.066264  0.066264  0.066264  0.066264  0.066264
       0.019178  0.076712    0.066264  0.066264  0.066264  0.066264  0.066264
       0.076712  0.500000    0.066264  0.066264  0.066264  0.066264  0.066264
       0.500000  1.000000    0.066264  0.066264  0.066264  0.066264  0.066264
       1.000000  2.000000    0.066264  0.066264  0.066264  0.066264  0.066264
       2.000000  5.000000    0.066264  0.066264  0.066264  0.066264  0.066264
       5.000000  10.000000   0.063976  0.063976  0.063976  0.063976  0.063976
       10.000000 15.000000   0.063976  0.063976  0.063976  0.063976  0.063976
       15.000000 20.000000   0.061872  0.061872  0.061872  0.061872  0.061872
       20.000000 25.000000   0.061872  0.061872  0.061872  0.061872  0.061872
       25.000000 30.000000   0.061872  0.061872  0.061872  0.061872  0.061872
       30.000000 35.000000   0.061947  0.061947  0.061947  0.061947  0.061947
       35.000000 40.000000   0.061947  0.061947  0.061947  0.061947  0.061947
       40.000000 45.000000   0.061947  0.061947  0.061947  0.061947  0.061947
       45.000000 50.000000   0.061947  0.061947  0.061947  0.061947  0.061947
       50.000000 55.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       55.000000 60.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       60.000000 65.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       65.000000 70.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       70.000000 75.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       75.000000 80.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       80.000000 85.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       85.000000 90.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       90.000000 95.000000   0.062029  0.062029  0.062029  0.062029  0.062029
       95.000000 125.000000  0.062029  0.062029  0.062029  0.062029  0.062029

                             draw_494  draw_495  draw_496  draw_497  draw_498  \
sex    age_start age_end
Female 0.000000  0.019178    0.067283  0.067283  0.067283  0.067283  0.067283

In [40]:
hgb_sd = hgb_sd * scale_factor

In [41]:
assert np.allclose(
    hgb_sd.mul(wealth_quintile_probabilities, axis=0).groupby([c for c in hgb_sd.index.names if c != 'wealth_quintile']).sum(),
    pre_disparity_groups,
)

In [42]:
hgb_sd.columns.name = "draw"
hgb_sd = hgb_sd.stack().rename("sd").reset_index()
hgb_sd

           sex  age_start     age_end wealth_quintile      draw         sd
0       Female        0.0    0.019178          lowest    draw_0  10.934018
1       Female        0.0    0.019178          lowest    draw_1  15.248582
2       Female        0.0    0.019178          lowest    draw_2  12.793660
3       Female        0.0    0.019178          lowest    draw_3  13.952230
4       Female        0.0    0.019178          lowest    draw_4  12.875777
...        ...        ...         ...             ...       ...        ...
124995    Male       95.0  125.000000         highest  draw_495  38.237787
124996    Male       95.0  125.000000         highest  draw_496  36.635558
124997    Male       95.0  125.000000         highest  draw_497  36.002955
124998    Male       95.0  125.000000         highest  draw_498  34.653317
124999    Male       95.0  125.000000         highest  draw_499  31.370762

[125000 rows x 6 columns]

In [43]:
mean_and_sd_hgb = pd.concat([
    hgb_mean.merge(hgb_sd, how="outer", validate="m:1").assign(scenario='baseline'),
    counterfactual_hgb_mean.merge(hgb_sd, how="outer", validate="m:1").assign(scenario='intervention')
])
mean_and_sd_hgb

,sex,age_start,age_end,wealth_quintile,draw,mean,sd,scenario
0,Female,0.0,0.019178,lowest,draw_0,138.477305,10.934018,baseline
1,Female,0.0,0.019178,lowest,draw_1,138.622225,15.248582,baseline
2,Female,0.0,0.019178,lowest,draw_2,140.460574,12.793660,baseline
3,Female,0.0,0.019178,lowest,draw_3,139.921181,13.952230,baseline
4,Female,0.0,0.019178,lowest,draw_4,138.651285,12.875777,baseline
...,...,...,...,...,...,...,...,...
124995,Male,95.0,125.000000,second,draw_495,102.264838,40.066317,intervention
124996,Male,95.0,125.000000,second,draw_496,102.548445,38.387469,intervention
124997,Male,95.0,125.000000,second,draw_497,101.871760,37.724615,intervention
124998,Male,95.0,125.000000,second,draw_498,103.187056,36.310437,intervention
124999,Male,95.0,125.000000,second,draw_499,103.252294,32.870911,intervention

In [44]:
thresholds = reshape_to_vivarium_format(pd.read_csv('/share/mnch/anemia/code/reference/model/anemia_thresholds.csv'), location.title()).droplevel(["age_group_name", "grp"]).reset_index()
thresholds

,sex,age_start,age_end,hgb_lower_anemic,hgb_lower_mild,hgb_lower_moderate,hgb_lower_severe,hgb_upper_anemic,hgb_upper_mild,hgb_upper_moderate,hgb_upper_severe,pregnant
0,Female,0.000000,0.019178,0,145,100,0,160,160,145,100,0
1,Female,0.019178,0.076712,0,120,85,0,135,135,120,85,0
2,Female,0.076712,0.500000,0,100,70,0,110,110,100,70,0
3,Female,0.500000,1.000000,0,100,70,0,110,110,100,70,0
4,Female,1.000000,2.000000,0,100,70,0,110,110,100,70,0
5,Female,2.000000,5.000000,0,100,70,0,110,110,100,70,0
6,Female,5.000000,10.000000,0,110,80,0,115,115,110,80,0
7,Female,10.000000,15.000000,0,100,70,0,110,110,100,70,1
8,Female,10.000000,15.000000,0,110,80,0,115,115,110,80,0
9,Female,15.000000,20.000000,0,110,80,0,120,120,110,80,0
10,Female,15.000000,20.000000,0,100,70,0,110,110,100,70,1
11,Female,20.000000,25.000000,0,110,80,0,120,120,110,80,0
12,Female,20.000000,25.000000,0,100,70,0,110,110,100,70,1
13,Female,25.000000,30.000000,0,110,80,0,120,120,110,80,0
14,Female,25.000000,30.000000,0,100,70,0,110,110,100,70,1
15,Female,30.000000,35.000000,0,110,80,0,120,120,110,80,0
16,Female,30.000000,35.000000,0,100,70,0,110,110,100,70,1
17,Female,35.000000,40.000000,0,110,80,0,120,120,110,80,0
18,Female,35.000000,40.000000,0,100,70,0,110,110,100,70,1
19,Female,40.000000,45.000000,0,110,80,0,120,120,110,80,0
20,Female,40.000000,45.000000,0,100,70,0,110,110,100,70,1
21,Female,45.000000,50.000000,0,110,80,0,120,120,110,80,0
22,Female,45.000000,50.000000,0,100,70,0,110,110,100,70,1
23,Female,50.000000,55.000000,0,110,80,0,120,120,110,80,0
24,Female,50.000000,55.000000,0,100,70,0,110,110,100,70,1
25,Female,55.000000,60.000000,0,110,80,0,120,120,110,80,0
26,Female,60.000000,65.000000,0,110,80,0,120,120,110,80,0
27,Female,65.000000,70.000000,0,110,80,0,120,120,110,80,0
28,Female,70.000000,75.000000,0,110,80,0,120,120,110,80,0
29,Female,75.000000,80.000000,0,110,80,0,120,120,110,80,0
30,Female,80.000000,85.000000,0,110,80,0,120,120,110,80,0
31,Female,85.000000,90.000000,0,110,80,0,120,120,110,80,0
32,Female,90.000000,95.000000,0,110,80,0,120,120,110,80,0
33,Female,95.000000,125.000000,0,110,80,0,120,120,110,80,0
34,Male,0.000000,0.019178,0,145,100,0,160,160,145,100,0
35,Male,0.019178,0.076712,0,120,85,0,135,135,120,85,0
36,Male,0.076712,0.500000,0,100,70,0,110,110,100,70,0
37,Male,0.500000,1.000000,0,100,70,0,110,110,100,70,0
38,Male,1.000000,2.000000,0,100,70,0,110,110,100,70,0
39,Male,2.000000,5.000000,0,100,70,0,110,110,100,70,0
40,Male,5.000000,10.000000,0,110,80,0,115,115,110,80,0
41,Male,10.000000,15.000000,0,110,80,0,115,115,110,80,0
42,Male,15.000000,20.000000,0,110,80,0,130,130,110,80,0
43,Male,20.000000,25.000000,0,110,80,0,130,130,110,80,0
44,Male,25.000000,30.000000,0,110,80,0,130,130,110,80,0
45,Male,30.000000,35.000000,0,110,80,0,130,130,110,80,0
46,Male,35.000000,40.000000,0,110,80,0,130,130,110,80,0
47,Male,40.000000,45.000000,0,110,80,0,130,130,110,80,0
48,Male,45.000000,50.000000,0,110,80,0,130,130,110,80,0
49,Male,50.000000,55.000000,0,110,80,0,130,130,110,80,0
50,Male,55.000000,60.000000,0,110,80,0,130,130,110,80,0
51,Male,60.000000,65.000000,0,110,80,0,130,130,110,80,0
52,Male,65.000000,70.000000,0,110,80,0,130,130,110,80,0
53,Male,70.000000,75.000000,0,110,80,0,130,130,110,80,0
54,Male,75.000000,80.000000,0,110,80,0,130,130,110,80,0
55,Male,80.000000,85.000000,0,110,80,0,130,130,110,80,0
56,Male,85.000000,90.000000,0,110,80,0,130,130,110,80,0
57,Male,90.000000,95.000000,0,110,80,0,130,130,110,80,0
58,Male,95.000000,125.000000,0,110,80,0,130,130,110,80,0

In [45]:
mean_and_sd_hgb = mean_and_sd_hgb.assign(pregnant=0).merge(thresholds, on=["sex", "age_start", "age_end", "pregnant"], how="left", validate="m:1")
mean_and_sd_hgb

,sex,age_start,age_end,wealth_quintile,draw,mean,sd,scenario,pregnant,hgb_lower_anemic,hgb_lower_mild,hgb_lower_moderate,hgb_lower_severe,hgb_upper_anemic,hgb_upper_mild,hgb_upper_moderate,hgb_upper_severe
0,Female,0.0,0.019178,lowest,draw_0,138.477305,10.934018,baseline,0,0,145,100,0,160,160,145,100
1,Female,0.0,0.019178,lowest,draw_1,138.622225,15.248582,baseline,0,0,145,100,0,160,160,145,100
2,Female,0.0,0.019178,lowest,draw_2,140.460574,12.793660,baseline,0,0,145,100,0,160,160,145,100
3,Female,0.0,0.019178,lowest,draw_3,139.921181,13.952230,baseline,0,0,145,100,0,160,160,145,100
4,Female,0.0,0.019178,lowest,draw_4,138.651285,12.875777,baseline,0,0,145,100,0,160,160,145,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,Male,95.0,125.000000,second,draw_495,102.264838,40.066317,intervention,0,0,110,80,0,130,130,110,80
249996,Male,95.0,125.000000,second,draw_496,102.548445,38.387469,intervention,0,0,110,80,0,130,130,110,80
249997,Male,95.0,125.000000,second,draw_497,101.871760,37.724615,intervention,0,0,110,80,0,130,130,110,80
249998,Male,95.0,125.000000,second,draw_498,103.187056,36.310437,intervention,0,0,110,80,0,130,130,110,80
249999,Male,95.0,125.000000,second,draw_499,103.252294,32.870911,intervention,0,0,110,80,0,130,130,110,80

In [46]:
assert (
    (mean_and_sd_hgb.hgb_upper_mild == mean_and_sd_hgb.hgb_upper_anemic).all() &
    (mean_and_sd_hgb.hgb_lower_severe == mean_and_sd_hgb.hgb_lower_anemic).all()
)
mean_and_sd_hgb = mean_and_sd_hgb.drop(columns=["hgb_upper_anemic", "hgb_lower_anemic"])

In [47]:
assert (
    (mean_and_sd_hgb.hgb_lower_mild == mean_and_sd_hgb.hgb_upper_moderate).all() &
    (mean_and_sd_hgb.hgb_lower_moderate == mean_and_sd_hgb.hgb_upper_severe).all()
)
mean_and_sd_hgb = mean_and_sd_hgb.drop(columns=["hgb_lower_mild", "hgb_lower_moderate"])

In [48]:
def _hemoglobin_distribution_parts_from_mean_sd(mean, sd):
    # NOTE: This is an unusual ensemble distribution. We should add functionality to the
    # EnsembleDistribution class to make this easier.
    x_min = 0
    x_max = 220
    gamma_params = risk_distributions.risk_distributions.Gamma.get_parameters(
        mean=mean, sd=sd
    )
    # NOTE: We have to override these, otherwise Gamma is overly conservative in what values
    # are computable
    # https://github.com/ihmeuw/risk_distributions/issues/61
    gamma_params["x_min"] = x_min
    gamma_params["x_max"] = x_max
    hemoglobin_distribution_gamma_part = risk_distributions.risk_distributions.Gamma(
        gamma_params
    )

    # NOTE: Forced to duplicate https://github.com/ihmeuw/risk_distributions/blob/a9ed9d7e8372590018355012a7a7ffefa87b0819/src/risk_distributions/risk_distributions.py#L428-L434
    # because it doesn't permit the custom x_min and x_max, and these are used in calculating the others
    mgumbel_params = pd.DataFrame({
        "loc": x_max - mean - (np.euler_gamma * np.sqrt(6) / np.pi * sd),
        "scale": np.sqrt(6) / np.pi * sd,
        "x_min": x_min,
        "x_max": x_max,
    })
    hemoglobin_distribution_mgumbel_part = (
        risk_distributions.risk_distributions.MirroredGumbel(mgumbel_params)
    )
    return hemoglobin_distribution_gamma_part, hemoglobin_distribution_mgumbel_part

(
    hemoglobin_distribution_gamma_part,
    hemoglobin_distribution_mgumbel_part,
) = _hemoglobin_distribution_parts_from_mean_sd(mean_and_sd_hgb['mean'], mean_and_sd_hgb.sd)

def cdf(x):
    gamma_cdf = hemoglobin_distribution_gamma_part.cdf(x)
    # NOTE: There is a bug in this CDF function -- it is reversed!
    # https://github.com/ihmeuw/risk_distributions/issues/62
    mgumbel_cdf = 1 - hemoglobin_distribution_mgumbel_part.cdf(x)
    return (
        0.4
        * gamma_cdf
        + 0.6
        * mgumbel_cdf
    )

In [49]:
mean_and_sd_hgb["severe"] = cdf(mean_and_sd_hgb.hgb_upper_severe.copy()) - cdf(mean_and_sd_hgb.hgb_lower_severe.copy())
mean_and_sd_hgb["moderate"] = cdf(mean_and_sd_hgb.hgb_upper_moderate.copy()) - mean_and_sd_hgb["severe"].copy()
mean_and_sd_hgb["mild"] = cdf(mean_and_sd_hgb.hgb_upper_mild.copy()) - mean_and_sd_hgb["moderate"].copy() - mean_and_sd_hgb["severe"].copy()
mean_and_sd_hgb["anemic"] = mean_and_sd_hgb["mild"] + mean_and_sd_hgb["moderate"] + mean_and_sd_hgb["severe"]
mean_and_sd_hgb

,sex,age_start,age_end,wealth_quintile,draw,mean,sd,scenario,pregnant,hgb_lower_severe,hgb_upper_mild,hgb_upper_moderate,hgb_upper_severe,severe,moderate,mild,anemic
0,Female,0.0,0.019178,lowest,draw_0,138.477305,10.934018,baseline,0,0,160,145,100,0.003702,0.708900,0.275391,0.987992
1,Female,0.0,0.019178,lowest,draw_1,138.622225,15.248582,baseline,0,0,160,145,100,0.014031,0.625490,0.306242,0.945762
2,Female,0.0,0.019178,lowest,draw_2,140.460574,12.793660,baseline,0,0,160,145,100,0.005898,0.605890,0.349860,0.961648
3,Female,0.0,0.019178,lowest,draw_3,139.921181,13.952230,baseline,0,0,160,145,100,0.008843,0.607235,0.334980,0.951058
4,Female,0.0,0.019178,lowest,draw_4,138.651285,12.875777,baseline,0,0,160,145,100,0.007315,0.663041,0.302771,0.973128
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,Male,95.0,125.000000,second,draw_495,102.264838,40.066317,intervention,0,0,130,110,80,0.259645,0.298072,0.200246,0.757964
249996,Male,95.0,125.000000,second,draw_496,102.548445,38.387469,intervention,0,0,130,110,80,0.250609,0.306695,0.208659,0.765963
249997,Male,95.0,125.000000,second,draw_497,101.871760,37.724615,intervention,0,0,130,110,80,0.253340,0.312616,0.210960,0.776916
249998,Male,95.0,125.000000,second,draw_498,103.187056,36.310437,intervention,0,0,130,110,80,0.236032,0.317487,0.220419,0.773938
249999,Male,95.0,125.000000,second,draw_499,103.252294,32.870911,intervention,0,0,130,110,80,0.217514,0.341701,0.240633,0.799848

In [50]:
disability_weights = pd.read_hdf('/mnt/team/simulation_science/costeffectiveness/auxiliary_data/GBD_2021/02_processed_data/disability_weight/sequela/all/all.hdf')
disability_weights = disability_weights[disability_weights.healthstate.isin(['anemia_mild', 'anemia_mod', 'anemia_sev'])].set_index('healthstate').filter(like='draw_')
disability_weights.columns.name = 'draw'
disability_weights = disability_weights.stack().rename('disability_weight').reset_index()
disability_weights

      healthstate      draw  disability_weight
0     anemia_mild    draw_0           0.002420
1     anemia_mild    draw_1           0.003172
2     anemia_mild    draw_2           0.002644
3     anemia_mild    draw_3           0.003085
4     anemia_mild    draw_4           0.001845
...           ...       ...                ...
2995   anemia_sev  draw_995           0.174969
2996   anemia_sev  draw_996           0.086798
2997   anemia_sev  draw_997           0.131996
2998   anemia_sev  draw_998           0.124427
2999   anemia_sev  draw_999           0.138260

[3000 rows x 3 columns]

In [51]:
mean_and_sd_hgb = mean_and_sd_hgb.merge(
    disability_weights[disability_weights.healthstate == 'anemia_mild'][['draw', 'disability_weight']].rename(columns={'disability_weight': 'mild_dw'}),
    validate="m:1",
).merge(
    disability_weights[disability_weights.healthstate == 'anemia_mod'][['draw', 'disability_weight']].rename(columns={'disability_weight': 'moderate_dw'}),
    validate="m:1",
).merge(
    disability_weights[disability_weights.healthstate == 'anemia_sev'][['draw', 'disability_weight']].rename(columns={'disability_weight': 'severe_dw'}),
    validate="m:1",
)

In [52]:
mean_and_sd_hgb["mild_ylds"] = mean_and_sd_hgb.mild * mean_and_sd_hgb.mild_dw
mean_and_sd_hgb["moderate_ylds"] = mean_and_sd_hgb.moderate * mean_and_sd_hgb.moderate_dw
mean_and_sd_hgb["severe_ylds"] = mean_and_sd_hgb.severe * mean_and_sd_hgb.severe_dw
mean_and_sd_hgb['anemic_ylds'] = mean_and_sd_hgb['mild_ylds'] + mean_and_sd_hgb['moderate_ylds'] + mean_and_sd_hgb['severe_ylds']

In [53]:
index_cols = ['age_start', 'age_end', 'sex', 'draw', "wealth_quintile"]
value_cols = ["mild", "moderate", "severe", "anemic", "mild_ylds", "moderate_ylds", "severe_ylds", "anemic_ylds"]

baseline_anemia = mean_and_sd_hgb[mean_and_sd_hgb.scenario == 'baseline'].set_index(index_cols)[value_cols]
counterfactual_anemia = mean_and_sd_hgb[mean_and_sd_hgb.scenario == 'intervention'].set_index(index_cols)[value_cols]

In [54]:
baseline_anemia.sort_index()

                                                         mild  moderate  \
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth           0.413781  0.546932
                                    highest          0.463321  0.487676
                                    lowest           0.275391  0.708900
                                    middle           0.357673  0.615561
                                    second           0.349879  0.627360
...                                                       ...       ...
95.0      125.000000 Male   draw_99 fourth           0.214769  0.304197
                                    highest          0.225362  0.310701
                                    lowest           0.213739  0.312407
                                    middle           0.210380  0.302651
                                    second           0.213321  0.307401

                                                       severe    anemic  \
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth           0.002629  0.963342
                                    highest          0.001802  0.952800
                                    lowest           0.003702  0.987992
                                    middle           0.003241  0.976474
                                    second           0.002917  0.980155
...                                                       ...       ...
95.0      125.000000 Male   draw_99 fourth           0.230727  0.749693
                                    highest          0.214819  0.750882
                                    lowest           0.245789  0.771936
                                    middle           0.239584  0.752615
                                    second           0.239426  0.760147

                                                     mild_ylds  moderate_ylds  \
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth            0.001002       0.032433
                                    highest           0.001121       0.028919
                                    lowest            0.000667       0.042038
                                    middle            0.000866       0.036503
                                    second            0.000847       0.037203
...                                                        ...            ...
95.0      125.000000 Male   draw_99 fourth            0.000902       0.012679
                                    highest           0.000947       0.012950
                                    lowest            0.000898       0.013021
                                    middle            0.000884       0.012615
                                    second            0.000896       0.012813

                                                     severe_ylds  anemic_ylds
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth              0.000523     0.033958
                                    highest             0.000358     0.030399
                                    lowest              0.000736     0.043441
                                    middle              0.000645     0.038013
                                    second              0.000580     0.038630
...                                                          ...          ...
95.0      125.000000 Male   draw_99 fourth              0.027407     0.040988
                                    highest             0.025517     0.039414
                                    lowest              0.029196     0.043115
                                    middle              0.028459     0.041957
                                    second              0.028440     0.042149

[125000 rows x 8 columns]

In [55]:
counterfactual_anemia.sort_index()

                                                         mild  moderate  \
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth           0.434127  0.519577
                                    highest          0.485402  0.453858
                                    lowest           0.296323  0.686518
                                    middle           0.378990  0.590375
                                    second           0.370811  0.603425
...                                                       ...       ...
95.0      125.000000 Male   draw_99 fourth           0.215401  0.302192
                                    highest          0.226245  0.307459
                                    lowest           0.214354  0.311121
                                    middle           0.210957  0.301026
                                    second           0.213885  0.305968

                                                       severe    anemic  \
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth           0.002417  0.956121
                                    highest          0.001620  0.940880
                                    lowest           0.003446  0.986287
                                    middle           0.003001  0.972366
                                    second           0.002712  0.976948
...                                                       ...       ...
95.0      125.000000 Male   draw_99 fourth           0.225941  0.743534
                                    highest          0.208121  0.741826
                                    lowest           0.242340  0.767814
                                    middle           0.235406  0.747389
                                    second           0.235758  0.755611

                                                     mild_ylds  moderate_ylds  \
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth            0.001051       0.030811
                                    highest           0.001175       0.026914
                                    lowest            0.000717       0.040711
                                    middle            0.000917       0.035010
                                    second            0.000898       0.035783
...                                                        ...            ...
95.0      125.000000 Male   draw_99 fourth            0.000905       0.012596
                                    highest           0.000950       0.012815
                                    lowest            0.000900       0.012968
                                    middle            0.000886       0.012547
                                    second            0.000898       0.012753

                                                     severe_ylds  anemic_ylds
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth              0.000481     0.032343
                                    highest             0.000322     0.028411
                                    lowest              0.000686     0.042114
                                    middle              0.000597     0.036524
                                    second              0.000539     0.037220
...                                                          ...          ...
95.0      125.000000 Male   draw_99 fourth              0.026839     0.040339
                                    highest             0.024722     0.038487
                                    lowest              0.028786     0.042655
                                    middle              0.027963     0.041396
                                    second              0.028005     0.041656

[125000 rows x 8 columns]

In [56]:
baseline_anemia - counterfactual_anemia

                                                         mild  moderate  \
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth          -0.020346  0.027355
                                    highest         -0.022081  0.033818
                                    lowest          -0.020932  0.022382
                                    middle          -0.021317  0.025185
                                    second          -0.020933  0.023935
...                                                       ...       ...
95.0      125.000000 Male   draw_99 fourth          -0.000631  0.002005
                                    highest         -0.000883  0.003242
                                    lowest          -0.000614  0.001287
                                    middle          -0.000577  0.001625
                                    second          -0.000564  0.001433

                                                       severe    anemic  \
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth           0.000211  0.007221
                                    highest          0.000182  0.011920
                                    lowest           0.000256  0.001706
                                    middle           0.000240  0.004108
                                    second           0.000205  0.003207
...                                                       ...       ...
95.0      125.000000 Male   draw_99 fourth           0.004785  0.006159
                                    highest          0.006697  0.009056
                                    lowest           0.003449  0.004121
                                    middle           0.004178  0.005226
                                    second           0.003667  0.004536

                                                     mild_ylds  moderate_ylds  \
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth           -0.000049       0.001622
                                    highest          -0.000053       0.002005
                                    lowest           -0.000051       0.001327
                                    middle           -0.000052       0.001494
                                    second           -0.000051       0.001419
...                                                        ...            ...
95.0      125.000000 Male   draw_99 fourth           -0.000003       0.000084
                                    highest          -0.000004       0.000135
                                    lowest           -0.000003       0.000054
                                    middle           -0.000002       0.000068
                                    second           -0.000002       0.000060

                                                     severe_ylds  anemic_ylds
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth              0.000042     0.001615
                                    highest             0.000036     0.001988
                                    lowest              0.000051     0.001327
                                    middle              0.000048     0.001490
                                    second              0.000041     0.001409
...                                                          ...          ...
95.0      125.000000 Male   draw_99 fourth              0.000568     0.000649
                                    highest             0.000796     0.000927
                                    lowest              0.000410     0.000461
                                    middle              0.000496     0.000562
                                    second              0.000436     0.000493

[125000 rows x 8 columns]

In [57]:
# BUT our counterfactual is only in a world where everyone is iron-responsive.
# Cleaned this up from https://github.com/ihmeuw/vivarium_research_lsff/blob/1cb465a752d299401ae366db537dc8d557162184/multiplication_models/iron_model_U5.ipynb,
# but have not checked it in extreme detail.
iron_responsive_anemia_sequelae = [
    gbd_mapping.sequelae.mild_anemia_due_to_schistosomiasis,
    gbd_mapping.sequelae.moderate_anemia_due_to_schistosomiasis,
    gbd_mapping.sequelae.severe_anemia_due_to_schistosomiasis,
    gbd_mapping.sequelae.mild_anemia_due_to_hookworm_disease,
    gbd_mapping.sequelae.moderate_anemia_due_to_hookworm_disease,
    gbd_mapping.sequelae.severe_anemia_due_to_hookworm_disease,
    gbd_mapping.sequelae.mild_anemia_due_to_other_neglected_tropical_diseases,
    gbd_mapping.sequelae.moderate_anemia_due_to_other_neglected_tropical_diseases,
    gbd_mapping.sequelae.severe_anemia_due_to_other_neglected_tropical_diseases,
    gbd_mapping.sequelae.mild_anemia_due_to_maternal_hemorrhage,
    gbd_mapping.sequelae.moderate_anemia_due_to_maternal_hemorrhage,
    gbd_mapping.sequelae.severe_anemia_due_to_maternal_hemorrhage,
    gbd_mapping.sequelae.mild_iron_deficiency_anemia,
    gbd_mapping.sequelae.moderate_iron_deficiency_anemia,
    gbd_mapping.sequelae.severe_iron_deficiency_anemia,
    gbd_mapping.sequelae.mild_anemia_due_to_other_infectious_diseases,
    gbd_mapping.sequelae.moderate_anemia_due_to_other_infectious_diseases,
    gbd_mapping.sequelae.severe_anemia_due_to_other_infectious_diseases,
    gbd_mapping.sequelae.menstrual_disorders_with_mild_anemia,
    gbd_mapping.sequelae.menstrual_disorders_with_moderate_anemia,
    gbd_mapping.sequelae.menstrual_disorders_with_severe_anemia,
    gbd_mapping.sequelae.stage_3_chronic_kidney_disease_due_to_hypertension_with_mild_anemia,
    gbd_mapping.sequelae.stage_3_chronic_kidney_disease_due_to_hypertension_with_moderate_anemia,
    gbd_mapping.sequelae.stage_3_chronic_kidney_disease_due_to_hypertension_with_severe_anemia,
    gbd_mapping.sequelae.stage_3_chronic_kidney_disease_due_to_glomerulonephritis_with_mild_anemia,
    gbd_mapping.sequelae.stage_3_chronic_kidney_disease_due_to_glomerulonephritis_with_moderate_anemia,
    gbd_mapping.sequelae.stage_3_chronic_kidney_disease_due_to_glomerulonephritis_with_severe_anemia,
    gbd_mapping.sequelae.stage_3_chronic_kidney_disease_due_to_other_and_unspecified_causes_with_mild_anemia,
    gbd_mapping.sequelae.stage_3_chronic_kidney_disease_due_to_other_and_unspecified_causes_with_moderate_anemia,
    gbd_mapping.sequelae.stage_3_chronic_kidney_disease_due_to_other_and_unspecified_causes_with_severe_anemia,
    gbd_mapping.sequelae.uterine_fibroids_symptomatic_with_mild_anemia,
    gbd_mapping.sequelae.uterine_fibroids_symptomatic_with_moderate_anemia,
    gbd_mapping.sequelae.uterine_fibroids_symptomatic_with_severe_anemia,
    gbd_mapping.sequelae.stage_5_chronic_kidney_disease_untreated_due_to_hypertension_with_mild_anemia,
    gbd_mapping.sequelae.stage_5_chronic_kidney_disease_untreated_due_to_hypertension_with_moderate_anemia,
    gbd_mapping.sequelae.stage_5_chronic_kidney_disease_untreated_due_to_hypertension_with_severe_anemia,
    gbd_mapping.sequelae.stage_5_chronic_kidney_disease_untreated_due_to_glomerulonephritis_with_mild_anemia,
    gbd_mapping.sequelae.stage_5_chronic_kidney_disease_untreated_due_to_glomerulonephritis_with_moderate_anemia,
    gbd_mapping.sequelae.stage_5_chronic_kidney_disease_untreated_due_to_glomerulonephritis_with_severe_anemia,
    gbd_mapping.sequelae.stage_5_chronic_kidney_disease_untreated_due_to_other_and_unspecified_causes_with_mild_anemia,
    gbd_mapping.sequelae.stage_5_chronic_kidney_disease_untreated_due_to_other_and_unspecified_causes_with_moderate_anemia,
    gbd_mapping.sequelae.stage_5_chronic_kidney_disease_untreated_due_to_other_and_unspecified_causes_with_severe_anemia,
    gbd_mapping.sequelae.stage_4_chronic_kidney_disease_untreated_due_to_hypertension_with_mild_anemia,
    gbd_mapping.sequelae.stage_4_chronic_kidney_disease_untreated_due_to_hypertension_with_moderate_anemia,
    gbd_mapping.sequelae.stage_4_chronic_kidney_disease_untreated_due_to_hypertension_with_severe_anemia,
    gbd_mapping.sequelae.stage_4_chronic_kidney_disease_untreated_due_to_glomerulonephritis_with_mild_anemia,
    gbd_mapping.sequelae.stage_4_chronic_kidney_disease_untreated_due_to_glomerulonephritis_with_moderate_anemia,
    gbd_mapping.sequelae.stage_4_chronic_kidney_disease_untreated_due_to_glomerulonephritis_with_severe_anemia,
    gbd_mapping.sequelae.stage_4_chronic_kidney_disease_untreated_due_to_other_and_unspecified_causes_with_mild_anemia,
    gbd_mapping.sequelae.stage_4_chronic_kidney_disease_untreated_due_to_other_and_unspecified_causes_with_moderate_anemia,
    gbd_mapping.sequelae.stage_4_chronic_kidney_disease_untreated_due_to_other_and_unspecified_causes_with_severe_anemia,
    gbd_mapping.sequelae.mildly_symptomatic_pud_with_mild_anemia,
    gbd_mapping.sequelae.moderately_symptomatic_pud_with_mild_anemia,
    gbd_mapping.sequelae.mildly_symptomatic_pud_with_moderate_anemia,
    gbd_mapping.sequelae.moderately_symptomatic_pud_with_moderate_anemia,
    gbd_mapping.sequelae.mildly_symptomatic_pud_with_severe_anemia,
    gbd_mapping.sequelae.moderately_symptomatic_pud_with_severe_anemia,
    gbd_mapping.sequelae.asymptomatic_pud_with_mild_anemia,
    gbd_mapping.sequelae.asymptomatic_pud_with_moderate_anemia,
    gbd_mapping.sequelae.asymptomatic_pud_with_severe_anemia,
    gbd_mapping.sequelae.mildy_symptomatic_gastritis_duodenitis_with_mild_anemia,
    gbd_mapping.sequelae.moderately_symptomatic_gastritis_duodenitis_with_mild_anemia,
    gbd_mapping.sequelae.mildly_symptomatic_gastritis_duodenitis_with_moderate_anemia,
    gbd_mapping.sequelae.moderately_symptomatic_gastritis_duodenitis_with_moderate_anemia,
    gbd_mapping.sequelae.mildy_symptomatic_gastritis_duodenitis_with_severe_anemia,
    gbd_mapping.sequelae.moderately_symptomatic_gastritis_duodenitis_with_severe_anemia,
    gbd_mapping.sequelae.asymptomatic_gastritis_duodenitis_with_mild_anemia,
    gbd_mapping.sequelae.asymptomatic_gastritis_duodenitis_with_moderate_anemia,
    gbd_mapping.sequelae.asymptomatic_gastritis_duodenitis_with_severe_anemia,
    gbd_mapping.sequelae.stage_3_chronic_kidney_disease_due_to_type_1_diabetes_mellitus_with_severe_anemia,
    gbd_mapping.sequelae.stage_3_chronic_kidney_disease_due_to_type_2_diabetes_mellitus_with_severe_anemia,
    gbd_mapping.sequelae.stage_3_chronic_kidney_disease_due_to_type_1_diabetes_mellitus_with_moderate_anemia,
    gbd_mapping.sequelae.stage_3_chronic_kidney_disease_due_to_type_2_diabetes_mellitus_with_mdoerate_anemia,
    gbd_mapping.sequelae.stage_3_chronic_kidney_disease_due_to_type_1_diabetes_mellitus_with_mild_anemia,
    gbd_mapping.sequelae.stage_3_chronic_kidney_disease_due_to_type_2_diabetes_mellitus_with_mild_anemia,
    gbd_mapping.sequelae.stage_4_chronic_kidney_disease_untreated_due_to_type_1_diabetes_mellitus_with_severe_anemia,
    gbd_mapping.sequelae.stage_4_chronic_kidney_disease_untreated_due_to_type_2_diabetes_mellitus_with_severe_anemia,
    gbd_mapping.sequelae.stage_4_chronic_kidney_disease_untreated_due_to_type_1_diabetes_mellitus_with_moderate_anemia,
    gbd_mapping.sequelae.stage_4_chronic_kidney_disease_untreated_due_to_type_2_diabetes_mellitus_with_mdoerate_anemia,
    gbd_mapping.sequelae.stage_4_chronic_kidney_disease_untreated_due_to_type_1_diabetes_mellitus_with_mild_anemia,
    gbd_mapping.sequelae.stage_4_chronic_kidney_disease_untreated_due_to_type_2_diabetes_mellitus_with_mild_anemia,
    gbd_mapping.sequelae.stage_5_chronic_kidney_disease_untreated_due_to_type_1_diabetes_mellitus_with_severe_anemia,
    gbd_mapping.sequelae.stage_5_chronic_kidney_disease_untreated_due_to_type_2_diabetes_mellitus_with_severe_anemia,
    gbd_mapping.sequelae.stage_5_chronic_kidney_disease_untreated_due_to_type_1_diabetes_mellitus_with_moderate_anemia,
    gbd_mapping.sequelae.stage_5_chronic_kidney_disease_untreated_due_to_type_2_diabetes_mellitus_with_moderate_anemia,
    gbd_mapping.sequelae.stage_5_chronic_kidney_disease_untreated_due_to_type_1_diabetes_mellitus_with_mild_anemia,
    gbd_mapping.sequelae.stage_5_chronic_kidney_disease_untreated_due_to_type_2_diabetes_mellitus_with_mild_anemia,
    gbd_mapping.sequelae.vitamin_a_deficiency_with_mild_anemia,
    gbd_mapping.sequelae.vitamin_a_deficiency_with_moderate_anemia,
    gbd_mapping.sequelae.vitamin_a_deficiency_with_severe_anemia,
    gbd_mapping.sequelae.ulcerative_colitis_with_mild_anemia,
    gbd_mapping.sequelae.ulcerative_colitis_with_moderate_anemia,
    gbd_mapping.sequelae.ulcerative_colitis_with_severe_anemia,
    gbd_mapping.sequelae.crohns_disease_with_mild_anemia,
    gbd_mapping.sequelae.crohns_disease_with_moderate_anemia,
    gbd_mapping.sequelae.crohns_disease_with_severe_anemia,
    gbd_mapping.sequelae.complicated_pud_with_mild_anemia,
    gbd_mapping.sequelae.complicated_pud_with_moderate_anemia,
    gbd_mapping.sequelae.complicated_pud_with_severe_anemia,
    gbd_mapping.sequelae.complicated_gastritis_duodenitis_with_mild_anemia,
    gbd_mapping.sequelae.complicated_gastritis_duodenitis_with_moderate_anemia,
    gbd_mapping.sequelae.complicated_gastritis_duodenitis_with_severe_anemia,
    gbd_mapping.sequelae.severe_acute_uncomplicated_pud_with_mild_anemia,
    gbd_mapping.sequelae.severe_acute_uncomplicated_pud_with_moderate_anemia,
    gbd_mapping.sequelae.severe_acute_uncomplicated_pud_with_severe_anemia,
    gbd_mapping.sequelae.severe_acute_uncomplicated_gastritis_duodenitis_with_mild_anemia,
    gbd_mapping.sequelae.severe_acute_uncomplicated_gastritis_duodenitis_with_moderate_anemia,
    gbd_mapping.sequelae.severe_acute_uncomplicated_gastritis_duodenitis_with_severe_anemia,
    gbd_mapping.sequelae.end_stage_renal_disease_on_dialysis_due_to_type_1_diabetes_mellitus_with_mild_anemia,
    gbd_mapping.sequelae.end_stage_renal_disease_on_dialysis_due_to_type_2_diabetes_mellitus_with_mild_anemia,
    gbd_mapping.sequelae.end_stage_renal_disease_on_dialysis_due_to_hypertension_with_mild_anemia,
    gbd_mapping.sequelae.end_stage_renal_disease_on_dialysis_due_to_glomerulonephritis_with_mild_anemia,
    gbd_mapping.sequelae.end_stage_renal_disease_on_dialysis_due_to_other_and_unspecified_causes_with_mild_anemia,
    gbd_mapping.sequelae.end_stage_renal_disease_on_dialysis_due_to_type_1_diabetes_mellitus_with_moderate_anemia,
    gbd_mapping.sequelae.end_stage_renal_disease_on_dialysis_due_to_type_2_diabetes_mellitus_with_moderate_anemia,
    gbd_mapping.sequelae.end_stage_renal_disease_on_dialysis_due_to_hypertension_with_moderate_anemia,
    gbd_mapping.sequelae.end_stage_renal_disease_on_dialysis_due_to_glomerulonephritis_with_moderate_anemia,
    gbd_mapping.sequelae.end_stage_renal_disease_on_dialysis_due_to_other_and_unspecified_causes_with_moderate_anemia,
    gbd_mapping.sequelae.end_stage_renal_disease_on_dialysis_due_to_type_1_diabetes_mellitus_with_severe_anemia,
    gbd_mapping.sequelae.end_stage_renal_disease_on_dialysis_due_to_type_2_diabetes_mellitus_with_severe_anemia,
    gbd_mapping.sequelae.end_stage_renal_disease_on_dialysis_due_to_hypertension_with_severe_anemia,
    gbd_mapping.sequelae.end_stage_renal_disease_on_dialysis_due_to_glomerulonephritis_with_severe_anemia,
    gbd_mapping.sequelae.end_stage_renal_disease_on_dialysis_due_to_other_and_unspecified_causes_with_severe_anemia,
    gbd_mapping.sequelae.cirrhosis_and_other_chronic_liver_diseases_due_to_hepatitis_b_decompensated_with_mild_anemia,
    gbd_mapping.sequelae.cirrhosis_and_other_chronic_liver_diseases_due_to_hepatitis_b_decompensated_with_moderate_anemia,
    gbd_mapping.sequelae.cirrhosis_and_other_chronic_liver_diseases_due_to_hepatitis_b_decompensated_with_severe_anemia,
    gbd_mapping.sequelae.cirrhosis_and_other_chronic_liver_diseases_due_to_hepatitis_c_decompensated_with_mild_anemia,
    gbd_mapping.sequelae.cirrhosis_and_other_chronic_liver_diseases_due_to_hepatitis_c_decompensated_with_moderate_anemia,
    gbd_mapping.sequelae.cirrhosis_and_other_chronic_liver_diseases_due_to_hepatitis_c_decompensated_with_severe_anemia,
    gbd_mapping.sequelae.cirrhosis_and_other_chronic_liver_diseases_due_to_alcohol_decompensated_with_mild_anemia,
    gbd_mapping.sequelae.cirrhosis_and_other_chronic_liver_diseases_due_to_alcohol_decompensated_with_moderate_anemia,
    gbd_mapping.sequelae.cirrhosis_and_other_chronic_liver_diseases_due_to_alcohol_decompensated_with_severe_anemia,
    gbd_mapping.sequelae.cirrhosis_and_other_chronic_liver_diseases_due_to_other_decompensated_with_mild_anemia,
    gbd_mapping.sequelae.cirrhosis_and_other_chronic_liver_diseases_due_to_other_decompensated_with_moderate_anemia,
    gbd_mapping.sequelae.cirrhosis_and_other_chronic_liver_diseases_due_to_other_decompensated_with_severe_anemia,
    gbd_mapping.sequelae.cirrhosis_and_other_chronic_liver_diseases_due_to_nash_decompensated_with_mild_anemia,
    gbd_mapping.sequelae.cirrhosis_and_other_chronic_liver_diseases_due_to_nash_decompensated_with_moderate_anemia,
    gbd_mapping.sequelae.cirrhosis_and_other_chronic_liver_diseases_due_to_nash_decompensated_with_severe_anemia,
]

In [58]:
non_iron_responsive_anemia_sequelae = [
    gbd_mapping.sequelae.mild_anemia_due_to_other_hemoglobinopathies_and_hemolytic_anemias,
    gbd_mapping.sequelae.moderate_anemia_due_to_other_hemoglobinopathies_and_hemolytic_anemias,
    gbd_mapping.sequelae.severe_anemia_due_to_other_hemoglobinopathies_and_hemolytic_anemias,
    gbd_mapping.sequelae.mild_anemia_due_to_b_thalassemia_trait,
    gbd_mapping.sequelae.moderate_anemia_due_to_b_thalassemia_trait,
    gbd_mapping.sequelae.severe_anemia_due_to_b_thalassemia_trait,
    gbd_mapping.sequelae.mild_anemia_due_to_hemoglobin_e_trait,
    gbd_mapping.sequelae.moderate_anemia_due_to_hemoglobin_e_trait,
    gbd_mapping.sequelae.severe_anemia_due_to_hemoglobin_e_trait,
    gbd_mapping.sequelae.mild_anemia_due_to_sickle_cell_trait,
    gbd_mapping.sequelae.moderate_anemia_due_to_sickle_cell_trait,
    gbd_mapping.sequelae.severe_anemia_due_to_sickle_cell_trait,
    gbd_mapping.sequelae.hemizygous_g6pd_deficiency_with_mild_anemia,
    gbd_mapping.sequelae.hemizygous_g6pd_deficiency_with_moderate_anemia,
    gbd_mapping.sequelae.hemizygous_g6pd_deficiency_with_severe_anemia,
    gbd_mapping.sequelae.mild_anemia_due_to_malaria_parasitemia_pfpr,
    gbd_mapping.sequelae.moderate_anemia_due_to_malaria_parasitemia_pfpr,
    gbd_mapping.sequelae.severe_anemia_due_to_malaria_parasitemia_pfpr,
    gbd_mapping.sequelae.mild_anemia_due_to_homozygous_sickle_cell_and_severe_sickle_cell_beta_thalassemia,
    gbd_mapping.sequelae.moderate_anemia_due_to_homozygous_sickle_cell_and_severe_sickle_cell_beta_thalassemia,
    gbd_mapping.sequelae.severe_anemia_due_to_homozygous_sickle_cell_and_severe_sickle_cell_beta_thalassemia,
    gbd_mapping.sequelae.mild_anemia_due_to_hemoglobin_sc_disease,
    gbd_mapping.sequelae.moderate_anemia_due_to_hemoglobin_sc_disease,
    gbd_mapping.sequelae.severe_anemia_due_to_hemoglobin_sc_disease,
    gbd_mapping.sequelae.mild_anemia_due_to_mild_sickle_cell_beta_thalassemia,
    gbd_mapping.sequelae.moderate_anemia_due_to_mild_sickle_cell_beta_thalassemia,
    gbd_mapping.sequelae.severe_anemia_due_to_mild_sickle_cell_beta_thalassemia,
    gbd_mapping.sequelae.severe_malaria_with_mild_anemia,
    gbd_mapping.sequelae.severe_malaria_with_moderate_anemia,
    gbd_mapping.sequelae.severe_malaria_with_severe_anemia,
    gbd_mapping.sequelae.mild_malaria_with_mild_anemia,
    gbd_mapping.sequelae.mild_malaria_with_moderate_anemia,
    gbd_mapping.sequelae.mild_malaria_with_severe_anemia,
    gbd_mapping.sequelae.moderate_malaria_with_mild_anemia,
    gbd_mapping.sequelae.moderate_malaria_with_moderate_anemia,
    gbd_mapping.sequelae.moderate_malaria_with_severe_anemia,
    gbd_mapping.sequelae.early_hiv_with_mild_anemia,
    gbd_mapping.sequelae.early_hiv_with_moderate_anemia,
    gbd_mapping.sequelae.early_hiv_with_severe_anemia,
    gbd_mapping.sequelae.symptomatic_hiv_with_mild_anemia,
    gbd_mapping.sequelae.symptomatic_hiv_with_moderate_anemia,
    gbd_mapping.sequelae.symptomatic_hiv_with_severe_anemia,
    gbd_mapping.sequelae.hiv_aids_with_antiretroviral_treatment_with_mild_anemia,
    gbd_mapping.sequelae.hiv_aids_with_antiretroviral_treatment_with_moderate_anemia,
    gbd_mapping.sequelae.hiv_aids_with_antiretroviral_treatment_with_severe_anemia,
    gbd_mapping.sequelae.aids_with_mild_anemia,
    gbd_mapping.sequelae.aids_with_moderate_anemia,
    gbd_mapping.sequelae.aids_with_severe_anemia,
    gbd_mapping.sequelae.hiv_aids_drug_susceptible_tuberculosis_with_mild_anemia,
    gbd_mapping.sequelae.hiv_aids_drug_susceptible_tuberculosis_with_moderate_anemia,
    gbd_mapping.sequelae.hiv_aids_drug_susceptible_tuberculosis_with_severe_anemia,
    gbd_mapping.sequelae.hiv_aids_multidrug_resistant_tuberculosis_without_extensive_drug_resistance_with_mild_anemia,
    gbd_mapping.sequelae.hiv_aids_multidrug_resistant_tuberculosis_without_extensive_drug_resistance_with_moderate_anemia,
    gbd_mapping.sequelae.hiv_aids_multidrug_resistant_tuberculosis_without_extensive_drug_resistance_with_severe_anemia,
    gbd_mapping.sequelae.hiv_aids_extensively_drug_resistant_tuberculosis_with_mild_anemia,
    gbd_mapping.sequelae.hiv_aids_extensively_drug_resistant_tuberculosis_with_moderate_anemia,
    gbd_mapping.sequelae.hiv_aids_extensively_drug_resistant_tuberculosis_with_severe_anemia,
    gbd_mapping.sequelae.mild_anemia_due_to_malaria_vivax_pvpr,
    gbd_mapping.sequelae.moderate_anemia_due_to_malaria_vivax_pvpr,
    gbd_mapping.sequelae.severe_anemia_due_to_malaria_vivax_pvpr,
]

In [59]:
len(iron_responsive_anemia_sequelae)

138

In [60]:
len(non_iron_responsive_anemia_sequelae)

60

In [61]:
loguru.logger.disable("vivarium_inputs.validation.raw")

In [62]:
iron_responsive_prevalence = None

for sequela in tqdm(iron_responsive_anemia_sequelae):
    try:
        sequela_prevalence = vivarium_inputs.get_measure(sequela, "prevalence", location.title()).droplevel(["location", "year_start", "year_end"])
    except DataDoesNotExistError as e:
        assert 'zero' in str(e)
        continue
    except DataAbnormalError as e:
        assert 'zero' in str(e)
        continue

    if iron_responsive_prevalence is None:
        iron_responsive_prevalence = sequela_prevalence
    else:
        iron_responsive_prevalence += sequela_prevalence

  0%|          | 0/138 [00:00<?, ?it/s]

In [63]:
non_iron_responsive_prevalence = None

for sequela in tqdm(non_iron_responsive_anemia_sequelae):
    try:
        sequela_prevalence = vivarium_inputs.get_measure(sequela, "prevalence", location.title()).droplevel(["location", "year_start", "year_end"])
    except DataDoesNotExistError as e:
        assert 'zero' in str(e)
        continue
    except DataAbnormalError as e:
        assert 'zero' in str(e)
        continue

    if non_iron_responsive_prevalence is None:
        non_iron_responsive_prevalence = sequela_prevalence
    else:
        non_iron_responsive_prevalence += sequela_prevalence

  0%|          | 0/60 [00:00<?, ?it/s]

In [64]:
loguru.logger.enable("vivarium_inputs.validation.raw")

In [65]:
iron_responsive_prevalence.columns.name = "draw"
iron_responsive_prevalence = iron_responsive_prevalence.stack().pipe(lambda s: s[s.index.get_level_values("draw").isin(DRAWS)])
iron_responsive_prevalence

sex     age_start  age_end     draw
Female  0.0        0.019178    draw_0      0.870859
                               draw_1      0.834114
                               draw_2      0.837499
                               draw_3      0.801072
                               draw_4      0.794379
                                             ...
Male    95.0       125.000000  draw_495    0.657506
                               draw_496    0.624656
                               draw_497    0.643068
                               draw_498    0.633495
                               draw_499    0.653186
Length: 25000, dtype: float64

In [66]:
non_iron_responsive_prevalence.columns.name = "draw"
non_iron_responsive_prevalence = non_iron_responsive_prevalence.stack().pipe(lambda s: s[s.index.get_level_values("draw").isin(DRAWS)])
non_iron_responsive_prevalence

sex     age_start  age_end     draw
Female  0.0        0.019178    draw_0      0.056061
                               draw_1      0.052256
                               draw_2      0.055149
                               draw_3      0.047436
                               draw_4      0.053121
                                             ...
Male    95.0       125.000000  draw_495    0.097808
                               draw_496    0.091776
                               draw_497    0.093861
                               draw_498    0.093842
                               draw_499    0.097005
Length: 25000, dtype: float64

In [67]:
iron_responsive_proportion = iron_responsive_prevalence / (iron_responsive_prevalence + non_iron_responsive_prevalence)
iron_responsive_proportion

sex     age_start  age_end     draw
Female  0.0        0.019178    draw_0      0.939519
                               draw_1      0.941045
                               draw_2      0.938219
                               draw_3      0.944095
                               draw_4      0.937320
                                             ...
Male    95.0       125.000000  draw_495    0.870507
                               draw_496    0.871899
                               draw_497    0.872632
                               draw_498    0.870979
                               draw_499    0.870693
Length: 25000, dtype: float64

In [68]:
assert (iron_responsive_proportion <= 1).all()

In [69]:
iron_responsive_proportion.sort_values()

sex     age_start  age_end    draw
Male    15.0       20.000000  draw_329    0.726722
                              draw_338    0.730490
        20.0       25.000000  draw_314    0.737482
        15.0       20.000000  draw_4      0.737639
        20.0       25.000000  draw_123    0.738444
                                            ...
Female  0.0        0.019178   draw_60     0.947937
                              draw_83     0.948082
                              draw_220    0.948098
                              draw_425    0.948795
                              draw_75     0.948839
Length: 25000, dtype: float64

In [70]:
# NOTE: I am pretty sure this is correct, but it is quite difficult to think through *why*.

# First, observe that people in the population who start as non-anemic never factor into
# any of these metrics. If they started non-anemic, our counterfactual can only shift them up,
# so they did not change anemia categories between scenarios and hence have no importance to
# anemia prevalence or YLDs.

# So you can think of our hemoglobin distributions as only being of interest in the part
# of them below the anemia threshold.

# *Within* this subpopulation, we make the assumption that iron-responsive and non-iron-responsive
# anemic people have the same distributions of hemoglobin. This is probably not true, but GBD doesn't
# give us anything better.

# So you can think of our original distribution as a mixture of two parts, which are the same.
# Then we shift one of those parts (the iron-responsive part) and calculate all these stats from
# that new distribution.

# Our *actual* result should be about a mixture distribution that has the non-iron-responsive part
# the same as in baseline, with the shifted iron-responsive part.
# For all these metrics, it is pretty straightforward to see that the metric in such a mixture is
# just a weighted average of the metrics in each part, since they all depend on CDFs which combine
# this way.

counterfactual_anemia_accounting_for_non_response = (
    counterfactual_anemia.mul(iron_responsive_proportion, axis=0) +
    baseline_anemia.mul(1 - iron_responsive_proportion, axis=0)
)
counterfactual_anemia_accounting_for_non_response

                                                         mild  moderate  \
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth           0.432896  0.521232
                                    highest          0.484067  0.455904
                                    lowest           0.295057  0.687872
                                    middle           0.377700  0.591898
                                    second           0.369545  0.604873
...                                                       ...       ...
95.0      125.000000 Male   draw_99 fourth           0.215312  0.302474
                                    highest          0.226121  0.307916
                                    lowest           0.214267  0.311302
                                    middle           0.210876  0.301255
                                    second           0.213806  0.306169

                                                       severe    anemic  \
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth           0.002430  0.956558
                                    highest          0.001631  0.941601
                                    lowest           0.003462  0.986390
                                    middle           0.003015  0.972614
                                    second           0.002724  0.977142
...                                                       ...       ...
95.0      125.000000 Male   draw_99 fourth           0.226615  0.744401
                                    highest          0.209064  0.743101
                                    lowest           0.242825  0.768394
                                    middle           0.235994  0.748124
                                    second           0.236275  0.756250

                                                     mild_ylds  moderate_ylds  \
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth            0.001048       0.030909
                                    highest           0.001172       0.027035
                                    lowest            0.000714       0.040791
                                    middle            0.000914       0.035100
                                    second            0.000894       0.035869
...                                                        ...            ...
95.0      125.000000 Male   draw_99 fourth            0.000904       0.012607
                                    highest           0.000950       0.012834
                                    lowest            0.000900       0.012975
                                    middle            0.000886       0.012557
                                    second            0.000898       0.012761

                                                     severe_ylds  anemic_ylds
age_start age_end    sex    draw    wealth_quintile
0.0       0.019178   Female draw_0  fourth              0.000483     0.032441
                                    highest             0.000324     0.028531
                                    lowest              0.000689     0.042194
                                    middle              0.000600     0.036614
                                    second              0.000542     0.037306
...                                                          ...          ...
95.0      125.000000 Male   draw_99 fourth              0.026919     0.040430
                                    highest             0.024834     0.038618
                                    lowest              0.028844     0.042719
                                    middle              0.028033     0.041475
                                    second              0.028066     0.041725

[125000 rows x 8 columns]

In [71]:
assert ((baseline_anemia - counterfactual_anemia_accounting_for_non_response).anemic_ylds > 0).all()

In [72]:
baseline_ylds = (baseline_anemia.anemic_ylds.unstack("draw").mean(axis=1) * non_pregnant_pop)
baseline_ylds

age_start  age_end     sex     wealth_quintile
0.0        0.019178    Female  fourth             1059.997610
                               highest             769.541848
                               lowest             1801.271863
                               middle             1244.355229
                               second             1419.783311
                                                     ...
95.0       125.000000  Male    fourth              894.100061
                               highest            1059.690219
                               lowest              827.604317
                               middle              868.092670
                               second              844.438359
Length: 250, dtype: float64

In [73]:
intervention_ylds = (counterfactual_anemia_accounting_for_non_response.anemic_ylds.unstack("draw").mean(axis=1) * non_pregnant_pop)

In [74]:
baseline_ylds.groupby(["wealth_quintile"]).sum() - intervention_ylds.groupby(["wealth_quintile"]).sum()

wealth_quintile
fourth     134418.148177
highest    168446.428250
lowest     123170.634922
middle     128389.677916
second     117541.167482
dtype: float64

In [75]:
ylds = pd.concat([
    baseline_ylds.rename("value").reset_index().assign(scenario="baseline"),
    intervention_ylds.rename("value").reset_index().assign(scenario="intervention")
], ignore_index=True)
ylds

     age_start     age_end     sex wealth_quintile        value      scenario
0          0.0    0.019178  Female          fourth  1059.997610      baseline
1          0.0    0.019178  Female         highest   769.541848      baseline
2          0.0    0.019178  Female          lowest  1801.271863      baseline
3          0.0    0.019178  Female          middle  1244.355229      baseline
4          0.0    0.019178  Female          second  1419.783311      baseline
..         ...         ...     ...             ...          ...           ...
495       95.0  125.000000    Male          fourth   881.484946  intervention
496       95.0  125.000000    Male         highest  1037.502802  intervention
497       95.0  125.000000    Male          lowest   819.728976  intervention
498       95.0  125.000000    Male          middle   857.744221  intervention
499       95.0  125.000000    Male          second   835.642500  intervention

[500 rows x 6 columns]

In [76]:
results_dir = f'./results/{vehicle.lower()}/{location.lower()}/{intervention_scenario.lower()}'

In [77]:
path = f'{results_dir}/ylds.parquet'
pathlib.Path(path).parent.mkdir(exist_ok=True, parents=True)
ylds.to_parquet(path)

In [78]:
baseline_anemia_prevalence = baseline_anemia['anemic'].unstack("draw").mean(axis=1)
baseline_anemia_prevalence

age_start  age_end     sex     wealth_quintile
0.0        0.019178    Female  fourth             0.917220
                               highest            0.900539
                               lowest             0.965487
                               middle             0.940266
                               second             0.947353
                                                    ...
95.0       125.000000  Male    fourth             0.762443
                               highest            0.763989
                               lowest             0.784717
                               middle             0.765232
                               second             0.772893
Length: 250, dtype: float64

In [79]:
baseline_anemia_cases = baseline_anemia_prevalence.mul(non_pregnant_pop, axis=0)
baseline_anemia_cases

age_start  age_end     sex     wealth_quintile
0.0        0.019178    Female  fourth             33424.279506
                               highest            26298.067393
                               lowest             47936.142149
                               middle             36378.268813
                               second             41281.501854
                                                      ...
95.0       125.000000  Male    fourth             13163.809909
                               highest            16264.929961
                               lowest             11909.410763
                               middle             12526.984211
                               second             12249.198027
Length: 250, dtype: float64

In [80]:
baseline_anemia_cases.sum() / non_pregnant_pop.sum()

0.4130474930130347

In [81]:
baseline_anemia_cases.groupby(["wealth_quintile"]).sum() / non_pregnant_pop.groupby(["wealth_quintile"]).sum()

wealth_quintile
fourth     0.392112
highest    0.367032
lowest     0.464735
middle     0.416044
second     0.426803
dtype: float64

In [82]:
intervention_anemia_prevalence = counterfactual_anemia_accounting_for_non_response['anemic'].unstack("draw").mean(axis=1)
intervention_anemia_prevalence

age_start  age_end     sex     wealth_quintile
0.0        0.019178    Female  fourth             0.906810
                               highest            0.885088
                               lowest             0.961508
                               middle             0.933052
                               second             0.941240
                                                    ...
95.0       125.000000  Male    fourth             0.757056
                               highest            0.756073
                               lowest             0.781134
                               middle             0.760664
                               second             0.768936
Length: 250, dtype: float64

In [83]:
anemia_prevalence = pd.concat([
    baseline_anemia_prevalence.rename("value").reset_index().assign(scenario="baseline"),
    intervention_anemia_prevalence.rename("value").reset_index().assign(scenario="intervention")
], ignore_index=True)
anemia_prevalence

     age_start     age_end     sex wealth_quintile     value      scenario
0          0.0    0.019178  Female          fourth  0.917220      baseline
1          0.0    0.019178  Female         highest  0.900539      baseline
2          0.0    0.019178  Female          lowest  0.965487      baseline
3          0.0    0.019178  Female          middle  0.940266      baseline
4          0.0    0.019178  Female          second  0.947353      baseline
..         ...         ...     ...             ...       ...           ...
495       95.0  125.000000    Male          fourth  0.757056  intervention
496       95.0  125.000000    Male         highest  0.756073  intervention
497       95.0  125.000000    Male          lowest  0.781134  intervention
498       95.0  125.000000    Male          middle  0.760664  intervention
499       95.0  125.000000    Male          second  0.768936  intervention

[500 rows x 6 columns]

In [84]:
path = f'{results_dir}/anemia_prevalence.parquet'
pathlib.Path(path).parent.mkdir(exist_ok=True, parents=True)
anemia_prevalence.to_parquet(path)

In [85]:
intervention_anemia_cases = intervention_anemia_prevalence.mul(non_pregnant_pop, axis=0)
intervention_anemia_cases

age_start  age_end     sex     wealth_quintile
0.0        0.019178    Female  fourth             33044.907875
                               highest            25846.870322
                               lowest             47738.591671
                               middle             36099.172689
                               second             41015.107357
                                                      ...
95.0       125.000000  Male    fourth             13070.805034
                               highest            16096.398796
                               lowest             11855.030768
                               middle             12452.202185
                               second             12186.489671
Length: 250, dtype: float64

In [86]:
intervention_anemia_cases.sum() / non_pregnant_pop.sum()

0.4008263788165891

In [87]:
intervention_anemia_cases.groupby(["wealth_quintile"]).sum() / non_pregnant_pop.groupby(["wealth_quintile"]).sum()

wealth_quintile
fourth     0.379731
highest    0.350495
lowest     0.454383
middle     0.404654
second     0.416440
dtype: float64

In [88]:
(baseline_anemia_cases.groupby(["wealth_quintile"]).sum() - intervention_anemia_cases.groupby(["wealth_quintile"]).sum()).map(lambda x: f'{round(x):,.0f}')

wealth_quintile
fourth     3,472,008
highest    4,657,447
lowest     2,839,037
middle     3,181,152
second     2,876,375
dtype: object

In [89]:
anemia_cases = pd.concat([
    baseline_anemia_cases.rename("value").reset_index().assign(scenario="baseline"),
    intervention_anemia_cases.rename("value").reset_index().assign(scenario="intervention")
], ignore_index=True)
anemia_cases

     age_start     age_end     sex wealth_quintile         value      scenario
0          0.0    0.019178  Female          fourth  33424.279506      baseline
1          0.0    0.019178  Female         highest  26298.067393      baseline
2          0.0    0.019178  Female          lowest  47936.142149      baseline
3          0.0    0.019178  Female          middle  36378.268813      baseline
4          0.0    0.019178  Female          second  41281.501854      baseline
..         ...         ...     ...             ...           ...           ...
495       95.0  125.000000    Male          fourth  13070.805034  intervention
496       95.0  125.000000    Male         highest  16096.398796  intervention
497       95.0  125.000000    Male          lowest  11855.030768  intervention
498       95.0  125.000000    Male          middle  12452.202185  intervention
499       95.0  125.000000    Male          second  12186.489671  intervention

[500 rows x 6 columns]

In [90]:
path = f'{results_dir}/anemia_cases.parquet'
pathlib.Path(path).parent.mkdir(exist_ok=True, parents=True)
anemia_cases.to_parquet(path)