In [1]:
import pandas as pd, numpy as np

In [2]:
df = pd.DataFrame({
    'scaled_surv_0': [0.5, 0.75],
    'scaled_surv_1': [0.4, 0.75],
    'lambda_years': [1, 2],
})
df

   scaled_surv_0  scaled_surv_1  lambda_years
0           0.50           0.40             1
1           0.75           0.75             2

In [3]:
num_draws = 2

In [4]:
df[[f'surv_abs_{i}' for i in range(num_draws)]] = df.filter(like='scaled_surv_').mul(np.exp(df.lambda_years), axis=0).rename(columns=lambda c: c.replace('scaled_surv_', 'surv_abs_'))
df

   scaled_surv_0  scaled_surv_1  lambda_years  surv_abs_0  surv_abs_1
0           0.50           0.40             1    1.359141    1.087313
1           0.75           0.75             2    5.541792    5.541792