In [1]:
import numpy as np, matplotlib.pyplot as plt, pandas as pd

pd.set_option("display.max_rows", 8)
!date

Mon Aug 24 22:27:12 PDT 2026

# Mean deaths and stillbirths averted by adding folate by wealth quintile

In [2]:
import vivarium_inputs
import db_queries
import vivarium.gbd_mapping as gbd_mapping
import pathlib
from lsff_utils import config_utils

In [3]:
location = "india"
vehicle = "rice"

In [4]:
# Parameters
location = "ethiopia"
vehicle = "salt"

In [5]:
intervention_scenarios = config_utils.get_config()["custom_intervention_scenarios"].get(
    location, ["intervention"]
)
intervention_scenarios

['intervention_25_nrv', 'intervention_100_nrv']

## Forecasted births and stillbirths

In [6]:
asfr = vivarium_inputs.get_measure(
    gbd_mapping.covariates.age_specific_fertility_rate,
    "estimate",
    location.title(),
    years=2022,
).value

2026-08-24 22:27:17.165 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:17.221 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:17.226 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 22:27:17.254 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:17.255 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:17.260 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 22:27:17.266 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:17.268 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:17.272 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_annual_years'

2026-08-24 22:27:17.277 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:17.278 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:17.302 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_covariate_estimate'

2026-08-24 22:27:17.328 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:17.329 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:17.333 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_age_group_id'

2026-08-24 22:27:17.339 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:17.341 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:17.344 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_path_to_global'

2026-08-24 22:27:17.362 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:17.363 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:17.366 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_estimation_years'

2026-08-24 22:27:17.373 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:17.383 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:17.386 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_annual_years'

2026-08-24 22:27:17.392 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:17.393 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:17.396 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_age_bins'

2026-08-24 22:27:17.407 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:17.409 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:17.413 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_estimation_years'

2026-08-24 22:27:17.428 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:17.430 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:17.434 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_annual_years'

2026-08-24 22:27:17.440 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:17.440 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:17.445 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_age_group_id'

2026-08-24 22:27:17.466 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:17.467 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:17.472 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 22:27:17.478 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:17.480 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:17.486 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 22:27:17.497 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:17.497 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:17.500 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_age_bins'

2026-08-24 22:27:17.513 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:17.514 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:17.517 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 22:27:17.524 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:17.525 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:17.528 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 22:27:17.535 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:17.536 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:17.539 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_age_bins'

In [7]:
asfr = asfr[asfr.index.get_level_values("parameter") == "mean_value"].droplevel(
    "parameter"
)

In [8]:
# Scale ASFR in each category down proportionally to the scale-down in TFR forecasted from GBD 2017
if location == "india":
    asfr_2030_to_2022_ratio = 1.61 / 1.91  # http://ihmeuw.org/6j8s
elif location == "nigeria":
    asfr_2030_to_2022_ratio = 4.43 / 4.96  # http://ihmeuw.org/6jqx
elif location == "ethiopia":
    asfr_2030_to_2022_ratio = 3.27 / 4.10  # http://ihmeuw.org/6j7d

asfr = asfr * asfr_2030_to_2022_ratio
asfr[asfr > 0]

location  sex     age_start  age_end  year_start  year_end
Ethiopia  Female  10.0       15.0     2022        2023        0.002380
                  15.0       20.0     2022        2023        0.039140
                  20.0       25.0     2022        2023        0.149981
                  25.0       30.0     2022        2023        0.146846
                                                                ...
                  35.0       40.0     2022        2023        0.105399
                  40.0       45.0     2022        2023        0.050481
                  45.0       50.0     2022        2023        0.014600
                  50.0       55.0     2022        2023        0.001324
Name: value, Length: 9, dtype: float64

In [9]:
asfr = (
    asfr.reset_index()
    .assign(year_start=2030, year_end=2031)
    .set_index(asfr.index.names)
    .value
)
asfr.sort_values()

location  sex     age_start  age_end    year_start  year_end
Ethiopia  Female  0.000000   0.019178   2030        2031        0.000000
                  0.019178   0.076712   2030        2031        0.000000
                  0.076712   0.500000   2030        2031        0.000000
                  0.500000   1.000000   2030        2031        0.000000
                                                                  ...
                  35.000000  40.000000  2030        2031        0.105399
                  30.000000  35.000000  2030        2031        0.146170
                  25.000000  30.000000  2030        2031        0.146846
                  20.000000  25.000000  2030        2031        0.149981
Name: value, Length: 50, dtype: float64

In [10]:
from vivarium_inputs import utilities
from vivarium_inputs.utility_data import get_location_id
from vivarium_gbd_access.gbd import get_age_group_id, SEX, RELEASE_IDS

In [11]:
def get_population_future(location, year):
    # Cobbled together from pieces of vivarium_inputs and vivarium_gbd_access
    # TODO: vivarium_inputs should be able to get forecasted pop!
    location_id = get_location_id(location)
    year_id = year
    data = db_queries.get_population(
        age_group_id=get_age_group_id(),
        location_id=location_id,
        year_id=year_id,
        sex_id=SEX.MALE + SEX.FEMALE + SEX.COMBINED,
        release_id=RELEASE_IDS.GBD_2021,
        forecasted_pop=True,
    )
    data = utilities.normalize_sex(
        data.drop("run_id", axis="columns").rename(columns={"population": "value"}),
        fill_value=None,
        cols_to_fill=utilities.DRAW_COLUMNS,
    )
    data = utilities.reshape(data, ["value"])
    data = utilities.scrub_gbd_conventions(data, location)
    data = utilities.split_interval(
        data, interval_column="age", split_column_prefix="age"
    )
    data = utilities.split_interval(
        data, interval_column="year", split_column_prefix="year"
    )
    return utilities.sort_hierarchical_data(data)

In [12]:
pop = get_population_future(location.title(), 2030).value.reindex(asfr.index)
pop

/tmp/ipykernel_4105752/2995218429.py:4: DeprecationWarning: get_location_id is deprecated. Use resolve_location instead.
  location_id = get_location_id(location)
2026-08-24 22:27:17.969 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:17.970 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:17.974 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 22:27:17.980 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:17.981 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:17.984 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_age_group_id'

2026-08-24 22:27:18.252 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:18.253 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:18.257 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 22:27:18.264 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:18.265 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:18.269 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 22:27:18.282 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:18.284 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:18.288 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_age_bins'

location  sex     age_start  age_end     year_start  year_end
Ethiopia  Female  0.000000   0.019178    2030        2031         34555.502815
                  0.019178   0.076712    2030        2031        102821.618998
                  0.076712   0.500000    2030        2031                  NaN
                  0.500000   1.000000    2030        2031                  NaN
                                                                     ...
          Male    80.000000  85.000000   2030        2031        215000.475056
                  85.000000  90.000000   2030        2031        100478.541795
                  90.000000  95.000000   2030        2031         33156.550480
                  95.000000  125.000000  2030        2031          8245.199268
Name: value, Length: 50, dtype: float64

In [13]:
# Forecasted population does not have younger ages, but luckily none of these are WRA
assert (pop.index.get_level_values("age_end")[pop.isna()] < 10).all()
pop[pop.isna()]

location  sex     age_start  age_end  year_start  year_end
Ethiopia  Female  0.076712   0.5      2030        2031       NaN
                  0.500000   1.0      2030        2031       NaN
                  1.000000   2.0      2030        2031       NaN
                  2.000000   5.0      2030        2031       NaN
          Male    0.076712   0.5      2030        2031       NaN
                  0.500000   1.0      2030        2031       NaN
                  1.000000   2.0      2030        2031       NaN
                  2.000000   5.0      2030        2031       NaN
Name: value, dtype: float64

In [14]:
pop = pop.fillna(0)

In [15]:
n_births = (pop * asfr).sum()
n_births

3748464.620344746

In [16]:
sbr = vivarium_inputs.get_measure(
    # GBD 2023 split this covariate into 20-week and 28-week variants and dropped
    # the unqualified one. Using 28 weeks to match data_keys.SBR in the maternal
    # sim, so the two stages share a stillbirth definition. NOTE this is not the
    # continuity-preserving choice: for Nigeria, GBD 2021's unqualified ratio was
    # 0.0387, the GBD 2023 20-week variant is 0.0436 (1.13x) and the 28-week is
    # 0.0265 (0.68x). So this cuts the stillbirth ratio by about a third versus
    # the published results. Needs a research decision.
    gbd_mapping.covariates.stillbirth_28_weeks_to_live_birth_ratio,
    "estimate",
    location.title(),
    years=2022,
).value
sbr

2026-08-24 22:27:18.496 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:18.498 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:18.501 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 22:27:18.510 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:18.511 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:18.514 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 22:27:18.521 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:18.522 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:18.526 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_annual_years'

2026-08-24 22:27:18.535 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:18.535 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:18.550 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_covariate_estimate'

2026-08-24 22:27:18.573 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:18.574 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:18.578 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_age_group_id'

2026-08-24 22:27:18.584 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:18.586 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:18.589 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_path_to_global'

2026-08-24 22:27:18.600 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:18.603 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:18.608 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_estimation_years'

2026-08-24 22:27:18.614 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:18.614 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:18.618 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_annual_years'

2026-08-24 22:27:18.626 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:18.628 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:18.641 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_estimation_years'

2026-08-24 22:27:18.645 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:18.647 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:18.650 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_annual_years'

2026-08-24 22:27:18.655 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:18.656 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:18.659 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_age_group_id'

2026-08-24 22:27:18.673 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:18.675 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:18.687 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 22:27:18.692 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:18.693 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:18.696 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 22:27:18.708 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:18.710 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:18.715 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 22:27:18.724 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:18.725 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:18.729 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 22:27:18.735 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:18.736 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:18.743 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_age_bins'

location  year_start  year_end  parameter
Ethiopia  2022        2023      lower_value    0.019748
                                mean_value     0.023416
                                upper_value    0.028076
Name: value, dtype: float64

In [17]:
sbr = sbr[sbr.index.get_level_values("parameter") == "mean_value"].droplevel(
    "parameter"
)
sbr

location  year_start  year_end
Ethiopia  2022        2023        0.023416
Name: value, dtype: float64

In [18]:
sbr = sbr.values[0]

In [19]:
births_and_stillbirths = n_births + n_births * sbr
births_and_stillbirths / 1e6

3.836239907227637

## Fertility (technically birth-and-stillbirth) disparities

In [20]:
if location == "india":
    dist_births_and_stillbirths_by_wealth = pd.Series(  # from file:///J:/DATA/DHS_PROG_DHS/IND/2019_2021/IND_DHS7_2019_2021_REP_FINAL_Y2022M05D11.PDF
        {  # Table 8.4 Perinatal mortality -- using "Number of pregnancies of 7 or more months' duration" as a proxy
            1: 56_979,
            2: 50_335,
            3: 45_189,
            4: 42_611,
            5: 36_290,
        }
    )
elif location == "nigeria":
    dist_births_and_stillbirths_by_wealth = pd.Series(  # from file:///J:/DATA/DHS_PROG_DHS/NGA/2018/NGA_DHS7_2018_REP_QUEST_Y2019M11D05.PDF
        {  # Table 8.4 Perinatal mortality
            1: 7_712,
            2: 7_886,
            3: 7_139,
            4: 6_328,
            5: 5_558,
        }
    )
elif location == "ethiopia":
    dist_births_and_stillbirths_by_wealth = pd.Series(  # from file:///J:/DATA/DHS_PROG_DHS/ETH/2016/ETH_DHS7_2016_REP_QUEST_Y2017M08D15.PDF
        {  # Table 8.4 Perinatal mortality
            1: 2_645,
            2: 2_516,
            3: 2_290,
            4: 2_018,
            5: 1_592,
        }
    )

dist_births_and_stillbirths_by_wealth.index.name = "wealth_quintile"

s_births = (
    n_births
    * dist_births_and_stillbirths_by_wealth
    / dist_births_and_stillbirths_by_wealth.sum()
)
s_births

wealth_quintile
1    896364.607252
2    852647.770074
3    776058.582460
4    683880.445155
5    539513.215404
dtype: float64

In [21]:
s_births_and_stillbirths_by_wealth = (
    births_and_stillbirths
    * dist_births_and_stillbirths_by_wealth
    / dist_births_and_stillbirths_by_wealth.sum()
)
s_births_and_stillbirths_by_wealth

wealth_quintile
1    917354.177255
2    872613.652164
3    794231.026811
4    699894.415766
5    552146.635232
dtype: float64

In [22]:
# http://ihmeuw.org/6jr2 -- extracted from GBD Foresight, count of NTD deaths in 2030 for under-1 year olds
# from GBD 2021
if location == "india":
    ntd_deaths = 4_273.37
elif location == "nigeria":
    ntd_deaths = 5_373.52
elif location == "ethiopia":
    ntd_deaths = 1_883.76


ntd_death_rate_per_birth = ntd_deaths / n_births
10_000 * ntd_death_rate_per_birth

5.025417579709611

In [23]:
# Assumed does not vary by wealth
champs_ntd_stillbirth_per_livebirth = 51 / (69 - 51)
ntd_stillbirths = ntd_deaths * champs_ntd_stillbirth_per_livebirth
10_000 * (
    ntd_deaths + ntd_stillbirths
) / n_births  # ntd rate, compare with 41 per 10,000 from Bhide et al https://pubmed.ncbi.nlm.nih.gov/23873811/

19.26410072222018

We could not find a good source for folate intake by wealth in India, or even a representative source for overall folate intake.  [This paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10755415/pdf/S1368980023002112a.pdf) has an overall number of 220 mcg/day for women, and since it is not too different from the values we found in Ethiopia and Nigeria, we are going to use it for now. (It also has standard deviation of 50, which we can use when we introduce heterogeneity)

In [24]:
if location == "india":
    folate_intake_by_wealth = pd.Series(
        {
            1: 220,
            2: 220,
            3: 220,
            4: 220,
            5: 220,  # NRV is 400 mcg/day
        }
    )
elif location == "nigeria":
    # Table 95 of NFCMS 2021 Report
    folate_intake_by_wealth = pd.Series(
        {
            1: 189,
            2: 198,
            3: 197,
            4: 203,
            5: 208,  # NRV is 400 mcg/day
        }
    )  # how can we use this to estimate disparities in NTD?
elif location == "ethiopia":
    # Table 6 of https://cdn.nutrition.org/article/S2475-2991%2824%2901728-1/fulltext
    folate_intake_by_wealth = pd.Series(
        {
            1: 166,
            2: 152,
            3: 137,
            4: 350,
            5: 469,  # NRV is 400 mcg/day
        }
    )  # how can we use this to estimate disparities in NTD?

folate_intake_by_wealth.index.name = "wealth_quintile"

In [25]:
if location == "india":
    s_dist_deaths_by_wealth = pd.Series(  # Table 7.9 on page 201 of the CNNS report has RBC folate deficiency rates;
        {  # it includes wealth stratification, but has a very low threshold for insufficiency
            1: 1,  # so I am assuming that most everyone is in the danger zone for low folate
            2: 1,
            3: 1,
            4: 1,
            5: 1,
        }
    )
elif location == "nigeria":
    s_dist_deaths_by_wealth = pd.Series(  # assume same rate for all, for now;
        {  # can CHAMPS offer more detail?  Need to infer wealth somehow
            1: 1,
            2: 1,
            3: 1,
            4: 1,
            5: 1,
        }
    )
elif location == "ethiopia":
    s_dist_deaths_by_wealth = pd.Series(
        {  # supplementation studies don't make this easy, but here is a guess
            1: 1,
            2: 1,
            3: 1,
            4: 1,
            5: 1,
        }
    )
    s_dist_deaths_by_wealth /= s_dist_deaths_by_wealth.mean()

s_dist_deaths_by_wealth.index.name = "wealth_quintile"
s_dist_deaths_by_wealth

wealth_quintile
1    1.0
2    1.0
3    1.0
4    1.0
5    1.0
dtype: float64

In [26]:
s_ntd_death_rate_per_birth = ntd_deaths / n_births * s_dist_deaths_by_wealth
10_000 * s_ntd_death_rate_per_birth

wealth_quintile
1    5.025418
2    5.025418
3    5.025418
4    5.025418
5    5.025418
dtype: float64

In [27]:
s_ntd_death_count = s_ntd_death_rate_per_birth * s_births
s_ntd_death_count

wealth_quintile
1    450.460646
2    428.491109
3    390.001844
4    343.678481
5    271.127920
dtype: float64

In [28]:
assert np.isclose(s_ntd_death_count.sum(), ntd_deaths)

In [29]:
s_ntd_stillbirth_count = s_ntd_death_count * champs_ntd_stillbirth_per_livebirth
s_ntd_stillbirth_count

wealth_quintile
1    1276.305162
2    1214.058143
3    1105.005226
4     973.755697
5     768.195773
dtype: float64

In [30]:
s_ntd_death_or_stillbirth_count = s_ntd_death_count + s_ntd_stillbirth_count
s_ntd_death_or_stillbirth_count

wealth_quintile
1    1726.765808
2    1642.549252
3    1495.007070
4    1317.434178
5    1039.323692
dtype: float64

In [31]:
# NOTE: NTD risk here means risk of having an "NTD-affected pregnancy",
# which is a stillbirth due to NTD, OR a birth with NTD (not necessarily fatal!)
# See Kirke 1993 ("Maternal plasma folate and vitamin B12 are independent risk factors for neural tube defects")
# where it says: "Early foetal
# deaths (<23 weeks gestation) attributable to NTDs
# were excluded because of the incomplete ascertain-
# ment of such cases and the difficulty of obtaining a
# valid control group."
# This implies that late foetal deaths, roughly equivalent to stillbirths,
# are included.
def backcalc_rbc(ntd_risk, method):
    """
    ln (odds of NTD risk) = 1.6563 − 1.2193 × ln (RBC) (Daly et al, 1995)
    ln (odds of NTD risk) = 4.57 − 1.70 × ln (RBC) (Crider et al, 2014)
    """

    odds = ntd_risk / (1 - ntd_risk)
    ln_odds = np.log(odds)
    if method == "daly":
        neg_ln_rbc = (ln_odds - 1.6563) / 1.2193
    elif method == "crider":
        neg_ln_rbc = (ln_odds - 4.57) / 1.70
    rbc = np.exp(-neg_ln_rbc)
    return rbc

In [32]:
# From GBD 2021 using GBD Compare, for year 2021
# NTD incident cases / NTD deaths in <1 year olds
# (all of GBD's incident cases are those who survived birth)
if location == "india":
    ntd_death_to_live_birth_case_ratio = 11_796.34 / 5_492.68
elif location == "nigeria":
    ntd_death_to_live_birth_case_ratio = 21_756.56 / 6_231.21
elif location == "ethiopia":
    ntd_death_to_live_birth_case_ratio = 3_982.63 / 2_255.6

ntd_death_to_live_birth_case_ratio

1.765663238162795

In [33]:
s_ntd_live_birth_cases = s_ntd_death_count * ntd_death_to_live_birth_case_ratio
s_ntd_live_birth_cases

wealth_quintile
1    795.361802
2    756.571000
3    688.611919
4    606.820460
5    478.720601
dtype: float64

In [34]:
s_ntd_affected_pregnancies = s_ntd_stillbirth_count + s_ntd_live_birth_cases

In [35]:
ntd_affected_pregnancy_risk = (
    s_ntd_affected_pregnancies / s_births_and_stillbirths_by_wealth
)
ntd_affected_pregnancy_risk

wealth_quintile
1    0.002258
2    0.002258
3    0.002258
4    0.002258
5    0.002258
dtype: float64

In [36]:
s_ntd_death_or_stillbirth_count / s_births

wealth_quintile
1    0.001926
2    0.001926
3    0.001926
4    0.001926
5    0.001926
dtype: float64

In [37]:
backcalc_rbc(ntd_affected_pregnancy_risk, "daly")

wealth_quintile
1    574.668008
2    574.668008
3    574.668008
4    574.668008
5    574.668008
dtype: float64

In [38]:
backcalc_rbc(
    ntd_affected_pregnancy_risk, "crider"
)  # compare with CNNS, https://www.unicef.org/india/media/2646/file/CNNS-report.pdf in Table 7.9
# NOTE: It's a bit hard to compare, due to units issues. That table reports
# proportions under 151 ng/ml. In our units (nmol/L), that is ~342.
# https://www.wolframalpha.com/input?i=151+ng%2Fml+of+folate+to+nmol%2FL

wealth_quintile
1    529.061884
2    529.061884
3    529.061884
4    529.061884
5    529.061884
dtype: float64

In [39]:
pop

location  sex     age_start  age_end     year_start  year_end
Ethiopia  Female  0.000000   0.019178    2030        2031         34555.502815
                  0.019178   0.076712    2030        2031        102821.618998
                  0.076712   0.500000    2030        2031             0.000000
                  0.500000   1.000000    2030        2031             0.000000
                                                                     ...
          Male    80.000000  85.000000   2030        2031        215000.475056
                  85.000000  90.000000   2030        2031        100478.541795
                  90.000000  95.000000   2030        2031         33156.550480
                  95.000000  125.000000  2030        2031          8245.199268
Name: value, Length: 50, dtype: float64

In [40]:
s_pop = pd.read_csv(f"../0100_data_prep/results/population/stratified/{location}.csv")
s_pop = s_pop.set_index([c for c in s_pop.columns if c != "value"])
s_pop

                                                                value
sex    age_start age_end    pregnant     wealth_quintile
Female 0.0       0.019178   not_pregnant 1                8110.649607
                                         2                7372.711095
                                         3                6970.098109
                                         4                6250.761973
...                                                               ...
Male   95.0      125.000000 not_pregnant 2                1527.072977
                                         3                1585.027440
                                         4                1677.097974
                                         5                1469.804071

[285 rows x 1 columns]

In [41]:
# WRA only
s_pop = s_pop[
    (s_pop.index.get_level_values("sex") == "Female")
    & (s_pop.index.get_level_values("age_start") >= 15)
    & (s_pop.index.get_level_values("age_end") <= 50)
].copy()

In [42]:
s_daily_vehicle = pd.read_csv(
    f"../0100_data_prep/results/{vehicle}/vehicle_consumption/amount/mean/{location}.csv"
)
assert (s_daily_vehicle.vehicle_name == vehicle).all()
s_daily_vehicle = s_daily_vehicle.drop(columns=["vehicle_name"])
s_daily_vehicle = s_daily_vehicle.set_index(
    [c for c in s_daily_vehicle.columns if c != "value"]
).value
s_daily_vehicle

wealth_quintile  sex     age_start  age_end
1                Female  15         50         7.1
2                Female  15         50         7.2
3                Female  15         50         7.7
4                Female  15         50         7.2
5                Female  15         50         6.5
Name: value, dtype: float64

In [43]:
from lsff_utils import data_processing

In [44]:
s_daily_vehicle = (
    s_pop.value
    * data_processing.reindex_series_onto_df_by_age_groups(s_pop, s_daily_vehicle)
).groupby("wealth_quintile").sum() / s_pop.value.groupby("wealth_quintile").sum()
s_daily_vehicle

wealth_quintile
1    7.1
2    7.2
3    7.7
4    7.2
5    6.5
Name: value, dtype: float64

In [45]:
any_consumers = pd.read_csv(
    f"../0100_data_prep/results/{vehicle}/vehicle_consumption/any/{location}.csv"
)
assert (any_consumers.vehicle_name == vehicle).all()
any_consumers = any_consumers.drop(columns=["vehicle_name"])
any_consumers = any_consumers.set_index(
    [c for c in any_consumers.columns if c != "value"]
).value
any_consumers

wealth_quintile  sex     age_start  age_end
1                Female  15         50         0.97
2                Female  15         50         0.97
3                Female  15         50         0.97
4                Female  15         50         0.97
5                Female  15         50         0.97
Name: value, dtype: float64

In [46]:
any_consumers = (
    s_pop.value
    * data_processing.reindex_series_onto_df_by_age_groups(s_pop, any_consumers)
).groupby("wealth_quintile").sum() / s_pop.value.groupby("wealth_quintile").sum()
any_consumers

wealth_quintile
1    0.97
2    0.97
3    0.97
4    0.97
5    0.97
Name: value, dtype: float64

In [47]:
s_daily_vehicle_among_consumers = s_daily_vehicle / any_consumers
s_daily_vehicle_among_consumers

wealth_quintile
1    7.319588
2    7.422680
3    7.938144
4    7.422680
5    6.701031
Name: value, dtype: float64

In [48]:
baseline_concentration_mcg_per_gram = pd.read_csv(
    f"../0100_data_prep/results/folate/{vehicle}/baseline_fortification/concentration/{location}.csv"
)
assert (baseline_concentration_mcg_per_gram.vehicle_name == vehicle).all()
assert baseline_concentration_mcg_per_gram.value.nunique() == 1
baseline_concentration_mcg_per_gram = baseline_concentration_mcg_per_gram.value.iloc[0]
baseline_concentration_mcg_per_gram

0.0

In [49]:
intervention_concentration_mcg_per_gram = pd.concat(
    [
        pd.read_csv(
            f"../0100_data_prep/results/folate/{vehicle}/{intervention_scenario}/intervention_fortification/concentration/{location}.csv"
        ).assign(scenario=intervention_scenario)
        for intervention_scenario in intervention_scenarios
    ]
)
assert (intervention_concentration_mcg_per_gram.vehicle_name == vehicle).all()
intervention_concentration_mcg_per_gram = (
    intervention_concentration_mcg_per_gram.drop(columns=["vehicle_name"])
    .set_index("scenario")
    .value
)
intervention_concentration_mcg_per_gram

scenario
intervention_25_nrv     14.084507
intervention_100_nrv    56.338028
Name: value, dtype: float64

In [50]:
eff_fort_baseline_path = f"../0100_data_prep/results/folate/{vehicle}/baseline_fortification/effective_coverage/{location}.csv"

df_eff_fort_baseline = pd.read_csv(eff_fort_baseline_path)
assert (df_eff_fort_baseline.vehicle_name == vehicle).all()

In [51]:
if location == "india" and vehicle == "rice":
    # Confusingly, our baseline scenario (our best guess about the present)
    # is *not* a good guess about 2019-2020 (which is when our baseline folate estimate is from),
    # because this program has rolled out entirely since then:
    # In the phase-I of the roll out, the fortified rice was introduced in the social welfare schemes such as Integrated Child Development Scheme (ICDS)
    # and Pradhan Mantri Poshan Shakti Nirman (PM POSHAN, earlier known as the National Program of Mid-Day Meal in Schools)
    # throughout India during 2021–22 [18].
    # Phase-II has covered aspirational and high burden districts for anemia (total 291 districts) under Public Distribution System (PDS) and other welfare schemes,
    # in addition to Phase-I districts, by March 2023 [18].
    # All the remaining districts in India will be covered in Phase III by March 2024 [19].
    # ~ https://pmc.ncbi.nlm.nih.gov/articles/PMC11305529/
    df_eff_fort_baseline_2019_2020 = df_eff_fort_baseline.assign(value=0)
else:
    df_eff_fort_baseline_2019_2020 = df_eff_fort_baseline

In [52]:
df_eff_fort_intervention = pd.concat(
    [
        pd.read_csv(
            f"../0100_data_prep/results/folate/{vehicle}/{intervention_scenario}/intervention_fortification/effective_coverage/{location}.csv"
        ).assign(scenario=intervention_scenario)
        for intervention_scenario in intervention_scenarios
    ]
)
assert (df_eff_fort_intervention.vehicle_name == vehicle).all()
df_eff_fort_intervention = df_eff_fort_intervention.drop(columns=["vehicle_name"])
df_eff_fort_intervention

    wealth_quintile     sex   value              scenario
0                 1  Female  0.6984   intervention_25_nrv
1                 1    Male  0.6984   intervention_25_nrv
2                 2  Female  0.6984   intervention_25_nrv
3                 2    Male  0.6984   intervention_25_nrv
..              ...     ...     ...                   ...
6                 4  Female  0.6984  intervention_100_nrv
7                 4    Male  0.6984  intervention_100_nrv
8                 5  Female  0.6984  intervention_100_nrv
9                 5    Male  0.6984  intervention_100_nrv

[20 rows x 4 columns]

In [53]:
# NOTE: Using DHS definition of WRA
population = (
    pd.read_csv(f"../0100_data_prep/results/population/stratified/{location}.csv")
    .groupby(["sex", "age_start", "age_end", "wealth_quintile"])
    .value.sum()
    .reset_index()
)
population = population[
    (population.sex == "Female")
    & (population.age_start >= 15)
    & (population.age_end <= 50)
]
population

       sex  age_start  age_end  wealth_quintile         value
40  Female       15.0     20.0                1  1.019154e+06
41  Female       15.0     20.0                2  1.154405e+06
42  Female       15.0     20.0                3  1.160923e+06
43  Female       15.0     20.0                4  1.239019e+06
..     ...        ...      ...              ...           ...
71  Female       45.0     50.0                2  3.496229e+05
72  Female       45.0     50.0                3  3.891729e+05
73  Female       45.0     50.0                4  4.024039e+05
74  Female       45.0     50.0                5  4.670795e+05

[35 rows x 5 columns]

In [54]:
if "sex" in df_eff_fort_baseline_2019_2020.columns:
    df_eff_fort_baseline_2019_2020 = df_eff_fort_baseline_2019_2020[
        (df_eff_fort_baseline_2019_2020.sex == "Female")
    ]

if "age_start" in df_eff_fort_baseline_2019_2020.columns:
    df_eff_fort_baseline_2019_2020 = df_eff_fort_baseline_2019_2020[
        (df_eff_fort_baseline_2019_2020.age_start >= 15)
        & (df_eff_fort_baseline_2019_2020.age_end <= 50)
    ]

In [55]:
if "sex" in df_eff_fort_intervention.columns:
    df_eff_fort_intervention = df_eff_fort_intervention[
        (df_eff_fort_intervention.sex == "Female")
    ]

if "age_start" in df_eff_fort_intervention.columns:
    df_eff_fort_intervention = df_eff_fort_intervention[
        (df_eff_fort_intervention.age_start >= 15)
        & (df_eff_fort_intervention.age_end <= 50)
    ]

In [56]:
def aggregate_using_population(effective_fort):
    merge_cols = [
        c
        for c in ["sex", "wealth_quintile", "age_start", "age_end"]
        if c in effective_fort.columns
    ]
    merged = effective_fort.merge(
        population.reset_index(),
        on=[c for c in merge_cols if "age" not in c],
        suffixes=("_fort", "_pop"),
    )
    assert ("age_start" in merge_cols) == ("age_end" in merge_cols)
    if "age_start" in merge_cols:
        merged = merged[
            (merged.age_start_pop >= merged.age_start_fort)
            & (merged.age_end_pop <= merged.age_end_fort)
        ]
    print(merged)
    assert len(merged) == len(population) * (
        1
        if "scenario" not in effective_fort.columns
        else effective_fort.scenario.nunique()
    )
    group_cols = [c for c in ["scenario", "wealth_quintile"] if c in merged]
    return merged.groupby(group_cols).apply(
        lambda df: (df.value_fort * df.value_pop).sum() / df.value_pop.sum()
    )

In [57]:
df_eff_fort_baseline_2019_2020 = aggregate_using_population(
    df_eff_fort_baseline_2019_2020
)
df_eff_fort_baseline_2019_2020

   vehicle_name  wealth_quintile  value_fort  index     sex  age_start  \
0          salt                1         0.0     40  Female       15.0
1          salt                1         0.0     45  Female       20.0
2          salt                1         0.0     50  Female       25.0
3          salt                1         0.0     55  Female       30.0
..          ...              ...         ...    ...     ...        ...
31         salt                5         0.0     59  Female       30.0
32         salt                5         0.0     64  Female       35.0
33         salt                5         0.0     69  Female       40.0
34         salt                5         0.0     74  Female       45.0

    age_end     value_pop
0      20.0  1.019154e+06
1      25.0  9.466980e+05
2      30.0  8.116082e+05
3      35.0  7.923943e+05
..      ...           ...
31     35.0  9.194147e+05
32     40.0  7.731326e+05
33     45.0  6.274605e+05
34     50.0  4.670795e+05

[35 rows x 8 columns]

wealth_quintile
1    0.0
2    0.0
3    0.0
4    0.0
5    0.0
dtype: float64

In [58]:
df_eff_fort_baseline = aggregate_using_population(df_eff_fort_baseline)
df_eff_fort_baseline

   vehicle_name  wealth_quintile  value_fort  index     sex  age_start  \
0          salt                1         0.0     40  Female       15.0
1          salt                1         0.0     45  Female       20.0
2          salt                1         0.0     50  Female       25.0
3          salt                1         0.0     55  Female       30.0
..          ...              ...         ...    ...     ...        ...
31         salt                5         0.0     59  Female       30.0
32         salt                5         0.0     64  Female       35.0
33         salt                5         0.0     69  Female       40.0
34         salt                5         0.0     74  Female       45.0

    age_end     value_pop
0      20.0  1.019154e+06
1      25.0  9.466980e+05
2      30.0  8.116082e+05
3      35.0  7.923943e+05
..      ...           ...
31     35.0  9.194147e+05
32     40.0  7.731326e+05
33     45.0  6.274605e+05
34     50.0  4.670795e+05

[35 rows x 8 columns]

wealth_quintile
1    0.0
2    0.0
3    0.0
4    0.0
5    0.0
dtype: float64

In [59]:
df_eff_fort_intervention = aggregate_using_population(df_eff_fort_intervention)
df_eff_fort_intervention

    wealth_quintile     sex  value_fort              scenario  index  \
0                 1  Female      0.6984   intervention_25_nrv     40
1                 1  Female      0.6984   intervention_25_nrv     45
2                 1  Female      0.6984   intervention_25_nrv     50
3                 1  Female      0.6984   intervention_25_nrv     55
..              ...     ...         ...                   ...    ...
66                5  Female      0.6984  intervention_100_nrv     59
67                5  Female      0.6984  intervention_100_nrv     64
68                5  Female      0.6984  intervention_100_nrv     69
69                5  Female      0.6984  intervention_100_nrv     74

    age_start  age_end     value_pop
0        15.0     20.0  1.019154e+06
1        20.0     25.0  9.466980e+05
2        25.0     30.0  8.116082e+05
3        30.0     35.0  7.923943e+05
..        ...      ...           ...
66       30.0     35.0  9.194147e+05
67       35.0     40.0  7.731326e+05
68       40.0     45.0  6.274605e+05
69       45.0     50.0  4.670795e+05

[70 rows x 8 columns]

scenario              wealth_quintile
intervention_100_nrv  1                  0.6984
                      2                  0.6984
                      3                  0.6984
                      4                  0.6984
                                          ...
intervention_25_nrv   2                  0.6984
                      3                  0.6984
                      4                  0.6984
                      5                  0.6984
Length: 10, dtype: float64

In [60]:
RBC_baseline = backcalc_rbc(ntd_affected_pregnancy_risk, "crider")
RBC_baseline

wealth_quintile
1    529.061884
2    529.061884
3    529.061884
4    529.061884
5    529.061884
dtype: float64

In [61]:
# Fortification folate needs to be converted into dietary folate equivalents (DFEs)
# for use with our effect size.
# https://www.jandonline.org/article/S0002-8223(00)00027-4/pdf
fortification_mcg_to_dfe = 1.7

In [62]:
# Delete fortification effect baked into our baseline folate estimate.
# In non-India locations, this is going to be zero.
# For India, our current source for baseline folate is very rough,
# but it does appear to be from before the fortification program (2019-2020).
s_zero_folate = folate_intake_by_wealth - (
    df_eff_fort_baseline_2019_2020
    * s_daily_vehicle_among_consumers
    * baseline_concentration_mcg_per_gram
    * fortification_mcg_to_dfe
)

In [63]:
s_baseline_folate = s_zero_folate + (
    df_eff_fort_baseline
    * s_daily_vehicle_among_consumers
    * baseline_concentration_mcg_per_gram
    * fortification_mcg_to_dfe
)
s_baseline_folate

wealth_quintile
1    166.0
2    152.0
3    137.0
4    350.0
5    469.0
dtype: float64

In [64]:
s_intervention_folate = s_zero_folate + (
    df_eff_fort_intervention
    * s_daily_vehicle_among_consumers
    * intervention_concentration_mcg_per_gram
    * fortification_mcg_to_dfe
)
s_intervention_folate

scenario              wealth_quintile
intervention_100_nrv  1                  655.600000
                      2                  648.495775
                      3                  667.974648
                      4                  846.495775
                                            ...
intervention_25_nrv   2                  276.123944
                      3                  269.743662
                      4                  474.123944
                      5                  581.056338
Length: 10, dtype: float64

In [65]:
zero_folate_pct_decrease = (
    folate_intake_by_wealth - s_zero_folate
) / folate_intake_by_wealth

In [66]:
baseline_folate_pct_increase_from_zero = (
    s_baseline_folate - s_zero_folate
) / folate_intake_by_wealth
baseline_folate_pct_increase_from_zero

wealth_quintile
1    0.0
2    0.0
3    0.0
4    0.0
5    0.0
dtype: float64

In [67]:
intevention_folate_pct_increase_from_zero = (
    s_intervention_folate - s_zero_folate
) / folate_intake_by_wealth
intevention_folate_pct_increase_from_zero

scenario              wealth_quintile
intervention_100_nrv  1                  2.949398
                      2                  3.266420
                      3                  3.875727
                      4                  1.418559
                                           ...
intervention_25_nrv   2                  0.816605
                      3                  0.968932
                      4                  0.354640
                      5                  0.238926
Length: 10, dtype: float64

In [68]:
RBC_zero = RBC_baseline / (1 + ((6 / 10) * zero_folate_pct_decrease))
RBC_zero

wealth_quintile
1    529.061884
2    529.061884
3    529.061884
4    529.061884
5    529.061884
dtype: float64

In [69]:
RBC_baseline = RBC_zero * (1 + ((6 / 10) * baseline_folate_pct_increase_from_zero))
RBC_baseline

wealth_quintile
1    529.061884
2    529.061884
3    529.061884
4    529.061884
5    529.061884
dtype: float64

In [70]:
RBC_intervention = RBC_zero * (
    1 + ((6 / 10) * intevention_folate_pct_increase_from_zero)
)
RBC_intervention

scenario              wealth_quintile
intervention_100_nrv  1                  1465.310190
                      2                  1565.944738
                      3                  1759.361653
                      4                   979.365294
                                            ...
intervention_25_nrv   2                   788.282597
                      3                   836.636826
                      4                   641.637736
                      5                   604.905897
Length: 10, dtype: float64

In [71]:
def calc_ntd_pr(df, method):
    ln_rbc = np.log(df)
    if method == "daly":
        ln_odds = 1.6563 - 1.2193 * ln_rbc
    elif method == "crider":
        ln_odds = 4.57 - 1.70 * ln_rbc
    p = np.exp(ln_odds)  # TODO: better transformation
    return p

In [72]:
# NOTE: All rates here are per birth!
s_ntd_affected_pregnancy_rate_zero = calc_ntd_pr(RBC_zero, "crider")
10_000 * s_ntd_affected_pregnancy_rate_zero

wealth_quintile
1    22.634181
2    22.634181
3    22.634181
4    22.634181
5    22.634181
dtype: float64

In [73]:
s_ntd_affected_pregnancy_rate_baseline = calc_ntd_pr(RBC_baseline, "crider")
10_000 * s_ntd_affected_pregnancy_rate_baseline

wealth_quintile
1    22.634181
2    22.634181
3    22.634181
4    22.634181
5    22.634181
dtype: float64

In [74]:
s_ntd_affected_pregnancy_rate_intervention = calc_ntd_pr(RBC_intervention, "crider")
10_000 * s_ntd_affected_pregnancy_rate_intervention

scenario              wealth_quintile
intervention_100_nrv  1                   4.005396
                      2                   3.577716
                      3                   2.935094
                      4                   7.945473
                                           ...
intervention_25_nrv   2                  11.491229
                      3                  10.385154
                      4                  16.305456
                      5                  18.024220
Length: 10, dtype: float64

In [75]:
s_ntd_affected_pregnancies_zero = (
    s_ntd_affected_pregnancy_rate_zero * s_births_and_stillbirths_by_wealth
)
s_ntd_affected_pregnancies_zero

wealth_quintile
1    2076.356013
2    1975.089500
3    1797.676850
4    1584.153661
5    1249.738666
dtype: float64

In [76]:
s_ntd_affected_pregnancies_baseline = (
    s_ntd_affected_pregnancy_rate_baseline * s_births_and_stillbirths_by_wealth
)
s_ntd_affected_pregnancies_baseline

wealth_quintile
1    2076.356013
2    1975.089500
3    1797.676850
4    1584.153661
5    1249.738666
dtype: float64

In [77]:
s_ntd_affected_pregnancies_intervention = (
    s_ntd_affected_pregnancy_rate_intervention * s_births_and_stillbirths_by_wealth
)
s_ntd_affected_pregnancies_intervention

scenario              wealth_quintile
intervention_100_nrv  1                   367.436721
                      2                   312.196372
                      3                   233.114305
                      4                   556.099243
                                            ...
intervention_25_nrv   2                  1002.740347
                      3                   824.821116
                      4                  1141.209778
                      5                   995.201269
Length: 10, dtype: float64

In [78]:
ntd_cases_by_scenario = pd.concat(
    [
        s_ntd_affected_pregnancies_zero.rename("value")
        .to_frame()
        .assign(entity="ntd", scenario="zero")
        .set_index(["entity", "scenario"], append=True)
        .value,
        s_ntd_affected_pregnancies_baseline.rename("value")
        .to_frame()
        .assign(entity="ntd", scenario="baseline")
        .set_index(["entity", "scenario"], append=True)
        .value,
        *[
            s_ntd_affected_pregnancies_intervention.loc[intervention_scenario]
            .rename("value")
            .to_frame()
            .assign(entity="ntd", scenario=intervention_scenario)
            .set_index(["entity", "scenario"], append=True)
            .value
            for intervention_scenario in intervention_scenarios
        ],
    ]
)
ntd_cases_by_scenario

wealth_quintile  entity  scenario
1                ntd     zero                    2076.356013
2                ntd     zero                    1975.089500
3                ntd     zero                    1797.676850
4                ntd     zero                    1584.153661
                                                    ...
2                ntd     intervention_100_nrv     312.196372
3                ntd     intervention_100_nrv     233.114305
4                ntd     intervention_100_nrv     556.099243
5                ntd     intervention_100_nrv     578.338418
Name: value, Length: 20, dtype: float64

In [79]:
(
    ntd_cases_by_scenario[
        ntd_cases_by_scenario.index.get_level_values("scenario") == "baseline"
    ].droplevel("scenario")
    - ntd_cases_by_scenario[
        ntd_cases_by_scenario.index.get_level_values("scenario") == "intervention"
    ].droplevel("scenario")
)

wealth_quintile  entity
1                ntd      NaN
2                ntd      NaN
3                ntd      NaN
4                ntd      NaN
5                ntd      NaN
Name: value, dtype: float64

In [80]:
(
    ntd_cases_by_scenario[
        ntd_cases_by_scenario.index.get_level_values("scenario") == "zero"
    ].droplevel("scenario")
    - ntd_cases_by_scenario[
        ntd_cases_by_scenario.index.get_level_values("scenario") == "baseline"
    ].droplevel("scenario")
)

wealth_quintile  entity
1                ntd       0.0
2                ntd       0.0
3                ntd       0.0
4                ntd       0.0
5                ntd       0.0
Name: value, dtype: float64

In [81]:
path = f"./results/{location}/{vehicle}/ntd_cases_by_scenario.csv"
pathlib.Path(path).parent.mkdir(exist_ok=True, parents=True)
ntd_cases_by_scenario.to_csv(path)

In [82]:
ntd_deaths_and_stillbirths_by_scenario = ntd_cases_by_scenario * (
    s_ntd_death_or_stillbirth_count / s_ntd_affected_pregnancies
)

In [83]:
(
    ntd_deaths_and_stillbirths_by_scenario[
        ntd_deaths_and_stillbirths_by_scenario.index.get_level_values("scenario")
        == "baseline"
    ].droplevel("scenario")
    - ntd_deaths_and_stillbirths_by_scenario[
        ntd_deaths_and_stillbirths_by_scenario.index.get_level_values("scenario")
        == "intervention"
    ].droplevel("scenario")
)

wealth_quintile  entity
1                ntd      NaN
2                ntd      NaN
3                ntd      NaN
4                ntd      NaN
5                ntd      NaN
dtype: float64

In [84]:
(
    ntd_deaths_and_stillbirths_by_scenario[
        ntd_deaths_and_stillbirths_by_scenario.index.get_level_values("scenario")
        == "zero"
    ].droplevel("scenario")
    - ntd_deaths_and_stillbirths_by_scenario[
        ntd_deaths_and_stillbirths_by_scenario.index.get_level_values("scenario")
        == "baseline"
    ].droplevel("scenario")
)

wealth_quintile  entity
1                ntd       0.0
2                ntd       0.0
3                ntd       0.0
4                ntd       0.0
5                ntd       0.0
dtype: float64

In [85]:
# For calculating YLLs
tmrle = vivarium_inputs.get_theoretical_minimum_risk_life_expectancy()
tmrle

2026-08-24 22:27:25.215 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:25.216 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:25.226 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 22:27:25.238 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:25.240 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:25.249 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 22:27:25.262 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:25.263 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:25.268 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_most_recent_year'

2026-08-24 22:27:25.275 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:25.276 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:25.283 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_theoretical_minimum_risk_life_expectancy'

2026-08-24 22:27:25.290 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:25.292 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:25.299 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_age_group_id'

2026-08-24 22:27:25.310 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:25.312 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:25.316 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_path_to_global'

2026-08-24 22:27:25.595 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:25.597 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:25.604 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_most_recent_year'

2026-08-24 22:27:25.611 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:25.613 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:25.619 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 22:27:25.630 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:25.632 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:25.636 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_location_ids'

2026-08-24 22:27:25.643 | DEBUG    | vivarium_gbd_access.utilities:get_memory:61 - Config: 'input_data:
    intermediary_data_cache_path:
        user_configs: /mnt/team/simulation_science/costeffectiveness/vivarium_cache
    cache_data:
        base: True'

2026-08-24 22:27:25.645 | DEBUG    | vivarium_gbd_access.utilities:get_memory:66 - Cache Dir: '/mnt/team/simulation_science/costeffectiveness/vivarium_cache'

2026-08-24 22:27:25.651 | INFO     | vivarium_gbd_access.utilities:wrapper:47 - Using cached data for 'get_age_bins'

                       value
age_start age_end
0.00      0.01     89.958040
0.01      0.02     89.975474
0.02      0.03     89.990990
0.03      0.04     89.985077
...                      ...
109.97    109.98    4.509941
109.98    109.99    4.504631
109.99    110.00    4.499321
110.00    125.00    4.494011

[11001 rows x 1 columns]

In [86]:
# NOTE: Treating stillbirths as a death!
yll_per_stillbirth_or_death = float(tmrle.iloc[0])
yll_per_stillbirth_or_death

89.95803974533831

In [87]:
ylls_by_scenario = (
    ntd_deaths_and_stillbirths_by_scenario * yll_per_stillbirth_or_death
).rename("value")
ylls_by_scenario

wealth_quintile  entity  scenario
1                ntd     zero                    155688.058534
2                ntd     zero                    148094.954734
3                ntd     zero                    134792.307766
4                ntd     zero                    118782.042390
                                                     ...
2                ntd     intervention_100_nrv     23408.917703
3                ntd     intervention_100_nrv     17479.234432
4                ntd     intervention_100_nrv     41697.093827
5                ntd     intervention_100_nrv     43364.618041
Name: value, Length: 20, dtype: float64

In [88]:
path = f"./results/{location}/{vehicle}/ylls_by_scenario.csv"
pathlib.Path(path).parent.mkdir(exist_ok=True, parents=True)
ylls_by_scenario.to_csv(path)