In [1]:
import db_queries
from get_draws.api import get_draws
import pandas as pd, numpy as np

In [2]:
locations = ["india", "nigeria"]
index_cols = ["location", "sex", "age_start", "age_end", "vehicle", "wealth_quintile"]

age_group_ids = [
    2,3,
    388,389,
    6,7,8,9,10,11,12,13,14,15,16,17,18,19,20, 30, 31, 32, 235
]
sex_ids = [1,2]

DRAWS = [f'draw_{i}' for i in range(500)] # NOTE: Some GBD 2021 things return 1,000 but others don't

In [3]:
from vivarium_inputs import utility_data

Config: 'input_data:
    cache_data:
        base: True
    intermediary_data_cache_path:
        base: /share/scratch/users/{username}/cache'
Cache Dir: '/share/scratch/users/zmbc/cache'

In [4]:
location_crosswalk = pd.DataFrame({
    'location': [location.title() for location in locations],
    'location_id': [utility_data.get_location_id(location.title()) for location in locations],
})
location_crosswalk

  location  location_id
0    India          163
1  Nigeria          214

In [5]:
sex_crosswalk = pd.DataFrame({
    'sex': ['Male', 'Female'],
    'sex_id': [1, 2],
})
sex_crosswalk

      sex  sex_id
0    Male       1
1  Female       2

In [6]:
mean_difference = (
    pd.read_csv('../0100_data_prep/results/iron/fortification_hemoglobin_effects.csv')
        .rename(columns={'vehicle_name': 'vehicle'})
        .set_index('vehicle').value
)
mean_difference

vehicle
rice        3.25
salt        4.40
bouillon    4.20
Name: value, dtype: float64

In [7]:
effective_baseline_coverage = pd.concat([
    pd.read_csv(f'../0100_data_prep/results/iron/effective_baseline_coverage/{location}.csv')
        .assign(location=location.title())
        .rename(columns={'vehicle_name': 'vehicle'})
    for location in locations
])
effective_baseline_coverage

       sex  age_start  age_end wealth_quintile   vehicle     value location
0   Female        0.0      5.0          lowest      rice  0.294750    India
1   Female        0.0      5.0          second      rice  0.298731    India
2   Female        0.0      5.0          middle      rice  0.278976    India
3   Female        0.0      5.0          fourth      rice  0.239271    India
4   Female        0.0      5.0         highest      rice  0.137355    India
5   Female        5.0     15.0          lowest      rice  0.384923    India
6   Female        5.0     15.0          second      rice  0.372437    India
7   Female        5.0     15.0          middle      rice  0.344120    India
8   Female        5.0     15.0          fourth      rice  0.298223    India
9   Female        5.0     15.0         highest      rice  0.170117    India
10  Female       15.0     30.0          lowest      rice  0.340118    India
11  Female       15.0     30.0          second      rice  0.347715    India
12  Female       15.0     30.0          middle      rice  0.308190    India
13  Female       15.0     30.0          fourth      rice  0.278779    India
14  Female       15.0     30.0         highest      rice  0.166026    India
15  Female       30.0     50.0          lowest      rice  0.367724    India
16  Female       30.0     50.0          second      rice  0.365385    India
17  Female       30.0     50.0          middle      rice  0.329747    India
18  Female       30.0     50.0          fourth      rice  0.282996    India
19  Female       30.0     50.0         highest      rice  0.151076    India
20  Female       50.0    100.0          lowest      rice  0.384766    India
21  Female       50.0    100.0          second      rice  0.371403    India
22  Female       50.0    100.0          middle      rice  0.335342    India
23  Female       50.0    100.0          fourth      rice  0.282802    India
24  Female       50.0    100.0         highest      rice  0.145853    India
25    Male        0.0      5.0          lowest      rice  0.301125    India
26    Male        0.0      5.0          second      rice  0.304958    India
27    Male        0.0      5.0          middle      rice  0.276643    India
28    Male        0.0      5.0          fourth      rice  0.239590    India
29    Male        0.0      5.0         highest      rice  0.136388    India
30    Male        5.0     15.0          lowest      rice  0.388070    India
31    Male        5.0     15.0          second      rice  0.375826    India
32    Male        5.0     15.0          middle      rice  0.337651    India
33    Male        5.0     15.0          fourth      rice  0.298466    India
34    Male        5.0     15.0         highest      rice  0.165816    India
35    Male       15.0     30.0          lowest      rice  0.361587    India
36    Male       15.0     30.0          second      rice  0.347710    India
37    Male       15.0     30.0          middle      rice  0.305303    India
38    Male       15.0     30.0          fourth      rice  0.281030    India
39    Male       15.0     30.0         highest      rice  0.164437    India
40    Male       30.0     50.0          lowest      rice  0.354325    India
41    Male       30.0     50.0          second      rice  0.351664    India
42    Male       30.0     50.0          middle      rice  0.311270    India
43    Male       30.0     50.0          fourth      rice  0.275204    India
44    Male       30.0     50.0         highest      rice  0.148838    India
45    Male       50.0    100.0          lowest      rice  0.379384    India
46    Male       50.0    100.0          second      rice  0.365984    India
47    Male       50.0    100.0          middle      rice  0.328989    India
48    Male       50.0    100.0          fourth      rice  0.280128    India
49    Male       50.0    100.0         highest      rice  0.145417    India
0      NaN        NaN      NaN          fourth  bouillon  0.535497  Nigeria
1      NaN        NaN      NaN         highest  bouillon  0.559838  Nigeria
2      NaN        NaN      NaN          lowest  bouillon  0.415369  Nigeria
3      NaN        NaN      NaN          middle  bouillon  0.510484  Nigeria
4      NaN        NaN      NaN          second  bouillon  0.467278  Nigeria

In [8]:
def expand(df):
    for col in sorted(list(set(df.columns) - {'value'})):
        if df[col].isnull().any():
            df = pd.concat([
                df[df[col].notnull()],
                *[df[df[col].isnull()].assign(**{col: value}) for value in df[df[col].notnull()][col].unique()]
            ])
    
    return df

In [9]:
effective_baseline_coverage["age_start"] = effective_baseline_coverage.age_start.fillna(0)
effective_baseline_coverage["age_end"] = effective_baseline_coverage.age_end.fillna(100)

In [10]:
effective_baseline_coverage = expand(effective_baseline_coverage)
effective_baseline_coverage

       sex  age_start  age_end wealth_quintile   vehicle     value location
0   Female        0.0      5.0          lowest      rice  0.294750    India
1   Female        0.0      5.0          second      rice  0.298731    India
2   Female        0.0      5.0          middle      rice  0.278976    India
3   Female        0.0      5.0          fourth      rice  0.239271    India
4   Female        0.0      5.0         highest      rice  0.137355    India
5   Female        5.0     15.0          lowest      rice  0.384923    India
6   Female        5.0     15.0          second      rice  0.372437    India
7   Female        5.0     15.0          middle      rice  0.344120    India
8   Female        5.0     15.0          fourth      rice  0.298223    India
9   Female        5.0     15.0         highest      rice  0.170117    India
10  Female       15.0     30.0          lowest      rice  0.340118    India
11  Female       15.0     30.0          second      rice  0.347715    India
12  Female       15.0     30.0          middle      rice  0.308190    India
13  Female       15.0     30.0          fourth      rice  0.278779    India
14  Female       15.0     30.0         highest      rice  0.166026    India
15  Female       30.0     50.0          lowest      rice  0.367724    India
16  Female       30.0     50.0          second      rice  0.365385    India
17  Female       30.0     50.0          middle      rice  0.329747    India
18  Female       30.0     50.0          fourth      rice  0.282996    India
19  Female       30.0     50.0         highest      rice  0.151076    India
20  Female       50.0    100.0          lowest      rice  0.384766    India
21  Female       50.0    100.0          second      rice  0.371403    India
22  Female       50.0    100.0          middle      rice  0.335342    India
23  Female       50.0    100.0          fourth      rice  0.282802    India
24  Female       50.0    100.0         highest      rice  0.145853    India
25    Male        0.0      5.0          lowest      rice  0.301125    India
26    Male        0.0      5.0          second      rice  0.304958    India
27    Male        0.0      5.0          middle      rice  0.276643    India
28    Male        0.0      5.0          fourth      rice  0.239590    India
29    Male        0.0      5.0         highest      rice  0.136388    India
30    Male        5.0     15.0          lowest      rice  0.388070    India
31    Male        5.0     15.0          second      rice  0.375826    India
32    Male        5.0     15.0          middle      rice  0.337651    India
33    Male        5.0     15.0          fourth      rice  0.298466    India
34    Male        5.0     15.0         highest      rice  0.165816    India
35    Male       15.0     30.0          lowest      rice  0.361587    India
36    Male       15.0     30.0          second      rice  0.347710    India
37    Male       15.0     30.0          middle      rice  0.305303    India
38    Male       15.0     30.0          fourth      rice  0.281030    India
39    Male       15.0     30.0         highest      rice  0.164437    India
40    Male       30.0     50.0          lowest      rice  0.354325    India
41    Male       30.0     50.0          second      rice  0.351664    India
42    Male       30.0     50.0          middle      rice  0.311270    India
43    Male       30.0     50.0          fourth      rice  0.275204    India
44    Male       30.0     50.0         highest      rice  0.148838    India
45    Male       50.0    100.0          lowest      rice  0.379384    India
46    Male       50.0    100.0          second      rice  0.365984    India
47    Male       50.0    100.0          middle      rice  0.328989    India
48    Male       50.0    100.0          fourth      rice  0.280128    India
49    Male       50.0    100.0         highest      rice  0.145417    India
0   Female        0.0    100.0          fourth  bouillon  0.535497  Nigeria
1   Female        0.0    100.0         highest  bouillon  0.559838  Nigeria
2   Female        0.0    100.0          lowest  bouillon  0.415369  Nigeria
3   Female        0.0    100.0          middle  bouillon  0.510484  Nigeria
4   Female        0.0    100.0          second  bouillon  0.467278  Nigeria
0     Male        0.0    100.0          fourth  bouillon  0.535497  Nigeria
1     Male        0.0    100.0         highest  bouillon  0.559838  Nigeria
2     Male        0.0    100.0          lowest  bouillon  0.415369  Nigeria
3     Male        0.0    100.0          middle  bouillon  0.510484  Nigeria
4     Male        0.0    100.0          second  bouillon  0.467278  Nigeria

In [11]:
effective_counterfactual_coverage = pd.concat([
    pd.read_csv(f'../0100_data_prep/results/iron/intervention/effective_intervention_coverage/{location}.csv')
        .assign(location=location.title())
        .rename(columns={'vehicle_name': 'vehicle'})
    for location in locations
])
effective_counterfactual_coverage

       sex  age_start  age_end wealth_quintile   vehicle     value location
0   Female        0.0      5.0          lowest      rice  0.480406    India
1   Female        0.0      5.0          second      rice  0.489626    India
2   Female        0.0      5.0          middle      rice  0.485256    India
3   Female        0.0      5.0          fourth      rice  0.465103    India
4   Female        0.0      5.0         highest      rice  0.414788    India
5   Female        5.0     15.0          lowest      rice  0.518084    India
6   Female        5.0     15.0          second      rice  0.516194    India
7   Female        5.0     15.0          middle      rice  0.503733    India
8   Female        5.0     15.0          fourth      rice  0.480683    India
9   Female        5.0     15.0         highest      rice  0.422328    India
10  Female       15.0     30.0          lowest      rice  0.490001    India
11  Female       15.0     30.0          second      rice  0.501241    India
12  Female       15.0     30.0          middle      rice  0.487280    India
13  Female       15.0     30.0          fourth      rice  0.469486    India
14  Female       15.0     30.0         highest      rice  0.419791    India
15  Female       30.0     50.0          lowest      rice  0.503897    India
16  Female       30.0     50.0          second      rice  0.507550    India
17  Female       30.0     50.0          middle      rice  0.494016    India
18  Female       30.0     50.0          fourth      rice  0.471461    India
19  Female       30.0     50.0         highest      rice  0.412698    India
20  Female       50.0    100.0          lowest      rice  0.512845    India
21  Female       50.0    100.0          second      rice  0.511724    India
22  Female       50.0    100.0          middle      rice  0.496223    India
23  Female       50.0    100.0          fourth      rice  0.470077    India
24  Female       50.0    100.0         highest      rice  0.409320    India
25    Male        0.0      5.0          lowest      rice  0.483839    India
26    Male        0.0      5.0          second      rice  0.494608    India
27    Male        0.0      5.0          middle      rice  0.481946    India
28    Male        0.0      5.0          fourth      rice  0.465632    India
29    Male        0.0      5.0         highest      rice  0.413389    India
30    Male        5.0     15.0          lowest      rice  0.519111    India
31    Male        5.0     15.0          second      rice  0.516849    India
32    Male        5.0     15.0          middle      rice  0.500768    India
33    Male        5.0     15.0          fourth      rice  0.480827    India
34    Male        5.0     15.0         highest      rice  0.419766    India
35    Male       15.0     30.0          lowest      rice  0.501616    India
36    Male       15.0     30.0          second      rice  0.502132    India
37    Male       15.0     30.0          middle      rice  0.486072    India
38    Male       15.0     30.0          fourth      rice  0.471222    India
39    Male       15.0     30.0         highest      rice  0.418450    India
40    Male       30.0     50.0          lowest      rice  0.497343    India
41    Male       30.0     50.0          second      rice  0.501660    India
42    Male       30.0     50.0          middle      rice  0.485614    India
43    Male       30.0     50.0          fourth      rice  0.468666    India
44    Male       30.0     50.0         highest      rice  0.411957    India
45    Male       50.0    100.0          lowest      rice  0.508877    India
46    Male       50.0    100.0          second      rice  0.506940    India
47    Male       50.0    100.0          middle      rice  0.492198    India
48    Male       50.0    100.0          fourth      rice  0.468024    India
49    Male       50.0    100.0         highest      rice  0.408955    India
0   Female        NaN      NaN          lowest  bouillon  0.618069  Nigeria
1   Female        NaN      NaN          second  bouillon  0.626300  Nigeria
2   Female        NaN      NaN          middle  bouillon  0.627742  Nigeria
3   Female        NaN      NaN          fourth  bouillon  0.632860  Nigeria
4   Female        NaN      NaN         highest  bouillon  0.629615  Nigeria
5     Male        NaN      NaN          lowest  bouillon  0.618069  Nigeria
6     Male        NaN      NaN          second  bouillon  0.626300  Nigeria
7     Male        NaN      NaN          middle  bouillon  0.627742  Nigeria
8     Male        NaN      NaN          fourth  bouillon  0.632860  Nigeria
9     Male        NaN      NaN         highest  bouillon  0.629615  Nigeria

In [12]:
effective_counterfactual_coverage["age_start"] = effective_counterfactual_coverage.age_start.fillna(0)
effective_counterfactual_coverage["age_end"] = effective_counterfactual_coverage.age_end.fillna(100)

In [13]:
effective_counterfactual_coverage = expand(effective_counterfactual_coverage)
effective_counterfactual_coverage

       sex  age_start  age_end wealth_quintile   vehicle     value location
0   Female        0.0      5.0          lowest      rice  0.480406    India
1   Female        0.0      5.0          second      rice  0.489626    India
2   Female        0.0      5.0          middle      rice  0.485256    India
3   Female        0.0      5.0          fourth      rice  0.465103    India
4   Female        0.0      5.0         highest      rice  0.414788    India
5   Female        5.0     15.0          lowest      rice  0.518084    India
6   Female        5.0     15.0          second      rice  0.516194    India
7   Female        5.0     15.0          middle      rice  0.503733    India
8   Female        5.0     15.0          fourth      rice  0.480683    India
9   Female        5.0     15.0         highest      rice  0.422328    India
10  Female       15.0     30.0          lowest      rice  0.490001    India
11  Female       15.0     30.0          second      rice  0.501241    India
12  Female       15.0     30.0          middle      rice  0.487280    India
13  Female       15.0     30.0          fourth      rice  0.469486    India
14  Female       15.0     30.0         highest      rice  0.419791    India
15  Female       30.0     50.0          lowest      rice  0.503897    India
16  Female       30.0     50.0          second      rice  0.507550    India
17  Female       30.0     50.0          middle      rice  0.494016    India
18  Female       30.0     50.0          fourth      rice  0.471461    India
19  Female       30.0     50.0         highest      rice  0.412698    India
20  Female       50.0    100.0          lowest      rice  0.512845    India
21  Female       50.0    100.0          second      rice  0.511724    India
22  Female       50.0    100.0          middle      rice  0.496223    India
23  Female       50.0    100.0          fourth      rice  0.470077    India
24  Female       50.0    100.0         highest      rice  0.409320    India
25    Male        0.0      5.0          lowest      rice  0.483839    India
26    Male        0.0      5.0          second      rice  0.494608    India
27    Male        0.0      5.0          middle      rice  0.481946    India
28    Male        0.0      5.0          fourth      rice  0.465632    India
29    Male        0.0      5.0         highest      rice  0.413389    India
30    Male        5.0     15.0          lowest      rice  0.519111    India
31    Male        5.0     15.0          second      rice  0.516849    India
32    Male        5.0     15.0          middle      rice  0.500768    India
33    Male        5.0     15.0          fourth      rice  0.480827    India
34    Male        5.0     15.0         highest      rice  0.419766    India
35    Male       15.0     30.0          lowest      rice  0.501616    India
36    Male       15.0     30.0          second      rice  0.502132    India
37    Male       15.0     30.0          middle      rice  0.486072    India
38    Male       15.0     30.0          fourth      rice  0.471222    India
39    Male       15.0     30.0         highest      rice  0.418450    India
40    Male       30.0     50.0          lowest      rice  0.497343    India
41    Male       30.0     50.0          second      rice  0.501660    India
42    Male       30.0     50.0          middle      rice  0.485614    India
43    Male       30.0     50.0          fourth      rice  0.468666    India
44    Male       30.0     50.0         highest      rice  0.411957    India
45    Male       50.0    100.0          lowest      rice  0.508877    India
46    Male       50.0    100.0          second      rice  0.506940    India
47    Male       50.0    100.0          middle      rice  0.492198    India
48    Male       50.0    100.0          fourth      rice  0.468024    India
49    Male       50.0    100.0         highest      rice  0.408955    India
0   Female        0.0    100.0          lowest  bouillon  0.618069  Nigeria
1   Female        0.0    100.0          second  bouillon  0.626300  Nigeria
2   Female        0.0    100.0          middle  bouillon  0.627742  Nigeria
3   Female        0.0    100.0          fourth  bouillon  0.632860  Nigeria
4   Female        0.0    100.0         highest  bouillon  0.629615  Nigeria
5     Male        0.0    100.0          lowest  bouillon  0.618069  Nigeria
6     Male        0.0    100.0          second  bouillon  0.626300  Nigeria
7     Male        0.0    100.0          middle  bouillon  0.627742  Nigeria
8     Male        0.0    100.0          fourth  bouillon  0.632860  Nigeria
9     Male        0.0    100.0         highest  bouillon  0.629615  Nigeria

In [14]:
age_groups = db_queries.get_age_metadata(release_id=9).set_index('age_group_id').rename(columns={'age_group_years_start': 'age_start', 'age_group_years_end': 'age_end'})
assert set(age_group_ids) <= set(age_groups.index)
age_groups = age_groups.loc[age_group_ids][["age_start", "age_end"]]
age_groups["age_end"] = age_groups.age_end.replace(125, 100)
age_groups

              age_start     age_end
age_group_id
2              0.000000    0.019178
3              0.019178    0.076712
388            0.076712    0.500000
389            0.500000    1.000000
6              5.000000   10.000000
7             10.000000   15.000000
8             15.000000   20.000000
9             20.000000   25.000000
10            25.000000   30.000000
11            30.000000   35.000000
12            35.000000   40.000000
13            40.000000   45.000000
14            45.000000   50.000000
15            50.000000   55.000000
16            55.000000   60.000000
17            60.000000   65.000000
18            65.000000   70.000000
19            70.000000   75.000000
20            75.000000   80.000000
30            80.000000   85.000000
31            85.000000   90.000000
32            90.000000   95.000000
235           95.000000  100.000000

In [15]:
def map_to_gbd_age_groups(df):
    return (
        age_groups.merge(df, how="cross", suffixes=("", "_orig"))
            .pipe(lambda df: df[(df.age_end <= df.age_end_orig) & (df.age_start >= df.age_start_orig)])
            .drop(columns=["age_start_orig", "age_end_orig"])
    )

In [16]:
effective_baseline_coverage.set_index(["sex", "age_start", "age_end", "wealth_quintile", "vehicle", "location"]).index.is_unique

True

In [17]:
effective_counterfactual_coverage.set_index(["sex", "age_start", "age_end", "wealth_quintile", "vehicle", "location"]).index.is_unique

True

In [18]:
effective_baseline_coverage = map_to_gbd_age_groups(effective_baseline_coverage).set_index(index_cols).value
effective_counterfactual_coverage = map_to_gbd_age_groups(effective_counterfactual_coverage).set_index(index_cols).value

In [19]:
delta_effective_coverage = effective_counterfactual_coverage.sub(effective_baseline_coverage)
delta_effective_coverage

location  sex     age_start  age_end     vehicle   wealth_quintile
India     Female  0.0        0.019178    rice      fourth             0.225832
                                                   highest            0.277433
                                                   lowest             0.185656
                                                   middle             0.206280
                                                   second             0.190895
                                                                        ...
Nigeria   Male    95.0       100.000000  bouillon  fourth             0.097363
                                                   highest            0.069777
                                                   lowest             0.202700
                                                   middle             0.117258
                                                   second             0.159021
Name: value, Length: 460, dtype: float64

In [20]:
def reformat_gbd_data(df):
    index_cols = []
    if "location_id" in df.columns:
        df = df.merge(location_crosswalk, on="location_id").drop(columns=["location_id"])
        index_cols += ["location"]
    if "sex_id" in df.columns:
        df = df.merge(sex_crosswalk, on="sex_id").drop(columns=["sex_id"])
        index_cols += ["sex"]
    if "age_group_id" in df.columns:
        df = df.merge(age_groups, on="age_group_id").drop(columns=["age_group_id"])
        index_cols += ["age_start", "age_end"]
    if len(index_cols) > 0:
        df = df.set_index(index_cols)
    return df

In [21]:
hgb_mean = reformat_gbd_data(
    get_draws('modelable_entity_id',
                    10487,
                    source='epi',
                    location_id=list(location_crosswalk.location_id),
                    age_group_id=age_group_ids,
                    sex_id=list(sex_crosswalk.sex_id),
                    year_id=2021,
                    release_id=9)
)
hgb_mean = hgb_mean[DRAWS].copy()
hgb_mean

,,,,draw_0,draw_1,draw_2,draw_3,draw_4,draw_5,draw_6,draw_7,draw_8,draw_9,...,draw_490,draw_491,draw_492,draw_493,draw_494,draw_495,draw_496,draw_497,draw_498,draw_499
location,sex,age_start,age_end,,,,,,,,,,,,,,,,,,,,,
India,Female,0.000000,0.019178,141.027303,141.174892,143.047093,142.497768,141.204487,141.832669,140.942772,142.891759,141.388006,143.166841,...,140.459189,140.765055,142.503501,140.558958,141.696270,140.565670,141.885428,142.433822,140.370106,142.464730
Nigeria,Female,0.000000,0.019178,140.203331,139.700680,137.486100,143.738463,148.622155,142.898403,135.879741,146.860804,148.441575,136.598751,...,140.399313,143.182558,134.555407,144.192173,135.913431,140.135379,136.145279,139.567376,146.074584,142.051915
India,Male,0.000000,0.019178,146.600654,149.103908,146.074897,145.748027,149.507916,145.964431,146.225025,145.316586,149.278837,147.447709,...,148.331245,145.371190,150.039668,148.060737,146.862862,146.927253,148.502610,148.079533,148.912936,146.613964
Nigeria,Male,0.000000,0.019178,139.655000,152.652888,141.405358,135.236759,145.950384,148.051338,145.753920,143.368754,148.505532,149.271473,...,151.005295,142.522210,132.928140,140.653593,156.208075,152.033406,131.602486,153.680412,146.369116,149.265222
India,Female,0.019178,0.076712,128.185915,129.096397,129.130806,127.546092,129.886294,129.778156,127.898826,129.079936,129.428546,128.289116,...,128.716439,129.137330,128.530514,127.198688,128.109218,127.745823,128.225212,127.911793,129.511153,128.852131
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Nigeria,Male,0.076712,0.500000,94.267052,98.335982,96.967303,98.720429,100.392380,97.388312,99.835516,105.483599,97.071404,97.055824,...,96.493032,97.136619,103.343167,97.834196,95.880294,99.447538,99.703969,102.837446,97.052305,103.362419
India,Female,0.500000,1.000000,101.917809,99.823676,100.483745,100.428266,100.642931,100.292157,99.313897,100.007150,99.623193,99.082577,...,101.271734,100.142204,101.161263,101.477375,100.662558,100.274449,100.699653,99.977255,100.885253,99.743914
Nigeria,Female,0.500000,1.000000,100.148802,99.844921,99.645127,100.145850,100.608923,101.012091,100.358797,98.995013,99.743129,100.867444,...,98.288392,99.606637,100.119695,99.217875,98.652748,99.338615,99.382140,98.823520,99.294049,98.803754
India,Male,0.500000,1.000000,98.720550,100.044084,99.267918,100.076804,100.198902,99.619711,100.155947,99.160058,99.632622,100.092466,...,100.009775,100.192999,99.589137,99.186866,99.669854,99.030782,99.804187,98.127701,100.055717,99.584572
Nigeria,Male,0.500000,1.000000,100.092403,98.678200,93.913129,99.908232,98.806275,97.043218,90.629506,95.910213,94.262673,97.302075,...,98.150349,96.048034,95.821581,97.069076,95.799663,92.833911,95.228194,99.271147,96.006244,95.463522

In [22]:
hemoglobin_mean_disparities = pd.concat([
    pd.read_csv(f'../0100_data_prep/results/hemoglobin/mean_disparities/{location}.csv')
        .assign(location=location.title())
    for location in locations
])
hemoglobin_mean_disparities = (
    map_to_gbd_age_groups(hemoglobin_mean_disparities[hemoglobin_mean_disparities.pregnant == "not_pregnant"].drop(columns=["pregnant"]))
        .set_index(["location", "sex", "age_start", "age_end", "wealth_quintile"]).value
)
hemoglobin_mean_disparities

location  sex     age_start  age_end     wealth_quintile
India     Female  0.0        0.019178    lowest             103.655561
                                         second             105.257986
                                         middle             105.397530
                                         fourth             106.765336
                                         highest            107.989017
                                                               ...
Nigeria   Male    95.0       100.000000  lowest             113.444966
                                         second             115.420130
                                         middle             116.087185
                                         fourth             116.578539
                                         highest            118.793246
Name: value, Length: 460, dtype: float64

In [23]:
wealth_quintile_probabilities = pd.concat([
    pd.read_csv(f'../0100_data_prep/results/wealth_quintile_probabilities/{location}.csv')
        .assign(location=location.title())
    for location in locations
])
wealth_quintile_probabilities

,sex,age_start,age_end,pregnant,lowest,second,middle,fourth,highest,location
0,Female,0.0,5.0,not_pregnant,0.251317,0.220571,0.195838,0.184456,0.147818,India
1,Female,5.0,15.0,not_pregnant,0.269038,0.219459,0.193766,0.172569,0.145167,India
2,Female,15.0,30.0,not_pregnant,0.179314,0.203535,0.211692,0.209712,0.195747,India
3,Female,15.0,30.0,pregnant,0.221262,0.222487,0.214771,0.182324,0.159154,India
4,Female,30.0,50.0,not_pregnant,0.174181,0.188673,0.199713,0.213463,0.223970,India
5,Female,30.0,50.0,pregnant,0.314491,0.182529,0.131633,0.167147,0.204200,India
6,Female,50.0,100.0,not_pregnant,0.188708,0.187540,0.191253,0.199636,0.232863,India
7,Male,0.0,5.0,not_pregnant,0.242600,0.215610,0.200229,0.183923,0.157639,India
8,Male,5.0,15.0,not_pregnant,0.261604,0.217675,0.190718,0.176545,0.153458,India
9,Male,15.0,30.0,not_pregnant,0.169172,0.205794,0.214029,0.208330,0.202675,India
10,Male,30.0,50.0,not_pregnant,0.167563,0.183939,0.203419,0.219906,0.225173,India
11,Male,50.0,100.0,not_pregnant,0.176575,0.184392,0.190461,0.200876,0.247696,India
0,Female,0.0,5.0,not_pregnant,0.220707,0.219801,0.207518,0.182416,0.169557,Nigeria
1,Female,5.0,15.0,not_pregnant,0.222903,0.211314,0.200941,0.189893,0.174949,Nigeria
2,Female,15.0,30.0,not_pregnant,0.164706,0.194882,0.200646,0.223887,0.215879,Nigeria
3,Female,15.0,30.0,pregnant,0.229613,0.268268,0.218846,0.169231,0.114043,Nigeria
4,Female,30.0,50.0,not_pregnant,0.167401,0.176111,0.188324,0.215674,0.252490,Nigeria
5,Female,30.0,50.0,pregnant,0.247800,0.198377,0.181613,0.163402,0.208807,Nigeria
6,Female,50.0,100.0,not_pregnant,0.196077,0.184902,0.228885,0.192974,0.197161,Nigeria
7,Male,0.0,5.0,not_pregnant,0.214963,0.223211,0.203137,0.188194,0.170495,Nigeria
8,Male,5.0,15.0,not_pregnant,0.227134,0.211917,0.202795,0.189340,0.168813,Nigeria
9,Male,15.0,30.0,not_pregnant,0.194480,0.197231,0.196587,0.211924,0.199779,Nigeria
10,Male,30.0,50.0,not_pregnant,0.155586,0.166481,0.189007,0.217201,0.271724,Nigeria
11,Male,50.0,100.0,not_pregnant,0.209864,0.183658,0.188784,0.202148,0.215546,Nigeria

In [24]:
map_to_gbd_age_groups(wealth_quintile_probabilities[wealth_quintile_probabilities.pregnant == "not_pregnant"].drop(columns=["pregnant"]))

,age_start,age_end,sex,lowest,second,middle,fourth,highest,location
0,0.000000,0.019178,Female,0.251317,0.220571,0.195838,0.184456,0.147818,India
5,0.000000,0.019178,Male,0.242600,0.215610,0.200229,0.183923,0.157639,India
10,0.000000,0.019178,Female,0.220707,0.219801,0.207518,0.182416,0.169557,Nigeria
15,0.000000,0.019178,Male,0.214963,0.223211,0.203137,0.188194,0.170495,Nigeria
20,0.019178,0.076712,Female,0.251317,0.220571,0.195838,0.184456,0.147818,India
...,...,...,...,...,...,...,...,...,...
439,90.000000,95.000000,Male,0.209864,0.183658,0.188784,0.202148,0.215546,Nigeria
444,95.000000,100.000000,Female,0.188708,0.187540,0.191253,0.199636,0.232863,India
449,95.000000,100.000000,Male,0.176575,0.184392,0.190461,0.200876,0.247696,India
454,95.000000,100.000000,Female,0.196077,0.184902,0.228885,0.192974,0.197161,Nigeria
459,95.000000,100.000000,Male,0.209864,0.183658,0.188784,0.202148,0.215546,Nigeria

In [25]:
wealth_quintile_probabilities = (
    map_to_gbd_age_groups(wealth_quintile_probabilities[wealth_quintile_probabilities.pregnant == "not_pregnant"].drop(columns=["pregnant"]))
        .set_index(["location", "sex", "age_start", "age_end"])
)
wealth_quintile_probabilities.columns.name = 'wealth_quintile'
wealth_quintile_probabilities = wealth_quintile_probabilities.stack()
wealth_quintile_probabilities

location  sex     age_start  age_end     wealth_quintile
India     Female  0.0        0.019178    lowest             0.251317
                                         second             0.220571
                                         middle             0.195838
                                         fourth             0.184456
                                         highest            0.147818
                                                              ...
Nigeria   Male    95.0       100.000000  lowest             0.209864
                                         second             0.183658
                                         middle             0.188784
                                         fourth             0.202148
                                         highest            0.215546
Length: 460, dtype: float64

In [26]:
pre_disparity_groups = hgb_mean.mul(wealth_quintile_probabilities, axis=0).groupby([c for c in hgb_mean.index.names if c != 'wealth_quintile']).sum()
pre_disparity_groups

                                          draw_0      draw_1      draw_2  \
location sex    age_start age_end
India    Female 0.000000  0.019178    141.027303  141.174892  143.047093
                0.019178  0.076712    128.185915  129.096397  129.130806
                0.076712  0.500000    103.541148  104.218523  102.321094
                0.500000  1.000000    101.917809   99.823676  100.483745
                5.000000  10.000000   112.932920  111.768831  112.598540
...                                          ...         ...         ...
Nigeria  Male   75.000000 80.000000   125.293565  127.635808  121.016674
                80.000000 85.000000   136.438006  140.853010  131.367813
                85.000000 90.000000   133.029351  120.328832  136.611180
                90.000000 95.000000   116.866389  104.222078  111.737153
                95.000000 100.000000  104.414752  104.110723   99.482286

                                          draw_3      draw_4      draw_5  \
location sex    age_start age_end
India    Female 0.000000  0.019178    142.497768  141.204487  141.832669
                0.019178  0.076712    127.546092  129.886294  129.778156
                0.076712  0.500000    104.327579  103.623847  103.637978
                0.500000  1.000000    100.428266  100.642931  100.292157
                5.000000  10.000000   114.147894  113.027698  112.048307
...                                          ...         ...         ...
Nigeria  Male   75.000000 80.000000   127.115747  138.057306  124.135326
                80.000000 85.000000   139.943361  136.350483  131.038066
                85.000000 90.000000   126.391697  129.370208  136.797710
                90.000000 95.000000   113.207507  106.352527   98.297926
                95.000000 100.000000  102.887575  107.603354  105.459291

                                          draw_6      draw_7      draw_8  \
location sex    age_start age_end
India    Female 0.000000  0.019178    140.942772  142.891759  141.388006
                0.019178  0.076712    127.898826  129.079936  129.428546
                0.076712  0.500000    103.094638  103.816330  101.953160
                0.500000  1.000000     99.313897  100.007150   99.623193
                5.000000  10.000000   112.435412  112.251242  114.540273
...                                          ...         ...         ...
Nigeria  Male   75.000000 80.000000   131.351376  140.422146  134.386319
                80.000000 85.000000   123.096959  137.390001  135.796309
                85.000000 90.000000   127.729441  121.481892  124.340741
                90.000000 95.000000   113.236702  105.723986  114.701460
                95.000000 100.000000  103.255580  110.455551  105.846010

                                          draw_9  ...    draw_490    draw_491  \
location sex    age_start age_end                 ...
India    Female 0.000000  0.019178    143.166841  ...  140.459189  140.765055
                0.019178  0.076712    128.289116  ...  128.716439  129.137330
                0.076712  0.500000    104.552078  ...  102.776895  103.279928
                0.500000  1.000000     99.082577  ...  101.271734  100.142204
                5.000000  10.000000   112.764552  ...  113.947008  111.993490
...                                          ...  ...         ...         ...
Nigeria  Male   75.000000 80.000000   133.184690  ...  136.984105  141.082724
                80.000000 85.000000   130.850945  ...  126.774249  139.078352
                85.000000 90.000000   129.907846  ...  123.342804  132.476853
                90.000000 95.000000   109.299417  ...  106.352476  105.521819
                95.000000 100.000000  113.724775  ...  106.311908  106.971579

                                        draw_492    draw_493    draw_494  \
location sex    age_start age_end
India    Female 0.000000  0.019178    142.503501  140.558958  141.696270
                0.019178  0.076712    128.530514  127.198688  128.109218
                0.076712  0.500000    104.036275  103.587425  104.193430
                0.500000  1.000000    101.161263  101.477375  100.662558
                5.000000  10.000000   112.378643  113.183957  113.243814
...                                          ...         ...         ...
Nigeria  Male   75.000000 80.000000   131.090270  135.219269  126.878436
                80.000000 85.000000   136.918367  135.456264  134.112398
                85.000000 90.000000   123.531592  144.984255  127.535764
                90.000000 95.000000   114.953481  113.025229  112.124140
                95.000000 100.000000   95.910911  108.030062  102.529970

                                        draw_495    draw_496    draw_497  \
location sex    age_start age_end
India    Female 0.000000  0.019178    140.565670  141.885428  142.433822
                0.019178  0.076712    127.745823  128.225212  127.911793
                0.076712  0.500000    103.253998  103.231000  103.510927
                0.500000  1.000000    100.274449  100.699653   99.977255
                5.000000  10.000000   113.480999  113.136011  113.778551
...                                          ...         ...         ...
Nigeria  Male   75.000000 80.000000   133.934524  131.760939  128.905181
                80.000000 85.000000   127.342256  142.406766  137.752048
                85.000000 90.000000   138.086811  132.068711  135.543279
                90.000000 95.000000   111.885647  112.683427  108.517975
                95.000000 100.000000   96.924863  106.085833  105.254256

                                        draw_498    draw_499
location sex    age_start age_end
India    Female 0.000000  0.019178    140.370106  142.464730
                0.019178  0.076712    129.511153  128.852131
                0.076712  0.500000    103.239451  102.902167
                0.500000  1.000000    100.885253   99.743914
                5.000000  10.000000   113.516170  112.611751
...                                          ...         ...
Nigeria  Male   75.000000 80.000000   138.241755  136.243081
                80.000000 85.000000   145.959345  141.414186
                85.000000 90.000000   127.135783  122.665154
                90.000000 95.000000   110.880241  107.681955
                95.000000 100.000000   99.199204  107.279436

[92 rows x 500 columns]

In [27]:
hgb_mean = hgb_mean.mul(hemoglobin_mean_disparities, axis=0)

In [28]:
scale_factor = pre_disparity_groups / hgb_mean.mul(wealth_quintile_probabilities, axis=0).groupby([c for c in hgb_mean.index.names if c != 'wealth_quintile']).sum()
scale_factor

                                        draw_0    draw_1    draw_2    draw_3  \
location sex    age_start age_end
India    Female 0.000000  0.019178    0.009473  0.009473  0.009473  0.009473
                0.019178  0.076712    0.009473  0.009473  0.009473  0.009473
                0.076712  0.500000    0.009473  0.009473  0.009473  0.009473
                0.500000  1.000000    0.009473  0.009473  0.009473  0.009473
                5.000000  10.000000   0.009011  0.009011  0.009011  0.009011
...                                        ...       ...       ...       ...
Nigeria  Male   75.000000 80.000000   0.008614  0.008614  0.008614  0.008614
                80.000000 85.000000   0.008614  0.008614  0.008614  0.008614
                85.000000 90.000000   0.008614  0.008614  0.008614  0.008614
                90.000000 95.000000   0.008614  0.008614  0.008614  0.008614
                95.000000 100.000000  0.008614  0.008614  0.008614  0.008614

                                        draw_4    draw_5    draw_6    draw_7  \
location sex    age_start age_end
India    Female 0.000000  0.019178    0.009473  0.009473  0.009473  0.009473
                0.019178  0.076712    0.009473  0.009473  0.009473  0.009473
                0.076712  0.500000    0.009473  0.009473  0.009473  0.009473
                0.500000  1.000000    0.009473  0.009473  0.009473  0.009473
                5.000000  10.000000   0.009011  0.009011  0.009011  0.009011
...                                        ...       ...       ...       ...
Nigeria  Male   75.000000 80.000000   0.008614  0.008614  0.008614  0.008614
                80.000000 85.000000   0.008614  0.008614  0.008614  0.008614
                85.000000 90.000000   0.008614  0.008614  0.008614  0.008614
                90.000000 95.000000   0.008614  0.008614  0.008614  0.008614
                95.000000 100.000000  0.008614  0.008614  0.008614  0.008614

                                        draw_8    draw_9  ...  draw_490  \
location sex    age_start age_end                         ...
India    Female 0.000000  0.019178    0.009473  0.009473  ...  0.009473
                0.019178  0.076712    0.009473  0.009473  ...  0.009473
                0.076712  0.500000    0.009473  0.009473  ...  0.009473
                0.500000  1.000000    0.009473  0.009473  ...  0.009473
                5.000000  10.000000   0.009011  0.009011  ...  0.009011
...                                        ...       ...  ...       ...
Nigeria  Male   75.000000 80.000000   0.008614  0.008614  ...  0.008614
                80.000000 85.000000   0.008614  0.008614  ...  0.008614
                85.000000 90.000000   0.008614  0.008614  ...  0.008614
                90.000000 95.000000   0.008614  0.008614  ...  0.008614
                95.000000 100.000000  0.008614  0.008614  ...  0.008614

                                      draw_491  draw_492  draw_493  draw_494  \
location sex    age_start age_end
India    Female 0.000000  0.019178    0.009473  0.009473  0.009473  0.009473
                0.019178  0.076712    0.009473  0.009473  0.009473  0.009473
                0.076712  0.500000    0.009473  0.009473  0.009473  0.009473
                0.500000  1.000000    0.009473  0.009473  0.009473  0.009473
                5.000000  10.000000   0.009011  0.009011  0.009011  0.009011
...                                        ...       ...       ...       ...
Nigeria  Male   75.000000 80.000000   0.008614  0.008614  0.008614  0.008614
                80.000000 85.000000   0.008614  0.008614  0.008614  0.008614
                85.000000 90.000000   0.008614  0.008614  0.008614  0.008614
                90.000000 95.000000   0.008614  0.008614  0.008614  0.008614
                95.000000 100.000000  0.008614  0.008614  0.008614  0.008614

                                      draw_495  draw_496  draw_497  draw_498  \
location sex    age_start age_end
India    Female 0.000000  0.019178    0.009473  0.009473  0.009473  0.009473
                0.019178  0.076712    0.009473  0.009473  0.009473  0.009473
                0.076712  0.500000    0.009473  0.009473  0.009473  0.009473
                0.500000  1.000000    0.009473  0.009473  0.009473  0.009473
                5.000000  10.000000   0.009011  0.009011  0.009011  0.009011
...                                        ...       ...       ...       ...
Nigeria  Male   75.000000 80.000000   0.008614  0.008614  0.008614  0.008614
                80.000000 85.000000   0.008614  0.008614  0.008614  0.008614
                85.000000 90.000000   0.008614  0.008614  0.008614  0.008614
                90.000000 95.000000   0.008614  0.008614  0.008614  0.008614
                95.000000 100.000000  0.008614  0.008614  0.008614  0.008614

                                      draw_499
location sex    age_start age_end
India    Female 0.000000  0.019178    0.009473
                0.019178  0.076712    0.009473
                0.076712  0.500000    0.009473
                0.500000  1.000000    0.009473
                5.000000  10.000000   0.009011
...                                        ...
Nigeria  Male   75.000000 80.000000   0.008614
                80.000000 85.000000   0.008614
                85.000000 90.000000   0.008614
                90.000000 95.000000   0.008614
                95.000000 100.000000  0.008614

[92 rows x 500 columns]

In [29]:
hgb_mean = hgb_mean * scale_factor

In [30]:
assert np.allclose(
    hgb_mean.mul(wealth_quintile_probabilities, axis=0).groupby([c for c in hgb_mean.index.names if c != 'wealth_quintile']).sum(),
    pre_disparity_groups,
)

In [31]:
hgb_mean = (
    hgb_mean.reset_index()
        .assign(vehicle=lambda x: x.location.map({"India": 'rice', "Nigeria": 'bouillon'}))
        .set_index(list(hgb_mean.index.names) + ['vehicle'])
)
hgb_mean

                                                                   draw_0  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   lowest          rice      138.477305
                                     second          rice      140.618044
                                     middle          rice      140.804466
                                     fourth          rice      142.631768
                                     highest         rice      144.266529
...                                                                   ...
Nigeria  Male   95.0      100.000000 lowest          bouillon  102.033291
                                     second          bouillon  103.809769
                                     middle          bouillon  104.409723
                                     fourth          bouillon  104.851652
                                     highest         bouillon  106.843576

                                                                   draw_1  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   lowest          rice      138.622225
                                     second          rice      140.765205
                                     middle          rice      140.951821
                                     fourth          rice      142.781036
                                     highest         rice      144.417508
...                                                                   ...
Nigeria  Male   95.0      100.000000 lowest          bouillon  101.736197
                                     second          bouillon  103.507502
                                     middle          bouillon  104.105710
                                     fourth          bouillon  104.546351
                                     highest         bouillon  106.532475

                                                                   draw_2  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   lowest          rice      140.460574
                                     second          rice      142.631972
                                     middle          rice      142.821064
                                     fourth          rice      144.674537
                                     highest         rice      146.332711
...                                                                   ...
Nigeria  Male   95.0      100.000000 lowest          bouillon   97.213324
                                     second          bouillon   98.905882
                                     middle          bouillon   99.477495
                                     fourth          bouillon   99.898547
                                     highest         bouillon  101.796374

                                                                   draw_3  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   lowest          rice      139.921181
                                     second          rice      142.084241
                                     middle          rice      142.272607
                                     fourth          rice      144.118962
                                     highest         rice      145.770769
...                                                                   ...
Nigeria  Male   95.0      100.000000 lowest          bouillon  100.540946
                                     second          bouillon  102.291441
                                     middle          bouillon  102.882620
                                     fourth          bouillon  103.318085
                                     highest         bouillon  105.280875

                                                                   draw_4  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   lowest          rice      138.651285
                                     second          rice      140.794714
                                     middle          rice      140.981370
                                     fourth          rice      142.810967
                                     highest         rice      144.447783
...                                                                   ...
Nigeria  Male   95.0      100.000000 lowest          bouillon  105.149169
                                     second          bouillon  106.979896
                                     middle          bouillon  107.598172
                                     fourth          bouillon  108.053596
                                     highest         bouillon  110.106349

                                                                   draw_5  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   lowest          rice      139.268108
                                     second          rice      141.421073
                                     middle          rice      141.608559
                                     fourth          rice      143.446296
                                     highest         rice      145.090393
...                                                                   ...
Nigeria  Male   95.0      100.000000 lowest          bouillon  103.054007
                                     second          bouillon  104.848256
                                     middle          bouillon  105.454212
                                     fourth          bouillon  105.900561
                                     highest         bouillon  107.912412

                                                                   draw_6  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   lowest          rice      138.394302
                                     second          rice      140.533758
                                     middle          rice      140.720068
                                     fourth          rice      142.546275
                                     highest         rice      144.180056
...                                                                   ...
Nigeria  Male   95.0      100.000000 lowest          bouillon  100.900558
                                     second          bouillon  102.657314
                                     middle          bouillon  103.250608
                                     fourth          bouillon  103.687630
                                     highest         bouillon  105.657440

                                                                   draw_7  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   lowest          rice      140.308049
                                     second          rice      142.477090
                                     middle          rice      142.665976
                                     fourth          rice      144.517436
                                     highest         rice      146.173810
...                                                                   ...
Nigeria  Male   95.0      100.000000 lowest          bouillon  107.936314
                                     second          bouillon  109.815568
                                     middle          bouillon  110.450232
                                     fourth          bouillon  110.917728
                                     highest         bouillon  113.024892

                                                                   draw_8  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   lowest          rice      138.831486
                                     second          rice      140.977700
                                     middle          rice      141.164599
                                     fourth          rice      142.996574
                                     highest         rice      144.635517
...                                                                   ...
Nigeria  Male   95.0      100.000000 lowest          bouillon  103.431906
                                     second          bouillon  105.232735
                                     middle          bouillon  105.840913
                                     fourth          bouillon  106.288898
                                     highest         bouillon  108.308127

                                                                   draw_9  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   lowest          rice      140.578156
                                     second          rice      142.751373
                                     middle          rice      142.940623
                                     fourth          rice      144.795647
                                     highest         rice      146.455209
...                                                                   ...
Nigeria  Male   95.0      100.000000 lowest          bouillon  111.130975
                                     second          bouillon  113.065850
                                     middle          bouillon  113.719299
                                     fourth          bouillon  114.200631
                                     highest         bouillon  116.370163

                                                               ...  \
location sex    age_start age_end    wealth_quintile vehicle   ...
India    Female 0.0       0.019178   lowest          rice      ...
                                     second          rice      ...
                                     middle          rice      ...
                                     fourth          rice      ...
                                     highest         rice      ...
...                                                            ...
Nigeria  Male   95.0      100.000000 lowest          bouillon  ...
                                     second          bouillon  ...
                                     middle          bouillon  ...
                                     fourth          bouillon  ...
                                     highest         bouillon  ...

                                                                 draw_490  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   lowest          rice      137.919464
                                     second          rice      140.051579
                                     middle          rice      140.237250
                                     fourth          rice      142.057191
                                     highest         rice      143.685367
...                                                                   ...
Nigeria  Male   95.0      100.000000 lowest          bouillon  103.887178
                                     second          bouillon  105.695934
                                     middle          bouillon  106.306789
                                     fourth          bouillon  106.756746
                                     highest         bouillon  108.784863

                                                                 draw_491  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   lowest          rice      138.219798
                                     second          rice      140.356556
                                     middle          rice      140.542632
                                     fourth          rice      142.366536
                                     highest         rice      143.998257
...                                                                   ...
Nigeria  Male   95.0      100.000000 lowest          bouillon  104.531803
                                     second          bouillon  106.351782
                                     middle          bouillon  106.966427
                                     fourth          bouillon  107.419177
                                     highest         bouillon  109.459878

                                                                 draw_492  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   lowest          rice      139.926810
                                     second          rice      142.089957
                                     middle          rice      142.278331
                                     fourth          rice      144.124760
                                     highest         rice      145.776633
...                                                                   ...
Nigeria  Male   95.0      100.000000 lowest          bouillon   93.723404
                                     second          bouillon   95.355200
                                     middle          bouillon   95.906293
                                     fourth          bouillon   96.312229
                                     highest         bouillon   98.141925

                                                                 draw_493  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   lowest          rice      138.017429
                                     second          rice      140.151058
                                     middle          rice      140.336861
                                     fourth          rice      142.158095
                                     highest         rice      143.787427
...                                                                   ...
Nigeria  Male   95.0      100.000000 lowest          bouillon  105.566145
                                     second          bouillon  107.404132
                                     middle          bouillon  108.024860
                                     fourth          bouillon  108.482089
                                     highest         bouillon  110.542983

                                                                 draw_494  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   lowest          rice      139.134176
                                     second          rice      141.285070
                                     middle          rice      141.472376
                                     fourth          rice      143.308346
                                     highest         rice      144.950862
...                                                                   ...
Nigeria  Male   95.0      100.000000 lowest          bouillon  100.191498
                                     second          bouillon  101.935908
                                     middle          bouillon  102.525033
                                     fourth          bouillon  102.958984
                                     highest         bouillon  104.914952

                                                                 draw_495  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   lowest          rice      138.024019
                                     second          rice      140.157751
                                     middle          rice      140.343562
                                     fourth          rice      142.164883
                                     highest         rice      143.794293
...                                                                   ...
Nigeria  Male   95.0      100.000000 lowest          bouillon   94.714230
                                     second          bouillon   96.363277
                                     middle          bouillon   96.920195
                                     fourth          bouillon   97.330423
                                     highest         bouillon   99.179462

                                                                 draw_496  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   lowest          rice      139.319914
                                     second          rice      141.473679
                                     middle          rice      141.661235
                                     fourth          rice      143.499656
                                     highest         rice      145.144365
...                                                                   ...
Nigeria  Male   95.0      100.000000 lowest          bouillon  103.666259
                                     second          bouillon  105.471168
                                     middle          bouillon  106.080724
                                     fourth          bouillon  106.529725
                                     highest         bouillon  108.553528

                                                                 draw_497  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   lowest          rice      139.858392
                                     second          rice      142.020481
                                     middle          rice      142.208762
                                     fourth          rice      144.054288
                                     highest         rice      145.705354
...                                                                   ...
Nigeria  Male   95.0      100.000000 lowest          bouillon  102.853649
                                     second          bouillon  104.644410
                                     middle          bouillon  105.249188
                                     fourth          bouillon  105.694669
                                     highest         bouillon  107.702608

                                                                 draw_498  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   lowest          rice      137.831991
                                     second          rice      139.962754
                                     middle          rice      140.148307
                                     fourth          rice      141.967094
                                     highest         rice      143.594237
...                                                                   ...
Nigeria  Male   95.0      100.000000 lowest          bouillon   96.936698
                                     second          bouillon   98.624440
                                     middle          bouillon   99.194426
                                     fourth          bouillon   99.614280
                                     highest         bouillon  101.506707

                                                                 draw_499
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   lowest          rice      139.888740
                                     second          rice      142.051299
                                     middle          rice      142.239621
                                     fourth          rice      144.085548
                                     highest         rice      145.736972
...                                                                   ...
Nigeria  Male   95.0      100.000000 lowest          bouillon  104.832639
                                     second          bouillon  106.657856
                                     middle          bouillon  107.274270
                                     fourth          bouillon  107.728323
                                     highest         bouillon  109.774897

[460 rows x 500 columns]

In [32]:
counterfactual_hgb_mean = hgb_mean.add(delta_effective_coverage * mean_difference, axis=0)
counterfactual_hgb_mean

                                                                   draw_0  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   fourth          rice      143.365723
                                     highest         rice      145.168187
                                     lowest          rice      139.080689
                                     middle          rice      141.474875
                                     second          rice      141.238453
...                                                                   ...
Nigeria  Male   95.0      100.000000 fourth          bouillon  105.260577
                                     highest         bouillon  107.136639
                                     lowest          bouillon  102.884631
                                     middle          bouillon  104.902207
                                     second          bouillon  104.477659

                                                                   draw_1  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   fourth          rice      143.514991
                                     highest         rice      145.319166
                                     lowest          rice      139.225609
                                     middle          rice      141.622231
                                     second          rice      141.385614
...                                                                   ...
Nigeria  Male   95.0      100.000000 fourth          bouillon  104.955276
                                     highest         bouillon  106.825538
                                     lowest          bouillon  102.587537
                                     middle          bouillon  104.598194
                                     second          bouillon  104.175392

                                                                   draw_2  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   fourth          rice      145.408492
                                     highest         rice      147.234369
                                     lowest          rice      141.063957
                                     middle          rice      143.491473
                                     second          rice      143.252381
...                                                                   ...
Nigeria  Male   95.0      100.000000 fourth          bouillon  100.307472
                                     highest         bouillon  102.089437
                                     lowest          bouillon   98.064663
                                     middle          bouillon   99.969979
                                     second          bouillon   99.573772

                                                                   draw_3  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   fourth          rice      144.852917
                                     highest         rice      146.672426
                                     lowest          rice      140.524565
                                     middle          rice      142.943016
                                     second          rice      142.704650
...                                                                   ...
Nigeria  Male   95.0      100.000000 fourth          bouillon  103.727010
                                     highest         bouillon  105.573938
                                     lowest          bouillon  101.392286
                                     middle          bouillon  103.375104
                                     second          bouillon  102.959331

                                                                   draw_4  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   fourth          rice      143.544923
                                     highest         rice      145.349440
                                     lowest          rice      139.254669
                                     middle          rice      141.651779
                                     second          rice      141.415123
...                                                                   ...
Nigeria  Male   95.0      100.000000 fourth          bouillon  108.462520
                                     highest         bouillon  110.399412
                                     lowest          bouillon  106.000508
                                     middle          bouillon  108.090656
                                     second          bouillon  107.647786

                                                                   draw_5  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   fourth          rice      144.180252
                                     highest         rice      145.992051
                                     lowest          rice      139.871492
                                     middle          rice      142.278968
                                     second          rice      142.041482
...                                                                   ...
Nigeria  Male   95.0      100.000000 fourth          bouillon  106.309486
                                     highest         bouillon  108.205475
                                     lowest          bouillon  103.905347
                                     middle          bouillon  105.946696
                                     second          bouillon  105.516146

                                                                   draw_6  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   fourth          rice      143.280230
                                     highest         rice      145.081714
                                     lowest          rice      138.997686
                                     middle          rice      141.390477
                                     second          rice      141.154167
...                                                                   ...
Nigeria  Male   95.0      100.000000 fourth          bouillon  104.096555
                                     highest         bouillon  105.950503
                                     lowest          bouillon  101.751898
                                     middle          bouillon  103.743092
                                     second          bouillon  103.325204

                                                                   draw_7  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   fourth          rice      145.251391
                                     highest         rice      147.075467
                                     lowest          rice      140.911432
                                     middle          rice      143.336385
                                     second          rice      143.097499
...                                                                   ...
Nigeria  Male   95.0      100.000000 fourth          bouillon  111.326653
                                     highest         bouillon  113.317955
                                     lowest          bouillon  108.787654
                                     middle          bouillon  110.942716
                                     second          bouillon  110.483458

                                                                   draw_8  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   fourth          rice      143.730530
                                     highest         rice      145.537175
                                     lowest          rice      139.434869
                                     middle          rice      141.835008
                                     second          rice      141.598109
...                                                                   ...
Nigeria  Male   95.0      100.000000 fourth          bouillon  106.697823
                                     highest         bouillon  108.601190
                                     lowest          bouillon  104.283245
                                     middle          bouillon  106.333396
                                     second          bouillon  105.900624

                                                                   draw_9  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   fourth          rice      145.529602
                                     highest         rice      147.356867
                                     lowest          rice      141.181540
                                     middle          rice      143.611032
                                     second          rice      143.371782
...                                                                   ...
Nigeria  Male   95.0      100.000000 fourth          bouillon  114.609556
                                     highest         bouillon  116.663226
                                     lowest          bouillon  111.982314
                                     middle          bouillon  114.211783
                                     second          bouillon  113.733740

                                                               ...  \
location sex    age_start age_end    wealth_quintile vehicle   ...
India    Female 0.0       0.019178   fourth          rice      ...
                                     highest         rice      ...
                                     lowest          rice      ...
                                     middle          rice      ...
                                     second          rice      ...
...                                                            ...
Nigeria  Male   95.0      100.000000 fourth          bouillon  ...
                                     highest         bouillon  ...
                                     lowest          bouillon  ...
                                     middle          bouillon  ...
                                     second          bouillon  ...

                                                                 draw_490  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   fourth          rice      142.791146
                                     highest         rice      144.587024
                                     lowest          rice      138.522847
                                     middle          rice      140.907659
                                     second          rice      140.671988
...                                                                   ...
Nigeria  Male   95.0      100.000000 fourth          bouillon  107.165671
                                     highest         bouillon  109.077925
                                     lowest          bouillon  104.738518
                                     middle          bouillon  106.799272
                                     second          bouillon  106.363823

                                                                 draw_491  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   fourth          rice      143.100491
                                     highest         rice      144.899915
                                     lowest          rice      138.823182
                                     middle          rice      141.213041
                                     second          rice      140.976966
...                                                                   ...
Nigeria  Male   95.0      100.000000 fourth          bouillon  107.828102
                                     highest         bouillon  109.752941
                                     lowest          bouillon  105.383143
                                     middle          bouillon  107.458911
                                     second          bouillon  107.019672

                                                                 draw_492  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   fourth          rice      144.858715
                                     highest         rice      146.678291
                                     lowest          rice      140.530194
                                     middle          rice      142.948740
                                     second          rice      142.710367
...                                                                   ...
Nigeria  Male   95.0      100.000000 fourth          bouillon   96.721154
                                     highest         bouillon   98.434988
                                     lowest          bouillon   94.574744
                                     middle          bouillon   96.398776
                                     second          bouillon   96.023090

                                                                 draw_493  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   fourth          rice      142.892050
                                     highest         rice      144.689085
                                     lowest          rice      138.620812
                                     middle          rice      141.007270
                                     second          rice      140.771467
...                                                                   ...
Nigeria  Male   95.0      100.000000 fourth          bouillon  108.891014
                                     highest         bouillon  110.836046
                                     lowest          bouillon  106.417484
                                     middle          bouillon  108.517343
                                     second          bouillon  108.072022

                                                                 draw_494  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   fourth          rice      144.042301
                                     highest         rice      145.852519
                                     lowest          rice      139.737560
                                     middle          rice      142.142785
                                     second          rice      141.905479
...                                                                   ...
Nigeria  Male   95.0      100.000000 fourth          bouillon  103.367909
                                     highest         bouillon  105.208015
                                     lowest          bouillon  101.042837
                                     middle          bouillon  103.017517
                                     second          bouillon  102.603798

                                                                 draw_495  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   fourth          rice      142.898838
                                     highest         rice      144.695951
                                     lowest          rice      138.627403
                                     middle          rice      141.013971
                                     second          rice      140.778160
...                                                                   ...
Nigeria  Male   95.0      100.000000 fourth          bouillon   97.739348
                                     highest         bouillon   99.472525
                                     lowest          bouillon   95.565569
                                     middle          bouillon   97.412679
                                     second          bouillon   97.031167

                                                                 draw_496  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   fourth          rice      144.233611
                                     highest         rice      146.046022
                                     lowest          rice      139.923298
                                     middle          rice      142.331644
                                     second          rice      142.094088
...                                                                   ...
Nigeria  Male   95.0      100.000000 fourth          bouillon  106.938650
                                     highest         bouillon  108.846591
                                     lowest          bouillon  104.517598
                                     middle          bouillon  106.573208
                                     second          bouillon  106.139058

                                                                 draw_497  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   fourth          rice      144.788244
                                     highest         rice      146.607012
                                     lowest          rice      140.461775
                                     middle          rice      142.879171
                                     second          rice      142.640890
...                                                                   ...
Nigeria  Male   95.0      100.000000 fourth          bouillon  106.103594
                                     highest         bouillon  107.995671
                                     lowest          bouillon  103.704989
                                     middle          bouillon  105.741672
                                     second          bouillon  105.312300

                                                                 draw_498  \
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   fourth          rice      142.701049
                                     highest         rice      144.495895
                                     lowest          rice      138.435374
                                     middle          rice      140.818716
                                     second          rice      140.583163
...                                                                   ...
Nigeria  Male   95.0      100.000000 fourth          bouillon  100.023205
                                     highest         bouillon  101.799770
                                     lowest          bouillon   97.788038
                                     middle          bouillon   99.686910
                                     second          bouillon   99.292330

                                                                 draw_499
location sex    age_start age_end    wealth_quintile vehicle
India    Female 0.0       0.019178   fourth          rice      144.819503
                                     highest         rice      146.638629
                                     lowest          rice      140.492124
                                     middle          rice      142.910030
                                     second          rice      142.671708
...                                                                   ...
Nigeria  Male   95.0      100.000000 fourth          bouillon  108.137248
                                     highest         bouillon  110.067959
                                     lowest          bouillon  105.683979
                                     middle          bouillon  107.766754
                                     second          bouillon  107.325746

[460 rows x 500 columns]

In [33]:
hgb_mean.columns.name = "draw"
hgb_mean = hgb_mean.stack().rename("mean").reset_index()

In [34]:
counterfactual_hgb_mean.columns.name = "draw"
counterfactual_hgb_mean = counterfactual_hgb_mean.stack().rename("mean").reset_index()

In [35]:
hgb_sd = reformat_gbd_data(
    get_draws('modelable_entity_id',
                10488,
                source='epi',
                location_id=list(location_crosswalk.location_id),
                age_group_id=age_group_ids,
                sex_id=list(sex_crosswalk.sex_id),
                year_id=2021,
                release_id=9)
)

hgb_sd = hgb_sd[DRAWS].copy()
hgb_sd

,,,,draw_0,draw_1,draw_2,draw_3,draw_4,draw_5,draw_6,draw_7,draw_8,draw_9,...,draw_490,draw_491,draw_492,draw_493,draw_494,draw_495,draw_496,draw_497,draw_498,draw_499
location,sex,age_start,age_end,,,,,,,,,,,,,,,,,,,,,
India,Female,0.000000,0.019178,11.056572,15.419496,12.937057,14.108613,13.020095,12.577809,17.754828,13.099648,11.912721,13.534418,...,10.329697,10.668878,13.046126,10.782160,11.950843,10.353358,20.932112,15.441125,15.067467,12.300862
Nigeria,Female,0.000000,0.019178,26.026960,23.907182,16.403169,18.715768,17.036223,21.455689,13.328800,27.165364,32.583905,8.017943,...,25.491270,12.187820,14.047787,26.560128,18.689541,12.964533,19.262095,9.520727,18.461955,21.695176
India,Male,0.000000,0.019178,7.610899,6.575979,7.453095,6.250333,7.920491,6.340217,6.466164,6.139428,5.691987,7.091346,...,7.533375,6.431263,7.397510,7.293675,7.932027,7.802585,6.921468,7.639538,8.448905,8.150727
Nigeria,Male,0.000000,0.019178,8.741365,8.444370,10.058485,9.269974,11.570569,8.714296,6.731408,7.346581,8.429818,6.594639,...,6.056589,10.017631,12.212247,11.265512,11.507346,8.898354,16.829171,19.359118,7.850751,10.302650
India,Female,0.019178,0.076712,18.143206,17.170122,18.638921,21.675732,17.362276,18.653702,20.182212,17.627105,18.478847,19.942071,...,18.396669,19.537466,16.708525,20.642018,22.565014,22.806860,18.916546,19.554642,17.105346,19.331287
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Nigeria,Male,0.076712,0.500000,10.834561,14.464839,16.716692,13.781233,14.308120,18.266908,13.962939,16.882978,15.100336,13.834311,...,11.962733,16.352547,21.153987,12.123287,16.187477,11.642224,18.578292,17.016439,19.081475,19.191454
India,Female,0.500000,1.000000,13.756756,14.711771,13.648304,13.187534,13.376081,14.524967,13.737699,14.473522,14.511934,14.818950,...,13.570370,14.580505,13.474202,14.509005,13.042663,14.323584,13.957877,14.127909,13.305026,13.191365
Nigeria,Female,0.500000,1.000000,15.088749,16.763458,14.467460,14.968448,14.433290,15.700162,16.891376,14.383653,13.580970,13.668688,...,13.607053,14.132132,15.332481,15.166399,15.459204,13.412401,14.305163,15.815794,15.249249,13.555534
India,Male,0.500000,1.000000,14.652405,12.306607,13.147011,14.384103,13.694239,15.034635,12.720333,14.333813,14.068139,13.625568,...,11.019248,14.282181,14.629603,13.141845,13.836835,14.308459,15.653441,15.653901,13.516023,14.657258
Nigeria,Male,0.500000,1.000000,17.866906,15.667957,15.926898,17.670570,14.772919,14.854953,30.422870,14.828441,11.787412,15.491633,...,13.173665,13.902300,21.809913,14.368223,19.246321,15.843389,17.233076,13.225374,17.182869,18.253406

In [36]:
hgb_sd.columns.name = "draw"
hgb_sd = hgb_sd.stack().rename("sd").reset_index()
hgb_sd

      location     sex  age_start   age_end      draw         sd
0        India  Female        0.0  0.019178    draw_0  11.056572
1        India  Female        0.0  0.019178    draw_1  15.419496
2        India  Female        0.0  0.019178    draw_2  12.937057
3        India  Female        0.0  0.019178    draw_3  14.108613
4        India  Female        0.0  0.019178    draw_4  13.020095
...        ...     ...        ...       ...       ...        ...
45995  Nigeria    Male        0.5  1.000000  draw_495  15.843389
45996  Nigeria    Male        0.5  1.000000  draw_496  17.233076
45997  Nigeria    Male        0.5  1.000000  draw_497  13.225374
45998  Nigeria    Male        0.5  1.000000  draw_498  17.182869
45999  Nigeria    Male        0.5  1.000000  draw_499  18.253406

[46000 rows x 6 columns]

In [37]:
import risk_distributions

In [38]:
hgb_sd

      location     sex  age_start   age_end      draw         sd
0        India  Female        0.0  0.019178    draw_0  11.056572
1        India  Female        0.0  0.019178    draw_1  15.419496
2        India  Female        0.0  0.019178    draw_2  12.937057
3        India  Female        0.0  0.019178    draw_3  14.108613
4        India  Female        0.0  0.019178    draw_4  13.020095
...        ...     ...        ...       ...       ...        ...
45995  Nigeria    Male        0.5  1.000000  draw_495  15.843389
45996  Nigeria    Male        0.5  1.000000  draw_496  17.233076
45997  Nigeria    Male        0.5  1.000000  draw_497  13.225374
45998  Nigeria    Male        0.5  1.000000  draw_498  17.182869
45999  Nigeria    Male        0.5  1.000000  draw_499  18.253406

[46000 rows x 6 columns]

In [39]:
hgb_mean

,location,sex,age_start,age_end,wealth_quintile,vehicle,draw,mean
0,India,Female,0.0,0.019178,lowest,rice,draw_0,138.477305
1,India,Female,0.0,0.019178,lowest,rice,draw_1,138.622225
2,India,Female,0.0,0.019178,lowest,rice,draw_2,140.460574
3,India,Female,0.0,0.019178,lowest,rice,draw_3,139.921181
4,India,Female,0.0,0.019178,lowest,rice,draw_4,138.651285
...,...,...,...,...,...,...,...,...
229995,Nigeria,Male,95.0,100.000000,highest,bouillon,draw_495,99.179462
229996,Nigeria,Male,95.0,100.000000,highest,bouillon,draw_496,108.553528
229997,Nigeria,Male,95.0,100.000000,highest,bouillon,draw_497,107.702608
229998,Nigeria,Male,95.0,100.000000,highest,bouillon,draw_498,101.506707
229999,Nigeria,Male,95.0,100.000000,highest,bouillon,draw_499,109.774897

In [40]:
mean_and_sd_hgb = pd.concat([
    hgb_mean.merge(hgb_sd, how="outer", validate="m:1").assign(scenario='baseline'),
    counterfactual_hgb_mean.merge(hgb_sd, how="outer", validate="m:1").assign(scenario='intervention')
])
mean_and_sd_hgb

,location,sex,age_start,age_end,wealth_quintile,vehicle,draw,mean,sd,scenario
0,India,Female,0.0,0.019178,lowest,rice,draw_0,138.477305,11.056572,baseline
1,India,Female,0.0,0.019178,second,rice,draw_0,140.618044,11.056572,baseline
2,India,Female,0.0,0.019178,middle,rice,draw_0,140.804466,11.056572,baseline
3,India,Female,0.0,0.019178,fourth,rice,draw_0,142.631768,11.056572,baseline
4,India,Female,0.0,0.019178,highest,rice,draw_0,144.266529,11.056572,baseline
...,...,...,...,...,...,...,...,...,...,...
229995,Nigeria,Male,95.0,100.000000,fourth,bouillon,draw_499,108.137248,17.423849,intervention
229996,Nigeria,Male,95.0,100.000000,highest,bouillon,draw_499,110.067959,17.423849,intervention
229997,Nigeria,Male,95.0,100.000000,lowest,bouillon,draw_499,105.683979,17.423849,intervention
229998,Nigeria,Male,95.0,100.000000,middle,bouillon,draw_499,107.766754,17.423849,intervention
229999,Nigeria,Male,95.0,100.000000,second,bouillon,draw_499,107.325746,17.423849,intervention

In [41]:
thresholds = reformat_gbd_data(
    pd.read_csv('/share/mnch/anemia/code/reference/model/anemia_thresholds.csv')
)
thresholds

                             age_group_name  pregnant              grp  \
sex    age_start age_end
Female 0.000000  0.019178    Early Neonatal         0          under_5
Male   0.000000  0.019178    Early Neonatal         0          under_5
Female 0.019178  0.076712     Late Neonatal         0          under_5
Male   0.019178  0.076712     Late Neonatal         0          under_5
Female 0.076712  0.500000        1-5 months         0          under_5
Male   0.076712  0.500000        1-5 months         0          under_5
Female 0.500000  1.000000       6-11 months         0          under_5
Male   0.500000  1.000000       6-11 months         0          under_5
Female 5.000000  10.000000           5 to 9         0         sa_child
Male   5.000000  10.000000           5 to 9         0         sa_child
Female 10.000000 15.000000         10 to 14         0         sa_child
                 15.000000         10 to 14         1   adult_female_p
Male   10.000000 15.000000         10 to 14         0         sa_child
Female 15.000000 20.000000         15 to 19         0  adult_female_np
                 20.000000         15 to 19         1   adult_female_p
Male   15.000000 20.000000         15 to 19         0       adult_male
Female 20.000000 25.000000         20 to 24         0  adult_female_np
                 25.000000         20 to 24         1   adult_female_p
Male   20.000000 25.000000         20 to 24         0       adult_male
Female 25.000000 30.000000         25 to 29         0  adult_female_np
                 30.000000         25 to 29         1   adult_female_p
Male   25.000000 30.000000         25 to 29         0       adult_male
Female 30.000000 35.000000         30 to 34         0  adult_female_np
                 35.000000         30 to 34         1   adult_female_p
Male   30.000000 35.000000         30 to 34         0       adult_male
Female 35.000000 40.000000         35 to 39         0  adult_female_np
                 40.000000         35 to 39         1   adult_female_p
Male   35.000000 40.000000         35 to 39         0       adult_male
Female 40.000000 45.000000         40 to 44         0  adult_female_np
                 45.000000         40 to 44         1   adult_female_p
Male   40.000000 45.000000         40 to 44         0       adult_male
Female 45.000000 50.000000         45 to 49         0  adult_female_np
                 50.000000         45 to 49         1   adult_female_p
Male   45.000000 50.000000         45 to 49         0       adult_male
Female 50.000000 55.000000         50 to 54         0  adult_female_np
                 55.000000         50 to 54         1   adult_female_p
Male   50.000000 55.000000         50 to 54         0       adult_male
Female 55.000000 60.000000         55 to 59         0  adult_female_np
Male   55.000000 60.000000         55 to 59         0       adult_male
Female 60.000000 65.000000         60 to 64         0  adult_female_np
Male   60.000000 65.000000         60 to 64         0       adult_male
Female 65.000000 70.000000         65 to 69         0  adult_female_np
Male   65.000000 70.000000         65 to 69         0       adult_male
Female 70.000000 75.000000         70 to 74         0  adult_female_np
Male   70.000000 75.000000         70 to 74         0       adult_male
Female 75.000000 80.000000         75 to 79         0  adult_female_np
Male   75.000000 80.000000         75 to 79         0       adult_male
Female 80.000000 85.000000         80 to 84         0  adult_female_np
Male   80.000000 85.000000         80 to 84         0       adult_male
Female 85.000000 90.000000         85 to 89         0  adult_female_np
Male   85.000000 90.000000         85 to 89         0       adult_male
Female 90.000000 95.000000         90 to 94         0  adult_female_np
Male   90.000000 95.000000         90 to 94         0       adult_male
Female 95.000000 100.000000         95 plus         0  adult_female_np
Male   95.000000 100.000000         95 plus         0       adult_male

                             hgb_lower_mild  hgb_upper_mild  \
sex    age_start age_end
Female 0.000000  0.019178               145             160
Male   0.000000  0.019178               145             160
Female 0.019178  0.076712               120             135
Male   0.019178  0.076712               120             135
Female 0.076712  0.500000               100             110
Male   0.076712  0.500000               100             110
Female 0.500000  1.000000               100             110
Male   0.500000  1.000000               100             110
Female 5.000000  10.000000              110             115
Male   5.000000  10.000000              110             115
Female 10.000000 15.000000              110             115
                 15.000000              100             110
Male   10.000000 15.000000              110             115
Female 15.000000 20.000000              110             120
                 20.000000              100             110
Male   15.000000 20.000000              110             130
Female 20.000000 25.000000              110             120
                 25.000000              100             110
Male   20.000000 25.000000              110             130
Female 25.000000 30.000000              110             120
                 30.000000              100             110
Male   25.000000 30.000000              110             130
Female 30.000000 35.000000              110             120
                 35.000000              100             110
Male   30.000000 35.000000              110             130
Female 35.000000 40.000000              110             120
                 40.000000              100             110
Male   35.000000 40.000000              110             130
Female 40.000000 45.000000              110             120
                 45.000000              100             110
Male   40.000000 45.000000              110             130
Female 45.000000 50.000000              110             120
                 50.000000              100             110
Male   45.000000 50.000000              110             130
Female 50.000000 55.000000              110             120
                 55.000000              100             110
Male   50.000000 55.000000              110             130
Female 55.000000 60.000000              110             120
Male   55.000000 60.000000              110             130
Female 60.000000 65.000000              110             120
Male   60.000000 65.000000              110             130
Female 65.000000 70.000000              110             120
Male   65.000000 70.000000              110             130
Female 70.000000 75.000000              110             120
Male   70.000000 75.000000              110             130
Female 75.000000 80.000000              110             120
Male   75.000000 80.000000              110             130
Female 80.000000 85.000000              110             120
Male   80.000000 85.000000              110             130
Female 85.000000 90.000000              110             120
Male   85.000000 90.000000              110             130
Female 90.000000 95.000000              110             120
Male   90.000000 95.000000              110             130
Female 95.000000 100.000000             110             120
Male   95.000000 100.000000             110             130

                             hgb_lower_moderate  hgb_upper_moderate  \
sex    age_start age_end
Female 0.000000  0.019178                   100                 145
Male   0.000000  0.019178                   100                 145
Female 0.019178  0.076712                    85                 120
Male   0.019178  0.076712                    85                 120
Female 0.076712  0.500000                    70                 100
Male   0.076712  0.500000                    70                 100
Female 0.500000  1.000000                    70                 100
Male   0.500000  1.000000                    70                 100
Female 5.000000  10.000000                   80                 110
Male   5.000000  10.000000                   80                 110
Female 10.000000 15.000000                   80                 110
                 15.000000                   70                 100
Male   10.000000 15.000000                   80                 110
Female 15.000000 20.000000                   80                 110
                 20.000000                   70                 100
Male   15.000000 20.000000                   80                 110
Female 20.000000 25.000000                   80                 110
                 25.000000                   70                 100
Male   20.000000 25.000000                   80                 110
Female 25.000000 30.000000                   80                 110
                 30.000000                   70                 100
Male   25.000000 30.000000                   80                 110
Female 30.000000 35.000000                   80                 110
                 35.000000                   70                 100
Male   30.000000 35.000000                   80                 110
Female 35.000000 40.000000                   80                 110
                 40.000000                   70                 100
Male   35.000000 40.000000                   80                 110
Female 40.000000 45.000000                   80                 110
                 45.000000                   70                 100
Male   40.000000 45.000000                   80                 110
Female 45.000000 50.000000                   80                 110
                 50.000000                   70                 100
Male   45.000000 50.000000                   80                 110
Female 50.000000 55.000000                   80                 110
                 55.000000                   70                 100
Male   50.000000 55.000000                   80                 110
Female 55.000000 60.000000                   80                 110
Male   55.000000 60.000000                   80                 110
Female 60.000000 65.000000                   80                 110
Male   60.000000 65.000000                   80                 110
Female 65.000000 70.000000                   80                 110
Male   65.000000 70.000000                   80                 110
Female 70.000000 75.000000                   80                 110
Male   70.000000 75.000000                   80                 110
Female 75.000000 80.000000                   80                 110
Male   75.000000 80.000000                   80                 110
Female 80.000000 85.000000                   80                 110
Male   80.000000 85.000000                   80                 110
Female 85.000000 90.000000                   80                 110
Male   85.000000 90.000000                   80                 110
Female 90.000000 95.000000                   80                 110
Male   90.000000 95.000000                   80                 110
Female 95.000000 100.000000                  80                 110
Male   95.000000 100.000000                  80                 110

                             hgb_lower_severe  hgb_upper_severe  \
sex    age_start age_end
Female 0.000000  0.019178                   0               100
Male   0.000000  0.019178                   0               100
Female 0.019178  0.076712                   0                85
Male   0.019178  0.076712                   0                85
Female 0.076712  0.500000                   0                70
Male   0.076712  0.500000                   0                70
Female 0.500000  1.000000                   0                70
Male   0.500000  1.000000                   0                70
Female 5.000000  10.000000                  0                80
Male   5.000000  10.000000                  0                80
Female 10.000000 15.000000                  0                80
                 15.000000                  0                70
Male   10.000000 15.000000                  0                80
Female 15.000000 20.000000                  0                80
                 20.000000                  0                70
Male   15.000000 20.000000                  0                80
Female 20.000000 25.000000                  0                80
                 25.000000                  0                70
Male   20.000000 25.000000                  0                80
Female 25.000000 30.000000                  0                80
                 30.000000                  0                70
Male   25.000000 30.000000                  0                80
Female 30.000000 35.000000                  0                80
                 35.000000                  0                70
Male   30.000000 35.000000                  0                80
Female 35.000000 40.000000                  0                80
                 40.000000                  0                70
Male   35.000000 40.000000                  0                80
Female 40.000000 45.000000                  0                80
                 45.000000                  0                70
Male   40.000000 45.000000                  0                80
Female 45.000000 50.000000                  0                80
                 50.000000                  0                70
Male   45.000000 50.000000                  0                80
Female 50.000000 55.000000                  0                80
                 55.000000                  0                70
Male   50.000000 55.000000                  0                80
Female 55.000000 60.000000                  0                80
Male   55.000000 60.000000                  0                80
Female 60.000000 65.000000                  0                80
Male   60.000000 65.000000                  0                80
Female 65.000000 70.000000                  0                80
Male   65.000000 70.000000                  0                80
Female 70.000000 75.000000                  0                80
Male   70.000000 75.000000                  0                80
Female 75.000000 80.000000                  0                80
Male   75.000000 80.000000                  0                80
Female 80.000000 85.000000                  0                80
Male   80.000000 85.000000                  0                80
Female 85.000000 90.000000                  0                80
Male   85.000000 90.000000                  0                80
Female 90.000000 95.000000                  0                80
Male   90.000000 95.000000                  0                80
Female 95.000000 100.000000                 0                80
Male   95.000000 100.000000                 0                80

                             hgb_lower_anemic  hgb_upper_anemic
sex    age_start age_end
Female 0.000000  0.019178                   0               160
Male   0.000000  0.019178                   0               160
Female 0.019178  0.076712                   0               135
Male   0.019178  0.076712                   0               135
Female 0.076712  0.500000                   0               110
Male   0.076712  0.500000                   0               110
Female 0.500000  1.000000                   0               110
Male   0.500000  1.000000                   0               110
Female 5.000000  10.000000                  0               115
Male   5.000000  10.000000                  0               115
Female 10.000000 15.000000                  0               115
                 15.000000                  0               110
Male   10.000000 15.000000                  0               115
Female 15.000000 20.000000                  0               120
                 20.000000                  0               110
Male   15.000000 20.000000                  0               130
Female 20.000000 25.000000                  0               120
                 25.000000                  0               110
Male   20.000000 25.000000                  0               130
Female 25.000000 30.000000                  0               120
                 30.000000                  0               110
Male   25.000000 30.000000                  0               130
Female 30.000000 35.000000                  0               120
                 35.000000                  0               110
Male   30.000000 35.000000                  0               130
Female 35.000000 40.000000                  0               120
                 40.000000                  0               110
Male   35.000000 40.000000                  0               130
Female 40.000000 45.000000                  0               120
                 45.000000                  0               110
Male   40.000000 45.000000                  0               130
Female 45.000000 50.000000                  0               120
                 50.000000                  0               110
Male   45.000000 50.000000                  0               130
Female 50.000000 55.000000                  0               120
                 55.000000                  0               110
Male   50.000000 55.000000                  0               130
Female 55.000000 60.000000                  0               120
Male   55.000000 60.000000                  0               130
Female 60.000000 65.000000                  0               120
Male   60.000000 65.000000                  0               130
Female 65.000000 70.000000                  0               120
Male   65.000000 70.000000                  0               130
Female 70.000000 75.000000                  0               120
Male   70.000000 75.000000                  0               130
Female 75.000000 80.000000                  0               120
Male   75.000000 80.000000                  0               130
Female 80.000000 85.000000                  0               120
Male   80.000000 85.000000                  0               130
Female 85.000000 90.000000                  0               120
Male   85.000000 90.000000                  0               130
Female 90.000000 95.000000                  0               120
Male   90.000000 95.000000                  0               130
Female 95.000000 100.000000                 0               120
Male   95.000000 100.000000                 0               130

In [42]:
mean_and_sd_hgb = mean_and_sd_hgb.assign(pregnant=0).merge(thresholds, on=["sex", "age_start", "age_end", "pregnant"], how="left", validate="m:1")
mean_and_sd_hgb

,location,sex,age_start,age_end,wealth_quintile,vehicle,draw,mean,sd,scenario,...,age_group_name,grp,hgb_lower_mild,hgb_upper_mild,hgb_lower_moderate,hgb_upper_moderate,hgb_lower_severe,hgb_upper_severe,hgb_lower_anemic,hgb_upper_anemic
0,India,Female,0.0,0.019178,lowest,rice,draw_0,138.477305,11.056572,baseline,...,Early Neonatal,under_5,145,160,100,145,0,100,0,160
1,India,Female,0.0,0.019178,second,rice,draw_0,140.618044,11.056572,baseline,...,Early Neonatal,under_5,145,160,100,145,0,100,0,160
2,India,Female,0.0,0.019178,middle,rice,draw_0,140.804466,11.056572,baseline,...,Early Neonatal,under_5,145,160,100,145,0,100,0,160
3,India,Female,0.0,0.019178,fourth,rice,draw_0,142.631768,11.056572,baseline,...,Early Neonatal,under_5,145,160,100,145,0,100,0,160
4,India,Female,0.0,0.019178,highest,rice,draw_0,144.266529,11.056572,baseline,...,Early Neonatal,under_5,145,160,100,145,0,100,0,160
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459995,Nigeria,Male,95.0,100.000000,fourth,bouillon,draw_499,108.137248,17.423849,intervention,...,95 plus,adult_male,110,130,80,110,0,80,0,130
459996,Nigeria,Male,95.0,100.000000,highest,bouillon,draw_499,110.067959,17.423849,intervention,...,95 plus,adult_male,110,130,80,110,0,80,0,130
459997,Nigeria,Male,95.0,100.000000,lowest,bouillon,draw_499,105.683979,17.423849,intervention,...,95 plus,adult_male,110,130,80,110,0,80,0,130
459998,Nigeria,Male,95.0,100.000000,middle,bouillon,draw_499,107.766754,17.423849,intervention,...,95 plus,adult_male,110,130,80,110,0,80,0,130
459999,Nigeria,Male,95.0,100.000000,second,bouillon,draw_499,107.325746,17.423849,intervention,...,95 plus,adult_male,110,130,80,110,0,80,0,130

In [43]:
assert (
    (mean_and_sd_hgb.hgb_upper_mild == mean_and_sd_hgb.hgb_upper_anemic).all() &
    (mean_and_sd_hgb.hgb_lower_severe == mean_and_sd_hgb.hgb_lower_anemic).all()
)
mean_and_sd_hgb = mean_and_sd_hgb.drop(columns=["hgb_upper_anemic", "hgb_lower_anemic"])

In [44]:
assert (
    (mean_and_sd_hgb.hgb_lower_mild == mean_and_sd_hgb.hgb_upper_moderate).all() &
    (mean_and_sd_hgb.hgb_lower_moderate == mean_and_sd_hgb.hgb_upper_severe).all()
)
mean_and_sd_hgb = mean_and_sd_hgb.drop(columns=["hgb_lower_mild", "hgb_lower_moderate"])

In [45]:
def _hemoglobin_distribution_parts_from_mean_sd(mean, sd):
    # NOTE: This is an unusual ensemble distribution. We should add functionality to the
    # EnsembleDistribution class to make this easier.
    x_min = 0
    x_max = 220
    gamma_params = risk_distributions.risk_distributions.Gamma.get_parameters(
        mean=mean, sd=sd
    )
    # NOTE: We have to override these, otherwise Gamma is overly conservative in what values
    # are computable
    # https://github.com/ihmeuw/risk_distributions/issues/61
    gamma_params["x_min"] = x_min
    gamma_params["x_max"] = x_max
    hemoglobin_distribution_gamma_part = risk_distributions.risk_distributions.Gamma(
        gamma_params
    )

    # NOTE: Forced to duplicate https://github.com/ihmeuw/risk_distributions/blob/a9ed9d7e8372590018355012a7a7ffefa87b0819/src/risk_distributions/risk_distributions.py#L428-L434
    # because it doesn't permit the custom x_min and x_max, and these are used in calculating the others
    mgumbel_params = pd.DataFrame({
        "loc": x_max - mean - (np.euler_gamma * np.sqrt(6) / np.pi * sd),
        "scale": np.sqrt(6) / np.pi * sd,
        "x_min": x_min,
        "x_max": x_max,
    })
    hemoglobin_distribution_mgumbel_part = (
        risk_distributions.risk_distributions.MirroredGumbel(mgumbel_params)
    )
    return hemoglobin_distribution_gamma_part, hemoglobin_distribution_mgumbel_part

(
    hemoglobin_distribution_gamma_part,
    hemoglobin_distribution_mgumbel_part,
) = _hemoglobin_distribution_parts_from_mean_sd(mean_and_sd_hgb['mean'], mean_and_sd_hgb.sd)

def cdf(x):
    gamma_cdf = hemoglobin_distribution_gamma_part.cdf(x)
    # NOTE: There is a bug in this CDF function -- it is reversed!
    # https://github.com/ihmeuw/risk_distributions/issues/62
    mgumbel_cdf = 1 - hemoglobin_distribution_mgumbel_part.cdf(x)
    return (
        0.4
        * gamma_cdf
        + 0.6
        * mgumbel_cdf
    )

In [46]:
mean_and_sd_hgb["severe"] = cdf(mean_and_sd_hgb.hgb_upper_severe.copy()) - cdf(mean_and_sd_hgb.hgb_lower_severe.copy())
mean_and_sd_hgb["moderate"] = cdf(mean_and_sd_hgb.hgb_upper_moderate.copy()) - mean_and_sd_hgb["severe"].copy()
mean_and_sd_hgb["mild"] = cdf(mean_and_sd_hgb.hgb_upper_mild.copy()) - mean_and_sd_hgb["moderate"].copy() - mean_and_sd_hgb["severe"].copy()
mean_and_sd_hgb["anemic"] = mean_and_sd_hgb["mild"] + mean_and_sd_hgb["moderate"] + mean_and_sd_hgb["severe"]
mean_and_sd_hgb

,location,sex,age_start,age_end,wealth_quintile,vehicle,draw,mean,sd,scenario,...,age_group_name,grp,hgb_upper_mild,hgb_upper_moderate,hgb_lower_severe,hgb_upper_severe,severe,moderate,mild,anemic
0,India,Female,0.0,0.019178,lowest,rice,draw_0,138.477305,11.056572,baseline,...,Early Neonatal,under_5,160,145,0,100,0.003894,0.706046,0.277390,0.987329
1,India,Female,0.0,0.019178,second,rice,draw_0,140.618044,11.056572,baseline,...,Early Neonatal,under_5,160,145,0,100,0.003030,0.625916,0.350447,0.979392
2,India,Female,0.0,0.019178,middle,rice,draw_0,140.804466,11.056572,baseline,...,Early Neonatal,under_5,160,145,0,100,0.002965,0.618794,0.356695,0.978454
3,India,Female,0.0,0.019178,fourth,rice,draw_0,142.631768,11.056572,baseline,...,Early Neonatal,under_5,160,145,0,100,0.002396,0.548791,0.415040,0.966227
4,India,Female,0.0,0.019178,highest,rice,draw_0,144.266529,11.056572,baseline,...,Early Neonatal,under_5,160,145,0,100,0.001982,0.487061,0.460202,0.949245
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459995,Nigeria,Male,95.0,100.000000,fourth,bouillon,draw_499,108.137248,17.423849,intervention,...,95 plus,adult_male,130,110,0,80,0.057745,0.452552,0.409866,0.920163
459996,Nigeria,Male,95.0,100.000000,highest,bouillon,draw_499,110.067959,17.423849,intervention,...,95 plus,adult_male,130,110,0,80,0.048209,0.416406,0.431422,0.896036
459997,Nigeria,Male,95.0,100.000000,lowest,bouillon,draw_499,105.683979,17.423849,intervention,...,95 plus,adult_male,130,110,0,80,0.072486,0.497147,0.374489,0.944122
459998,Nigeria,Male,95.0,100.000000,middle,bouillon,draw_499,107.766754,17.423849,intervention,...,95 plus,adult_male,130,110,0,80,0.059773,0.459413,0.405066,0.924252
459999,Nigeria,Male,95.0,100.000000,second,bouillon,draw_499,107.325746,17.423849,intervention,...,95 plus,adult_male,130,110,0,80,0.062277,0.467532,0.399089,0.928897

In [47]:
disability_weights = pd.read_hdf('/mnt/team/simulation_science/costeffectiveness/auxiliary_data/GBD_2021/02_processed_data/disability_weight/sequela/all/all.hdf')
disability_weights = disability_weights[disability_weights.healthstate.isin(['anemia_mild', 'anemia_mod', 'anemia_sev'])].set_index('healthstate').filter(like='draw_')
disability_weights.columns.name = 'draw'
disability_weights = disability_weights.stack().rename('disability_weight').reset_index()
disability_weights

      healthstate      draw  disability_weight
0     anemia_mild    draw_0           0.002420
1     anemia_mild    draw_1           0.003172
2     anemia_mild    draw_2           0.002644
3     anemia_mild    draw_3           0.003085
4     anemia_mild    draw_4           0.001845
...           ...       ...                ...
2995   anemia_sev  draw_995           0.174969
2996   anemia_sev  draw_996           0.086798
2997   anemia_sev  draw_997           0.131996
2998   anemia_sev  draw_998           0.124427
2999   anemia_sev  draw_999           0.138260

[3000 rows x 3 columns]

In [48]:
mean_and_sd_hgb = mean_and_sd_hgb.merge(
    disability_weights[disability_weights.healthstate == 'anemia_mild'][['draw', 'disability_weight']].rename(columns={'disability_weight': 'mild_dw'}),
    validate="m:1",
).merge(
    disability_weights[disability_weights.healthstate == 'anemia_mod'][['draw', 'disability_weight']].rename(columns={'disability_weight': 'moderate_dw'}),
    validate="m:1",
).merge(
    disability_weights[disability_weights.healthstate == 'anemia_sev'][['draw', 'disability_weight']].rename(columns={'disability_weight': 'severe_dw'}),
    validate="m:1",
)

In [49]:
mean_and_sd_hgb["mild_ylds"] = mean_and_sd_hgb.mild * mean_and_sd_hgb.mild_dw
mean_and_sd_hgb["moderate_ylds"] = mean_and_sd_hgb.moderate * mean_and_sd_hgb.moderate_dw
mean_and_sd_hgb["severe_ylds"] = mean_and_sd_hgb.severe * mean_and_sd_hgb.severe_dw
mean_and_sd_hgb['anemic_ylds'] = mean_and_sd_hgb['mild_ylds'] + mean_and_sd_hgb['moderate_ylds'] + mean_and_sd_hgb['severe_ylds']

In [50]:
index_cols = ['location', 'age_start', 'age_end', 'sex', 'draw', 'vehicle', "wealth_quintile"]
value_cols = ["mild", "moderate", "severe", "anemic", "mild_ylds", "moderate_ylds", "severe_ylds", "anemic_ylds"]

baseline_anemia = mean_and_sd_hgb[mean_and_sd_hgb.scenario == 'baseline'].set_index(index_cols)[value_cols]
counterfactual_anemia = mean_and_sd_hgb[mean_and_sd_hgb.scenario == 'intervention'].set_index(index_cols)[value_cols]

In [51]:
baseline_anemia.sort_index()

                                                                           mild  \
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth           0.415040
                                                      highest          0.460202
                                                      lowest           0.277390
                                                      middle           0.356695
                                                      second           0.350447
...                                                                         ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth           0.308946
                                                      highest          0.327652
                                                      lowest           0.277851
                                                      middle           0.304404
                                                      second           0.298027

                                                                       moderate  \
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth           0.548791
                                                      highest          0.487061
                                                      lowest           0.706046
                                                      middle           0.618794
                                                      second           0.625916
...                                                                         ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth           0.468263
                                                      highest          0.448116
                                                      lowest           0.493218
                                                      middle           0.472472
                                                      second           0.478019

                                                                         severe  \
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth           0.002396
                                                      highest          0.001982
                                                      lowest           0.003894
                                                      middle           0.002965
                                                      second           0.003030
...                                                                         ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth           0.141823
                                                      highest          0.124332
                                                      lowest           0.169661
                                                      middle           0.145947
                                                      second           0.151688

                                                                         anemic  \
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth           0.966227
                                                      highest          0.949245
                                                      lowest           0.987329
                                                      middle           0.978454
                                                      second           0.979392
...                                                                         ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth           0.919033
                                                      highest          0.900100
                                                      lowest           0.940731
                                                      middle           0.922823
                                                      second           0.927734

                                                                       mild_ylds  \
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth            0.001005
                                                      highest           0.001114
                                                      lowest            0.000671
                                                      middle            0.000863
                                                      second            0.000848
...                                                                          ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth            0.001298
                                                      highest           0.001376
                                                      lowest            0.001167
                                                      middle            0.001279
                                                      second            0.001252

                                                                       moderate_ylds  \
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth                0.032544
                                                      highest               0.028883
                                                      lowest                0.041869
                                                      middle                0.036695
                                                      second                0.037117
...                                                                              ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth                0.019518
                                                      highest               0.018678
                                                      lowest                0.020558
                                                      middle                0.019693
                                                      second                0.019924

                                                                       severe_ylds  \
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth              0.000477
                                                      highest             0.000394
                                                      lowest              0.000775
                                                      middle              0.000590
                                                      second              0.000603
...                                                                            ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth              0.016846
                                                      highest             0.014769
                                                      lowest              0.020153
                                                      middle              0.017336
                                                      second              0.018018

                                                                       anemic_ylds
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth              0.034025
                                                      highest             0.030391
                                                      lowest              0.043315
                                                      middle              0.038148
                                                      second              0.038568
...                                                                            ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth              0.037662
                                                      highest             0.034823
                                                      lowest              0.041878
                                                      middle              0.038308
                                                      second              0.039194

[230000 rows x 8 columns]

In [52]:
counterfactual_anemia.sort_index()

                                                                           mild  \
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth           0.436339
                                                      highest          0.481151
                                                      lowest           0.298026
                                                      middle           0.378799
                                                      second           0.371078
...                                                                         ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth           0.313116
                                                      highest          0.330200
                                                      lowest           0.287961
                                                      middle           0.309567
                                                      second           0.305264

                                                                       moderate  \
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth           0.520881
                                                      highest          0.453881
                                                      lowest           0.683881
                                                      middle           0.593111
                                                      second           0.602177
...                                                                         ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth           0.464191
                                                      highest          0.444935
                                                      lowest           0.486012
                                                      middle           0.467670
                                                      second           0.471692

                                                                         severe  \
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth           0.002200
                                                      highest          0.001785
                                                      lowest           0.003628
                                                      middle           0.002742
                                                      second           0.002818
...                                                                         ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth           0.138005
                                                      highest          0.121854
                                                      lowest           0.160675
                                                      middle           0.141257
                                                      second           0.145168

                                                                         anemic  \
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth           0.959420
                                                      highest          0.936817
                                                      lowest           0.985535
                                                      middle           0.974651
                                                      second           0.976073
...                                                                         ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth           0.915312
                                                      highest          0.896989
                                                      lowest           0.934648
                                                      middle           0.918494
                                                      second           0.922125

                                                                       mild_ylds  \
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth            0.001056
                                                      highest           0.001165
                                                      lowest            0.000721
                                                      middle            0.000917
                                                      second            0.000898
...                                                                          ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth            0.001315
                                                      highest           0.001387
                                                      lowest            0.001209
                                                      middle            0.001300
                                                      second            0.001282

                                                                       moderate_ylds  \
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth                0.030888
                                                      highest               0.026915
                                                      lowest                0.040554
                                                      middle                0.035172
                                                      second                0.035709
...                                                                              ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth                0.019348
                                                      highest               0.018545
                                                      lowest                0.020258
                                                      middle                0.019493
                                                      second                0.019661

                                                                       severe_ylds  \
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth              0.000438
                                                      highest             0.000355
                                                      lowest              0.000722
                                                      middle              0.000545
                                                      second              0.000561
...                                                                            ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth              0.016393
                                                      highest             0.014475
                                                      lowest              0.019086
                                                      middle              0.016779
                                                      second              0.017244

                                                                       anemic_ylds
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth              0.032382
                                                      highest             0.028435
                                                      lowest              0.041998
                                                      middle              0.036634
                                                      second              0.037168
...                                                                            ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth              0.037056
                                                      highest             0.034407
                                                      lowest              0.040553
                                                      middle              0.037572
                                                      second              0.038187

[230000 rows x 8 columns]

In [53]:
baseline_anemia - counterfactual_anemia

                                                                           mild  \
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth          -0.021299
                                                      highest         -0.020949
                                                      lowest          -0.020637
                                                      middle          -0.022103
                                                      second          -0.020631
...                                                                         ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth          -0.004170
                                                      highest         -0.002548
                                                      lowest          -0.010110
                                                      middle          -0.005163
                                                      second          -0.007237

                                                                       moderate  \
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth           0.027910
                                                      highest          0.033180
                                                      lowest           0.022165
                                                      middle           0.025683
                                                      second           0.023739
...                                                                         ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth           0.004072
                                                      highest          0.003181
                                                      lowest           0.007207
                                                      middle           0.004802
                                                      second           0.006326

                                                                         severe  \
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth           0.000196
                                                      highest          0.000197
                                                      lowest           0.000267
                                                      middle           0.000223
                                                      second           0.000212
...                                                                         ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth           0.003818
                                                      highest          0.002477
                                                      lowest           0.008986
                                                      middle           0.004690
                                                      second           0.006520

                                                                         anemic  \
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth           0.006808
                                                      highest          0.012428
                                                      lowest           0.001794
                                                      middle           0.003803
                                                      second           0.003319
...                                                                         ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth           0.003721
                                                      highest          0.003111
                                                      lowest           0.006082
                                                      middle           0.004329
                                                      second           0.005609

                                                                       mild_ylds  \
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth           -0.000052
                                                      highest          -0.000051
                                                      lowest           -0.000050
                                                      middle           -0.000054
                                                      second           -0.000050
...                                                                          ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth           -0.000018
                                                      highest          -0.000011
                                                      lowest           -0.000042
                                                      middle           -0.000022
                                                      second           -0.000030

                                                                       moderate_ylds  \
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth                0.001655
                                                      highest               0.001968
                                                      lowest                0.001314
                                                      middle                0.001523
                                                      second                0.001408
...                                                                              ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth                0.000170
                                                      highest               0.000133
                                                      lowest                0.000300
                                                      middle                0.000200
                                                      second                0.000264

                                                                       severe_ylds  \
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth              0.000039
                                                      highest             0.000039
                                                      lowest              0.000053
                                                      middle              0.000044
                                                      second              0.000042
...                                                                            ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth              0.000454
                                                      highest             0.000294
                                                      lowest              0.001067
                                                      middle              0.000557
                                                      second              0.000774

                                                                       anemic_ylds
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth              0.001643
                                                      highest             0.001956
                                                      lowest              0.001317
                                                      middle              0.001514
                                                      second              0.001400
...                                                                            ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth              0.000606
                                                      highest             0.000416
                                                      lowest              0.001325
                                                      middle              0.000736
                                                      second              0.001008

[230000 rows x 8 columns]

In [54]:
# BUT our counterfactual is only in a world where everyone is iron-responsive.
iron_responsive_anemia_sequelae = [1004, 1005, 1006, 1008, 1009, 1010, 1012, 1013, 
                                   1014, 1016, 1017, 1018, 1020, 1021, 1022, 1024, 1025, 1026, 
                                   1028, 1029, 1030, 1032, 1033, 1034, 1361, 1364, 1367, 1373, 1376, 
                                   1379, 1385, 1388, 1391, 1397, 1400, 1403, 1409, 1412, 1415, 1421, 
                                   1424, 1427, 1433, 1436, 1439, 1445, 1448, 1451, 5213, 5216, 5219, 
                                   5222, 5225, 5228, 5237, 5240, 5243, 5246, 5249, 5252, 5261, 5264, 
                                   5267, 5270, 5273, 5276, 4985, 4988, 4991, 4994, 4997, 5000, 5009, 
                                   5012, 5015, 5678, 5681, 5684, 7214, 7217, 7220, 4952, 4955, 4958, 
                                   4961, 4964, 4967, 4976, 4979, 4982, 5627, 5630, 5633, 7202, 7205, 
                                   7208, 5393, 5396, 5399, 182, 183, 184, 240, 241, 242, 177, 178, 
                                   179, 144,145,146,172,173,174,525,526,527,1106,1107,1108,537,538,
                                   539,206,207,208, 22989, 22990, 22991, 22992, 22993, 22999, 23000, 
                                   23001, 23002, 23003, 23009, 23010, 23011, 23012, 23013,
                                   5567, 5570, 5573, 5579, 5582, 5585,
                                   23030, 23031, 23032, 23034, 23035, 23036, 23038, 23039, 23040,
                                   23042, 23043, 23044, 23046, 23047, 23048]

ira_prev = reformat_gbd_data(get_draws('sequela_id', iron_responsive_anemia_sequelae, 
                 source='como',
                 location_id=list(location_crosswalk.location_id),
                 age_group_id=age_group_ids,
                 sex_id=list(sex_crosswalk.sex_id),
                 year_id=2021,
                 release_id=9))
ira_prev = ira_prev.groupby(['location', 'sex', 'age_start', 'age_end']).sum().filter(like="draw")
ira_prev

/ihme/homes/zmbc/src/vivarium_gates_lsff_by_wealth_quintile/5000_analyze_results/.venv/lib/python3.11/site-packages/get_draws/api.py:192: UserWarning: No version_id was specified, so get_draws will automatically determine a best version ID to use from the given parameters. If you want to retrieve a specific version please pass a version_id directly.
  warnings.warn(

                                        draw_0    draw_1   draw_10  draw_100  \
location sex    age_start age_end
India    Female 0.000000  0.019178    0.899755  0.857321  0.874569  0.887292
                0.019178  0.076712    0.554685  0.561048  0.597522  0.581726
                0.076712  0.500000    0.643967  0.624061  0.637449  0.645793
                0.500000  1.000000    0.725464  0.750456  0.728443  0.701269
                5.000000  10.000000   0.555297  0.520194  0.565855  0.496835
...                                        ...       ...       ...       ...
Nigeria  Male   75.000000 80.000000   0.351996  0.298188  0.312676  0.250711
                80.000000 85.000000   0.406368  0.438780  0.325427  0.407567
                85.000000 90.000000   0.468550  0.372964  0.461027  0.401142
                90.000000 95.000000   0.790239  0.790406  0.814604  0.779747
                95.000000 100.000000  0.814702  0.794083  0.811262  0.809367

                                      draw_101  draw_102  draw_103  draw_104  \
location sex    age_start age_end
India    Female 0.000000  0.019178    0.890960  0.855054  0.900705  0.873191
                0.019178  0.076712    0.594051  0.552846  0.589743  0.603153
                0.076712  0.500000    0.655441  0.671472  0.655737  0.656435
                0.500000  1.000000    0.727631  0.716115  0.744202  0.733556
                5.000000  10.000000   0.557040  0.508719  0.506782  0.499247
...                                        ...       ...       ...       ...
Nigeria  Male   75.000000 80.000000   0.239969  0.222730  0.267228  0.218114
                80.000000 85.000000   0.476539  0.406879  0.376987  0.267299
                85.000000 90.000000   0.368977  0.479217  0.373618  0.430667
                90.000000 95.000000   0.738822  0.810613  0.789167  0.804813
                95.000000 100.000000  0.771474  0.824473  0.831639  0.738796

                                      draw_105  draw_106  ...   draw_90  \
location sex    age_start age_end                         ...
India    Female 0.000000  0.019178    0.882671  0.851349  ...  0.882201
                0.019178  0.076712    0.583521  0.590471  ...  0.593110
                0.076712  0.500000    0.632689  0.662699  ...  0.634974
                0.500000  1.000000    0.676764  0.684945  ...  0.730368
                5.000000  10.000000   0.548485  0.523623  ...  0.511438
...                                        ...       ...  ...       ...
Nigeria  Male   75.000000 80.000000   0.206974  0.305279  ...  0.381780
                80.000000 85.000000   0.332065  0.260452  ...  0.412952
                85.000000 90.000000   0.476602  0.398233  ...  0.550522
                90.000000 95.000000   0.497839  0.720409  ...  0.842854
                95.000000 100.000000  0.824819  0.860051  ...  0.872844

                                       draw_91   draw_92   draw_93   draw_94  \
location sex    age_start age_end
India    Female 0.000000  0.019178    0.886455  0.870279  0.898175  0.932924
                0.019178  0.076712    0.550909  0.578389  0.587658  0.563501
                0.076712  0.500000    0.650047  0.639402  0.655071  0.677751
                0.500000  1.000000    0.729601  0.764601  0.733136  0.744315
                5.000000  10.000000   0.521493  0.512802  0.551412  0.508867
...                                        ...       ...       ...       ...
Nigeria  Male   75.000000 80.000000   0.266314  0.413537  0.228288  0.222798
                80.000000 85.000000   0.410859  0.566198  0.224144  0.318082
                85.000000 90.000000   0.447799  0.432167  0.400423  0.408042
                90.000000 95.000000   0.798896  0.837589  0.771650  0.802353
                95.000000 100.000000  0.750285  0.808186  0.807051  0.834591

                                       draw_95   draw_96   draw_97   draw_98  \
location sex    age_start age_end
India    Female 0.000000  0.019178    0.860818  0.914988  0.909893  0.880446
                0.019178  0.076712    0.553161  0.597025  0.561666  0.552383
                0.076712  0.500000    0.681264  0.679245  0.685253  0.664178
                0.500000  1.000000    0.690546  0.719280  0.739307  0.747377
                5.000000  10.000000   0.524569  0.509383  0.506688  0.491530
...                                        ...       ...       ...       ...
Nigeria  Male   75.000000 80.000000   0.300589  0.230692  0.247713  0.218047
                80.000000 85.000000   0.302188  0.385459  0.360242  0.307777
                85.000000 90.000000   0.390677  0.420622  0.472688  0.430528
                90.000000 95.000000   0.784153  0.772980  0.819392  0.828180
                95.000000 100.000000  0.794225  0.814850  0.790197  0.853127

                                       draw_99
location sex    age_start age_end
India    Female 0.000000  0.019178    0.919725
                0.019178  0.076712    0.556267
                0.076712  0.500000    0.650342
                0.500000  1.000000    0.730879
                5.000000  10.000000   0.500628
...                                        ...
Nigeria  Male   75.000000 80.000000   0.201266
                80.000000 85.000000   0.440308
                85.000000 90.000000   0.452254
                90.000000 95.000000   0.805370
                95.000000 100.000000  0.751525

[92 rows x 500 columns]

In [55]:
ira_prev.columns.name = "draw"
ira_prev = ira_prev.stack().pipe(lambda s: s[s.index.get_level_values("draw").isin(DRAWS)])
ira_prev

location  sex     age_start  age_end     draw
India     Female  0.0        0.019178    draw_0      0.899755
                                         draw_1      0.857321
                                         draw_10     0.874569
                                         draw_100    0.887292
                                         draw_101    0.890960
                                                       ...
Nigeria   Male    95.0       100.000000  draw_95     0.794225
                                         draw_96     0.814850
                                         draw_97     0.790197
                                         draw_98     0.853127
                                         draw_99     0.751525
Length: 46000, dtype: float64

In [56]:
iron_responsive_proportion = ira_prev / baseline_anemia.anemic.droplevel("vehicle")
iron_responsive_proportion

location  sex     age_start  age_end     draw     wealth_quintile
India     Female  0.0        0.019178    draw_0   lowest             0.911302
                                                  second             0.918687
                                                  middle             0.919568
                                                  fourth             0.931204
                                                  highest            0.947864
                                                                       ...
Nigeria   Male    95.0       100.000000  draw_99  lowest             0.798873
                                                  second             0.810065
                                                  middle             0.814376
                                                  fourth             0.817734
                                                  highest            0.834934
Length: 230000, dtype: float64

In [57]:
# NOTE: I am pretty sure this is correct, but it is quite difficult to think through *why*.

# First, observe that people in the population who start as non-anemic never factor into
# any of these metrics. If they started non-anemic, our counterfactual can only shift them up,
# so they did not change anemia categories between scenarios and hence have no importance to
# anemia prevalence or YLDs.

# So you can think of our hemoglobin distributions as only being of interest in the part
# of them below the anemia threshold.

# *Within* this subpopulation, we make the assumption that iron-responsive and non-iron-responsive
# anemic people have the same distributions of hemoglobin. This is probably not true, but GBD doesn't
# give us anything better.

# So you can think of our original distribution as a mixture of two parts, which are the same.
# Then we shift one of those parts (the iron-responsive part) and calculate all these stats from
# that new distribution.

# Our *actual* result should be about a mixture distribution that has the non-iron-responsive part
# the same as in baseline, with the shifted iron-responsive part.
# For all these metrics, it is pretty straightforward to see that the metric in such a mixture is
# just a weighted average of the metrics in each part.

counterfactual_anemia_accounting_for_non_response = (
    counterfactual_anemia.mul(iron_responsive_proportion, axis=0) +
    baseline_anemia.mul(1 - iron_responsive_proportion, axis=0)
)
counterfactual_anemia_accounting_for_non_response

                                                                           mild  \
location age_start age_end    sex    draw    wealth_quintile vehicle
India    0.0       0.019178   Female draw_0  fourth          rice      0.434873
                                             highest         rice      0.480059
                                             lowest          rice      0.296196
                                             middle          rice      0.377021
                                             second          rice      0.369400
...                                                                         ...
Nigeria  95.0      100.000000 Male   draw_99 fourth          bouillon  0.312356
                                             highest         bouillon  0.329780
                                             lowest          bouillon  0.285928
                                             middle          bouillon  0.308609
                                             second          bouillon  0.303890

                                                                       moderate  \
location age_start age_end    sex    draw    wealth_quintile vehicle
India    0.0       0.019178   Female draw_0  fourth          rice      0.522801
                                             highest         rice      0.455611
                                             lowest          rice      0.685847
                                             middle          rice      0.595177
                                             second          rice      0.604107
...                                                                         ...
Nigeria  95.0      100.000000 Male   draw_99 fourth          bouillon  0.464933
                                             highest         bouillon  0.445460
                                             lowest          bouillon  0.487461
                                             middle          bouillon  0.468562
                                             second          bouillon  0.472894

                                                                         severe  \
location age_start age_end    sex    draw    wealth_quintile vehicle
India    0.0       0.019178   Female draw_0  fourth          rice      0.002214
                                             highest         rice      0.001795
                                             lowest          rice      0.003651
                                             middle          rice      0.002760
                                             second          rice      0.002836
...                                                                         ...
Nigeria  95.0      100.000000 Male   draw_99 fourth          bouillon  0.138701
                                             highest         bouillon  0.122263
                                             lowest          bouillon  0.162483
                                             middle          bouillon  0.142127
                                             second          bouillon  0.146407

                                                                         anemic  \
location age_start age_end    sex    draw    wealth_quintile vehicle
India    0.0       0.019178   Female draw_0  fourth          rice      0.959888
                                             highest         rice      0.937465
                                             lowest          rice      0.985694
                                             middle          rice      0.974957
                                             second          rice      0.976343
...                                                                         ...
Nigeria  95.0      100.000000 Male   draw_99 fourth          bouillon  0.915990
                                             highest         bouillon  0.897503
                                             lowest          bouillon  0.935872
                                             middle          bouillon  0.919298
                                             second          bouillon  0.923190

                                                                       mild_ylds  \
location age_start age_end    sex    draw    wealth_quintile vehicle
India    0.0       0.019178   Female draw_0  fourth          rice       0.001053
                                             highest         rice       0.001162
                                             lowest          rice       0.000717
                                             middle          rice       0.000913
                                             second          rice       0.000894
...                                                                          ...
Nigeria  95.0      100.000000 Male   draw_99 fourth          bouillon   0.001312
                                             highest         bouillon   0.001385
                                             lowest          bouillon   0.001201
                                             middle          bouillon   0.001296
                                             second          bouillon   0.001276

                                                                       moderate_ylds  \
location age_start age_end    sex    draw    wealth_quintile vehicle
India    0.0       0.019178   Female draw_0  fourth          rice           0.031002
                                             highest         rice           0.027018
                                             lowest          rice           0.040671
                                             middle          rice           0.035294
                                             second          rice           0.035824
...                                                                              ...
Nigeria  95.0      100.000000 Male   draw_99 fourth          bouillon       0.019379
                                             highest         bouillon       0.018567
                                             lowest          bouillon       0.020318
                                             middle          bouillon       0.019530
                                             second          bouillon       0.019711

                                                                       severe_ylds  \
location age_start age_end    sex    draw    wealth_quintile vehicle
India    0.0       0.019178   Female draw_0  fourth          rice         0.000440
                                             highest         rice         0.000357
                                             lowest          rice         0.000726
                                             middle          rice         0.000549
                                             second          rice         0.000564
...                                                                            ...
Nigeria  95.0      100.000000 Male   draw_99 fourth          bouillon     0.016476
                                             highest         bouillon     0.014523
                                             lowest          bouillon     0.019301
                                             middle          bouillon     0.016883
                                             second          bouillon     0.017391

                                                                       anemic_ylds
location age_start age_end    sex    draw    wealth_quintile vehicle
India    0.0       0.019178   Female draw_0  fourth          rice         0.032495
                                             highest         rice         0.028537
                                             lowest          rice         0.042114
                                             middle          rice         0.036756
                                             second          rice         0.037282
...                                                                            ...
Nigeria  95.0      100.000000 Male   draw_99 fourth          bouillon     0.037166
                                             highest         bouillon     0.034475
                                             lowest          bouillon     0.040819
                                             middle          bouillon     0.037709
                                             second          bouillon     0.038378

[230000 rows x 8 columns]

In [58]:
averted_anemia = baseline_anemia - counterfactual_anemia_accounting_for_non_response
averted_anemia

                                                                           mild  \
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth          -0.019834
                                                      highest         -0.019857
                                                      lowest          -0.018806
                                                      middle          -0.020325
                                                      second          -0.018954
...                                                                         ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth          -0.003410
                                                      highest         -0.002127
                                                      lowest          -0.008077
                                                      middle          -0.004205
                                                      second          -0.005863

                                                                       moderate  \
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth           0.025990
                                                      highest          0.031450
                                                      lowest           0.020199
                                                      middle           0.023617
                                                      second           0.021808
...                                                                         ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth           0.003330
                                                      highest          0.002656
                                                      lowest           0.005757
                                                      middle           0.003910
                                                      second           0.005125

                                                                         severe  \
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth           0.000183
                                                      highest          0.000187
                                                      lowest           0.000243
                                                      middle           0.000205
                                                      second           0.000194
...                                                                         ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth           0.003122
                                                      highest          0.002068
                                                      lowest           0.007178
                                                      middle           0.003819
                                                      second           0.005281

                                                                         anemic  \
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth           0.006339
                                                      highest          0.011780
                                                      lowest           0.001635
                                                      middle           0.003497
                                                      second           0.003049
...                                                                         ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth           0.003043
                                                      highest          0.002597
                                                      lowest           0.004859
                                                      middle           0.003525
                                                      second           0.004543

                                                                       mild_ylds  \
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth           -0.000048
                                                      highest          -0.000048
                                                      lowest           -0.000046
                                                      middle           -0.000049
                                                      second           -0.000046
...                                                                          ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth           -0.000014
                                                      highest          -0.000009
                                                      lowest           -0.000034
                                                      middle           -0.000018
                                                      second           -0.000025

                                                                       moderate_ylds  \
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth                0.001541
                                                      highest               0.001865
                                                      lowest                0.001198
                                                      middle                0.001401
                                                      second                0.001293
...                                                                              ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth                0.000139
                                                      highest               0.000111
                                                      lowest                0.000240
                                                      middle                0.000163
                                                      second                0.000214

                                                                       severe_ylds  \
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth              0.000036
                                                      highest             0.000037
                                                      lowest              0.000048
                                                      middle              0.000041
                                                      second              0.000039
...                                                                            ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth              0.000371
                                                      highest             0.000246
                                                      lowest              0.000853
                                                      middle              0.000454
                                                      second              0.000627

                                                                       anemic_ylds
location age_start age_end    sex    draw    vehicle  wealth_quintile
India    0.0       0.019178   Female draw_0  rice     fourth              0.001530
                                                      highest             0.001854
                                                      lowest              0.001201
                                                      middle              0.001392
                                                      second              0.001286
...                                                                            ...
Nigeria  95.0      100.000000 Male   draw_99 bouillon fourth              0.000495
                                                      highest             0.000347
                                                      lowest              0.001059
                                                      middle              0.000599
                                                      second              0.000816

[230000 rows x 8 columns]

In [59]:
assert (averted_anemia.anemic_ylds > 0).all()

In [60]:
pop = reformat_gbd_data(
    db_queries.get_population(
        location_id=list(location_crosswalk.location_id),
        age_group_id=age_group_ids,
        sex_id=list(sex_crosswalk.sex_id),
        year_id=2030,
        release_id=9,
        forecasted_pop=True
    )
).population
pop

location  sex     age_start  age_end
India     Male    0.000000   0.019178      195123.148258
Nigeria   Male    0.000000   0.019178       78940.003165
India     Female  0.000000   0.019178      176190.386041
Nigeria   Female  0.000000   0.019178       76752.699967
India     Male    0.019178   0.076712      580497.144153
                                               ...
Nigeria   Female  90.000000  95.000000      69350.824104
India     Male    95.000000  100.000000    269449.783462
Nigeria   Male    95.000000  100.000000     16933.452258
India     Female  95.000000  100.000000    371349.796191
Nigeria   Female  95.000000  100.000000     22274.971240
Name: population, Length: 84, dtype: float64

In [61]:
pop = reformat_gbd_data(db_queries.get_population(
    location_id=list(location_crosswalk.location_id),
    age_group_id=age_group_ids,
    sex_id=list(sex_crosswalk.sex_id),
    release_id=9,
    year_id=2021,
    forecasted_pop=False, # Was missing age groups!
)).population
pop

location  sex     age_start  age_end
India     Male    0.000000   0.019178    2.183097e+05
Nigeria   Male    0.000000   0.019178    7.992764e+04
India     Female  0.000000   0.019178    1.975581e+05
Nigeria   Female  0.000000   0.019178    7.684611e+04
India     Male    0.019178   0.076712    6.478743e+05
                                             ...
Nigeria   Female  0.076712   0.500000    1.653024e+06
India     Male    0.500000   1.000000    5.610299e+06
Nigeria   Male    0.500000   1.000000    1.966178e+06
India     Female  0.500000   1.000000    5.085507e+06
Nigeria   Female  0.500000   1.000000    1.904590e+06
Name: population, Length: 92, dtype: float64

In [62]:
import gbd_mapping

In [63]:
asfr = reformat_gbd_data(db_queries.get_covariate_estimates(
    int(gbd_mapping.covariates.age_specific_fertility_rate.gbd_id),
    location_id=list(location_crosswalk.location_id),
    age_group_id=age_group_ids,
    sex_id=list(sex_crosswalk.sex_id),
    year_id=2021,
    release_id=9,
).drop(columns=["location_name", "sex"])).mean_value
asfr

location  sex     age_start  age_end
India     Male    0.000000   0.019178    0.0
Nigeria   Male    0.000000   0.019178    0.0
India     Female  0.000000   0.019178    0.0
Nigeria   Female  0.000000   0.019178    0.0
India     Male    0.019178   0.076712    0.0
                                        ...
Nigeria   Female  0.076712   0.500000    0.0
India     Male    0.500000   1.000000    0.0
Nigeria   Male    0.500000   1.000000    0.0
India     Female  0.500000   1.000000    0.0
Nigeria   Female  0.500000   1.000000    0.0
Name: mean_value, Length: 92, dtype: float64

In [64]:
sbr = reformat_gbd_data(db_queries.get_covariate_estimates(
    int(gbd_mapping.covariates.stillbirth_to_live_birth_ratio.gbd_id),
    location_id=list(location_crosswalk.location_id),
    year_id=2021,
    release_id=9,
).drop(columns=["sex_id", "location_name", "sex", "age_group_id", "age_group_name"])).mean_value
sbr

location
India      0.017119
Nigeria    0.038684
Name: mean_value, dtype: float64

In [65]:
maternal_abortion_miscarriage_incidence = reformat_gbd_data(db_queries.get_outputs(
    topic='cause',
    release_id=9,
    year_id=2021,
    cause_id=int(gbd_mapping.causes.maternal_abortion_and_miscarriage.gbd_id),
    sex_id=sex_ids,
    location_id=list(location_crosswalk.location_id),
    age_group_id=age_group_ids,
    measure_id=6,
    metric_id=3,
).drop(columns=["sex", "location_name"])).val.fillna(0)
maternal_abortion_miscarriage_incidence.sort_values()

location  sex     age_start  age_end
India     Female  65.0       70.0       0.000000
Nigeria   Male    80.0       85.0       0.000000
India     Male    80.0       85.0       0.000000
Nigeria   Female  75.0       80.0       0.000000
India     Female  75.0       80.0       0.000000
                                          ...
Nigeria   Female  20.0       25.0       0.035416
                  30.0       35.0       0.036698
India     Female  25.0       30.0       0.037986
Nigeria   Female  25.0       30.0       0.038699
India     Female  20.0       25.0       0.046091
Name: val, Length: 92, dtype: float64

In [66]:
ectopic_pregnancy_incidence = reformat_gbd_data(db_queries.get_outputs(
    topic='cause',
    release_id=9,
    year_id=2021,
    cause_id=int(gbd_mapping.causes.ectopic_pregnancy.gbd_id),
    sex_id=sex_ids,
    location_id=list(location_crosswalk.location_id),
    age_group_id=age_group_ids,
    measure_id=6,
    metric_id=3,
).drop(columns=["sex", "location_name"])).val.fillna(0)
ectopic_pregnancy_incidence.sort_values()

location  sex     age_start  age_end
India     Female  65.0       70.0       0.000000
Nigeria   Male    80.0       85.0       0.000000
India     Male    80.0       85.0       0.000000
Nigeria   Female  75.0       80.0       0.000000
India     Female  75.0       80.0       0.000000
                                          ...
Nigeria   Female  20.0       25.0       0.008187
India     Female  25.0       30.0       0.008453
Nigeria   Female  35.0       40.0       0.009958
                  25.0       30.0       0.010354
                  30.0       35.0       0.012120
Name: val, Length: 92, dtype: float64

In [67]:
pregnancy_incidence = (
    asfr
    + (asfr * sbr)
    + maternal_abortion_miscarriage_incidence
    + ectopic_pregnancy_incidence
)
pregnancy_incidence[pregnancy_incidence > 0]

location  sex     age_start  age_end
India     Female  10.0       15.0       0.000395
Nigeria   Female  10.0       15.0       0.003561
India     Female  15.0       20.0       0.015350
Nigeria   Female  15.0       20.0       0.101501
India     Female  20.0       25.0       0.159986
Nigeria   Female  20.0       25.0       0.254413
India     Female  25.0       30.0       0.181117
Nigeria   Female  25.0       30.0       0.279034
India     Female  30.0       35.0       0.106541
Nigeria   Female  30.0       35.0       0.258724
India     Female  35.0       40.0       0.043143
Nigeria   Female  35.0       40.0       0.175022
India     Female  40.0       45.0       0.014067
Nigeria   Female  40.0       45.0       0.092714
India     Female  45.0       50.0       0.004355
Nigeria   Female  45.0       50.0       0.042147
India     Female  50.0       55.0       0.000471
Nigeria   Female  50.0       55.0       0.004797
dtype: float64

In [68]:
# https://github.com/ihmeuw/vivarium_gates_iv_iron/blob/862b057457cea2410e8d24c2c9c38c43419cd8b2/src/vivarium_gates_iv_iron/data/loader.py#L237C5-L240C6
PARTIAL_TERM: float = 24 / 52
FULL_TERM: float = 40 / 52
pregnant_prevalence = (
    FULL_TERM * (asfr + asfr * sbr)
    + PARTIAL_TERM * (maternal_abortion_miscarriage_incidence + ectopic_pregnancy_incidence)
)

In [69]:
pregnancy_pop = (pop * pregnant_prevalence)
pregnancy_pop[pregnancy_pop > 0]

location  sex     age_start  age_end
India     Female  10.0       15.0       1.892408e+04
Nigeria   Female  10.0       15.0       4.156882e+04
India     Female  15.0       20.0       6.499476e+05
Nigeria   Female  15.0       20.0       9.886794e+05
India     Female  20.0       25.0       6.821581e+06
Nigeria   Female  20.0       25.0       2.056488e+06
India     Female  25.0       30.0       7.486302e+06
Nigeria   Female  25.0       30.0       1.853251e+06
India     Female  30.0       35.0       4.196408e+06
Nigeria   Female  30.0       35.0       1.374654e+06
India     Female  35.0       40.0       1.583992e+06
Nigeria   Female  35.0       40.0       7.679469e+05
India     Female  40.0       45.0       4.451042e+05
Nigeria   Female  40.0       45.0       3.332663e+05
India     Female  45.0       50.0       1.170784e+05
Nigeria   Female  45.0       50.0       1.302636e+05
India     Female  50.0       55.0       1.046194e+04
Nigeria   Female  50.0       55.0       1.179362e+04
dtype: float64

In [70]:
non_pregnant_pop = pop - pregnancy_pop
non_pregnant_pop

location  sex     age_start  age_end
India     Male    0.000000   0.019178    2.183097e+05
Nigeria   Male    0.000000   0.019178    7.992764e+04
India     Female  0.000000   0.019178    1.975581e+05
Nigeria   Female  0.000000   0.019178    7.684611e+04
India     Male    0.019178   0.076712    6.478743e+05
                                             ...
Nigeria   Female  0.076712   0.500000    1.653024e+06
India     Male    0.500000   1.000000    5.610299e+06
Nigeria   Male    0.500000   1.000000    1.966178e+06
India     Female  0.500000   1.000000    5.085507e+06
Nigeria   Female  0.500000   1.000000    1.904590e+06
Length: 92, dtype: float64

In [71]:
baseline_ylds = (baseline_anemia.anemic_ylds.unstack("draw").mean(axis=1) * non_pregnant_pop)
baseline_ylds

location  age_start  age_end     sex     vehicle   wealth_quintile
India     0.0        0.019178    Female  rice      fourth             5750.771980
                                                   highest            5209.516075
                                                   lowest             7152.648727
                                                   middle             6367.337643
                                                   second             6430.516419
                                                                         ...
Nigeria   95.0       100.000000  Male    bouillon  fourth              380.578395
                                                   highest             351.484752
                                                   lowest              424.345933
                                                   middle              387.245278
                                                   second              396.415810
Length: 460, dtype: float64

In [72]:
intervention_ylds = (counterfactual_anemia_accounting_for_non_response.anemic_ylds.unstack("draw").mean(axis=1) * non_pregnant_pop)

In [73]:
baseline_ylds.groupby(["location", "wealth_quintile"]).sum() - intervention_ylds.groupby(["location", "wealth_quintile"]).sum()

location  wealth_quintile
India     fourth             689946.027730
          highest            943640.988275
          lowest             501618.341505
          middle             613020.970442
          second             534975.129983
Nigeria   fourth              66259.360871
          highest             48541.842639
          lowest             132340.293560
          middle              79324.501100
          second             105829.837146
dtype: float64

In [74]:
ylds = pd.concat([
    baseline_ylds.rename("value").reset_index().assign(scenario="baseline"),
    intervention_ylds.rename("value").reset_index().assign(scenario="intervention")
], ignore_index=True)
ylds

,location,age_start,age_end,sex,vehicle,wealth_quintile,value,scenario
0,India,0.0,0.019178,Female,rice,fourth,5750.771980,baseline
1,India,0.0,0.019178,Female,rice,highest,5209.516075,baseline
2,India,0.0,0.019178,Female,rice,lowest,7152.648727,baseline
3,India,0.0,0.019178,Female,rice,middle,6367.337643,baseline
4,India,0.0,0.019178,Female,rice,second,6430.516419,baseline
...,...,...,...,...,...,...,...,...
915,Nigeria,95.0,100.000000,Male,bouillon,fourth,375.117253,intervention
916,Nigeria,95.0,100.000000,Male,bouillon,highest,347.674494,intervention
917,Nigeria,95.0,100.000000,Male,bouillon,lowest,412.586977,intervention
918,Nigeria,95.0,100.000000,Male,bouillon,middle,380.633678,intervention
919,Nigeria,95.0,100.000000,Male,bouillon,second,387.392111,intervention

In [75]:
import pathlib

for location in ylds.location.unique():
    path = f'./{location}/ylds.parquet'
    pathlib.Path(path).parent.mkdir(exist_ok=True, parents=True)
    ylds[ylds.location == location].to_parquet(path)

In [76]:
baseline_anemia_cases = baseline_anemia['anemic'].unstack("draw").mean(axis=1).mul(non_pregnant_pop, axis=0)
baseline_anemia_cases

location  age_start  age_end     sex     vehicle   wealth_quintile
India     0.0        0.019178    Female  rice      fourth             182072.755947
                                                   highest            176975.193249
                                                   lowest             190432.360172
                                                   middle             186483.358390
                                                   second             186863.573565
                                                                          ...
Nigeria   95.0       100.000000  Male    bouillon  fourth               7843.840504
                                                   highest              7659.389484
                                                   lowest               8051.353400
                                                   middle               7880.280825
                                                   second               7927.317581
Length: 460, dtype: float64

In [77]:
intervention_anemia_cases = counterfactual_anemia_accounting_for_non_response['anemic'].unstack("draw").mean(axis=1).mul(non_pregnant_pop, axis=0)
intervention_anemia_cases

location  age_start  age_end     sex     wealth_quintile  vehicle
India     0.0        0.019178    Female  fourth           rice        180007.001360
                                         highest          rice        173703.048276
                                         lowest           rice        189635.357137
                                         middle           rice        185102.799651
                                         second           rice        185633.027977
                                                                          ...
Nigeria   95.0       100.000000  Male    fourth           bouillon      7812.090096
                                         highest          bouillon      7631.800686
                                         lowest           bouillon      8000.752731
                                         middle           bouillon      7843.579597
                                         second           bouillon      7880.119843
Length: 460, dtype: float64

In [78]:
(baseline_anemia_cases.groupby(["location", "wealth_quintile"]).sum() - intervention_anemia_cases.groupby(["location", "wealth_quintile"]).sum()).map(lambda x: f'{round(x):,.0f}')

location  wealth_quintile
India     fourth             18,091,890
          highest            25,756,279
          lowest             11,938,505
          middle             15,598,499
          second             13,374,540
Nigeria   fourth              1,622,614
          highest             1,311,831
          lowest              2,746,437
          middle              1,905,650
          second              2,418,965
dtype: object